### ISSUE TITLE
How to use a Polymer custom-style include in a lit-element element?

### ISSUE THREAD

**Issue by rictic** [Polymer/lit-element#100]
e.g. iron-doc-viewer defines a default theme by writing this imperatively into document.head:

```html
<dom-module id="iron-doc-default-theme">
  <template>
    <style>
     /* styles here */
    </style>
  </template>
</dom-module>
```

If I have a LitElement, how do I use custom-style to include that style into my shadow root's styles?

I've tried a bunch of variants of this, but it doesn't look like it's working:

```typescript
  _render() {
    return html`
      <custom-style include="iron-doc-default-theme">
        <style include="iron-doc-default-theme"></style>
      </custom-style>
    `;
  }
```

**Comment by justinfagnani** [comment]
`<custom-style>` is supposed to be for main document styles. It just scopes the styles so they don't errantly style elements in emulated shadow roots.

I think the best current solution is something like:

```js
import {DomModule} from '@polymer/lib/elements/dom-module.js';

const ironDocThemeTemplate = DomModule.import('iron-doc-default-theme', 'template');
const ironDocThemeStyle = ironDocThemeTemplate.content.firstElementChild.textContent;

...

  _render() {
    return html`
      ${ironDocThemeStyle}
    `;
  }
```

Assuming the lit-html + ShadyCSS fix is in place.

We should probably update modulizer to make this easier so that we can do:

```js
import {style} from '@polymer/iron-doc-viewer/default-theme.js';

...
  _render() {
    return html`
      ${ironDocThemeStyle}
    `;
  }
```

Which would mean generating:

```js

export const style = `...`;
const $_documentContainer = document.createElement('template');
$_documentContainer.setAttribute('style', 'display: none;');

$_documentContainer.innerHTML = `<dom-module id="iron-doc-default-theme">
  <template>
    <style>${style}</style>
  </template>
</dom-module>`;

document.head.appendChild($_documentContainer.content);
```

cc @sorvell

**Comment by sorvell** [comment]
You should never use a `<custom-style>` inside an element. It's for creating polyfill safe document styles.

Styling data can flow down to elements using css custom properties.

Styling can be shared between elements using the technique [shown above](https://github.com/Polymer/lit-element/issues/100#issuecomment-396793641).

**Comment by jogibear9988** [comment]
@justinfagnani 
we have a huge application and some components are switch to lit and some not. So I also need to use shared styles.

I now did this: 

      const bootstrapStyle = (<HTMLTemplateElement>DomModule.import('bootstrap', 'template')).content; 

this works inside my lit-element. But the lit-element used some Polymer Components inside. And with this code now, the "include" of the style inside the polymer component does not work any more.

any idea?
