### ISSUE TITLE
Deno compatibility

### ISSUE THREAD

**Issue by lusatiro** [Polymer/lit-element#1000]
## Description
- Deno community
- Full compatibility
- To use lit-element without other tools
- A way to load lit-element without npm/yarn, just like lit-html. Recently was released a new JS runtime called Deno, they allow imports from URLs. I saw that lit-html has no dependency and lit-element has a dependency upon lit-html. Allow devs load lit-element by a CDN/raw.github too would be great and could give a reason for teams adopt polymer project.

## Acceptance criteria
Load lit-element without npm/yarn

**Comment by bennypowers** [comment]
https://unpkg.com/lit-element?module
Does that fit the bill?

**Comment by lusatiro** [comment]
There's some problem occurring. But I believe it is Deno side
