### ISSUE TITLE
Is it possible and/or good practice to use textContent as if it were a property?

### ISSUE THREAD

**Issue by Christian24** [Polymer/lit-element#1015]
## Description
Hello,

I am sorry, this is a bit a question, but also a suggestion. 

Sometimes when designing new Web Components I want them to feel like native elements to the developers using them. With a lot of builtin elements you can do something like `<button>Hello world</button>`. If I wanted to do something similar in LitElement I could do something like this (the example is simplified, but I hope it becomes clear what I want to do):

```typescript
@customElement('my-button')
class MyButton extends LitElement {

render() {
     return html`<button>${this.textContent}</button>`
}

}
```
And then I could use it like so `<my-button>Hello world</my-button>`. I like this solution, because if someone put an input inside of there it would just render as text. This solution seems to work 9x.0 % of the time. However, sometimes if `textContent` changes the changes are not picked up by LitElement (sadly I do not have a reproduction or more info). Is this intentional? Is what I am doing even advisable or is it just breaking conventions? I for my two cents find it useful in certain situations and would love if this could be supported. 

Of course a different way of achieving something similar is:

```typescript
@customElement('my-button')
class MyButton extends LitElement {

render() {
     return html`<button><slot></slot></button>`
}

}
```

However, then users could render anything into `my-button`, not just text which might not be always desired.

Thanks very much in advance,
Christian

**Comment by justinfagnani** [comment]
Using `.textContent` and other DOM APIs is totally fine and a very nice property of lit-html expressions just being JavaScript. Like you noted though, the trick is in knowing when to update/re-render when the values change. In the DOM there are a number of APIs to monitor changes: events, MutationObservers, IntersectionObservers, ResizeObservers, etc.

In this case, using a `<slot>` is fine, IMO. You users could already put any content in your element - there's no way to prevent that actually.

This came up before in https://github.com/Polymer/lit-element/issues/954 where @arthurevans added a nice snippet for getting the current text content that works even with re-projection:

```ts
updateSlotted({target}) {
  this.myprop = target.assignedNodes().map((n) => n.textContent).join('');
}

render() {
  return html`<textarea .value=${this.myprop}></textarea>
    <div hidden>
      <slot @slotchange=${this.updateSlotted}></slot>
    </div>`;
}
```

**Comment by Christian24** [comment]
@justinfagnani cool. Thank you very much. I will try this out tomorrow. I hadn't even thought about using MutationObserver etc. Definitely something to play around with more.
