### ISSUE TITLE
global static property?

### ISSUE THREAD

**Issue by tamis-laan** [Polymer/lit-element#1017]
I'm writing a component that requires a global or static property such that when this property is changed multiple instances of the same component are updated. 

In my case it's an image with a source that can be set by the user. When the image source is changed on one component all other components should update to the new source (image).

To do this I tried using a static getter setter however it does not seem to work:

```javascript 
  static get properties(){
    return {
      src: {type:String}
    }
  }

  static _src = "" 
  static set src(value) {
    var oldValue = this._src 
    this._src = value
    this.requestUpdate('src',oldValue)
  }

  static get src() {return this._src}
```

**Comment by justinfagnani** [comment]
In order to have a single property change affect all instance of a component you're going to need to build a registry of instances. `this` inside of a static method refers to the constructor, not the instance, so `this.requestUpdate()` will not work.

You can use a Set for the registry, but to avoid a memory leak you'll have to remove the element at some point, so I'm using connect/disconnected here:

```ts
class MyElement extends LitElement {

  static _src = '';
  static get src() {
    return this._src;
  }
  static set src(value) {
    const oldValue = this._src;
    this._src = value;
    for (const instance of this._instances) {
      // I just created this name... other code, like in update() will have to
      // know it's not an instance property. You can leave the parameters out too.
      instance.requestUpdate('MyElement.src', oldValue);
    }
  }

  static _instances = new Set<MyElement>();

  connectedCallback() {
    super.connectedCallback();
    this.constructor._instances.add(this);
  }

  disconnectedCallback() {
    super.connectedCallback();
    this.constructor._instances.delete(this);
  }
}
```

**Comment by tamis-laan** [comment]
Thanks for the help!
