### ISSUE TITLE
custom element @change bound to different context?

### ISSUE THREAD

**Issue by tamis-laan** [Polymer/lit-element#1018]
I'm building a custom input element and doing some formatting. However when adding an onchange function I can't pull in data defined outside of the function. The on change function is not bound to the current context?

Here `data.value` is undefined (inside @change):
```javascript
var data = ......
return html`
<input-euro @change=${e=>data.value=e.target.value} value=${data.value}></input-euro>
`
```

While using a normal input element `data.value` is defined (inside @change):
```javascript
var data = ......
return html`
<input @change=${e=>data.value=e.target.value} value=${data.value}></input>
`
```

**Comment by jsilvermist** [comment]
You may want to use `.value=${}` instead to bind the property instead of the attribute.

**Comment by tamis-laan** [comment]
Wel that's not the problem. The problem is that I cannot access `data.value` inside the @change function when using my custom component. When using the standard input component I can.
