### ISSUE TITLE
[question] @eventOptions: options parameter is not optional ?

### ISSUE THREAD

**Issue by miyass** [Polymer/lit-element#1019]
## Description
Is `@eventOptions` options parameter not optional ?

<img width="722" alt="eventoption" src="https://user-images.githubusercontent.com/17075743/83968940-89346900-a907-11ea-8a9d-1e1000a8a11d.png">

[EventTarget#addEventListener options](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#Parameters) is optional, so I think this is also optional. 

When I don't need options, I have to add empty object. 
[stackblitz Example Link](https://stackblitz.com/edit/eventoptions-sample?file=wc-button.ts)

Thank you for your time.

**Comment by justinfagnani** [comment]
If you don't need any event options, don't use the `@eventOptions` decorator.

**Comment by miyass** [comment]
I misunderstood `@eventOptions` usage.
I solved this problem ! Thank you !
