### ISSUE TITLE
Make login form with google password manager.

### ISSUE THREAD

**Issue by Krishuthapa** [Polymer/lit-element#1023]
I am using LitElelement. I need to make a login form with feature of autocomplete of username and password. For this i need to integrate the form with google password manager.How can i achieve it with lit element?

**Comment by cintaccs** [comment]
I have the same challenge... even using MDC web components

**Comment by chase-moskal** [comment]
the best workaround i can think of: the web components need to accept the input elements from the top-level via slotting

that should work, but it makes form elements annoying and less elegant to use. on the plus side, the top-level markup gets lots of control over the input element attributes related to autofill and more, and we should be able to validate/manipulate the input elements from within the web component

**Comment by chase-moskal** [comment]
see PolymerElements/iron-form#197

**Comment by web-padawan** [comment]
We created [vaadin-login-overlay](https://github.com/vaadin/vaadin-login) because of exactly this thing (certain password managers not being able to work with inputs in Shadow DOM). Feel free to try if that component would work for you.

**Comment by chase-moskal** [comment]
of course a simple workaround is to use light-dom for reusable forms, via createRenderRoot

**Comment by justinfagnani** [comment]
@web-padawan that's very nice! The technique of using an overlay for this is probably the best idea for now. I think some common integration components, like for Stripe, use this approach too.

@chase-moskal the problem with just using createRenderRoot is that you need to use that all the way down from your app to the form. Overlays solve that problem.

**Comment by chase-moskal** [comment]
@justinfagnani — oh interesting, i must be missing something! what is meant by "overlay"? is this some kind of shadow dom feature i'm having trouble finding? i'm having trouble figuring this one out! thanks!

**Comment by kevinpschaaf** [comment]
By virtue of the `vaadin-login-overlay` hoisting the overlay contents into the main document, it works around the issue of password managers not finding form inputs to autocomplete in Shadow DOM.

To avoid needing workarounds like that, we'd need the relevant password managers to find form controls in Shadow DOM.  There are a couple of Chrome issues around its autofill features here you can follow:

* https://bugs.chromium.org/p/chromium/issues/detail?id=746593
* https://bugs.chromium.org/p/chromium/issues/detail?id=649162

Based on the description of the workarounds here (thank you @web-padawan!) and the fact that this isn't a LitElement-specific issue, I'm going to go ahead and close this issue.
