### ISSUE TITLE
Question: Is `unsafeHTML` necessary to render a bound html string?

### ISSUE THREAD

**Issue by timonson** [Polymer/lit-element#1024]
I want to add html strings, which are assigned to variables, to my `render` function. Is there another way than using `unsafeHTML` from `lit-html`?

**Comment by justinfagnani** [comment]
No. lit-html templates are fairly XSS-safe by treating all interpolated text as text content, not raw HTML. We're not willing to relax this as it's a very important security property. Limiting unsafe HTML and SVG to directive also makes it easier to perform security audits on codebases.

**Comment by timonson** [comment]
Thank you @justinfagnani !
