### ISSUE TITLE
devtools assertion fails on reusing elements with static get styles declared.

### ISSUE THREAD

**Issue by marcus13345** [Polymer/lit-element#1027]
### Description

I'm not sure if this is an error with devtools, chrome, or lit-element, or lit-html, as its too in the weeds for me to parse, but here's what I've gathered so far:

Electron logs
```
[26916:0627/034200.928:ERROR:CONSOLE(1217)] "console.assert", source: devtools://devtools/bundled/sdk/sdk.js (1217)
```
Every time I use a LitElement that has a `static get styles` within an `html` tagged template literal.

The first few numbers seem to be related to the process or time, as they change with each run. however, 1217 is always constant.
manually loading `location.href = 'devtools://devtools/bundled/sdk/sdk.js'` brings up a file, with line 1217:

```
_styleSheetAdded(header){console.assert(!this._styleSheetIdToHeader.get(header.styleSheetId));const styleSheetHeader=new CSSStyleSheetHeader(this,header);this._styleSheetIdToHeader.set(header.styleSheetId,styleSheetHeader);const url=styleSheetHeader.resourceURL();if(!this._styleSheetIdsForURL.get(url)){this._styleSheetIdsForURL.set(url,new Map());}
```

Seems to be the culprit.

Worth noting, this has yet to cause anything other than a cluttered stderr from the electron process, though it would be nice to clear up.

#### Live Demo

Code: https://stackblitz.com/edit/lit-element-example-q283qs?file=index.js
Demo: https://lit-element-example-q283qs.stackblitz.io

#### Steps to Reproduce
- Open the demo page above in chrome (im using chrome edge)
- Open devtools (detached from the page)
- press Ctrl + Shift + I with devtools focused.
- this will open a devtools for devtools. in there you will see the analogous error to what is seen in electron's main process.

![image](https://user-images.githubusercontent.com/6365746/85917943-9076d480-b82c-11ea-932c-9b90e4310ad5.png)

#### Expected Results
It would be expected that LitElement doesnt cause an assertion in devtools to fail

#### Actual Results
The assertion is failed.

### Browsers Affected

- [x] Chrome
- [ ] Firefox (Not Tested)
- [x] Edge
- [ ] Safari 11 (Not Tested)
- [ ] Safari 10 (Not Tested)
- [ ] IE 11 (Not Tested)

Reason for untestedness is that I'm not sure how to open devtools for the devtools on non chrome browsers, to see if the analogous error occurs.

### Versions

- lit-element: v2.3.1
- webcomponents: N/A (not shown in `npm ls`)

If there's any other information I can provide, or if you have any  intuition who better to open this bug with, it would be greatly appreciated.

**Comment by justinfagnani** [comment]
This seems like an issue in DevTools, possibly some faulty assumptions about constructible stylesheets. Chrome nightly has support for editing constructible stylesheets, so they might have fixed this along the way. Can you check with that? Either way, it doesn't look like a bug in LitElement.

**Comment by marcus13345** [comment]
@justinfagnani 

Just tested in Canary 86.0.4184.0, the issue is still present.

I'm not familiar with chrome/devtools issue tracking, should I open a bug with chromium, chrome, or is there something specific for devtools?

**Comment by justinfagnani** [comment]
@marcus13345 I think we need an issue on Chromium. cc @TimvdLippe in case he has an idea here

**Comment by OrKoN** [comment]
It appears to be a wrong assertion in DevTools, I have filed an issue here https://bugs.chromium.org/p/chromium/issues/detail?id=1104108 and I will take a look at it.

**Comment by justinfagnani** [comment]
Thanks @OrKoN!!

**Comment by justinfagnani** [comment]
Thanks for the report @marcus13345. Closing as being fixed upstream.
