### ISSUE TITLE
First time initialization of an element

### ISSUE THREAD

**Issue by TheEndeavor** [Polymer/lit-element#1028]
Is it possible to perform first time initialization of an element?

Specifically, I'm talking about initializing the internal state of an element **before** rendering but **after** any properties are updated.

I have tried the following functions:

- constructor() - properties are not yet updated at this stage.
- initialize() - properties are not yet updated here either.
- firstUpdated() - properties are updated here, but this function is called **after** the first call to render.

**Comment by justinfagnani** [comment]
I'm a bit unclean on what you mean by properties not being updated. If you initialize your properties in the constructor, they'll be updated there. Can you post a code snipped of what you're trying to accomplish?

**Comment by TheEndeavor** [comment]
I have an element that needs to load properties and internal state based on an ID. 

```js
class MyElement extends LitElement
{
    static properties()
    {
        return {
            itemId: { type: Number },
        };
    }

    constructor()
    {
        this.itemId = 0;
    }

    initializeBeforeRender()
    {
        // read the itemId property and load/initialize internal state before render().
    }
}
```

```html
<my-element itemId=7></my-element>
```

Is there a function I can be implementing to perform loading or initialization based on the properties that are set in the HTML, but **before** any calls to render?

**Comment by justinfagnani** [comment]
Ah. Ok, you want to respond to externally set state.

The main way to do this is by overriding `update()`, which is passed a Map of the properties changed since the previous update:

```js
class MyElement extends LitElement {
  static properties = {
    itemId: { type: Number },
  };

  constructor() {
    this.itemId = 0;
  }

  update(changedProperties) {
    // read the itemId property and load/initialize internal state before render().
    if (changedProperties.has('itemId')) {
      this._internalState = initializeFromId(this.itemId);
    }
    super.update(changedProperties);
  }
}
```

**Comment by TheEndeavor** [comment]
This makes a lot more sense. I didn't realize update was only called when properties had changed, and also executed before calls to render(). 

That clears up my issue.

Thanks!
