### ISSUE TITLE
Unexpected behaviour for _changedProperties

### ISSUE THREAD

**Issue by Avocher** [Polymer/lit-element#1029]
## Description
I noticed that `_changedProperties` in the lifecycle callbacks resets if the element doesn't render. This was slightly unexpected to me as I was looking for changes at a later lifecycle callback, but it got "dropped" because `shouldUpdate` returned `false`. I'd prefer if the `_changedProperties` contained the **changes since the last actual render** as it would make the callbacks less entangled to each other.

## Acceptance criteria
A nice open conversation about the behaviour of `_changedProperties` and preferably a change to the behaviour of `_changedProperties`.

**Comment by sorvell** [comment]
Your expectation is not unreasonable, and this is a little confusing. But at this point any change to this behavior would be a breaking change. Let me try to explain the intended design. 

The naming here is admittedly a little confusing, but the intention around `shouldUpdate` is really more like "should apply an update based on this set of changes." Returning false from `shouldUpdate` does not prevent the update cycle from completing, which clears any pending changes and resolves the `updateComplete` promise. By returning false from `shouldUpdate` you're saying this set of changes does not need to apply an update and therefore is irrelevant.

That said, if you really want to hang on the the set of changes, you can certainly do that by saving a copy of the `changedProperties` Map in `shouldUpdate`. The `shouldUpdate` implementation can then use the saved "previous changes" and the current set of `changedProperties` to decide whether or not to update.

Hope that helps.
