### ISSUE TITLE
Create svg <use> declarations with dynamic xlink:href attributes

### ISSUE THREAD

**Issue by porpoiseless** [Polymer/lit-element#1034]
## Description
I want to use svg symbols in a component. The symbols for a component's controls are all in an svg file, and they all have fragment names that can be predicted from the name of the associated control element.

The following snippet shows a hardcoded `xlink:href` location.

```js
import IconSheet from "./number.svg";

const svgLabelledRadio = (radioGroupName, valueName) =>
    html`<label>
  <input name="${radioGroupName}" type="radio" value="${valueName}"/>
${ svg`<svg><use xlink:href="#number-duplex"/></svg>`}
</label > `;

const radioGroup = (groupName, values) => html`
<div class="radio-group-container">
  ${values.map((value) => svgLabelledRadio(groupName, value))}
</div>
`;


class SVGRadioInput extends LitElement {

    render() {
        const { options, radioGroupName } = this;
        console.log(options);
        return html`<div class="svg-symbols-container">
    ${unsafeSVG(IconSheet)}
</div>
    <fieldset>
        <legend>Form: <output value="foo"></output></legend>
   ${radioGroup(radioGroupName, options)}
    </fieldset>`;
    };

    static get properties() {
        return {
            radioGroupName: {
                type: String
            },
            options: {
                type: Array
            }
        };
    }
   // get styles omitted
}

```

Here is the result in a browser. The hardcoded `xlink:href` attribute works. The shape above is the svg itself, which is left visible to show that the image gets inlined.

![image](https://user-images.githubusercontent.com/13423754/87842782-16060700-c864-11ea-90eb-c7f9cae38ed5.png)

If I change `xlink:href` attribute to a different fragment, that also works.

```js
const svgLabelledRadio = (radioGroupName, valueName) =>
    html`<label>
  <input name="${radioGroupName}" type="radio" value="${valueName}"/>
${ svg`<svg><use xlink:href="#number-potential"/></svg>`}
</label > `;
```

![image](https://user-images.githubusercontent.com/13423754/87842862-9cbae400-c864-11ea-8314-e81fdfbb2876.png)

And by inspecting I confirm what the expected `use` has for that attribute.

![image](https://user-images.githubusercontent.com/13423754/87842924-15ba3b80-c865-11ea-8b04-bfb6c07c6170.png)

When I change the template to determine the name of the fragment on the basis of the name of the control, the `use` declarations stop working.

```js

const svgLabelledRadio = (radioGroupName, valueName) =>
    html`<label>
  <input name="${radioGroupName}" type="radio" value="${valueName}"/>
${ svg`<svg><use xlink:href=${"#number-" + valueName}"/></svg>`}
</label > `;

```

Here is the broken version that results.

![image](https://user-images.githubusercontent.com/13423754/87843043-e5bf6800-c865-11ea-970c-1efb1df29c7a.png)

As you can see the fragment id is the same, and I've ruled out a problem with the svg or its fragments, since they're accessible when the reference is hardcoded.

For good measure, here is the component with its properties:

```html
    <svg-radio-input radioGroupName="number" options='["uniplex", "potential", "duplex", "multiplex"]'>
```

Is this the intended behavior here?

## Acceptance criteria

Solution must allow referencing of inline svg fragments using an id generated on the basis of an attribute or property of the component.

**Comment by justinfagnani** [comment]
We tried to support namespaced attributes, but the complexity and cost were too high, and it turns out that all browsers support the un-namespaced `href` attribute now. See: https://github.com/Polymer/lit-html/issues/423
