### ISSUE TITLE
DOM manipulation for DnD

### ISSUE THREAD

**Issue by mercmobily** [Polymer/lit-element#1035]
We enabled Drag & Drop on a list view. The source data is an array.

During dragging, we hide the dragged element with CSS.
The point is that when the element is dropped, the CSS magic is off, and the element "flashes" back to where it actually lives.
Once the server request is done, the element is placed in the right spot, where it was dropped (a render is triggered) IF the server responds with a 200.

We want to avoid the "flash" in the original position. We have tried moving the element in the DOM (yes, under lit-html's butt) and we obviously had weird problems (for example when an element is dragged to the last position, on the next render the last element is displayed twice). We haven't even tried to debug these problems, since we are doing something obviously awful.

Is it inconceivable to allow developers to modify the DOM, and then force a render bursting the cache altogether? I realise that it would a performance hit, but it would only ever happen on repositioning of items.

If not, what's the recommended way to deal with DnD, so that once an item is dropped it appears in the right spot? We *could*:

* change the source array on drop
* Request an update

However, in this case, if anything went wrong we would need to then move  again the element to its original position in the array, which is tricky for a number or reasons.

So, shorter version: what's the recommended way to deal with DnD, which nearly always requires DOM manipulation to "look right"?

**Comment by kevinpschaaf** [comment]
You should definitely avoid manually moving DOM that is rendered by `lit-html`.

What you described here is basically correct:
> * Change the source array on drop
> * Request an update

You should drive all changes to the DOM via the template, and think of the data you're using to render your template as the "view data".  If you want to do an optimistic drop, you need to update the view data (i.e. "change the source array on drop") and have `lit-html` render that.

If the data in the client that represents the server data can be divergent from the desired current render state (even for some amount of time), then I would recommend modeling that as such in your app (i.e. have "server data" and "view data" separate, and have explicit actions that update one to the other).  A simple example: https://jsbin.com/botepol/edit?html,output

Reconciling e.g. failed changes on the server with the view data is outside of the scope of responsibility of `LitElement`/`lit-html`.

**Comment by mercmobily** [comment]
That's what I thought.
Thanks for responding.
