### ISSUE TITLE
Unexpected token in lit-element node module

### ISSUE THREAD

**Issue by KaushalKhamar** [Polymer/lit-element#1045]
When running my application I am getting the issue of Unexpected token in lit-element node module

```
./node_modules/lit-element/lib/decorators.js
SyntaxError: C:\Development\Teams development\teams-master\node_modules\lit-element\lib\decorators.js: Unexpected token (209:21)

  207 |     name) => {
  208 |         const descriptor = {
> 209 |             async get() {
      |                      ^
  210 |                 await this.updateComplete;
  211 |                 return this.renderRoot.querySelector(selector);
  212 |             },
```

**Comment by LarsDenBakker** [comment]
We've been getting reports from open-wc users about this as well. 

It works fine in chrome: https://jsbin.com/mejatexuni/edit?html,output I wonder if it's not a bug in babel.

**Comment by LarsDenBakker** [comment]
Ah, there we go https://github.com/babel/babel/issues/11914

**Comment by KaushalKhamar** [comment]
But i don't think i am using babel in my react application.
@LarsDenBakker  Can you plese let me know where i need to add this in my application in order to resolve this issue?

```
"resolutions": {
  "@babel/core/@babel/parser": "7.11.0"
}
```

**Comment by LarsDenBakker** [comment]
This is fixed in babel, so if you reinstall to get the latest dependencies it should work.

**Comment by KaushalKhamar** [comment]
Adding **@babel/parser": "7.11.2** in **devDependencies** works for me.


```
"devDependencies": {
    "@babel/parser": "7.11.2"
  },
```
