### ISSUE TITLE
can't install LitElement

### ISSUE THREAD

**Issue by itsarnavsingh** [Polymer/lit-element#1054]
```npm install --save lit-element
npm ERR! Unexpected end of JSON input while parsing near '...,"dist":{"shasum":"ea'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\O\AppData\Roaming\npm-cache\_logs\2020-08-11T16_56_35_119Z-debug.log

```

**Comment by justinfagnani** [comment]
I think we'll need more information for this. We haven't had other reports of problems and haven't published a release in a little while, so I suspect something is happening on the npm side of things.

**Comment by justinfagnani** [comment]
I suspect npmjs.org was having problems on that day. Please reopen if this is still a problem.
