### ISSUE TITLE
Unexpected input range behavior 

### ISSUE THREAD

**Issue by jlesquembre** [Polymer/lit-element#106]
### Description

See the demo, I was expecting both input ranges to had initially the same value.

#### Live Demo

https://stackblitz.com/edit/lit-element-range?file=index.js

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

### Versions

- lit-element: v0.5.2
- webcomponents: v2.0.2

**Comment by jlesquembre** [comment]
@Link2Twenty I'm getting the same results using `$=` instead of `=` (on Chrome 66)

**Comment by Link2Twenty** [comment]
What are you expecting steps to do, do you know it's invalid syntax?
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range
Do you mean to do step?

**Comment by jlesquembre** [comment]
@Link2Twenty you are right, my mistake, I mean `step`. I updated the [example](https://stackblitz.com/edit/lit-element-range?file=index.js), and added a version with `$=`, but as you can see, the error is still there

**Comment by pshihn** [comment]
This is not lit-html related. If you do the same in raw javascript, you get the same issue (at least in Chrome): https://jsfiddle.net/shihn/4bux526p/8/
The declared node vs node created by javascript. I think the `defaultValue` is set in the constructor and not reset when the range values change. 
The best solution would be the set the initial value yourself.

**Comment by jlesquembre** [comment]
@pshihn Right, I guess lit-html is generating the element like in your example, since there is an expression on the template. And probably if there isn't an expression, lit-html uses `innerHTML`, maybe like this:
https://jsfiddle.net/4bux526p/24/

I'll set the initial value myself, but I still think that the behavior is bit confusing.

**Comment by sorvell** [comment]
As noted, this is just how the input element works. I'd recommend setting the input's `value` property. It's more clear and it avoids this issue.
