### ISSUE TITLE
 Overriding a component is no longer possible

### ISSUE THREAD

**Issue by BenoitClaveau** [Polymer/lit-element#1070]
With lit-element 2.1.2 I could override the render function of a component.
With lit-element 24.0 my component show me 'Object object'

My component extend a componented already extended. (Work if only 1)

Component A:
```
render() {
  return html`
    ${ this.renderComponent()}
  `;
}

renderComponent() {
  return null`;
}
```

Component B (B extend A)
```
renderComponent() {
  return html`<div>B</div>`;
}
```

Component C (C extend B)
```
renderComponent() {
  return html`<div>C</div>`;
}
```

Thx

**Comment by justinfagnani** [comment]
Sounds like you have multiple copies of `lit-html` in your node_modules folder.

Run `npm ls | grep lit-html` to find out, and if so `npm dedupe` usually fixes it.

**Comment by BenoitClaveau** [comment]
@justinfagnani I clear node_modules and get the same error.

**Comment by BenoitClaveau** [comment]
@justinfagnani Fixed with npm dedup. thx
