### ISSUE TITLE
LitElement CSS delete content-visibility:auto; style

### ISSUE THREAD

**Issue by herberthobregon** [Polymer/lit-element#1071]
## Description
- Who wants the functionality
 **everyone**
- What it is they want
don't delete content-visibility:auto; in css``
- Why they want it
- Functional description of task/subtask
```
.content {
    overflow-y: auto;
    content-visibility:auto; /* <--- don't delete this */
}
```

## Acceptance criteria
What the card must do in order to accept it as complete. Acceptance Criteria must be concrete or measurable.

**Comment by justinfagnani** [comment]
LitElement doesn't modify any CSS. We're going to need more information, ideally an online reproduction, to investigate this.

**Comment by herberthobregon** [comment]
So sorry! is my bundler (plugins in webpack)
I check in [https://codesandbox.io/s/litelement-vanilla-f4q54](https://codesandbox.io/s/litelement-vanilla-f4q54) and everything is ok!

>To check in condesanbox example, enable 
>chrome://flags/#enable-experimental-productivity-features


@justinfagnani thanks!
