### ISSUE TITLE
function string of styleMap and classMap get inserted into DOM

### ISSUE THREAD

**Issue by DominicTobias** [Polymer/lit-element#1074]
lit-html: 2.4.0
rollup: latest with nodeResolve and commonJs plugins

Hi, I have imported the directives like this and can confirm they have been imported as proper functions:

```js
import { classMap } from 'lit-html/directives/class-map';
import { styleMap } from 'lit-html/directives/style-map';
```

![Screenshot 2020-09-05 at 02 53 00](https://user-images.githubusercontent.com/760314/92276244-33ca2100-ef23-11ea-8c54-d569027ee8c3.png)

However when rendering them (in a vanilla React Gatsby project) the actual function as a string is inserted:

```js
@property({ type: Boolean })
  resizing = false;

  render() {
    return html`<div
      class=${classMap({
        wrapper: true,
        resizing: this.resizing,
      })}
      style=${styleMap({
        backgroundColor: 'blue',
        border: '1px solid black',
      })}
    >
      <div class="grip"></div>
    </div>`;
  }
```

![Screenshot 2020-09-05 at 02 50 55](https://user-images.githubusercontent.com/760314/92276135-03828280-ef23-11ea-8b03-5c6a02565c24.png)

Have you seen this before/any ideas why? Thanks

**Comment by justinfagnani** [comment]
This happens when you have multiple copies of lit-html in your project and you use `classMap` from one copy with a `render()` from another copy.

You could look at `window.litHtmlVersions` to see how many copies of lit-html there are. You can run `npm ls` to see where they're coming from, and `npm dedupe` often fixes the problem.

**Comment by DominicTobias** [comment]
Aha thanks, looks like I only have one version in node_modules but it comes up twice `window.litHtmlVersions
(2) ["1.3.0", "1.3.0"]` will keep digging

**Comment by DominicTobias** [comment]
I've now tried compiling with babel typescript and typescript, and loading the components in CRA and Gatsby, still the same issue 🤔

![Screenshot 2020-09-05 at 14 40 58](https://user-images.githubusercontent.com/760314/92299573-ff3b8100-ef85-11ea-8342-036e9042f167.png)

When logging it seems that lit-html.js is called twice, once in a normal environment and once in a bizarre one where window.alert and window.console are not defined. It seems that Webpack does something strange and calls this module twice. So it seems to me that lit-html isn't compatible with webpack.
