### ISSUE TITLE
recommended way to asynchronously fetch data for render call?

### ISSUE THREAD

**Issue by mkay581** [Polymer/lit-element#108]
### Description
~In the constructor on the [Bigger Example on the README](https://github.com/Polymer/lit-element/tree/fb90e7640777cab01c9eac2006cde558c34b041d#bigger-example), it shows to `await this.renderComplete`, but `await` can only be used inside of an `async` function and the constructor function is not marked as `async`.  It seems that the spec doesn't say anything about a class allowing asynchronous constructor functions.~ This was clarified below. I missed that the `async` is declared in the click event function inside constructor.

At any rate, the readme doesn't seem as clear about this, but what is the recommended way to asynchronously fetch data and use it in the `_render` call?

**Comment by Link2Twenty** [comment]
The `await` is inside the event listener function, which is async.

```JS
this.addEventListener('click', async (e) => {
      this.whales++;
      await this.renderComplete;
      this.dispatchEvent(new CustomEvent('whales', {detail: {whales: this.whales}}))
    });
```

**Comment by mkay581** [comment]
ah yes, sorry I missed that! Can you answer the second question I had here?

**Comment by pshihn** [comment]
@mkay581 You can call `_requestRender()` when your async data is ready, or update one of the properties that will also call a render.

**Comment by mkay581** [comment]
Thanks. Which lifecycle hook should I be using to asynchronously fetching my data? If I use `_requestRender()`, wouldn't the view be rendering for the first time unnecessarily then? Also after the data is ready, if I'm updating six operties on the component, wouldn't this render the component six times?

**Comment by pshihn** [comment]
@mkay581 updating n properties do not cause re-render n times. It just gets marked dirty and gets re-rendered once. 
As to when to fetch your data - it all depends on your application and what its state is. You could do it in the constructor of the element, as long as you are just setting the properties when the call comes back. If you want to be sure that the DOM is ready, you can do it in `connectedCallback`

**Comment by mkay581** [comment]
> updating n properties do not cause re-render n times. It just gets marked dirty and gets re-rendered once.

this doesn't seem correct because I've tried doing this and it does re-render n times. How could it mark it as dirty if lit element doesn't even know that the data and properties are being updated asynchronously? Is there some sort of run loop I'm not aware of that happens so that the code knows exactly when the "last" property is updated in order to render the component again?

**Comment by pshihn** [comment]
When you declare properties, a listener is added to its mutator. See this line of code that gets called with a bunch of property changes: https://github.com/Polymer/lit-element/blob/master/src/lit-element.ts#L180 

I've created an example for your use case: https://stackblitz.com/edit/lit-element-example-veuwoe?file=index.js

It loads properties asynchronously a second later and update 3 properties. In `_didRender`, I print the render count to the console. The render count only goes up by one.

**Comment by pshihn** [comment]
Also, keep in mind that lit-html is smart about updating properties, so it's not like the whole dom gets updated. Only the parts affected by the properties.

**Comment by pshihn** [comment]
@mkay581 You can do it in the constructor if your async call back is not manipulating the DOM. 
https://stackblitz.com/edit/lit-element-example-ku954n?file=index.js

btw, the connectedCallback is independent of your `display` property. It's called when the node is added to the DOM, not when it's made visible.

**Comment by mkay581** [comment]
Yeah the `connectedCallback()` is not called when component is made visible again, which is my point. I can't use `connectedCallback()` method because I actually need new data to be freshly fetched everytime the page (component) is shown. The `constructor` isn't an option because the DOM isn't ready, it's only called once, and I actually want to render the fetched data and not render the component unnecessarily until this data is fetched.

**Comment by pshihn** [comment]
I think, now I know what you want. How about you do this in your `_render` method

```javascript
_render() {
  if (!this.dataLoaded) {
    return html ``;
  }
  return html`...... your html....`;
}
```

and when your data is loaded update the dataLoaded property or called _requestRender

**Comment by Westbrook** [comment]
I discussed this with @mkay581 via slack and got some more information to help clarify an answer. In his context, he's working with `iron-pages` to display content and only wants to request the data for a page when it is the active page. To do so he's using code like so:

```
<iron-pages selected="0" attr-for-selected="active">
  <page-with-async-data-one active>One</page-with-async-data-one>
  <page-with-async-data-two>Two</page-with-async-data-two>
  <page-with-async-data-three>Three</page-with-async-data-three>
</iron-pages>
```

In the `page-with-async-data-one` I'm suggesting he relies less on `lit-element` and more on general JS to see something like the following manage his data:

```
static get properties() {
    return {
      active: Boolean
    }
}
connectedCallback() {
   super.connectedCallback();
   this.getAsyncData();
 }
get active() {
  return this._active;
}
set active(active) {
  if (active) this.getAsyncData();
  this._active = active;
}
getAsyncData() {
  if (this._gettingData) return;
  this._gettingData = true;
  //...request async data;
}
dataLoaded(data) {
  this.data = data;
  this._gettingData = false
}
_render() {
  if (this._gettingData) {
    return html `Loading...`;
  }
  return html`Something with all of the data put into a template.`;
}
```

@pshihn Thanks for the clarification on the rendering system, it made explaining this part much easier. Hope this helps anyone else who runs into this issue.

**Comment by mkay581** [comment]
Thanks @Westbrook  and @pshihn! I think I'm good to go now. Closing..

**Comment by nemethmik** [comment]
I have elaborated an even cleaner and a lot simpler solution to this problem. The trick is that your data loader function should be async, of course, and it should start with `await new Promise((r) => setTimeout(r, 0))`, which gives enough chance to Lit Element to complete the first rendering cycle.
```typescript
  ...
   override connectedCallback():void {
        super.connectedCallback()
        this.addData()
    }
    async addData():Promise<void> {
        //Call this from the constructor. Don't call it from firstUpdate
        //THIS IS VERY IMPORTANT TO GIVE a chance to the component to construct itself
        await new Promise((r) => setTimeout(r, 0))
        this.busyIndicator.active = true //This is a component on the page
        try {
            //THIS IS IMPORTANT TO FORCE the Busy indicator to kick in
            this.products = []
            await new Promise((r) => setTimeout(r, PageProducts.DEMODELAYFORDATALOAD))
            const response = await fetch("./products.json")
            const data = await response.json()
            this.products = [...data]
            this.busyIndicator.active = false
            //See https://lit.dev/docs/components/events/ why the need for this 0 timeout await :)
            await new Promise((r) => setTimeout(r, 0))
            this.dispatchCustomEvent("populate",this.products.length)
        } finally {
            this.busyIndicator.active = false //In case of exception
        }
    }
```
This is so usual scenario, that it could be built into Lit Element itself.

**Comment by justinfagnani** [comment]
See https://www.npmjs.com/package/@lit-labs/task

**Comment by dss010101** [comment]
> See https://www.npmjs.com/package/@lit-labs/task

is this the recommended way of doing async calls over say using fetch?  if so can you elaborate as to why?
