### ISSUE TITLE
TypeError: Illegal invocation error is thrown when using  queryAssignedNodes with text nodes

### ISSUE THREAD

**Issue by dmondev** [Polymer/lit-element#1088]
### Description

queryAssignedNodes throws A "TypeError: Illegal invocation" when slotted content contains text nodes.

#### Live Demo
https://webcomponents.dev/edit/FXrFMojSYzYa8eJNaJzh

#### Steps to Reproduce

1. Create `my-element` with child nodes containing text.

#### Expected Results
No error is throw

#### Actual Results
TypeError: Illegal invocation is thrown

### Browsers Affected (Haven't tested in other browsers)
- [x ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

### Versions
Uses the default/current version in https://webcomponents.dev

**Comment by sorvell** [comment]
Acknowledged. This is due to a typo in the code and there's obviously not a good test for this. We'll work on getting it fixed. Thanks.
