### ISSUE TITLE
_requestRender -> requestRender version issue

### ISSUE THREAD

**Issue by pshihn** [Polymer/lit-element#109]
### Description
Not a traditional issue.
The change from `_requestRender` to `requestRender` should have been released as v0.6, no?
When dependency is set to `^0.5.1` it will fetch `v0.5.2` which will break the code using `_requestRender`.
(I'm not really sure about standard versioning practices, thought I'd check)

#### Steps to Reproduce
Not really a step to reproduce, but a code sample where it broke:
https://github.com/wiredjs/wired-elements/blob/da4f150c04a336df41e228b794f14663f54b6d6f/packages/wired-card/wired-card.js#L55
[Related issue on wired-elements](https://github.com/wiredjs/wired-elements/issues/31)

### Browsers Affected
- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari 11
- [x] Safari 10
- [x] IE 11

### Versions
- lit-element: v0.5.2

**Comment by pshihn** [comment]
I updated my code to call `requestRender` instead and created a new release for the component. I don't know if anyone else was affected. Probably safe to add it back and deprecate for now.

**Comment by sorvell** [comment]
You're right. Sorry about this. Please also note, that version 0.6 will have some breaking API changes. It's currently released as a `dev` version if you'd like to take a look.
