### ISSUE TITLE
Example on animating array of items rendered 

### ISSUE THREAD

**Issue by andrewscofield** [Polymer/lit-element#1099]
## Description
Looking for an example on how to animate an array of items attached to my rendered template. For example below, if the items array gets changed and milk gets moved to the bottom of the array, it renders instantly. What is the best strategy to manage this? 

```
import { LitElement, html } from 'lit-element';

class MyElement extends LitElement {
  static get properties() {
    return {
      items: { type: Array },
    };
  }
  constructor() {
    super();
    this.items = ['milk','apples','cheese','chips','salsa'];
  }
  render() {
    return html`
      <ul>
        ${this.items.map(i => html`<li>${i}</li>`)}
      </ul>
    `;
  }
}

customElements.define('my-todo', MyElement);

```

**Comment by sorvell** [comment]
Sorry for the delay on this. We don't have good guidance right now for accomplishing this type of animation, but we hope to include some examples in our next major release which we're working on right now.

Generally, you can animate changes like this using the [FLIP technique](https://aerotwist.com/blog/flip-your-animations/). In lit-element, you can capture the "before" state of the DOM in `render` and apply changes to the after state in `updated`. This can also be done with lit-html directives but applying the "after state" must be done in `requestAnimationFrame` to be able to go after rendering. 

Here's a very simple example using a directive: https://stackblitz.com/edit/lit-element-animation-demo?file=src/my-element.js.

To handle elements being removed from the DOM a directive would need to manage a `templateResult` directly to be able to control the DOM removal.

**Comment by andrewscofield** [comment]
Thanks, this if very helpful to see your example using a directive. I thought I should be trying to do this at some part of the lifecycle and couldn't figure out which one. I've never written a directive before but it looks like that's the way to go so I'll have to read up on them.
