### ISSUE TITLE
Prettier

### ISSUE THREAD

**Issue by merlinnot** [Polymer/lit-element#110]
Hey, I'd like to propose switching from clang-format to [Prettier](https://prettier.io). I was recently going through the code of LitElement and the output of clang-format seems less clean and readable, at least to me. Other Google projects are happily using Prettier, like `firebase-js-sdk`.

What do you guys thinks? I'd be more than happy to make a PR.

**Comment by sorvell** [comment]
Thanks for the feedback. Not saying you're wrong, but we're going to stick with clang-format for now since it's got some configuration options we need.
