### ISSUE TITLE
Comment within html tag function makes rendering not to work properly

### ISSUE THREAD

**Issue by GHNewbiee** [Polymer/lit-element#1104]
# Description
When comment, under special circumstances, is included in an `html` tag function, then rendering fails.

# Steps to Reproduce
```ts
import { LitElement, customElement, css, html } from 'lit-element';

const styles = css`.main {...}`;

@customElement('my-element')
export class MyElement extends LitElement {
  static get styles() {
    return css`${styles}`;
  }

  render() {
    return html`
      <div>${styles}</div>  /* It works fine. */
      <!-- <div>${styles}</div> -->  /* It works fine, too. */
      <div>${myStyles}</div>  /* This causes rendering to fail. */
      <!-- <div>${myStyles}</div> -->   /* **This causes rendering to fail again!** */ 

      <div class="main">
        ...
      </div>
    `
  }
}
```
If we change `<div>${styles}</div>` into `<!-- <div>${styles}</div> -->` it works fine and one can wrongly assume that `<!-- -->` works as expected.

If we change it into `<div>${myStyles}</div>` then rendering fails. I suspect that happens because `${myStyles}` cannot be evaluated since `myStyles` does not exist; although, a warning could be rendered, like `#Failed`.

But if we change it into `<!-- <div>${myStyles}</div> -->` then rendering does fail again. `<!-- -->` within <code>html\`\`</code> does not work as expected.

**Comment by sorvell** [comment]
In lit-html we use standard Javascript as an input to rendering the template so we depend on Javascript error semantics before values get to lit-html. As noted, I believe the issue here is that `myStyles` is not defined. You should see an exception in the console stating this. This is standard Javascript behavior and I'm not sure we could do anything better. 

Hopefully that addresses the issue. Feel free to re-open if needed.

**Comment by justinfagnani** [comment]
I think the issue to understand here is that HTML comments are part of the template string contents and not the JS, so they do not comment out the JS expressions in the template:

From JS, this:
```ts
html`<!-- <div>${myStyles}</div> -->`
```
is not very different from :
```ts
html`${myStyles}`
```

and in each case `myStyles` is being referenced, and will cause an error if it's not declared.

**Comment by GHNewbiee** [comment]
@sorvell (*FOA thanks for your time and help*)
> ...
> You should see an exception in the console stating this.

Yes, I do see that.

> This is standard Javascript behavior and I'm not sure we could do anything better.

It is obvious that there is something weird in Javascript's behaviour in case of 
```js
html`<!-- <div>${myStyles}</div> -->`
```
Asking you to correct the Javascript's behaviour is out of the project's scope. But you might avoid "propagating" that weird behaviour by *filtering* all the comments before rendering the <code>html\`\`</code> content; if that is not costly.

You could also include a short note in `Lit-html` doc about including comments in <code>html\`\`</code> tag function.

**Comment by GHNewbiee** [comment]
*FOL TAL for your time!*
@sorvell
> ...
> This is standard Javascript behavior and I'm not sure we could do anything better.

It is obvious that there is something weird in Javascript's behaviour in case of 
```js
html`<!-- <div>${myStyles}</div> -->`
```
@justinfagnani
> I think the issue to understand here is that HTML comments are part of the template string contents and not the JS, so they do not comment out the JS expressions in the template:

In any case, comments should not cause any problem; comments should be in a "sealed box" without leak from any direction (i.e. from in to out, and from out to in).

**General**
"Propagating" that weird behaviour could be avoided by *filtering* all the comments before rendering the <code>html\`\`</code> content; if that is not costly.

If you are aware of more weird behaviours that causes similar problems, and "filtering" is costly, an additional `debug` method may be adopted for dev purpose.

You could also include a short note in `Lit-html` doc about comment's behaviour in <code>html\`\`</code> tag function and any other weird one you are aware.

**Comment by GHNewbiee** [comment]
Also the use of <code>`</code> within a <code>html``</code> comment causes problem:

```js
<!-- <div>This causes `cocoblocko`!</div> -->
```
`JS` very correctly parses and interprets the `<!-- -->` string as a `string` without any special `meaning` within <code>html``</code> tag function.

I believe that the implementation of <code>html``</code> tag function does not take care for the correct parsing of `<!-- -->` and its content but let the browser to catch the problem. It seems that it is more easier. Are you sure that have not forgotten to seal the box? -;) *TAL for your time*

**Comment by GHNewbiee** [comment]
>~It is obvious that there is something weird in Javascript's behaviour in case of~

**Update**: It is obvious that there is **not** something weird in Javascript's behaviour in case of
```js
html`<!-- <div>${myStyles}</div> -->`
```
>~Asking you to correct the Javascript's behaviour is out of the project's scope. But you might avoid "propagating" that weird behaviour by *filtering* all the comments before rendering the <code>html\`\`</code> content; if that is not costly.]~

**Update**: *filtering* all the comments before rendering the <code>html\`\`</code> content is required.

**Comment by justinfagnani** [comment]
@GHNewbiee if `myStyles` isn't defined, there's nothing we can do, you'll always get a JavaScript error. We also can't handle unescaped <code>\`</code> inside a template, as that ends the template itself in JavaScript. You need to escape it like <code>\\`</code>.

**Comment by GHNewbiee** [comment]
Since I am not an IT folk and my knowledge and skills are really limited, please let me know
- if removing all comments `<!-- ... -->` from the <code>html\`content\`</code> before rendering is possible, and
- if `content` can be transformed on the fly by using for example `content.replace(regex(commentCatcher), '')` and render the new content which is free of any comments, and hence any strings which may interfere with JS, and
- if that removing is quite expensive so as you let the browser to catch the error.

If the 1st answer is negative, then I really and deeply apologize for wasting your time and bothering you! *TALIA*

**Comment by justinfagnani** [comment]
I'm trying to explain that your error likely has nothing to do with the HTML comment. You're referencing a JavaScript variable that doesn't exist. The contents of the template don't matter. The inside of the template expressions (inside `${}`) are _JavaScript_ and the error that `${myStyles}` causes is a JavaScript error, far before lit-html even runs.

It's the same as:

```js
let x = myStyles; // Error, myStyles doesn't exist!
return html`${x}`;
```

The error is completely outside of lit-html's knowledge or control.

**Comment by GHNewbiee** [comment]
**Sorry**, I have been wrong!

Perhaps, a quick practical way to isolate `JS` variables from comments w/o erasing them is to remove the `$`.

**Mea culpa!**

**Comment by GHNewbiee** [comment]
> if myStyles isn't defined, there's nothing we can do, you'll always get a JavaScript error.

> The error is completely outside of lit-html's knowledge or control.

@justinfagnani I have seen in new [Lit](https://lit.dev/docs/templates/expressions/#invalid-locations) that the bug has been fixed. Well done!

>  We also can't handle unescaped <code>\`</code> inside a template, as that ends the template itself in JavaScript. You need to escape it like \`.

@justinfagnani One day, a solution will be found. `<!-- -->` **must** be a sealed box; whatever it includes should be hidden. Any other behaviour is a logical mistake ie a bug; in that case, maybe an "expensive" bug!
