### ISSUE TITLE
More strict types of callback parameters

### ISSUE THREAD

**Issue by merlinnot** [Polymer/lit-element#111]
Types of lifecycle callback parameters are very generic, namely `object`. We could leverage polymorphic `this` and mapped (`Partial` in particular) types to make it more strict.

I'll follow up with a PR.

**Comment by sorvell** [comment]
Sorry for the delay on this. The API has changed a good bit (merged to master and to be released in version 0.6). Please re-file this issue if the problem persists in the new version. Thanks.
