### ISSUE TITLE
Error throw when accessing queryAssignedNodes getter

### ISSUE THREAD

**Issue by ErikGrimes** [Polymer/lit-element#1122]
### Description
An error is throw when accessing the getter created by queryAssignedNodes with a filter targeting a slot containing nodes that are not elements.
#### Repository
https://github.com/ErikGrimes/lit-query-assigned-nodes-issue

#### Steps to Reproduce
Example:

1. Clone the repo
2. npm i
3. npm run storybook
4. Navigate to "AssignedNodes" -> "Simple"
5. Open the devtools console
6. Click boom

#### Expected Results
No error is throw

#### Actual Results
Error is thrown

_Chrome_
```
decorators.ts:470 Uncaught TypeError: Illegal invocation
    at decorators.ts:470
    at Array.filter (<anonymous>)
    at HTMLElement.get [as slotted] (decorators.ts:466)
    at HTMLElement.__goBoom (AssignedNodes.ts:20)
    at EventPart.handleEvent (parts.ts:532)
    at HTMLButtonElement.EventPart.__boundHandleEvent (parts.ts:490)
```
_Firefox_
```
Uncaught TypeError: 'webkitMatchesSelector' called on an object that does not implement interface Element.
```
_Safari 14_
```
TypeError: Can only call Element.webkitMatchesSelector on instances of Element
```

### Browsers Affected
- [x] Chrome
- [x] Firefox
- [x] Safari 14

### Versions
- lit-element: v2.4.0
- webcomponents: v2.5.0

**Comment by sorvell** [comment]
This was fixed via https://github.com/Polymer/lit-element/pull/1092/files and will be picked up in the next release which we can prioritize.

**Comment by slavoroi** [comment]
It was merged in October 2020 while the latest version came out in August 2020, which version fixes it?
