### ISSUE TITLE
lit-html + polymer templatize interop issues

### ISSUE THREAD

**Issue by mkorenko** [Polymer/lit-element#113]
Currently there is no way to set external event handlers or bindings inside templates that are passed to polymer elements that are using templatize for stamping instances of those templates:

```html
<iron-list items="${items}">
  <template>
    <div on-click="no_way_to_set_click_handler_here">
      ${this_template_part_throws_error}
      <!-- that works --> [[item]]
    </div>
  </template>
</iron-list>
```

There was an attempt to workaround bindings inside of templates in Polymer/lit-html#50 and it even works, but the PR was closed.
Event handlers issue can not be resolved is similar way, as you have to set event listeners on each instance of the template.

**Comment by mkorenko** [comment]
Polymer/lit-html#45

**Comment by sorvell** [comment]
Mixing binding types like this is not generally supported. Inside the iron-list template, this is a Polymer controlled binding context, outside it, the template parts are controlled by lit-html.

In addition, Polymer's binding system is somewhat limited when used outside of a Polymer element. In particular, bindings that rely on the outer scope, including computed properties and event listeners, won't work. You can, however, use event delegation to process events. Here's a quick example: http://jsbin.com/qunadi/1/edit?html,output.

A more long term solution for integrating a virtual list with LitElement will be to use [virtual-scroller](https://github.com/valdrinkoshi/virtual-scroller/blob/master/README.md). It's being designed such that it should work well with lit-html and LitElement.

**Comment by mfons** [comment]
I updated this jsbin to work with 0.6.1 of lit-element:  [http://jsbin.com/yedujav/edit?html,output](http://jsbin.com/yedujav/edit?html,output)
