### ISSUE TITLE
Under certain conditions, errors inside updated method are silenced

### ISSUE THREAD

**Issue by DimaDK02** [Polymer/lit-element#1131]
## 🐛 Bug Report

Under certain conditions, all errors inside `updated` method are silenced. This complicates debugging and can introduce very difficult to debug and unclear issues.

## To Reproduce

- Set some property inside `firstUpdated` method
- Inside `updated` method throw an error when another property changes

## Actual behavior

Error is caught and silenced inside [updating-element.ts line 720](https://github.com/Polymer/lit-element/blob/v2.4.0/src/lib/updating-element.ts#L720)
No error in the console

## Expected behavior

Error is thrown and visible in the console

## Link to reproducible sandbox

https://stackblitz.com/edit/znghnm?file=my-element.js

Note: when set property inside `connectedCallback` everything works fine. But it should also work fine when set inside `firstUpdated`

**Comment by sorvell** [comment]
This is a dup of https://github.com/Polymer/lit-element/issues/1081 and is fixed in the next major version. We hope to release the next version this quarter.
