### ISSUE TITLE
Default properties values are not working

### ISSUE THREAD

**Issue by jimsimon** [Polymer/lit-element#114]
### Description
Default values are not being applied when a property has one specified and its corresponding attribute is not defined.

#### Live Demo
https://lit-element-example-km85zd.stackblitz.io

#### Steps to Reproduce
1. Create `my-element`
2. Define a property with a default value
3. Use the default value in the element's template
4. Append `my-element` to document.body

#### Expected Results
The default value should be rendered

#### Actual Results
The default value is not rendered (nor is it passed to `_render` in the props object)

### Browsers Affected
- [x] Chrome -- other browsers were not tested

### Versions
- lit-element: v0.5.2
- webcomponentsjs: v2.0.2
- polymer: v3.0.2

**Comment by jsilvermist** [comment]
Default values are set in the constructor, not in the properties object.

```js
constructor() {
  super();

  this.mood = 'happy';
}
```

**Comment by jsilvermist** [comment]
Yes, using Polymer you can set the default value in properties or the constructor, for lit-element it uses the constructor only.

**Comment by jimsimon** [comment]
Ah okay.  Are there any other property restrictions?  I feel like I may have missed some documentation somewhere.

**Comment by mkay581** [comment]
Yeah, `observer`, `readOnly`, `notify`, etc are all not available in a Lit Element. It may be helpful to remember that a Polymer element is not a Lit element and, while they both do support the concept of `properties`, they are very different classes.

**Comment by jimsimon** [comment]
That makes sense, I'd just add that it's not super clear from the README and it's easy to make assumptions since this element is part of the Polymer project.  Would it make sense to add some sort of feature comparison to `PolymerElement` in the README?

**Comment by myfreeweb** [comment]
Looks like another difference is that attributes are not converted to camelCase when mapped to properties...

**Comment by hzmnet** [comment]
how to solve somehow we want to get values from an element prototype?
when we get value from "litelemnt.prototype.accessKey" the browser gets an error and stops running the code.
