### ISSUE TITLE
render html not displaying variables when extending from a node_modules class

### ISSUE THREAD

**Issue by vlaraort** [Polymer/lit-element#115]
### Description
render html not displaying variables when extending from a node_modules class

#### Live Demo
https://plnkr.co/edit/xMJxFi8YER0L22maiiUx?p=preview
(This works, but its as reference explained later, I can't reproduce because I can't add node_modules into plnkr)

#### Steps to Reproduce
In the provided example, we have a component, extending from a parent component, which extends from litElement, and it works well.

BUT, if my-parent-element.js is located inside node_modules, render() is working wrong.

If you create a project with this, and you locate `my-parent-element.js` into a node_modules folder, the variables are not getting displayed.

1. Copy `index.html` to a project
2. Copy `my-parent-element.js` to `node_modules/test/my-parent-element.js`
3. Change `import MyParentElement from './my-parent-element.js'` to `import MyParentElement from 'test/my-parent-element'`
4. Run `polymer serve`

#### Expected Results
Display:
Web Components are great!

#### Actual Results
Display:
Web Components are !

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [x] IE 11

### Versions
- webcomponents: v2.0.2
- lit-html: v0.10.2

**Comment by Westbrook** [comment]
One thing that has been noted in a number of issues is if your dependency and your app depend on different version of `lit-element` or `lit-html` you may run into this issue. Could you supply the `package.json` (as well as any lock files, preferably just the parts referencing these two dependencies) of the app and dependency to make sure that's not so?

It may also be helpful to see if you can recreate the `node_modules` basis of this issue via [Glitch](https://glitch.com/edit/#!/hello-lit-element?path=index.html:1:0) where you can make use of a `package.json` file to ensure dependencies are installed for a more direct comparison to what you're running into here.

**Comment by rafabernad** [comment]
Maybe this issue from lit-html could be related? https://github.com/Polymer/lit-html/issues/379
