### ISSUE TITLE
Performance issue in Safari (Mac): Forces layout/reflow on hover.

### ISSUE THREAD

**Issue by nirmalbaldaniya-dream** [Polymer/lit-element#1150]
### Description
In Safari (Mac), lit-element forces layout/reflow (Styles Invalidated & Styles Recalculated) on simple hovering the element. I have tried to verify it by simple demo page.

##### Stackblitz (fork/edit)
https://stackblitz.com/edit/simple-lit?file=index.html

##### Stackblitz (application)
https://simple-lit.stackblitz.io

#### Steps to Reproduce
- Open above application URL into Safari (Mac)
- Start timeline from developer tools.
- Now hover on first `H1` element.
- You will see that Styles would be Invalidated & Recalculated.

#### Expected Results
- Layout/Reflow should not be triggered.

### Browsers Affected
- [  ] Safari 14.0 (15610.1.28.1.9, 15610)

### Versions

- lit-element: v2.4.0
- webcomponents: v2.5.0

**Comment by sorvell** [comment]
Can you please verify the project link is working. It appears to be 404'ing.

Also, it seems unlikely this is related to LitElement and may be a Safari specific issue. Could you try reproducing the issue without LitElement?

**Comment by nirmalbaldaniya-dream** [comment]
@sorvell , Thank you very much for feedback! 

You are right. It's not an issue with the `LitElement` . I have updated the demo page & verified that it's an issue of the Safari with ShadowDOM. You can check the demo link. 

I'm closing the PR.

**Comment by 7999** [comment]
> @sorvell , Thank you very much for feedback!
> 
> You are right. It's not an issue with the `LitElement` . I have updated the demo page & verified that it's an issue of the Safari with ShadowDOM. You can check the demo link.
> 
> I'm closing this issue now.
@nirmalbaldaniya-dream 
hi,what do you mean the issue of Safari with ShadowDOM? I am meet a similar issue, could you give me some hint? thanks a lot
