### ISSUE TITLE
Foreach children in template - this.children unexpected behaviour

### ISSUE THREAD

**Issue by LukeTOBrien** [Polymer/lit-element#1152]
Hello there,

I have recently [asked this question on SO](https://stackoverflow.com/questions/66100062/litelement-foreach-children-in-template).  
But afther doing a bit more investigation I found some strange behaviour with th `this,children` property in Chrome and FF.  
I have created a [simple repo](https://github.com/LukeTOBrien/litelement-foreach-children) that demonstrates the behaviour.  
**With FF the behaviour happens because *one of the children contains a custom element*, if I remove the custom element then it behaves as expected,**

1) Inside `firstUpdated` the property `this.children` is returning 0 in Chrome when I expect it to be 4.  
![chrome-console](https://user-images.githubusercontent.com/16164373/107231818-a67e8180-6a18-11eb-9f7b-7b1448d0c85a.png)

2) Even more bizarrely, FireFox output 3 children, but when I expand the console log I can see `lenght: 4`.  
(`<span>` *contains a custom element*)  
![ffconsole](https://user-images.githubusercontent.com/16164373/107232460-5653ef00-6a19-11eb-85aa-b2dcd5431cb6.png)
You can see on the console log that `children.length: 3` but when I expand then `length: 4`
![ffconsole-expanded](https://user-images.githubusercontent.com/16164373/107232491-5fdd5700-6a19-11eb-9ecf-f2ee46d6c4e4.png)

Does anyone have any idea what is happening have?

**Comment by LukeTOBrien** [comment]
I have just found [this SO question](https://stackoverflow.com/questions/58035998/run-a-function-once-all-children-element-are-actually-updated).  
If I add a `setTimeout` in my `ComponentOne` then all is fine:

```ts
    firstUpdated() {
        setTimeout(() => {
        console.log("In FF, this.children == 3, in Chrome it == 0 - Why?")
        console.log("Children length " + this.children.length);
        console.log(this.children);
        console.log("Now in FF when we expand we have 4 children - Why?")
        }. 100);
    }
```

But the problem is that the children are just ordinary HTML elements, I cannot await [updateCompleted](https://lit-element.polymer-project.org/guide/lifecycle#updatecomplete)

**Comment by justinfagnani** [comment]
The best way to handle children is to assume that they change at any time (they can) and dynamically handle children changing via a slot and the `slotchage` event.

**Comment by LukeTOBrien** [comment]
hmmm, I wonder would it be possible to use [asyncReplace](https://lit-html.polymer-project.org/guide/template-reference#asyncappend-and-asyncreplace) to render the children within the template?

Now I understand more about the event loop and slots I will do some more investegation.

**Comment by LukeTOBrien** [comment]
I guess I will close this as it is expected browser behaviour...
