### ISSUE TITLE
Property Values are not always set before _firstRendered

### ISSUE THREAD

**Issue by craigjennings11** [Polymer/lit-element#116]
### Description
There are situations where the value assigned to a property in a lit-html template is not actually set on the element until after `_firstRendered` is called, thus the property value is not accessible in that method.

This is based off of [this stackoverflow question](https://stackoverflow.com/questions/50957689/litelement-rendering-template-without-values/50959750)

#### Live Demo
https://stackblitz.com/edit/lit-element-issue?file=index.js

Note that this example uses the same coding pattern found in the lit-html documentation [here](https://polymer.github.io/lit-html/guide/writing-templates.html#conditionals-ifs-and-loops)

#### Steps to Reproduce
1. Create an element that will dynamically render one of two child nodes (both should be lit-elements)
1. Assign a property value of the child elements to a variable
1. Render the parent, notice that for the first child render, the property value is properly set when `_firstRendered` is called
1. Trigger some event so that the parent node renders the second child node in place of the first one; notice that the second child's property is not correctly set when `_firstRendered` is called 

#### Expected Results
Property values are set before `_firstRendered` is called on all elements

#### Actual Results
Property value is set only on the first child element correctly. For the second child element, the first render contains only `undefined` properties then renders again once the property values have been applied. This means that when the second child's `_firstRendered` method is called, the properties have not been set to their correct values.

### Browsers Affected
- [x] Chrome
- [x] Firefox
- [x] Edge
- [ ] Safari 11 (unknown)
- [ ] Safari 10 (unknown)
- [x] IE 11

### Versions
- lit-element: v0.5.2
- webcomponents: v2.0.2

**Comment by Westbrook** [comment]
Isn't this functionality that you can opt into via `_shouldRender`?  https://stackblitz.com/edit/lit-element-issue-p3m41h?file=index.js

Being web components are required to have their constructor called without arguments, you going to get two passes on all properties, if there is a version of the properties that you don't want rendered it seems you have the lifecycle methods to do so. Every default value of a property could want from a slightly different interpolation here, so it seems better for customization that a specific approach isn't forced here. Can you think of a universally applicable test that would prevent the first call the `render()`?

**Comment by craigjennings11** [comment]
Even in your example, if you log `this.text` in `_firstRendered()` of the second child element, you'll see that the value is `undefined`. Adding the check blocks the first render if it's undefined, but does not block `_firstRendered()` from being called.

**Comment by Westbrook** [comment]
Interesting, it does seem that `_firstRendered()` is somewhat naively called in `ready()` with no gating or logic controlling it: https://github.com/Polymer/lit-element/blob/master/src/lit-element.ts#L109

Likely it's making the assumption that if you were setting your property defaults in the constructor as expected then you would already have triggered a render by that point. 🤔

It'll be interesting to see whether the team sees that as a documentation issue or a functional issue.

**Comment by bennypowers** [comment]
This situation leads to a pretty confusing developer experience:
```js
class ConfusedEl extends LitElement {
  _shouldRender(props, changed, old) {
    return false
  }

  _firstRendered() {
    console.log('hello!')
    this.shadowRoot.querySelector('#child').foo.bar()
  }
}
// hello
// Cannot Read Property foo of null
```

**Comment by craigjennings11** [comment]
I updated the snippet to use `0.6.0-dev.5` and I'm no longer seeing this problem.
