### ISSUE TITLE
Who's using LitElement in production?

### ISSUE THREAD

**Issue by ernsheong** [Polymer/lit-element#120]
Would be great to know who is using LitElement in production, as it builds the community and gives confidence in the technology.

To start the ball rolling, [PageDash](https://www.pagedash.com/) web app is using LitElement partially in production (still migrating over from Polymer 2)

**Comment by DavidValin** [comment]
Considering it. Now sure yet, due to the list of issues I see under "Issues"..

**Comment by ernsheong** [comment]
Vue has issues: https://github.com/vuejs/vue/issues
React has issues: https://github.com/facebook/react/issues

I'd say just play with it and if you are comfortable, go for it :)

**Comment by aadamsx** [comment]
I'm considering it for my next project that will go into production.  But I'm looking for more examples, maybe a LitElement form like [Meteor's](https://forums.meteor.com/), a LitElement cookbook, Developer guide, Udemy courses, Slack channel (specific to LitElement/LitHtml), etc -- we just need more help for developers for some to feel comfortable.

**Comment by eskan** [comment]
there's some slack channels related to lit and lit-element in the polymer workspace : https://polymer.slack.com

**Comment by mkay581** [comment]
I'm using it for heyimmark.com, my very very small experimental "diary". Its definitely not a complex app or anything but I've been using it to test lit elements and its been working well. Lit elements have helped alot for the more intricate details like the routing and the url-based scrolling.

**Comment by kenchris** [comment]
We have used it for a few of our demos and test applications with more to follow. Here is the manual test app for the W3C Generic Sensor API which is written using LitElement: https://intel.github.io/generic-sensor-demos/sensor-tester/build/bundled/

**Comment by LarsDenBakker** [comment]
We're using lit-html in production on a large enterprise app. Started out with polymer, now transitioning the core parts to lit. It's been a great experience so far! It's not public, so I can't show anything.

@aadamsx for examples I recommend looking at https://github.com/thepassle/create-lit-app

**Comment by merlinnot** [comment]
We use it in producion for some b2b apps at [Codemachine](https://codemachine.studio).

**Comment by yorrd** [comment]
using in production for 3 projects, several more to launch until the end of the year :v:

**Comment by MaKleSoft** [comment]
https://padlock.io/ - Current version is written in Polymer. Migrating to lit-element for v3.

**Comment by pshihn** [comment]
[Slick](https://poweredbyslick.com/) uses lit-element

**Comment by katejeffreys** [comment]
note to self re: possible future blog post

**Comment by motss** [comment]
I'm starting my own personal blog with latest `lit-element`. Going to upgrade that to `1.0 RC` later today.

Does that count?

**Comment by rickygarg** [comment]
We are using it for one workflow in our VC portfolio management tool: http://www.getfundwave.com/portfolio-management-software

Plan to use more of it once we figure how to get several modular lit-element components to work together in a non lit-element app. An example of that will be of much help!

**Comment by dowrow** [comment]
We are using it for all our front-ends (a homepage, landings, 3 web apps) at Citibox: https://citibox.com

**Comment by lpellegr** [comment]
We use lit-element and their companions for the [Ipregistry](https://ipregistry.co) dashboard:

https://dashboard.ipregistry.co

**Comment by T-Knott-Mesh** [comment]
MeshMyCampus.app

**Comment by T-Knott-Mesh** [comment]
Just released beta, up from alpha - Framework based on lit element coming Jan 2020 @ernsheong everything you see there is in house built on LitElement !

**Comment by MaKleSoft** [comment]
The latest (unreleased) version of https://padloc.app is built completely with lit-element as well. Source code here: https://github.com/padloc/padloc. We're actually looking for beta testers right now. If anybody is interested in helping out, let me know!

**Comment by T-Knott-Mesh** [comment]
Oh, and if you log on! Shoot create a direct message with me and share thoughts ! :) Also check out our new and awesome dark mode in the settings page!

**Comment by israelfloresdga** [comment]
I'm using it for a small civil association (home, calendar, directory, login, cms for admins), 

Also developing my personal page with it (home, info, blog). Is in standby because I started with the project I mentioned ealier

**Comment by kenchris** [comment]
I am using it for web platform API demos like https://kenchris.github.io/webnfc-groceries/

@larsgk

**Comment by justinfagnani** [comment]
This isn't an actionable issue currently. In the open source world, GitHub's "used by" tracker does a decent job of this. I'll close for now, and if we decide we want a "who's using lit" page, we'll open a new issue.

**Comment by atla5** [comment]
Boston University Libraries: [github repo](https://github.com/bulib/bulib-wc), [homepage](https://www.bu.edu/library/#footer), [storybook](https://bulib.github.io/bulib-wc/)
