### ISSUE TITLE
Bundling with rollup - Uncaught TypeError: Class constructor LitElement cannot be invoked without 'new'

### ISSUE THREAD

**Issue by johnlim** [Polymer/lit-element#122]
### Description
Bundling with rollup - Uncaught TypeError: Class constructor LitElement cannot be invoked without 'new'
#### Live Demo
https://github.com/johnlim/my-element.git

#### Steps to Reproduce
1) Clone the repo
2) `npm install`
3) `./node_modules/.bin rollup -c`
4) Serve index.html
5) console error `Uncaught TypeError: Class constructor LitElement cannot be invoked without 'new'`

#### Expected Results
Custom lit-element should be rendered

#### Actual Results
Console error `Uncaught TypeError: Class constructor LitElement cannot be invoked without 'new'` 

### Browsers Affected

- [ *] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

**Comment by nicolasparada** [comment]
This is an issue with babel. Try updating to version 7 or using [this plugin](https://github.com/WebReflection/babel-plugin-transform-builtin-classes).

**Comment by web-padawan** [comment]
See Polymer/tools#398 for correct Babel plugin version needed to make this work

**Comment by johnlim** [comment]
@web-padawan I've updated the Babel plugin but said issue still persists. If you'd like to have a go,  I've updated the repo with the suggested Babel version.

**Comment by Noooil** [comment]
inline your babelrc into rollup.config.js like this
`babel({
    // babelrc: false is needed to prevent reading broken .babelrc files from
    // dependencies (we have to process node_modules). Thats why we also need
    // to inline our own .babelrc file
    babelrc: false,
    presets: [["@babel/es2015", { modules: false }]],
    plugins: ["@babel/plugin-external-helpers"]
})`

**Comment by johnlim** [comment]
@Noooil Thanks! That works!
