### ISSUE TITLE
Plan for upgrading to lit-html's upcoming new syntax

### ISSUE THREAD

**Issue by justinfagnani** [Polymer/lit-element#123]
Because lit-element.js export `html` from lit-extended, upgrading to the upcoming new main module of lit-html with it's new syntax is going to be a little tricky. There necessarily has to be a breaking change, but I think we can minimize it.

I propose we phase the change over three releases of lit-element:

1. When the next version of lit-html is released, add `htmlExtended` and `htmlNew` exports. Users can import them like `import {LitElement, htmlExtended as html} from 'lit-element';`. `htmlExtended` is marked deprecated.

    `htmlNew` gives the option of adopting the new syntax right away. `htmlExtended` gives the option of making sure that the change in the next release won't cause a break. 

2. Switch the `html` export from lit-extended to the main lit-html `html` export. Deprecate `htmlNew`.

3. Remove `htmlExtended` and `htmlNew`.

We can also offer two codemods for [jscodeshift](https://github.com/facebook/jscodeshift) to make this easier: One to change from importing `html` to `htmlExtended as html`, and another to change from `htmlNew as html` to `html`. We could theoretically upgrade templates too, but that's a bit more work.

cc @sorvell @kevinpschaaf

**Comment by ernsheong** [comment]
My 2 cents is to just do a breaking change with semver, and do away with this `htmlNew`, `htmlExtended` business

**Comment by Noooil** [comment]
yeah we dont have version 1.0 yet so people knew that changes were about to be made

**Comment by LostInBrittany** [comment]
I kinda like the smooth migration path proposed by @justinfagnani even I understand the idea behind @ernsheong and @Noooil suggestion. If you can keep it smooth, do it (IMHO and all that...)

**Comment by merlinnot** [comment]
I’m also for a clean cut, if it’ll be staged, I’ll have to do project-wide changes twice, instead of doing it once and moving forward.

**Comment by justinfagnani** [comment]
Another problem with the clean cut approach is that projects that get multiple versions of lit-element and lit-html might have problems if they're sharing templates (due to instanceof not working).

We could decide to live with that pain for a short while and make projects upgrade all their templates at once to upgrade lit-element.

**Comment by abraham** [comment]
If you've got the time to do three releases, publish them all at the same time. Those of us that can can just upgrade to the latest and those that have more complex dependency graphs can upgrade as makes sense for them.

**Comment by claytongulick** [comment]
It's a simpler mental model to track significant API changes using semver than a phased/transitional approach. I'd prefer to not have to update versions/references/code twice. $0.02.

**Comment by ebidel** [comment]
+1 to what @claytongulick said. Proper semver and good release notes go a long way.

**Comment by emilio-martinez** [comment]
I agree—semver is the way to go. For projects using both lit-element and lit-html, the offset in APIs could be mitigated via peer dependency warnings.

Personally, I've been very aware that the current API isn't final when using lit-element in our projects. Having a breaking change before 1.0 seems reasonable, and could initially be introduced as 1.0 pre-releases if that helps projects transition + gather feedback.

**Comment by sorvell** [comment]
Changes are now merged to master, currently published under the `dev` tag and will be included in the upcoming `0.6` release.
