### ISSUE TITLE
Suggestion: requestRender to return a promise

### ISSUE THREAD

**Issue by MaKleSoft** [Polymer/lit-element#124]
Currently you have to write something like this, which seems a bit awkward to me.
```js
el.requestRender();
await el.renderComplete;
```
Simply having `requestRender` return `this.renderComplete` would make this a little more streamlined:
```js
await el.requestRender();
```

**Comment by sorvell** [comment]
The `requestRender` has changed to `invalidate()` in master and the upcoming 0.6 release, and it does now return a promise that resolves when the update is complete.
