### ISSUE TITLE
Misleading warning about property changes

### ISSUE THREAD

**Issue by AusIV** [Polymer/lit-element#136]
### Description
Under certain conditions, the warning:

```Setting properties in response to other properties changing considered harmful```

gets logged (often repeatedly) when an error occurred during the render process, rather than when properties changed in response to other properties

#### Live Demo
https://stackblitz.com/edit/lit-element-example-tjfppw

#### Steps to Reproduce
1. Throw an error in the _render() function.
2. Some time later, set the value of a property.

#### Expected Results
The error from the render function should be obvious in the browser's development console, and there should be no errors related to setting properties.

#### Actual Results
Any properties set after an error in the _render() function trigger the "Setting properties in response to other properties changing considered harmful" warning, which includes a stack trace. This pushes the original error up past the top of the console, making it look like the problem pertains to setting properties, distracting from the real problem

#### Cause

When properties are set, it checks to see if `element.__isChanging` is true, and logs a warning if it is (see https://github.com/Polymer/lit-element/blob/master/src/lit-element.ts#L209). 

In _flushProperties(), it sets `__isChanging = true`, calls `super._flushProperties()`, and after a success sets `__isChanging = false`. This means failures in `super._flushProperties()` leave `__isChanging == True`, so the warning will trigger until the next successful call to `_flushProperties()`.

### Browsers Affected

- [ x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

(I'm pretty sure it will effect all of the above, but I've only test on Chrome)

### Versions

- lit-element: v0.5.2
- webcomponents: vX.X.X

**Comment by sorvell** [comment]
This issue should no longer reproduce since we've removed the warning for the upcoming `0.6` release, currently in preview as `dev`. See the new [update lifecycle](https://github.com/Polymer/lit-element#advanced-update-lifecycle) for more info.
