### ISSUE TITLE
Feature Request: Add support for prop-types package (or something similar)

### ISSUE THREAD

**Issue by jimsimon** [Polymer/lit-element#138]
### Description

Please consider adding support for the prop-types package or some similar concept.  The standard static `properties` getter is great for production use, but it'd be even better to have the precondition checking that prop-types provides for development purposes.  I believe it'd be fairly easy (and inexpensive) to convert a prop-types object to a properties compatible object.

#### Live Demo
N/A

#### Steps to Reproduce

N/A

#### Expected Results

N/A

#### Actual Results

N/A

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

### Versions

- lit-element: N/A
- webcomponents: N/A

**Comment by justinfagnani** [comment]
I think runtime type-checking probably belongs at the level of a special emit mode for TypeScript, rather than something specific to LitElement. Why should only LitElement declared properties get type checking?

**Comment by justinfagnani** [comment]
We're not going to do this in LitElement. It should be possible in a subclass.
