### ISSUE TITLE
Conditional element rendering triggers excessive `render` call with undefined properties

### ISSUE THREAD

**Issue by dpikhulya** [Polymer/lit-element#143]
### Description
Rendering an element with some bound properties conditionally leads to the rendering of that element to be invoked twice, where the first rendering has a value of a bound property set to `undefined`, while a valid value is actually passed to it.

Note that the same scenario with the same property specified as an inline text (e.g. `myProp="value"` isntead of `myProp="${'value'}"`) works properly — only one rendering without an `undefined` value is invoked (see line 23 of the example below).

#### Live Demo
https://glitch.com/edit/#!/lit-element-undefined-prop-

#### Steps to Reproduce

0. [Run](https://lit-element-undefined-prop-.glitch.me/) the example above.
1. Open the browser's console.
2. Click the button to toggle the condition in `parent-element`.
3. See the `ChildElement.render: myProp is falsy` message displayed in the console, despite the `myProp` property value always getting a non-empty value.

#### Expected Results
`ChildElement.render()` is invoked only once per one condition change (per click of the button in the example), and has a valid non-undefined value for `myProp` property.

#### Actual Results
`ChildElement.render()` is invoked twice:
- Once with `myProp == undefined` (an invalid call)
- Once with `myProp == 'Non-empty value'` (a valid call)

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] IE 11

(didn't check in other browsers)

### Versions

- lit-element: v0.5.2
- webcomponents: v2.0.4

**Comment by kenchris** [comment]
Why don't you use a condition? `${myProp ? myProp : ''}`?

**Comment by sorvell** [comment]
This will be fixed in version `0.6` currently available in preview as `dev`. It's the same issue as explained here https://github.com/Polymer/lit-element/issues/129#issuecomment-416684279.

Here's the [updated example](https://glitch.com/edit/#!/destiny-talk) working with `dev`.

**Comment by sorvell** [comment]
This should also be addressed in `lit-html`. For reference, here's the [issue](https://github.com/Polymer/lit-html/issues/453).
