### ISSUE TITLE
Lit-Element not rendering when using styled buttons

### ISSUE THREAD

**Issue by vedtam** [Polymer/lit-element#147]
Hi,

In my project I use styled buttons to apply filters to a user's image. Now, when clicking a button, lit sets the property (to the right value coming from the click event) but the UI renders the penultimate value, not the current which was selected.

Worse than this, if I set the click event on a div (used as button), the UI doesn't render at all.

The only way I could get the buttons working (as expected) was by removing any styling and use a plain button element.

I created a Pen that demonstrates the above issues:
https://codepen.io/vedtam/pen/xJMOWN?editors=1000

- lit-element: v. 0.5.2
- webcomponents: v. 2.0.0

**Comment by Fischerfredl** [comment]
Hi vedtam,

I am not involved in the lit-element project, but i played around with the codepen and here is what i found:

* The blue div-btn sets the filter to "nashville", not "blue" like the other ones.
* The buttons do in fact work. They trigger the _render function and update the svg accordingly.

Chrome 68:

* The browser re-renders the svg not immediately, but after any interaction with the page (scrolling, clicking)
* The re-rendering of the svg can be triggered by placing `<div>${_filter}</div>` anywhere in the template.

Firefox 61:

* Works as expected. (Just had to change the version of the webcomponents-loader from `@next` to `@2.0.2`)

**Comment by vedtam** [comment]
Hi, 

Thanks for taking the time and trying it out. I've corrected the blue div's attribute to blue (thanks for mentioning).

Indeed if I place `<div>${_filter}</div>` into the page, it triggers a render but I'm a bit concerned about doing it in production (however until there gonna be a fix I must).

I'm wondering what's the issue with the latest version of Chrome, why does update only on scroll/click?

Thanks.

**Comment by kenchris** [comment]
Are you sure this is not a browser bug?

It never applies the filter for me in Chrome unless I resize the window containing the preview - even if I manually change the filter using DevTools

File a bug at https://crbug.com/new

**Comment by sorvell** [comment]
This looks like a Chrome bug. Filed here: https://bugs.chromium.org/p/chromium/issues/detail?id=878591
