### ISSUE TITLE
LitElment extends HTMLElement but TS type definitions get lost within mixin

### ISSUE THREAD

**Issue by emilio-martinez** [Polymer/lit-element#149]
### Description
LitElment extends HTMLElement but TS type definitions get lost within mixin

#### Live Demo
https://stackblitz.com/edit/typescript-iv8yk6

#### Steps to Reproduce

In the demo above, I'm showing two things:
- A mixin expecting to take a HTMLElement-ish constructor.
- Adding an event listener within a LitElement-created element.

The following things can be observed:
1. LitElement isn't reconized as a class that extends HTMLElement, even [though it does](https://github.com/Polymer/lit-element/blob/v0.5.2/src/lit-element.ts#L93). Applying the mixin triggers the Typescript compiler; otherwise `this` is ambiguous.
1. Trying to do standard HTMLElement stuff like `this.addEventListener` produces an error: `Property 'addEventListener' does not exist on type 'MyElement'.`

#### Expected Results
LitElement inheritance of HTMLElement should come through in type definitions.

This is likely an upstream issue with `PropertiesMixin` from `@polymer/polymer`. An issue could be opened in that repo as well, although the type definitions could probably be fixed within this project.

#### Actual Results
LitElement should be typed show it inherits HTMLElement.

### Browsers Affected

_This isn't browser related but more a type definitions issue._

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

### Versions

- lit-element: v0.5.2
- webcomponents: v2.0.4

Versions above reflected in demo. Note the demo only applies the es5 adapter.

**Comment by sorvell** [comment]
This should be fixed in master and the current `dev` release.
