### ISSUE TITLE
Make decorators work with new decorator spec

### ISSUE THREAD

**Issue by justinfagnani** [Polymer/lit-element#156]
Babel 7 has an implementation of the new spec. We should be able to make decorators detect how they're being called to work with either TypeScript or Babel 7.

**Comment by aadamsx** [comment]
Yes, Babel7!!

**Comment by HitkoDev** [comment]
While we're at it, could we add TypeScript decorator metadata support, so we wouldn't have to define property types twice?

**Comment by HitkoDev** [comment]
I believe lit/lit#3064 would solve that problem, as it will remove decorators from the code hence no need for reflection polyfill to be included in the production build.

**Comment by abraham** [comment]
I've been working on a much smaller implementation of Reflect.metadata you could try for a polyfill.

https://github.com/abraham/reflection

**Comment by blikblum** [comment]
I evaluated the possible compilers setup to support LitElement property decorator.

The source code can be found [here](https://github.com/blikblum/lit-element-decorator-tests) and the live examples [here](https://blikblum.github.io/lit-element-decorator-tests/).  

Basically the property decorator works with typescript but does not work with Babel 6 and Babel 7 (legacy). It can make work with Babel 7 (current spec) with a [few modifications](https://github.com/blikblum/lit-element-decorator-tests/blob/master/babel7/src/index.js#L7-L37).

The reason to typescript work and babel 6 / babel 7 (legacy) not work, all based in same spec ,is that the former initializes the value using a direct assignment while babel uses a Object.defineProperty call.

**Comment by justinfagnani** [comment]
@43081j I worked around that in lit/lit-element#422 by inducing a fake property with an initializer that sets the decorated property.

@littledan, you might be interested in the need to work around this. It turns out that an "initializer" as a class element isn't sufficient for us, because we still must return some element descriptor, so we still needed the fake property descriptor.

**Comment by littledan** [comment]
Yeah, we are adding a separate standalone initializer which doesn't bother defining a property, since that's a pretty common need. Took us some time to bikeshedding the name (maybe it will be `{kind: "hook", start() {}}`), but it got consensus at the last TC39 meeting. Would that solve the problem for you, or am I misunderstanding?

**Comment by trusktr** [comment]
related: https://github.com/Polymer/lit-element/issues/234#issuecomment-689811322

**Comment by bschlenk** [comment]
@HitkoDev I wrote a babel plugin that can automatically set lit-element's property type based on the typescript type info - no need for runtime reflection. https://github.com/bschlenk/babel-plugin-lit-property-types-from-ts
