### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by jogibear9988** [Polymer/lit-element#16]
Is the stamp of a lit-html element faster then the stamp of a polymer element?

**Comment by AndreasGalster** [comment]
Aye, would be nice to know how it compares. I've recently started converting a few components to lit, I'm thinking of converting a few more very tiny components that repeat like crazy in my app to lit if performance is much better :)

**Comment by jogibear9988** [comment]
Has anyone any performance results?

**Comment by vogloblinsky** [comment]
I have created a benchmark for web components librairies : https://github.com/vogloblinsky/web-components-benchmark

I will publish a blog post about that this week, but before i want to be sure my implementation is correct. I found very strange the result about deleting 50 items in my scenario.

![benchmark_delete](https://user-images.githubusercontent.com/2841805/36700951-b23dfe88-1b51-11e8-96a7-a5f6077dedd1.png)

Did i implemented something wrong ?

**Comment by kenchris** [comment]
Are you using 'repeat'? You might want to try the PR for 'repeat-splice'

**Comment by vogloblinsky** [comment]
Yes i use repeat (https://github.com/vogloblinsky/web-components-benchmark/blob/master/lit-element/js/my-todo.js#L51)

I didn't the repeat-slide PR in this repository.

**Comment by kenchris** [comment]
Potentially that could be much faster as it's ports over the same diffing algorithm that Polymer uses, though I haven't profiled it or attempted to optimize it any further

**Comment by kenchris** [comment]
It is a PR for lit-html itself

**Comment by vogloblinsky** [comment]
ok thanks i found it : https://github.com/Polymer/lit-html/pull/260

**Comment by kevinpschaaf** [comment]
The `repeat` directive is basically a placeholder implementation; it currently uses a simple/naive algorithm for updating based on changes to an array that has some degenerate cases, and we intend to improve that.  So from that point of view, it should still be considered work-in-progress and not ready for this type of performance bake-off yet.

Re: Polymer/lit-html#260, We need to explore the cost/benefit tradeoff of using `ArraySplice`, since it adds a lot of code and doesn't itself have stellar big-O perf characteristics (it has other degenerate cases).

**Comment by vogloblinsky** [comment]
Yes, i will remove WIP projects from this benchmark: lit-html, lit-element & Polymer 3

**Comment by bennypowers** [comment]
FWIW I don't think you should remove the WIP projects, since this info is still very useful to early adopters. You SHOULD however clearly mark them as WIP, perhaps with a background and a badge, or in a separate section of the page

**Comment by vogloblinsky** [comment]
Ok i will clearly sepearate them inside the graph for example.

**Comment by sorvell** [comment]
Closing this in favor of https://github.com/Polymer/lit-html/issues/242. This is also on the `lit-html` 1.0 roadmap https://github.com/Polymer/lit-html/issues/333.
