### ISSUE TITLE
Allow empty template results?

### ISSUE THREAD

**Issue by 43081j** [Polymer/lit-element#168]
Currently moving over to lit straight from polymer 2, we commonly have:

```js
if (!this.prop) {
  return html``;
}
return html`some content`;
```

Is it worth us allowing a `null` return type in `render` so we can have an empty template?

and inside lit, keep an `emptyTemplate` constant which is re-used (if needed)? 

so we can have `render(): TemplateResult|null`?

edit:

having thought again about this, in reality it is probably less efficient to have null checks in the core. i guess the only solution to this would be to have an `EmptyTemplate` constant which is an already new'd up template result.

cc @justinfagnani

**Comment by abraham** [comment]
There is some related conversations on https://github.com/Polymer/lit-html/issues/422

**Comment by mkay581** [comment]
Does returning `this.prop` in `_shouldRender()` (if using earlier versions) or `shouldUpdate()` work for you?
