### ISSUE TITLE
Attribute problem with new API

### ISSUE THREAD

**Issue by quetzalsly** [Polymer/lit-element#169]
I was learning web components by modifying the lit-element branch of polymer shop demo. Everything was fine until suddenly you guys decided to change the entire API without any warning or a changelog... Anyway my project is a learning project so I decided to update the code to work with the changes of lit-element. First of all I changed all the _render() to render() as well as the other API functions, the new properties system is using a map so I had to change that too. Now the main problem comes.

The code had a whole bunch of attributes like `<shop-home active?="${_page === 'home'}"></shop-home>` notice the `active?`. Lit-element instantly complained about that, so I decided to remove the question mark, it did not throw any errors but something broke for sure, page is behaving weirdly. The question mark thing is not the only weird attribute, there was also `aria-label$`  `class$`  and `style$` from the top of my head.

Ofcourse being a newbie I tried to just remove those extra symbols, making the lit-element error go away, but the problem to persist.

I would really love to know how to solve this problem without waiting for polymer shop to be updated. Thanks.

**Comment by jsilvermist** [comment]
The new syntax for boolean attributes is `?attr=${statement}` which replaces the old `attr?=${statement}` syntax.

Anything with a following `$` is an attribute binding, this is now the default action for bindings.

Anything without any special characters previously was a property binding, these should now be prefixed with a `.`, eg. `<my-el .prop=${statement}></my-el>`

Events were previously prefixed with `on-`, eg. `on-click=${handleClick}`. These should now be prefixed with an `@`, eg. `@click=${handleClick}`.

**Comment by jsilvermist** [comment]
For more information, check out https://polymer.github.io/lit-html/guide/ which has the latest documentation for `lit-html`.

For information on bindings specifically, see https://polymer.github.io/lit-html/guide/writing-templates.html#binding-types.

**Comment by quetzalsly** [comment]
Dammit, so everything that was not using $ has to now have a . ??? Arghhh... that means I have to manually replace 1000 occurances of this? I feel sad inside.

**Comment by jsilvermist** [comment]
Any attributes with just text were always attributes, but previously any attributes with a binding were set as properties, leading to a slightly confusing situation. Now, properties are explicitly set using `.`.

**Comment by LarsDenBakker** [comment]
Both lit-element and lit-html are in beta (0.x.x), it's written everywhere that API changes can be expected. They try to minimize it, but this was a necessary change to reduce confusion.

Attributes in markup:
* Before: <my-element foo="bar">
* After: <my-element foo="bar">

Attribute bindings:
* Before: <my-element foo$="${bar}">
* After: <my-element foo="${bar}">

Properties bindings:
* Before: <my-element foo="${bar}">
* After: <my-element .foo="${bar}">

Note how to how setting attributes in markup and bindings are similar now.

**Comment by MaKleSoft** [comment]
> you guys decided to change the entire API without any warning

There is a very clear and explicit warning in the readme:
> LitElement is currently in development. It's on the fast track to a 1.0 release, so we encourage you to use it and give us your feedback, but there are things that haven't been finalized yet and you can expect some changes.

In general, a `0.x` version always means "not stable - use at your own risk". https://semver.org/#spec-item-4

> Dammit, so everything that was not using $ has to now have a . ???

No, attribute bindings look like regular attributes now: `class$="my-class"` -> `class="my-class"`

>  Arghhh... that means I have to manually replace 1000 occurances of this? I feel sad inside

```regex
s/\(\S*\)$="\(.\{-}\)"/\1="\2"/
```

**Comment by quetzalsly** [comment]
Thanks everyone, nice regex also. I consider this issue solved.
