### ISSUE TITLE
@click not working?

### ISSUE THREAD

**Issue by rjsteinert** [Polymer/lit-element#170]
#### Live Demo

https://desert-whippet.glitch.me/

#### Steps to Reproduce
1. Clone the glitch hello lit element.
2. Add `@click="${(event) => alert('meow')}"` to the span tag.
3. Click the span tag in the live site.

#### Expected Results
Alert to pop up and say "meow".

#### Actual Results
Nothing happens.

### Browsers Affected

- [x] Chrome
- [?] Firefox
- [?] Edge
- [?] Safari 11
- [?] Safari 10
- [?] IE 11

### Versions

- lit-element: latest
- webcomponents: next

**Comment by Westbrook** [comment]
@rjsteinert Make sure you are pointing to `@dev` in order to take advantage of the new syntax.  Check out https://glitch.com/edit/#!/colorful-drink?path=package.json:9:4 to see that version of the dependency and https://colorful-drink.glitch.me/ where "eventing" will "meow" for you all day!

**Comment by jsilvermist** [comment]
To add on to what @Westbrook said/showed as an example, don't use `next` for the `polymer-cli`, this is a VERY old branch. Similarly `@webcomponents/webcomponentsjs@next` is also slightly old, but not nearly as much as the cli one.

**Comment by rjsteinert** [comment]
@Westbrook Thanks meow! desert-whippet is a go!

@jsilvermist Which version of polymer-cli and @webcomponents/webcomponentsjs would you recommend?

@notwaldorf Perhaps it's time to update the hello-lit-element project on glitch? There are a number of things that need updating such as `_render` -> `render` and no destructuring of variables in the render function.

**Comment by jsilvermist** [comment]
For the `polymer-cli` you're best using either `latest` or `^1.8.0` which currently point to the same version, but the latter is better for semver.

For `@webcomponents/webcomponentsjs`, it would be best to use either `latest`, or `^2.1.1`.

You can always use `npm [info|show|v] <package>` to see all release channels and which versions they point to, and the latest versions.

**Comment by sorvell** [comment]
Closing this in favor of an explicit issue to update the samples (https://github.com/Polymer/lit-element/issues/171). Thanks for the reminder.

**Comment by rjsteinert** [comment]
Thanks @jsilvermist - I always forget about just asking npm.

@sorvell I can relate to the tendency to have outdated glitch examples. Would be rad to have a way to fit publishing to glitch when also publishing to npm.
