### ISSUE TITLE
changed properties can be initially undefined (or always are)

### ISSUE THREAD

**Issue by 43081j** [Polymer/lit-element#175]
`_changedProperties` isn't really the same type as the properties we define as it can be `undefined` in all cases.

If we have:

```js
constructor() {
  this.foo = 5;
}
```

the first `update` call will have `foo => undefined` in the map and `this.foo = 5`.

it should really be `foo => 5` and `this.foo = 5` so both are initially the same, i think.

**Comment by sorvell** [comment]
This is by design. The idea is that `changedProperties` gives you the property values from the previous update. At the time of the first update, previous values are always `undefined`.

**Comment by 43081j** [comment]
Ah yes I see. So even if we set a property in the constructor, there isn't a "previous value" as we have never seen it change before. But it needs to be in the change map because it's initialisation is in fact a change. 

No worries. This is useful to understand for strongly typing the objects values.
