### ISSUE TITLE
When can we use the "reflect" and "attribute" property options?

### ISSUE THREAD

**Issue by kr05** [Polymer/lit-element#178]
I'm setting a property but it's not being reflected as an attribute even though I'm setting reflect to true, as explained in the documentation. Is this for the next release of lit-element?

     static get properties() {
          return {
               opened: {
                    type: Boolean,
                    reflect: true,
                    attribute: true
               }
          }
     }

     _closeDialog() {
        console.log('closing dialog...')
        this.resetValues();
        this.opened = false;
    }

Here's a screenshot of the console where I check the property and attribute:

![image](https://user-images.githubusercontent.com/11833744/45330597-048e9e00-b51b-11e8-8eda-1fa63bf147b2.png)

### Versions

- lit-element: v0.5.2
- webcomponents: v2.0.4

**Comment by sorvell** [comment]
That's right. This syntax will be supported in LitElement version `0.6` which is available as [dev](https://www.npmjs.com/package/@polymer/lit-element/v/0.6.0-dev.6) now. We realize the Readme is out of sync with the current release, but we will address this by releasing the new version shortly.
