### ISSUE TITLE
unsafeHTML no longer working as expected

### ISSUE THREAD

**Issue by mkay581** [Polymer/lit-element#182]
### Description
Weird output when using `unsafeHTML` inside of lit-element's `render()` on latest version. Was working in previous versions of lit-element. 

FWIW,  I've also tested `unsafeHTML` without lit-element which works fine. So leads me to believe the issue may be in lit-element.

#### Live Demo
https://stackblitz.com/edit/unsafe-html-lit-element

#### Expected Results
Render the passed html

#### Actual Results
Renders weird output

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

### Versions
- lit-html: v0.6.0-dev.6
- lit-element: v0.11.0-dev.3

**Comment by sorvell** [comment]
Yeah, there's a version mismatch there. Using the latest `lit-html` fixes it. Here's an updated example: https://stackblitz.com/edit/unsafe-html-lit-element-ct7ch3?file=index.js

**Comment by jay8t6** [comment]
@sorvell this seems to be working only on 0.11.4, I switched it to 0.12.0 and I get the same issue:
https://stackblitz.com/edit/unsafe-html-lit-element-5txaba

**Comment by jay8t6** [comment]
This is weird, when I try to open that link it works fine, but when I try to change the version back to 0.11.4, and then switch it to 0.12.0, it doesnt work.

**Comment by FDiskas** [comment]
Reproducible again: https://stackblitz.com/edit/unsafe-html-lit-element-dqpy64

**Comment by sorvell** [comment]
@FDiskas That's a different issue. The value passed to `unsafeHTML` is treated as HTML and cannot contain template parts. For this type of thing you'd want to export a function from the module you're importing something like 

```
export const myTemplate = (value) => html`<button>This is button ${value}</button>`;
```
