### ISSUE TITLE
Broken webcomponents.org page of LitElement

### ISSUE THREAD

**Issue by LasaleFamine** [Polymer/lit-element#193]
I think there is a problem with the [webcomponents.org page of LitElement](https://www.webcomponents.org/element/@polymer/lit-element).

![image](https://user-images.githubusercontent.com/13070349/45538819-5c255600-b808-11e8-9141-7950533b8639.png)

I saw that `0.5.0` version is displayed correctly instead, so I think there is something broken within the README (?).

**Comment by samuelli** [comment]
The readme is fixed. Looks like we were getting some broken responses from unpkg for some time. I'm noticing the "elements" is broken. I'll file a separate issue to track this.
