### ISSUE TITLE
if the value is undefined, then attribute being created

### ISSUE THREAD

**Issue by Leon-Alexey** [Polymer/lit-element#199]
do as it was, if the value is undefined, the attribute should not be created

version 0.6:
`
<a href="${item.link}" ></a>  --> <a href="undefined"></a> 
`

version 0.5.2:
`
<a href="${item.link}" ></a>  --> <a></a> 
`

**Comment by Leon-Alexey** [comment]
step forward and two backward, so lit-element becomes unusable, and support bad

**Comment by Leon-Alexey** [comment]
> ```
> <a .href="${item.link}"></a>
> ```

It's not working

**Comment by Leon-Alexey** [comment]
`
if (item.link !== undefined) {
  return html'<a href="${item.link}"></a>'
} else {
  retun html'<a></a>'
}
`

if need add 10 attributes then to make 10 'if'

**Comment by web-padawan** [comment]
@Leon-Alexey ok, the `href` is still attribute, so the proper solution would be to use directive:

```js
import { ifDefined } from 'lit-html/directives/if-defined.js';
```
and then use it like this:
```js
<a href="${ifDefined(item.link)}}"></a>
```
See working demo here: https://glitch.com/edit/#!/linen-bonsai?path=index.html:17:4

**Comment by Leon-Alexey** [comment]
works, Thanks!
