### ISSUE TITLE
Is it still possible to use attributeChangedCallback or is it only possible with render()

### ISSUE THREAD

**Issue by andreabosman16** [Polymer/lit-element#200]
I want to use attributeChangeCallback instead of the render because of the render method needs the properties declared and the attributeChangeCallback works with all attributes that may not or may be changed. When I use the AttributeChangeCallback function it isn't triggered. How to solve this?

**Comment by Scarygami** [comment]
The `render()` method always needs to be implemented and will be automatically called when one of the defined properties is changed.

If you want to trigger a render based on other conditions, e.g in the `attributeChangedCallback`, you have to call the `requestUpdate()` method.

**Comment by andreabosman16** [comment]
My problem is that the `attributeChangedCallback` isn't getting triggered I want to use the  `attributeChangedCallback` to set or remove attributes on the child nodes of the parent they must have the same attributes. So every attribute added or removed must be added or removed from the underlying elements this isn't possible with the render I think because I don t get the old value and the new. Another point is that I don t exactly know which attributes are being set so I don't want to declare them all

**Comment by Scarygami** [comment]
The `attributeChangedCallback` only gets called for attributes that you have specified in a static `observedAttributes` getter, which lit-element handles for you if you define your properties as attribute.

If you want to dynamically observe any attributes, you will must likely have to use a [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver), starting observing in the connectedCallback.

**Comment by sorvell** [comment]
Generally speaking, it's a good idea to have properties that reflect values set to attributes. This is what defining a property with `LitElement` sets up for you automatically (via `static get properties()` or `@property`). That said, you can definitely take control of this by implementing `static get observedAttributes()` and returning an array of attribute names to observe. If you want to include the properties setup for `LitElement` just include the result of `super.observedAttributes()` in that array you return.

You can call `requestUpdate()` in `attributeChangedCallback` to force an update regardless of whether properties have changed. Again, make sure to call `super.attributeChangedCallback()` if you want `LitElement` to deserialize attribute values to property values for any properties you've setup.

**Comment by andreabosman16** [comment]
Thank you worked perfect

**Comment by andreabosman16** [comment]
the `super.observedattributes` don t work it isn't getting any values.
