### ISSUE TITLE
TypeError in Firefox when using a particular element two times

### ISSUE THREAD

**Issue by gitaarik** [Polymer/lit-element#202]
### Description
When you have an element like this:

```
class MyElement extends LitElement {

  render() {
    const cool = html`cool!`;
    return html`
      <div>${cool}</div>
    `;
  }

}
```

And you use this element two times, then you get a `TypeError: this.endNode is null` in your Firefox console. If you don't use the `const` but just put the string `cool!` at the place of `${cool}` it doesn't happen. It works in Chrome.

#### Live Demo
Demo: https://understood-humor.glitch.me/
Source code: https://glitch.com/edit/#!/understood-humor

#### Steps to Reproduce
1. Create an element like mentioned above
2. Use this element two times on a page
3. Test in Firefox

#### Expected Results
You should get two times the text "cool!" underneath each other.

#### Actual Results
In Firefox the text "cool!" only appears one time. The first element is rendered, after that you get an error in the console `TypeError: this.endNode is null`.

### Browsers Affected

- [ ] Chrome
- [x] Firefox

### Versions
- lit-element: v0.6.0
- webcomponents: v2.1.2

**Comment by sorvell** [comment]
The issue is actually with the latest release of `lit-html`. Tracked as https://github.com/Polymer/lit-html/issues/505.

**Comment by gitaarik** [comment]
Nice! Thanks :smiley: :+1:
