### ISSUE TITLE
customElement decorator bug

### ISSUE THREAD

**Issue by fsx950223** [Polymer/lit-element#207]
### Description

If I import a file which use customElement decorator serveral times,there will be a "Failed to execute 'define' on 'CustomElementRegistry': this name has already been used with this registry" error
#### Live Demo

There is a example in my project's demo (https://github.com/fsx950223/chartjs-web-components/tree/master/demo).
#### Steps to Reproduce

1. Define element in base.js
 ``` js
import {LitElement,html,property,customElement} from '@polymer/lit-element'
@customElement('base-chart' as keyof HTMLElementTagNameMap)
export default class BaseChart extends LitElement{}
```
2. Import base.js in a file
``` js
import './base'
```
3. Import base.js in the other file
``` js
import './base'
```
4. They have different entries and use webpack bundle them
#### Expected Results

js exec normally
#### Actual Results

Failed to execute 'define' on 'CustomElementRegistry': this name has already been used with this registry
### Browsers Affected

- [*] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

### Versions

- lit-element: v0.6.1
- webcomponents: vX.X.X

**Comment by CaptainCodeman** [comment]
Your demo links don't demonstrate anything like you describe for me.

Are you sure you're not re-using the same name for multiple elements?

**Comment by fsx950223** [comment]
> Your demo links don't demonstrate anything like you describe for me.
> 
> Are you sure you're not re-using the same name for multiple elements?

Because import will exec .js.If I import a file several times,it will exec customElement.define(tagName) and this action leads to the error

**Comment by mkay581** [comment]
Looks like it's because you should only be registering a new custom element once, ie `customElements.define('my-element')`. After that, you should be reusing the custom element in your html

```html
<my-element id="one" />
<my-element id="two" />

**Comment by sorvell** [comment]
The `@customElements` decorator just calls `customElements.define`. Defining an element with the same name multiple times is an error (per the custom elements spec).

When you import your element, it's fine to load it from the same URL multiple times, but if your project layout is such that the element is being imported from different URLs then you'll get this error.

This can be annoying but it's something you'll need to clean up with your project dependencies.

**Comment by gugadev** [comment]
@sorvell I have a `ck-input` and a `ck-input-addon` elements. I'm building a UI Kit using web components and **provide wrappers for React**. So, inside the wrapper of both elements I import `ck-input`.

In React, If I do this:

```typescript
import { Input } from '@myorg/ui/react'
import { InputAddon } from '@myorg/ui/react'
```

It will cause the OP mentioned error. I need import the web component in it's React wrapper because are standalone components. I ended up creating my own `customElement` decorator to register the element just if it is not registered yet.

**Comment by maxshuty** [comment]
> @sorvell I have a `ck-input` and a `ck-input-addon` elements. I'm building a UI Kit using web components and **provide wrappers for React**. So, inside the wrapper of both elements I import `ck-input`.
> 
> In React, If I do this:
> 
> ```ts
> import { Input } from '@myorg/ui/react'
> import { InputAddon } from '@myorg/ui/react'
> ```
> 
> It will cause the OP mentioned error. I need import the web component in it's React wrapper because are standalone components. I ended up creating my own `customElement` decorator to register the element just if it is not registered yet.

Any chance you still have that decorator you used?

**Comment by maxshuty** [comment]
If anyone finds themselves in this situation, here is a custom decorator I built based off of LItElements `customElement` decorator. Usage is exactly the same as `@customElement('example-comp')` but instead is now called `registerCustomElement` so it's `@registerCustomElement('example-comp')`. The difference between this and LitElements is that this one will do a check if the component has already been registered or not. If not then it will not register it again and will not throw errors or prevent the component from working. Obviously it cannot be combined with `@customElement`.

```
/* 
This was pulled AND MODIFIED from the URL below as
LitElements does not prevent the same element from
being registered more than once causing errors.
https://github.com/lit/lit-element/blob/master/src/lib/decorators.ts
*/

export type Constructor<T> = {
  // tslint:disable-next-line:no-any
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  new (...args: any[]): T;
};

// From the TC39 Decorators proposal
interface ClassDescriptor {
  kind: 'class';
  elements: ClassElement[];
  finisher?: <T>(clazz: Constructor<T>) => undefined | Constructor<T>;
}

// From the TC39 Decorators proposal
interface ClassElement {
  kind: 'field' | 'method';
  key: PropertyKey;
  placement: 'static' | 'prototype' | 'own';
  initializer?: Function;
  extras?: ClassElement[];
  finisher?: <T>(clazz: Constructor<T>) => undefined | Constructor<T>;
  descriptor?: PropertyDescriptor;
}

const legacyCustomElement = (
  tagName: string,
  clazz: Constructor<HTMLElement>
) => {
  customElements.get('accordion-comp') ||
    window.customElements.define(tagName, clazz);
  // Cast as any because TS doesn't recognize the return type as being a
  // subtype of the decorated class when clazz is typed as
  // `Constructor<HTMLElement>` for some reason.
  // `Constructor<HTMLElement>` is helpful to make sure the decorator is
  // applied to elements however.
  // tslint:disable-next-line:no-any
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  return clazz as any;
};

const standardCustomElement = (
  tagName: string,
  descriptor: ClassDescriptor
) => {
  const {kind, elements} = descriptor;
  return {
    kind,
    elements,
    // This callback is called once the class is otherwise fully defined
    finisher(clazz: Constructor<HTMLElement>) {
      customElements.get('accordion-comp') ||
        window.customElements.define(tagName, clazz);
    },
  };
};

/**
 * Class decorator factory that defines the decorated class as a custom element.
 *
 * ```
 * @registerCustomElement('my-element')
 * class MyElement {
 *   render() {
 *     return html``;
 *   }
 * }
 * ```
 * @category Decorator
 * @param tagName The name of the custom element to define.
 */
export const registerCustomElement =
  (tagName: string) =>
  (classOrDescriptor: Constructor<HTMLElement> | ClassDescriptor) =>
    typeof classOrDescriptor === 'function'
      ? legacyCustomElement(tagName, classOrDescriptor)
      : standardCustomElement(tagName, classOrDescriptor);
```

**Comment by andrewshawcare** [comment]
A declarative decorator should not execute imperative mutative code.

If it does, it should at least be idempotent (there is no obvious expectation that a decorator should only ever be executed once).

This (or something similar) is required in the decorator, it shouldn't be a custom decorator implementation:

```js
if (!customElements.get(tagName)) {
  customElements.define(tagName, clazz)
}
```

At the very least, adding a parameter to the existing decorator to add the guard would be helpful:

```typescript
@customElement("my-element", { preventDuplicateRegistration: true })
```

**Comment by justinfagnani** [comment]
@andrewshawcare is not necessary to make this decorator "idempotent" since JavaScript and decorator semantics ensure that a decorator is run only once per class.

The problem here isn't idempotency, it's that the decorator is run with the same tag name on multiple different classes. Making the decorator skip subsequent classes that use same tag name does not make it idempotent. It makes the decorator fragile, since it could be hiding incompatibilities.

**Comment by andrewshawcare** [comment]
@justinfagnani are you saying that if I import the same component class from different files (or multiple times in the same "file") in the same browser context that the decorator associated with that component will only execute the custom element registration once?

What does [this issue in Storybook](https://github.com/storybookjs/storybook/tree/master/app/web-components#faq) reference? Why does the annotation run twice using HMR in Storybook?

**Comment by justinfagnani** [comment]
@andrewshawcare no, I'm saying that the customElement decorator only runs once per class. If you load multiple classes that use the decorator it runs for each class. There isn't a way to determine that two difference classes are "the same" - they are still fundamentally two different class declarations.

**Comment by andrewshawcare** [comment]
@justinfagnani Can you provide an example of the semantics you are describing? In what context does JavaScript and decorator semantics guarantee that a decorator is run only once per class?

If it runs twice if the same class is defined in different files, or loaded from the same file in different contexts, or defined twice in the same file... in what instance do semantics ensure the decorator is only executed once?

**Comment by justinfagnani** [comment]
> If it runs twice if the same class is defined in different files

In this case they aren't the same class. They are two different classes.

**Comment by andrewshawcare** [comment]
Understood. What about the other examples?

Regardless of how we get there, it seems there is an issue with annotation code executing against a global registry that throws an exception if values already exist for keys.

I don't understand how Javascript or annotations can provide safety from that reality. If the code executes twice because the execution environment "thinks" it's a different class, it's going to try and run the annotation again and an exception will occur. There seem to be valid use cases (e.g. HMR) that warrant discussion.

Maybe I haven't seen many annotations, aspects, or similar decorating code, but it's new to me to have an annotation that mutates a singleton registry using a global variable. Do you know of any others?
