### ISSUE TITLE
customElement tagName typings incorrect

### ISSUE THREAD

**Issue by asyncLiz** [Polymer/lit-element#210]
### Description

In TypeScript 3.0.0 for lit-element 0.6.1 the `@customElement` decorator has the following typings generated in `lib/decorators.d.ts`:

```ts
export declare const customElement: (tagName: "object" | "a" | "abbr" | "acronym" | "address" | "applet" | "area" | "article" | "aside" | "audio" | "b" | "base" | "basefont" | "bdo" | "big" | "blockquote" | "body" | "br" | "button" | "canvas" | "caption" | "center" | "cite" | "code" | "col" | "colgroup" | "data" | "datalist" | "dd" | "del" | "dfn" | "dir" | "div" | "dl" | "dt" | "em" | "embed" | "fieldset" | "figcaption" | "figure" | "font" | "footer" | "form" | "frame" | "frameset" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "head" | "header" | "hgroup" | "hr" | "html" | "i" | "iframe" | "img" | "input" | "ins" | "isindex" | "kbd" | "keygen" | "label" | "legend" | "li" | "link" | "listing" | "map" | "mark" | "marquee" | "menu" | "meta" | "meter" | "nav" | "nextid" | "nobr" | "noframes" | "noscript" | "ol" | "optgroup" | "option" | "output" | "p" | "param" | "picture" | "plaintext" | "pre" | "progress" | "q" | "rt" | "ruby" | "s" | "samp" | "script" | "section" | "select" | "slot" | "small" | "source" | "span" | "strike" | "strong" | "style" | "sub" | "sup" | "table" | "tbody" | "td" | "template" | "textarea" | "tfoot" | "th" | "thead" | "time" | "title" | "tr" | "track" | "tt" | "u" | "ul" | "var" | "video" | "wbr" | "xmp") => (clazz: Constructor<HTMLElement>) => any;
```

This prevents the decorator from being used properly since it forbids any element name defined on top of `HTMLElementTagNameMap` and suggests illegal names are valid.

I'm not sure why the `HTMLElementTagNameMap` [type requirement](https://github.com/Polymer/lit-element/blob/master/src/lib/decorators.ts#L43) on `@customElement` exists. The only benefit I can see is that after defining a new element in the map, `document.createElement()` is typed correctly.

Since most elements will likely be declared in HTML templates and not built programmatically, this benefit does not seem worth the extra maintenance of extending `HTMLElementTagNameMap` for every element.

#### Steps to Reproduce

Creating `my-element.ts` and compile it with TypeScript.
```ts
import { LitElement, customElement } from '@polymer/lit-element';

@customElement('my-element')
export class MyElement extends LitElement {}

declare global {
  interface HTMLElementTagNameMap {
    'my-element': MyElement;
  }
}
```

#### Expected Results

No error should be thrown when compiling.

#### Actual Results

```
[ts] Argument of type '"my-element"' is not assignable to parameter of type '"object" | "a" | "abbr" | "acronym" | "address" | "applet" | "area" | "article" | "aside" | "audio" | "b" | "base" | "basefont" | "bdo" | "big" | "blockquote" | "body" | "br" | "button" | ... 106 more ... | "xmp"'.
```

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari 11
- [x] Safari 10
- [x] IE 11

### Versions

- lit-element: v0.6.1
- typescript: v3.0.0

**Comment by justinfagnani** [comment]
See https://github.com/Microsoft/TypeScript/issues/27171 for the upstream issue.

You can cast the tag name to `any` as a workaround. We can also fix this by hand before publishing.

**Comment by justinfagnani** [comment]
> Since most elements will likely be declared in HTML templates and not built programmatically, this benefit does not seem worth the extra maintenance of extending HTMLElementTagNameMap for every element.

I added this for some future benefits that we'll get in tooling if the ecosystem has added their elements to the HTMLElementTagNameMap. We're going to do template validation based on the element interfaces declared there, so that property bindings are typechecked. This is the only way I know of currently to remind authors to add their element.

Aside from this additional type-checking, there's really no advantage of `@customElement` over `customElements.define`, so it's really the key feature.

**Comment by asyncLiz** [comment]
Thanks! I'll subscribe to the upstream issue.
