### ISSUE TITLE
[docs] Document ES5 "downlevelIteration" tsconfig requirement

### ISSUE THREAD

**Issue by asyncLiz** [Polymer/lit-element#211]
### Description

TypeScript 2.3 and later supports `for-of` iteration of iterables by setting `"downlevelIteration": true` in tsconfig's compilerOptions. If compiling to ES5, this flag is _required_ since `UpdatingElement` [uses](https://github.com/Polymer/lit-element/blob/master/src/lib/updating-element.ts#L157) [for-of](https://github.com/Polymer/lit-element/blob/master/src/lib/updating-element.ts#L352) for [iterating](https://github.com/Polymer/lit-element/blob/master/src/lib/updating-element.ts#L369) [maps](https://github.com/Polymer/lit-element/blob/master/src/lib/updating-element.ts#L585).

When this flag is not set and lit-element is compiled to ES5 using TypeScript, certain property options such as `reflect` and `attribute` will silently fail.

Either documentation should be added for TypeScript indicating that this flag is required when targeting ES5, or a different approach to iterating Maps in the source code should be used. For example:

```diff
-      for (const [k, v] of this._reflectingProperties) {
+      for (const [k, v] of Array.from(this._reflectingProperties)) {
         this._propertyToAttribute(k, this[k as keyof this], v);
       }
```

#### Steps to Reproduce

my-element.ts
```ts
import { LitElement, html, property } from '@polymer/lit-element';

class MyElement extends LitElement {
  @property({ type: String, reflect: true })
  prop = 'Hello';

  render() {
    return html`<div>Prop is ${this.prop}</div>`
  }
}

customElements.define('my-element', MyElement);
```
```sh
tsc my-element.ts --target es5
```

#### Expected Results

`<my-element>` should have a reflected `prop="Hello"` attribute.

#### Actual Results

Property is silently not reflected.

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari 11
- [x] Safari 10
- [x] IE 11

### Versions

- lit-element: v0.6.1
- webcomponents: v2.1.3

**Comment by katejeffreys** [comment]
Tools - babel, typescript, etc

**Comment by katejeffreys** [comment]
to be handled in https://github.com/Polymer/lit-element/issues/420 

sorry to be abrupt, am triaging
