### ISSUE TITLE
Replacement for _firstRendered?

### ISSUE THREAD

**Issue by KeithHenry** [Polymer/lit-element#214]
As I'm upgrading a Polymer 2 project I have a lot of `this.$.elementID` calls.

To help with this (until we can replace a lot of code) we had been using this mixin:

```
/** Get a lookup of all the elements in the shadow DOM by ID
 * @param element The element to scan
 * @returns Elements lookup*/
function getIdElements(context: DocumentFragment): { [key: string]: Element } {
    return [...context.querySelectorAll('[id]')].
        map(x => ({ id: x.id, element: x })).
        reduce<{ [key: string]: Element }>((a, c) => {
            a[c.id] = c.element;
            return a;
        }, {});
}

interface Constructor<T> { new(...args: any[]): T; }

export function With$<T extends Constructor<any>>(Base: T) {
    return class extends Base {

        /** After first render this holds references to elements by ID */
        $: { [key: string]: Element };

        /** Store a $ reference to the elements for easy access */
        _firstRendered() { this.$ = getIdElements(this.shadowRoot); }
    }
}
```

As of 0.6 this no longer works, partly because `LitElement` is now `abstract`, but also because `_firstRendered` has gone.

How should we hook up a mixin with 0.6 to run immediately after the lit-html render has built the shadow DOM?

**Comment by craigjennings11** [comment]
`_firstRendered` was changed to `firstUpdated` in [`v0.6.0`](https://github.com/Polymer/lit-element/blob/master/CHANGELOG.md#060---2018-09-13).

**Comment by KeithHenry** [comment]
Cheers, that did the trick.
