### ISSUE TITLE
Lifecycle function updated() not called when calling update() to manually trigger a rerender

### ISSUE THREAD

**Issue by gitaarik** [Polymer/lit-element#215]
### Description
When you call `this.update()`, the lifecycle function `updated()` doesn't get called.

#### Live Demo
Demo: https://thoughtful-wren.glitch.me/
Source: https://glitch.com/edit/#!/thoughtful-wren?path=index.html:35:0

#### Steps to Reproduce
1. Create an element and implement the lifecycle method `updated()` and put a console log in it
2. Create a button and call the `this.update()` method
3. Check whether the lifecycle method `updated()` gets called by checking if the log message got logged
4. To make sure a rerender really happens you can add a counter that is visible in the template, see the example at the URL above.

#### Expected Results
I would expect the lifecycle method `updated()` would be called after every rerender, even when a rerender is manually triggered by `this.update()`.

#### Actual Results
The lifecycle method `updated()` is not called when manually triggering a rerender using the `this.update()` method.

### Browsers Affected

- [x] Firefox
- [x] Chrome

### Versions

- lit-element: v0.6.1
- webcomponents: v2.1.3

**Comment by sorvell** [comment]
`update()` is protected and should not be called by user code. Instead call `requestUpdate()`.

**Comment by gitaarik** [comment]
Aha, clear, thanks!
