### ISSUE TITLE
Proposal: change the signature of the Constructor<T> type for use in mixins

### ISSUE THREAD

**Issue by jolleekin** [Polymer/lit-element#217]
### Issue
Please change the signature of the `Constructor<T>` type (declared in [decorators.ts](https://github.com/Polymer/lit-element/blob/master/src/lib/decorators.ts#L20)) to use `any` instead of `unknown` so it can be used to create mixins. Without this change, anyone using lit-element will have to declare his/her own `Constructor<T>` type to create mixins.
``` ts
export type Constructor<T> = {
  new (...args: unknown[]): T
};

// should be changed to

export type Constructor<T> = {
  new (...args: any[]): T
};

// or

export type Constructor<T> = new (...args: any[]) => T;
```

### Versions
- lit-element: v0.6.1

**Comment by aadamsx** [comment]
If you know what needs to be done (it sounds like you do), submit a PR! :)

**Comment by justinfagnani** [comment]
This seems fine, but we should file an upstream issue on TypeScript

**Comment by jolleekin** [comment]
Seems like this is the upstream issue [14126](https://github.com/Microsoft/TypeScript/issues/14126)
