### ISSUE TITLE
TypeError when using space-seperated classnames from variables in Template

### ISSUE THREAD

**Issue by ekatioz** [Polymer/lit-element#218]
### Description
I have all my classnames in a seperate file, so I import them in my element and use them as variables. When I try to use multiple classnames in a space-seperated style i.e.
`<div class="${styleNames.inline} ${styleNames.container}">`
I get a TypeError (is null) from template.js at
`lastAttributeNameRegex.exec(stringForPart)[2];`
where exec(...) returns null.

A workaround seems to be to omitt the space like so:
`<div class="${styleNames.inline}${styleNames.container}">`
or to use a extra method for building the classlist:
```
<div class="${this.getStyleNames()}"></div>

private getStyleNames(): string {
    return `${styleNames.linkIcon} ${this.icon ? this.icon : ''}`;
}
```

#### Sample Code
[On Stackblitz](https://stackblitz.com/edit/typescript-mkxhbe) the TypeError is not logged, but anyway there is something strange with how the template is interpreted.

#### Steps to Reproduce

1. Create `my-element`
2. Use Varables as shown above to build up classlist
3. transpile TypeScript for firefox (browserl.ist query ['last 10 ff versions', 'last 10 and_ff versions'])
4. make sure shadowDom & customcomponents are deactivated in about:config (ff < 63)
5. use `my-element` alongside with @webcomponents/webcomponentsjs

#### Expected Results
No error is thrown and `my-element` can be visualized.

#### Actual Results
TypeError is thown and `my-element` is not visualized.

### Browsers Affected

- [ ] Chrome
- [x] Firefox
- [x] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

### Versions

- lit-element: v0.6.1
- webcomponents: v2.1.3

**Comment by sorvell** [comment]
Can confirm the issue. It looks possibly related to `shady-render` in lit-html as it's fine in Chrome as seen here: https://glitch.com/edit/#!/rightful-dancer?path=my-element.ts

**Comment by sorvell** [comment]
The example above was updated to force the polyfills on and the problem no longer reproduces.
