### ISSUE TITLE
`customElement` decorator types not emitted with HTMLElementTagNameMap

### ISSUE THREAD

**Issue by emilio-martinez** [Polymer/lit-element#223]
### Description
`customElement` decorator types not emitted with HTMLElementTagNameMap. `keyof HTMLElementTagNameMap` is flattened on the emitted type declarations.

#### Live Demo
N/A

#### Steps to Reproduce

See emitted `decorators.d.ts` on v0.6.1: https://unpkg.com/@polymer/lit-element@0.6.1/lib/decorators.d.ts. Because the `tagName` parameter is flattened from `keyof HTMLElementTagNameMap` to the actual keys, the decorator will not type-check, even after using

```ts
declare global {
  interface HTMLElementTagNameMap {
    'my-element': MyElement;
  }
}
```

#### Expected Results
To be able to use augment the `HTMLElementTagNameMap` interface to use the decorator.

#### Actual Results
Typescript will not compile, even after adding

```ts
declare global {
  interface HTMLElementTagNameMap {
    'my-element': MyElement;
  }
}
```

### Browsers Affected
N/A. Related to Typescript compilation

### Versions
@polymer/lit-element@0.6.1
typescript@3.0.3

**Comment by Lodin** [comment]
Duplicate of #210

**Comment by emilio-martinez** [comment]
@Lodin Thank you!
