### ISSUE TITLE
unpkg doesnot have latest release

### ISSUE THREAD

**Issue by LRagji** [Polymer/lit-element#230]
### Description
Package CDN unpkg.com currently only has 0.5 as the latest release version . was expecting 0.6 as per the git latest git release tag

#### Steps to Reproduce
1) Hit https://unpkg.com/lit-element
2)It will redirect you to https://unpkg.com/lit-element@0.5.0/lit-element.js
3)Which states the latest version in 0.5

#### Expected Results
 https://unpkg.com/lit-element@0.6.0/lit-element.js

#### Actual Results
https://unpkg.com/lit-element@0.5.0/lit-element.js

**Comment by abraham** [comment]
That's the wrong package. This is published under [@polymer/lit-element](https://www.npmjs.com/package/@polymer/lit-element) which resolves as expected https://unpkg.com/@polymer/lit-element

**Comment by LRagji** [comment]
This works i was almost confused as the url i was using was also loading some incomplete package, do you think it should be on readme.md? may help few newcomers like me

**Comment by sorvell** [comment]
Sorry for the delay. I think there might be a slight delay, but looks good right now: https://unpkg.com/@polymer/lit-element@0.6.4/lit-element.js
