### ISSUE TITLE
HTML syntax coloring w/VSCode

### ISSUE THREAD

**Issue by aadamsx** [Polymer/lit-element#231]
Does anyone know of a VSCode plugin that will allow HTML syntax coloring to come through when in a string like so?

![image](https://user-images.githubusercontent.com/5341158/46229273-ab03dd00-c32a-11e8-83c6-dcdde802f2ae.png)

Right now I have ```lit-html``` by Matt Bierner installed but as you can see above it's not working! :)

**Comment by aadamsx** [comment]
For example, if you look at this VSCode plugin:

https://marketplace.visualstudio.com/items?itemName=bierner.lit-html

It shows the HTML looks like it's inside of a .html file and not inside a string...

**Comment by jolleekin** [comment]
I'm using this one https://github.com/Microsoft/typescript-styled-plugin

**Comment by sorvell** [comment]
There are a couple and as noted above, https://github.com/mjbvz/vscode-lit-html works well.
