### ISSUE TITLE
Add an `eventListenerOptions` decorator

### ISSUE THREAD

**Issue by justinfagnani** [Polymer/lit-element#237]
https://github.com/Polymer/lit-html/pull/531 adds support for declarative event listener options. We should support this with a decorator:

```ts
class MyElement extends LitElement {
  render() {
    return html`<button @click=${this.onClick}>Click Me</button>`;
  }

  @eventListenerOptions({capture: true})
  onClick(e) {
    console.log('clicked');
  }
}
```

We should also document that without decorators, users can simply set an attribute on the method directly:

```ts
MyElement.prototype.capture = true;
```

**Comment by justinfagnani** [comment]
@jolleekin the override will need its own options. We're not going to read from up the prototype chain.

**Comment by aadamsx** [comment]
@justinfagnani what do you mean by this?

> We're not going to read from up the prototype chain.

**Comment by frankiefu** [comment]
Fixed by https://github.com/Polymer/lit-element/pull/244
