### ISSUE TITLE
d.ts files with unknow

### ISSUE THREAD

**Issue by andreabosman16** [Polymer/lit-element#240]
the following d.ts files have a Promise with an unknown variable in it   `decorators.d.ts` `updating-element.d.ts` can these be changed or can these variable be typed checked with an actually named type?
When I run tsc there are errors because this is an unnamed type. I hope this can be fixed would help allot
because now I need to turn off libchecking.

**Comment by justinfagnani** [comment]
`unknown` has been in a few TypeScript releases now. It accurately describes our types, so we want to keep it.
