### ISSUE TITLE
Question: How lit-element resolves consecutive renders?

### ISSUE THREAD

**Issue by aletorrado** [Polymer/lit-element#242]
Hi, I couldn't find information about how lit-element merges results from consecutive render calls when they differs significantly. I think it would be nice to have this documented for user optimizations as well.

Can you give me some insights?

**Comment by aletorrado** [comment]
By the way, what I mean is what in React is called [Reconciliation](https://reactjs.org/docs/reconciliation.html). Given that both React and LitElement are based on heuristics to compare different DOM trees, clarifying these implementation details would give valuable information to ensure a performant element.

**Comment by sorvell** [comment]
In brief, `LitElement` uses `lit-html` to render HTML templates that contain "parts" which render dynamic content. It's only these dynamic parts which are updated when a template is re-rendered.

Here's some more information to review:
  * [lit-html docs](https://lit-html.polymer-project.org/guide/concepts)
  * [lit-html talk](https://www.youtube.com/watch?v=Io6JjgckHbg)
  * [vdom v. lit-html](https://www.youtube.com/watch?v=uCHZJy2n8Qs)
