### ISSUE TITLE
LitElement + Chart.js

### ISSUE THREAD

**Issue by aadamsx** [Polymer/lit-element#245]
I'm trying to get Chart.js working ... I was able to get it working outside the render, but inside I'm having an issue.  https://stackblitz.com/edit/lit-element-chartjs

**Comment by aadamsx** [comment]
I got this working by adding a div around the canvas element.

**Comment by web-padawan** [comment]
Let's not submit another issue for each JS library you happen to use 😄 

I mean, lots of libraries assuming using API like `document.querySelector` and relying on global CSS would be broken by Shadow DOM, and there is nothing much to do here for LitElement (except for drop Shadow DOM at all, which is probably not what the Polymer team is going to do),

**Comment by aadamsx** [comment]
@web-padawan hey, it should be obvious to guys like you that I'm not that knoledgeable about this library, shadow-dom, shadow-root, light-dom and the like.  Now that I'm starting research this stuff as I come across issues, I'm coming to the same conclusion as your comment above on my own (hence I closed this issue).

Some on here are unpompus and kind enough to ask me to get on slack for questions like this -- which I did today.;

**Comment by web-padawan** [comment]
@aadamsx don't hesitate to ask, and sorry if I was unfriendly. We should have a clear list of the implications Shadow DOM has, documented somewhere, now when LitElement is going to become stable. I believe Polymer team will be able to provide better docs quite soon.
