### ISSUE TITLE
Support mixins of official Polymer Elements

### ISSUE THREAD

**Issue by AndreasGalster** [Polymer/lit-element#25]
Right now lit-element is not compatible with mixins of elements which makes it close to impossible to use it in a production app since you cannot style elements as intended.

It would be great to get support for this soon so we can start using lit-element in production.

**Comment by TimvdLippe** [comment]
@AndreasGalster Do you mean JavaScript mixins or CSS mixins? The CSS mixins proposal has been abandoned in favor of `::part`, see https://github.com/webcomponents/shadycss#status

**Comment by sorvell** [comment]
Sorry for the delay on this but we're getting there. Closing this in favor of https://github.com/Polymer/lit-html/issues/326 which is in progress and should address this issue.
