### ISSUE TITLE
An array property's changes did not reflect automatically.

### ISSUE THREAD

**Issue by march23hare** [Polymer/lit-element#252]
### Description
An array property's changes did not reflect automatically.
When the array property calls splice method, then it changes but its connected DOM did not.
Please look at Live Demo. It will more easy to understand than I explained.

What do I do?

#### Live Demo
https://stackblitz.com/edit/array-change-not-reflects

#### Expected Results

Rerender as it's connected property changed

#### Actual Results

DOM does not change even the property has been changed.

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

### Versions

- lit-element: v0.6.0
- webcomponents: v2.0.0

**Comment by march23hare** [comment]
Thank you.
Hard-copying the array, then it works well.

**Comment by JSilversun** [comment]
Hello, I have a question, would it be better to copy the array/object or calling `this.requestUpdate` directly? Thanks

**Comment by moog16** [comment]
Fixed it by doing:
```
  onRemove(index) {
    console.log(`prev: `, this.myList);
    const myList = this.myList.slice();
    myList.splice(index, 1);
    this.myList = myList;
    console.log(`now: `, this.myList);
  }
```

**Comment by justinfagnani** [comment]
@JSilversun I like calling `requiresUpdate()`, though you (and future readers) do have to understand the LitElement lifecycle for that.

**Comment by moog16** [comment]
RequestUpdate? Is that the recommendation? As opposed to using property accessors?

**Comment by davidsteinberger** [comment]
@justinfagnani did u mean `requestUpdate` or indeed `requiresUpdate`?

**Comment by justinfagnani** [comment]
Sorry, I meant `requestUpdate`. There is no `requiresUpdate`.

**Comment by davidsteinberger** [comment]
Thanks for the clarification! I do it all the time this way, just never heard of `requiresUpdate`.
