### ISSUE TITLE
[docs] size of library

### ISSUE THREAD

**Issue by chiefcll** [Polymer/lit-element#253]
https://github.com/Polymer/lit-element

Saying ultra-light isn't useful information. Better to say ~5kb...

**Comment by katejeffreys** [comment]
It doesn't say ultra-light any more - will check what info we should be providing in the README

**Comment by msteller-connyun** [comment]
Yes, lit-element become really fat. To fat for my taste.

I think lit-element should lose weight.

**Comment by daKmoR** [comment]
@msteller-connyun how do you get to this number?
https://bundlephobia.com/result?p=lit-element@2.0.1
says 6.6 kB

**Comment by blikblum** [comment]
> https://bundlephobia.com/result?p=lit-element@2.0.1
says 6.6 kB

And most of it comes from lit-html.

The only room i see to reduce size is by removing support to IE11 / shady render

**Comment by msteller-connyun** [comment]
Well, I test the size under more practical conditions.

I do a webpack bundle with babel with the following code:

```
import {LitElement, property, html} from 'lit-element';
console.log(LitElement, property, html)
```

Because using lit-element in a webpack bundle and transpiled by babel is what I do in reality ;)

To simulate the gzip compression I just use the default zip archive from macos which is very close to the gzip file size.

with lit-element 0.x the gziped size was around 7 to 8k.

But with lit-element 2.0 it became really fat, what is a problem for me, because I'm an advocate of self-contained web-components, what means I bundle lit into the component.

**Comment by web-padawan** [comment]
> using lit-element in a webpack bundle and transpiled by babel is what I do in reality ;)

Consider using [webpack-babel-multi-target-plugin](https://github.com/DanielSchaffer/webpack-babel-multi-target-plugin) to serve ES modules code to evergreen browsers supporting them.

`lit-element` indeed contains usage of `async/await` and `for.. of` loops which was already discussed in #295. It is strongly recommended to avoid transpiling to ES5 unless you serve IE11 or Safari 9. All the modern browsers starting from Safari 10.1 support ES modules.

**Comment by msteller-connyun** [comment]
Well, the company which I work for needs for our components IE11 support (I’m the first one who would kill the support for that evil web browser...).

However, I’m just saying that lit-element did became much bigger under my build conditions, compared to previous versions.

**Comment by web-padawan** [comment]
We also support IE11 but that plugin allows to put all the verbose ES5 output into `nomodule` script which will be loaded as a fallback, while Chrome, Firefox, Safari and Edge will still get ES2015+

**Comment by msteller-connyun** [comment]
I understand what you suggest, but `nomodule` is not really a solution for me.

We build for our company self contained web components which should be easy to use in different projects. I want to avoid the complexity for developers to work with different versions of the components for different browsers just for size optimizations.

I just want to require in webpack an import like

```
import '@company-namepsace/my-component‘;
```

to enable the component in the project.

Or under some conditions they can be also lazy loaded (via webpack-babel)

```
await import('@company-namepsace/my-component‘);
```

And I didn’t anything about that webpack/babel supports `nomodule` for `import` and `import()`.

The perfect solution would be if you would deploy addtional a sized optimized ES5 version, but I’m very sure that this will not happen ;)

**Comment by daKmoR** [comment]
@msteller-connyun that is exactly what the [babel-multi-target-plugin](https://github.com/DanielSchaffer/webpack-babel-multi-target-plugin) does. As a user you just do
```
import '@company-namepsace/my-component‘;
```
and the plugin (depending on how you configured it) will produce multiple versions of your app... most commonly you will have 2 versions: one modern (small) and one legacy (big).

For an example setup that also loads the polyfills conditionally, you can take a look at https://open-wc.org/building/building-webpack.html.

Maybe it gives some inspiration :hugs:

**Comment by jhpratt** [comment]
I've just filed #612, which should reduce the size a fair amount if you don't need to support older browsers.

**Comment by justinfagnani** [comment]
I'm not sure we need to mention a specific size on the homepage. Lightweight seems good for now.

**Comment by mangelozzi** [comment]
For anyone else trying to figure out how much litElement will add to your project, its about 22Kb at the time of this writing (including reactive/lit=html/lit-element).
