### ISSUE TITLE
Set up some eslint rules that apply in markdown code blocks

### ISSUE THREAD

**Issue by katejeffreys** [Polymer/lit-element#265]
_Originally posted by @bennypowers in https://github.com/Polymer/lit-element/pull/263#issuecomment-430179234_

**Comment by bennypowers** [comment]
can do this easily with `eslint-plugin-markdown` see how [crocks](https://github.com/evilSoft/crocks) does it

**Comment by 43081j** [comment]
We probably don't need it quite like this anymore.

Most of the docs now use includes to display any JS examples. So, as long as we always try use includes (except for pseudo-code and what not), we should be able to just lint `docs/**/*.js`.

Though, we do use tslint, so it doesn't quite work against our docs
