### ISSUE TITLE
Maybe more useful sample element in tutorial

### ISSUE THREAD

**Issue by katejeffreys** [Polymer/lit-element#267]
I'll see what I can come up with for more realistic demo elements and names. (I had thought about trying to make the tutorial element more useful than just plopping out meaningless test strings but my priority is to get the syntax down. TODO..)

_Originally posted by @katejeffreys in https://github.com/Polymer/lit-element/pull/263/review_comment/create_

**Comment by jfbrennan** [comment]
Finding it to be just the right size to get comfortable. Would recommend anything more be part of an "advanced" examples page or something. The approachability right now is going to be nice for people coming from libraries that end in "eact" ;)
