### ISSUE TITLE
Investigate why clang-format mangles sources

### ISSUE THREAD

**Issue by 43081j** [Polymer/lit-element#270]
Currently we're missing a `.clang-format` so the `format` npm script won't be using the Google style config.

That's the first issue. Second issue is that if we try use the Google style (copied from polymer tools repo for example), it produces some real strangeness:

```js
@property() message='Hi';
```

Notice the lack of spacing around `=`.

```js
return queryFn(this.renderRoot !, selector);
```

Again crazy spacing around `!`.

Can we just not use clang-format against template strings and decorators? and typescript-specific stuff?

**Comment by sorvell** [comment]
A `.clang-format` was added in https://github.com/Polymer/lit-element/pull/536.

**Comment by 43081j** [comment]
@sorvell it was, but i suspect justin manually discarded the mangled parts...

i just pulled master and ran format (`npm run format`) and ended up with:

```ts
extra=''; // where's the spacing?

// elsewhere...

// whats up with the space before the backtick below?
return html `
```
