### ISSUE TITLE
[docs] change code samples to import by name with inline script

### ISSUE THREAD

**Issue by katejeffreys** [Polymer/lit-element#273]
I would suggest importing by name with inline script instead and let the tools will handle the resolution:

```html
<script type=module>
import 'package-name/existing-element.js';
</script>
```

This is what we did for PolymerElement demos (e.g. https://github.com/PolymerElements/iron-list/blob/master/demo/index.html#L20).

_Originally posted by @keanulee in https://github.com/Polymer/lit-element/pull/263_

**Comment by justinfagnani** [comment]
This appears to be done in the current site.
