### ISSUE TITLE
Composing custom lit-element using existing lit-elements

### ISSUE THREAD

**Issue by LRagji** [Polymer/lit-element#275]
I was looking to compose a lit-element using existing lit-element eg: Material design button, what i am confused on is where should i import the button if i import it on index page where my element is imported it works, but shouldn't i be importing it in my custom element? is there a way to do that, or is there a example some one can point me at?

**Comment by LarsDenBakker** [comment]
You can just import the module which defined the custom element. So in your own component:

```javascript
import 'material-design-button';
import { LitElement } from '@polymer/lit-element';

class MyComponent extends LitElement {

}

customElement.define('my-component, MyComponent);
```

**Comment by LRagji** [comment]
Sometimes you fail to check basics, i was actually loading everything from unpkg and i forgot to include ?module and was confused with how polymer loads stuff...:(
BTW do you have any idea on this https://github.com/Polymer/lit-element/issues/274 just want to keep html and js different..
Admins may Delete or close this issue 
Thanks

**Comment by LRagji** [comment]
Sometimes you fail to check basics, i was actually loading everything from unpkg and i forgot to include ?module and was confused with how polymer loads stuff...:(
BTW do you have any idea on this https://github.com/Polymer/lit-element/issues/274 just want to keep html and js different..
Admins may Delete or close this issue 
Thanks

**Comment by ernsheong** [comment]
@LRagji can may close this issue yourself
