### ISSUE TITLE
[repeat directive]: Parameters `index` of `KeyFn` and `ItemTemplate` should not be optional

### ISSUE THREAD

**Issue by jolleekin** [Polymer/lit-element#280]
### Issue
The current signatures of `KeyFn` and `ItemTemplate` specify `index` as optional
``` ts
export type KeyFn<T> = (item: T, index?: number) => any;
export type ItemTemplate<T> = (item: T, index?: number) => any;
```
With the above signatures of `KeyFn` and `ItemTemplate`, I have to include `!` with all occurrences of `index` in my callback.
``` ts
export class ArrayFormControl<E> extends FormControl<E[]> {
  keyFn?: KeyFn<E>;
  itemRenderer!: (item: E, index: number, host: ArrayFormControl<E>) => any;

  protected render(): TemplateResult {
    // [value] is an inherited property.
    return html`
      ${repeat(this.value!, this.keyFn!, this._renderItem)}
    `;
  }

  private _renderItem(item: E, index?: number): any {
    // I have to include `!` after [index].
    return this.itemRenderer(item, index!, this);
  }
}
```
### Solution
The solution is to remove the `?` in the signatures of `KeyFn` and `ItemTemplate`.
``` ts
export type KeyFn<T> = (item: T, index: number) => any;
export type ItemTemplate<T> = (item: T, index: number) => any;
```
Indexes are always passed to the callbacks. It's up to users to specify an `index` parameter in their callbacks or not. Both of the following callbacks would be valid.
``` ts
renderItem1(item: E): any;
renderItem2(item: E, index: number): any;
```

### Versions
- lit-element: v0.6.2

**Comment by ChrisBrownie55** [comment]
@jolleekin I think the reason why they have it marked as optional is that in TypeScript if you don't mark the parameter as optional and you don't pass it into the function/method, you get the following error:

```error
Supplied parameters do not match any signature of call target.
```

Which is basically TypeScript saying you never said that was an optional parameter.

**Comment by jolleekin** [comment]
@ChrisBrownie55
 That error is not a problem as parameters `keyFn` and `template` of the `repeat` directive are always called with an index.
``` ts
    // lit-html/directives/repeat

    let index = 0;
    for (const item of items) {
      newKeys[index] = keyFn ? keyFn(item, index) : index;
      newValues[index] = template!(item, index);
      index++;
    }
```

Anyway, this issue is in the wrong repo. It should be in `lit-html`.
