### ISSUE TITLE
TypeScript default values for class properties break the lit-element/updating-element

### ISSUE THREAD

**Issue by paulcodiny** [Polymer/lit-element#285]
Here is an example of code that behaves unexpectedly.

TypeScript element definition
```typescript
// imports
class MyElement extends LitElement {
  @property({ attribute: true, reflect: true })
  prop: boolean = true;
  ...
}
```

This code is compiled to ES5
```javascript
function MyElement() {
  var _this = _super.call(this) || this;
  _this.prop = true;
  return _this;
}
```
So, now the `prop` is set to `true` in the constructor.  
Due to the following flow:  
get observedAttributes (by the broser) -> creation of `prop` setters/getters (createProperty) -> constructor of `my-element` -> `prop` setter -> _requestPropertyUpdate -> LitElement.update -> UpdatingElement.update -> _propertyToAttribute -> setAttribute  custom element cannot be created.

#### Expected Results
`setAttribute` is not called during the constructor phase

#### Actual Results
`setAttribute` is called and the error
`Uncaught DOMException: Failed to construct 'CustomElement': The result must not have attributes`
is triggered

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

### Versions

- lit-element: v0.6.1
- webcomponents: v1.2.6

**Comment by pshihn** [comment]
This is definitely an issue for properties that are reflected. If you DO need to reflect this property, I'd suggest initializing the property in `connectedCallback` or perhaps in `createRenderRoot`

**Comment by sorvell** [comment]
This should not happen because `LitElement` sets attributes during the `update` cycle, which is asynchronous.

Here's a working example: https://glitch.com/edit/#!/opalescent-woodpecker?path=my-element.ts:9:59.

Please feel free to re-open the issue with more information if the problem persists.

**Comment by paulcodiny** [comment]
Thanks a lot!
I checked the example and it works perfectly. Seems, something is wrong with my code.
Will investigate more and re-open, if something pops up
