### ISSUE TITLE
Default property values are not applied to `changedProperties` until after `updated` has fired

### ISSUE THREAD

**Issue by ChrisBrownie55** [Polymer/lit-element#287]
#### Live Demo
[Here is a link to the live demo code on Glitch](https://glitch.com/edit/#!/separate-library)

#### Steps to Reproduce

1. Create an element: `class FooX extends LitElement`
2. Give it boolean property: `return { open: { type: Boolean } }`
3. Initialize that property to `false` in the constructor: `this.open = false`
4. Check the value of your property in the `updated` lifecycle method: `changedProperties.get('open')`

#### Expected Results

I expected `changedProperties.get('open')` to equal `false`

#### Actual Results

`changedProperties.get('open')` returns undefined

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari 11
- [x] Safari 10
- [x] IE 11

### Versions

- lit-element: v^0.6.2
- webcomponents: v^2.0.0

**Comment by msteller-connyun** [comment]
I think I have an issue which is connected to yours.

I have a lit-element with a boolean attribute:

```
  static get properties() {
    return {
      backdrop: {type: Boolean},
    };
  }
  constructor() {
    super();
    this.backdrop = true;
  }

<my-component backdrop="false"></my-component>

```

Independent of initial value in the my-componen backdrop attribute the result will always be `true`.
Even if I remove the default value `this.backdrop = true`, the result will always be `true`.

**Comment by ChrisBrownie55** [comment]
@msteller-connyun Boolean attributes' values are determined by whether or not that attribute exists or not. If you don't pass in `backdrop`, it becomes false. If you do pass in `backdrop` then it's true no matter the value. However, if I'm not mistaken you can do `.backdrop=${false}`

**Comment by jsilvermist** [comment]
If you want to default to true, you're probably better using a boolean attribute like `no-backdrop`.
Eg. `<my-el no-backdrop other-data="foo"></my-el>

**Comment by msteller-connyun** [comment]
Hm.... I think this is not very user friendly.

Just think of you built a widget with a boolean attribute. You set it the attribute to true in your implementation. Some time later an other developer see this attribute and want to disable it, so he will set it intunitiv to false and is confused why it’s not working.

I would strongly recommend to add a small check for booleans if the the string value is `false` (in combination with `toLowerCase()`) and then set the boolean to false.

**Comment by LarsDenBakker** [comment]
We should definitely stick to the HTML spec here even if it is unintuitive.:(

**Comment by msteller-connyun** [comment]
I have just discussed this with a colleague.

HTML already has a boolean, e.g. `disabled`.

 `disabled` is `true` as soon as the attribute is set (even if it is empty).

You could also think about adapting lit-html to the HTML standard, currently lit only sets a `true` if there is any content in the attribute.


http://joequery.me/code/html-boolean-attributes/

**Comment by msteller-connyun** [comment]
@LarsDenBakker 

See my last comment, I think lit doesn’t use the HTML spec correctly.

If I set just `<my-widet backdrop>` backdrop is undefined instead of `true`.

**Comment by LarsDenBakker** [comment]
Yes the expected behavior is that that sets it to true, I think this is how LitElement handles it

**Comment by msteller-connyun** [comment]
Then we have a bug:

```
  static get properties() {
    return {
      backdrop: {type: Boolean},
    };
  }

  render() {
    console.log('backdrop', this.getAttribute('backdrop'), this.backdrop); // -> "backdrop null undefined"
   }

```

However, I will just use strings instead of a boolean now. The HTML spec boolean implementation is to limited for my taste.
It makes it impossible to set a boolean default value to true and disable it with an attribute.

**Comment by ChrisBrownie55** [comment]
@msteller-connyun you still have to give it a default value in your contractor of false, I believe.

**Comment by pshihn** [comment]
@ChrisBrownie55 regarding your original issue - `changedProperties` is a Map with keys for the changed properties pointing to their previous values. Not their current values. You can get current value as `this.open`.

**Comment by ChrisBrownie55** [comment]
@pshihn I guess my question is then, why is it that the default value is set first in the constructor but the changedProperties starts with undefined, shouldn't the map be populated with the default value or did someone decide that it should always be populated with undefined first.

**Comment by pshihn** [comment]
@ChrisBrownie55 `changedProperties` contains keys of all the properties that have changed mapped to their previous values.  Initializing the property means when the next render is scheduled, it will be one the properties in the changedMap. Before it was initialized, the default value was `undefined`. 

I can see how it's not straightforward on first render, but the idea behind `changedProperties` is not to give the current state. Think of it as change of properties between renders. 
It would be weird if the map said the previous value was `true` and the current value was also `true`.
