### ISSUE TITLE
Mulitple Errors with reflected properties and updatestate errors.

### ISSUE THREAD

**Issue by andreabosman16** [Polymer/lit-element#289]
### Description
Errors when using multiple properties with the reflected property. 

#### Live Demo
DIY 

#### Steps to Reproduce
1. Create `my-textbox`
2. Create 4 properties with the `@property` decorator
3. Create one property of each type one inside the render 1 without reflect and 2 with reflect.
4. Test all the properties inside the connected callback with `console.log(Property)`.
 

#### Expected Results

No error with all the properties values inside the console.
#### Actual Results

Error CustomElement may not return attributes this error goes away when the reflected properties are optional and not declared inside the constructor.
When you do this all the reflected properties except the first one inside the dom will be undefined.
The issue is descript more in-depth here https://github.com/Polymer/lit-element/issues/224

I have a proposal I don t know if this is something that is wrong or I am using the lit-element wrong,
But i searched the code and i think there is a mistake inside the following function `_propertyToAttribute(name,options)` the following state is updated before setting a attribute or removing one from the dom : `this.updateState = this._updateState | STATE_IS_REFLECTING` . When the element is done with setting the property  the value will be set back like so `this._updateState = this._updateState & ~STATE_IS_REFLECTING;`.

There is one problem when setAttribute or RemoveAttribute is called the attributeChangedcallback is called and all waiting attributes start updating. This gives a problem when there are multiple attributes with reflect because when the attributeChangedattribute is called the following function is called as well `attributeToProperty` this function checks `this.updateState`. But this gives problems because `this.updateState` is still not updated so the reflected attributes will not be reflected. I commented the following inside the `_propertyToAttribute` 
 
 - `this._updateState = this._updateState | STATE_IS_REFLECTING;`
  - `// mark state not reflecting this._updateState = this._updateState & ~STATE_IS_REFLECTING;`

when commented the code runs smoothly and does what I expect it to do. 
I think the state needs to be set on an attribute not on the class itself this blocks the rest of the processes to work like intended.I Hope I will get a reaction if this is a bug or just me not getting the concept and randomly changing code until it works.

### Browsers Affected

- [*] Chrome
- [*] Firefox
- [*] Edge
- [*] Safari 11
- [*] Safari 10
- [*] IE 11

### Versions
- lit-element: v0.6.2
- webcomponents: vX.X.X

**Comment by sorvell** [comment]
We have finally understood the [underlying issue here](https://github.com/Polymer/lit-element/issues/258#issuecomment-447156886). Closing this issue since it is now clearly a dup of https://github.com/Polymer/lit-element/issues/258.
