### ISSUE TITLE
Make `validate` and `invalidate` protected

### ISSUE THREAD

**Issue by sorvell** [Polymer/lit-element#290]
These are useful extension points for scheduling rendering so they should be protected.

**Comment by Westbrook** [comment]
I'd love to help get this closed as it looks like a blocker to 1.0.0! If you aren't already working on it, of course...

This change is mainly updating:
```
private _validate() {
```
to
```
protected validate() {
```
and 
```
private async _invalidate() {
```
to
```
protected async invalidate() {
```
and then making reference corrections across the repo, right?

I'll get started on putting together PR, but look forward to any other desires around this in the interim!

**Comment by Westbrook** [comment]
I could probably use some help with the README content, too!

**Comment by daKmoR** [comment]
As I just saw it here: https://github.com/Polymer/lit-element/pull/276/files#diff-c5f280d12b2d91f8b89fe4ac3b6313d8R522

I think it will still be
```
protected _validate() {
protected async _invalidate() {
```

to keep following the naming conventions (as real protected and private are probably still some time off for "plain" javascript :see_no_evil: )

**Comment by Westbrook** [comment]
I guess it's a question of whether it's a `lifecycle` method, or an `extension` point... I was basing my decision off of https://github.com/Polymer/lit-element/blob/master/src/lib/updating-element.ts#L589

Hope this conversations is helping more than it's hurting @sorvell. Let me know which way I can move forward on this!
