### ISSUE TITLE
Removing an attribute for a property of type `String` sets the property to `null`

### ISSUE THREAD

**Issue by sorvell** [Polymer/lit-element#293]
This is obviously unexpected behavior. Here's an example:

https://glitch.com/edit/#!/titanium-gate

**Comment by kevinpschaaf** [comment]
Fixed by https://github.com/Polymer/lit-element/pull/369.

The default converter now returns literal `null` for `type: String` (not string `'null'`) when `attributeChangedCallback` returns `null` after removing a property.  `null` then bound to `textContent` results in an empty string.
