### ISSUE TITLE
Consider removing async/await for better browser support

### ISSUE THREAD

**Issue by popeindustries** [Polymer/lit-element#295]
Currently, [`updating-element._invalidate()`](https://github.com/Polymer/lit-element/blob/master/src/lib/updating-element.ts#L512) is the only `async` function in the codebase. Unfortunately, transpiling `async/await` for older browsers generates a lot of additional code (due to generator transpilation and the regenerator runtime required), and is generally avoided for production applications. Since this is the only place `async/await` is used, perhaps it would be possible to refactor this method to use plain Promises instead? 

I would prefer to open a PR rather than an issue, but my initial rewrite attempt was unsuccessful without a better understanding of the intended behaviour. I can certainly open a work-in-progress attempt if someone smarter than me is willing to help fix my faulty logic. 

**UPDATE**: use `fast-async` as Babel/Rollup plugin to transpile `async/await` to Promises (see comment [below](#issuecomment-437290194)

**Comment by mkay581** [comment]
Can you clarify which browsers you mean when you say "older browsers"? 🤔

**Comment by hyperpress** [comment]
Without knowing specifically what browsers are involved, I can't conceive of a good reason to remove async/await if the only reason is better support for old browsers. That would be a significant regression.

**Comment by eskan** [comment]
the only limitation i see is IE11, if i well remember it's in target browser list

**Comment by hyperpress** [comment]
While I think it's important to provide workaround solutions for IE11 when reasonable, we shouldn't end up with a significant regression just to satisfy the limitations of very old browsers.

**Comment by jsilvermist** [comment]
At this point, I feel like if it works at all in IE11 that's more than enough, and by no means should we avoid using new features just to avoid using a working polyfill in a dated browser.

**Comment by web-padawan** [comment]
One reason could be building a lightweight library on top of LitElement and distributing it as bundled UMD module. Including `regenerator-runtime` because of just 1 method would indeed hurt.

@sorvell @justinfagnani WDYT?

**Comment by popeindustries** [comment]
Thanks for the input! I certainly wouldn't have made the suggestion if I thought it would require significant negative changes. `async/await` code is certainly cleaner, but I don't think that rewriting to use Promises in this case would result in a major change. 

I am a fan of `async/await`, and use it as much as I can in Node and Service Workers, but I (and many others) think it's too early to require it as a production baseline for all clients. The transpiled code ([regenerator](https://github.com/facebook/regenerator/blob/master/packages/regenerator-runtime/runtime.js) runtime included) would add 700+ lines of additional code! 

I think **lit-html/lit-element** are exciting projects, and they deserve to reach as wide an audience as possible. Sometimes it's worth being a little pragmatic to achieve that.

**Comment by popeindustries** [comment]
Without diving into the details, I would expect that changing this:

```js
  private async _invalidate() {
    if (!this._hasRequestedUpdate) {
      // mark state updating...
      this._updateState = this._updateState | STATE_UPDATE_REQUESTED;
      let resolver: any;
      const previousValidatePromise = this._updatePromise;
      this._updatePromise = new Promise((r) => resolver = r);
      await previousValidatePromise;
      this._validate();
      resolver!(!this._hasRequestedUpdate);
    }
    return this.updateComplete;
  }
```

...to this:

```js
private _invalidate() {
    if (!this._hasRequestedUpdate) {
      // mark state updating...
      this._updateState = this._updateState | STATE_UPDATE_REQUESTED;
      let resolver: any;
      const previousValidatePromise = this._updatePromise;
      this._updatePromise = new Promise((r) => resolver = r);
      return previousValidatePromise.then(() => {
        this._validate();
        resolver!(!this._hasRequestedUpdate);
        return this.updateComplete;
      })
    }
    return this.updateComplete;
  }
```
...would be equivalent.

**Comment by Lodin** [comment]
Actually, I don't think that browsers that don't support `async-await` are the main target of `lit-element` library. Basically because all browsers that support WebComponents, the core and very essential concept of `lit-element`, definitely support `async-await` as well. For older browsers we have polyfills for WC and Babel for `async-await`.

**Comment by popeindustries** [comment]
@Lodin, in theory, I'm 100% in agreement with you, but in practice, the polyfill for `async/await` is so onerous that it's not really even an option. Maybe in a year or so we won't have to think about it anymore, but for large, high-traffic production sites, it's just not feasible.

**Comment by web-padawan** [comment]
Including `regenerator-runtime` would make sense if you use LitElement in the app consistently, and your app uses `async/await` too. 

However, what I'm saying is that we could build small web components library and provide it as UMD bundle to include on the static websites, e.g. not using `lit-html` at all. Thanks to small size of LitElement it is possible, but `regenerator-runtime` is 2 KB (even with Brotli compression).

Wasting 2KB of the network traffic for just 2 statements seems like an overkill for such cases.

**Comment by Lodin** [comment]
@popeindustries, I agree that `regenerator-runtime` is not the most convenient transformation (especially if we have promises), but comparing with the WC polyfill it doesn't look so onerous, IMO.

BTW, there is babel/babel#7076 that would solve your issue.

**Comment by popeindustries** [comment]
@Lodin thanks for the link. I didn't realise that there are (potentially) other transform alternatives available. 

I guess I can conclude from this discussion that transpiling `async/await` is mandatory for use with **lit-element**. I'd suggest that a note be added to the [Supported Browsers](
https://github.com/Polymer/lit-element#supported-browsers) Readme section in that case (and it wouldn't hurt to list all the polyfill requirements there as well).

**Comment by web-padawan** [comment]
@popeindustries I would like to still get some feedback from the authors, especially Steve and Justin.
The PR adding Babel transform, which is linked above, is more than 1 year old and still not merged.

**Comment by popeindustries** [comment]
@web-padawan OK, reopening until we hear from a maintainer...

**Comment by web-padawan** [comment]
BTW there is a community plugin which could be worth trying:
https://github.com/rpetrich/babel-plugin-transform-async-to-promises

**Comment by Lodin** [comment]
@web-padawan, yeah, Babel can be very slow in merging non-urgent PRs but I hope this feature will be added eventually.

**Comment by popeindustries** [comment]
I've had a chance to try out [`fast-async`](https://github.com/MatAtBread/fast-async) (tipped by Jason Miller and referenced in the Babel PR linked above), and I'm optimistic this could be a workable solution. It's in any case *way* better than Regenerator.

Using Babel and `@babel/preset-env`:

```js
{
    ...otherBabelConfig,
    presets: [
      [
        '@babel/preset-env',
        {
          targets: { browsers: ['ie >= 9'] },
          useBuiltIns: false,
          exclude: ['transform-regenerator', 'transform-async-to-generator']
        }
      ]
    ],
    plugins:[['module:fast-async',  { spec: true } ]]
}
```

Using Rollup.js:

```js
import nodent from 'rollup-plugin-nodent';

{
  ...otherRollupConfig,
  plugins: [
    nodent({ spec: true })
  ]
}
```

**Comment by popeindustries** [comment]
@justinfagnani thanks for responding. Will close this and keep experimenting with `fast-async`
