### ISSUE TITLE
render() method proposal

### ISSUE THREAD

**Issue by PaulMaly** [Polymer/lit-element#296]
Hi guys! Just learned about this great library. Thanks!

In my small implementation of a base class for `lit-html` I've used render() method to push `lit-html` directives directly to the child class, like this:

```javascript
class MyElement extends LitElement {
   ...
   render({ html, repeat, ...others }) {
        return html`
                ${repeat(...)}
        `;
   }
}
```
This helps me avoid permanent imports of `lit-html` stuff in each component because, well, `render()` method should return `TemplateResult` in all cases, I guess. 

So, seems, it sounds reasonable if a base class will provide all the stuff for this. What do you think about it?

**Comment by ChrisBrownie55** [comment]
Wouldn't this greatly increase the size of the class LitElement, therefore, forcing everyone's web components and apps to be slower?

**Comment by sorvell** [comment]
Thanks for the suggestion. For simplicity we're electing not to make any changes right now. It should, however, be pretty easy to make a subclass that modifies `render` as you see fit.
