### ISSUE TITLE
Example html file is not working

### ISSUE THREAD

**Issue by jnylund** [Polymer/lit-element#297]
### Description

When I use this example linked from the read.me (of lit-element) - https://gist.githubusercontent.com/sorvell/48f4b7be35c8748e8f6db5c66d36ee29/raw/2427328cf1ebae5077902a6bff5ddd8db45e83e4/index.html

Under Getting Started section:

You can also copy this HTML file into a local file and run it in any browser that supports JavaScript Modules.

The link of the html file goes to the gist noted above, when I try lit-element using this gist,  I get nothing rendered

#### Steps to Reproduce
Copy html and run it, it uses _render (not render),.

#### Expected Results
Should show the mood

#### Actual Results
blank page

### Browsers Affected

- [ x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

### Versions

- lit-element: vX.X.X
- webcomponents: vX.X.X

**Comment by thepassle** [comment]
It's a problem on Stackblitz' side:
https://github.com/Polymer/lit-element/issues/177#issuecomment-420222531

There's an issue on the Stackblitz repo here: 
https://github.com/stackblitz/core/issues/353#issuecomment-431711242

**Comment by jnylund** [comment]
Sorry, maybe my report was not clear. I'm confused, what does the lit-element instructions page (read.me) have to do with stackblitz?  I think either the read.me needs to be changed to point to another gist, or the gist needs to be updated.

**Comment by arthurevans** [comment]
@sorvell can you update your gist to match the minimal example in the README?

**Comment by sorvell** [comment]
Updated the example.

https://gist.github.com/sorvell/48f4b7be35c8748e8f6db5c66d36ee29

**Comment by mvysny** [comment]
This is NOT fixed. The README.md still points to https://gist.githubusercontent.com/sorvell/48f4b7be35c8748e8f6db5c66d36ee29/raw/2427328cf1ebae5077902a6bff5ddd8db45e83e4/index.html which still uses `_render()` instead of `render()`.
