### ISSUE TITLE
Empty and 404-ing docs pages.

### ISSUE THREAD

**Issue by bicknellr** [Polymer/lit-element#299]
This page is empty:
https://lit-element.polymer-project.org/docs/

Also, these pages linked under "API Documentation" in the left navigation don't seem to exist:
"Work with properties": https://lit-element.polymer-project.org/docs/properties
"Work with events": https://lit-element.polymer-project.org/docs/events
"Create reusable features": https://lit-element.polymer-project.org/docs/reuse
"Style elements with CSS": https://lit-element.polymer-project.org/docs/style
"API reference": https://lit-element.polymer-project.org/docs/api

This page is empty with a TODO:
https://lit-element.polymer-project.org/about

cc @katejeffreys

**Comment by bicknellr** [comment]
Also, in the footer used throughout the site, there's a "LitElement" link in the "More projects" list pointing to https://polymer.github.io/lit-element/ which also 404's.

**Comment by arthurevans** [comment]
Site has been updated and these issues appear to have been addressed.

**Comment by Cesarec88** [comment]
New Issue on [Try LitElement](https://lit-element.polymer-project.org/try) page, the link "Getting Started Page" exited 404 here the  [link](https://lit-element.polymer-project.org/start)

**Comment by jodekirk** [comment]
> New Issue on [Try LitElement](https://lit-element.polymer-project.org/try) page, the link "Getting Started Page" exited 404 here the [link](https://lit-element.polymer-project.org/start)

Getting Started Page link should be https://lit-element.polymer-project.org/guide/start

**Comment by bicknellr** [comment]
Looks like that link was fixed in https://github.com/Polymer/lit-element/pull/639. Probably just needs a new build pushed?
