### ISSUE TITLE
Add ES5 built

### ISSUE THREAD

**Issue by msteller-connyun** [Polymer/lit-element#302]
The current built (0.6.2) does not include a es5 built like most other libraries.

This brings some complications, because most babel configs exclude the node_module directory.

For lit-element projects I have to add @polymer/lit-element and lit-html to the babel directories and the babel regeneratorRuntime is required on runtime.

It would be very helpful if further versions of lit-element would contain a dependency free es5 built.

**Comment by web-padawan** [comment]
See clarifications at Polymer/lit-html#516

**Comment by msteller-connyun** [comment]
Hey web-padawan,

thank you for your answer.

I still think a es5 built would be very useful, because it make it’s easier to use lit-element what help lit-element to spread. ;)

SkateJs has a very similar approach like lit-element and offers an es5 build
https://github.com/skatejs/skatejs

However, it’s your decision.  But I strongly recommend to add a es5 to gain acceptance outside of the polymer ecosystem.

Btw, I found a solution for the regeneratorRuntime issue I mentioned. The babel-plugin 
https://babeljs.io/docs/en/babel-plugin-transform-runtime
will built the regeneratorRuntime into the build. With this plugin it’s no longer necessary for a lit-element widget to use  the babel/polyfill in the application runtime which allows us to build self-contained  lit-element widgets.

**Comment by justinfagnani** [comment]
We only publish unbundled ES2017 modules across all our projects. See the rationale here: https://lit-html.polymer-project.org/guide/concepts#javascript-modules
