### ISSUE TITLE
Default attribute values

### ISSUE THREAD

**Issue by msteller-connyun** [Polymer/lit-element#304]
### Description
Add a default values for properties

```
  static get properties() {
    return {
      width: {{attribute: 'my-width', type: String, default: '200px'},
    };
  }
```

#### Expected Results
The default value should be used if the attribute is empty.

#### Actual Results
There is no default value feature for properties. The workaround to define the default values in the constructor is from my point of few not a good solution because properties definition and default values are separated.

```
  static get properties() {
    return {
      width: {{attribute: 'my-width', type: String},
    };
  }

  constructor() {
    super();
   this.width =  '200px';
  }
```

### Versions

- lit-element: v0.6.3

**Comment by sorvell** [comment]
Thanks for the suggestion. We're electing not to add this right now for two reasons:

First, it's a standard practice to initialize properties in your class constructor and we don't want to buck that trend.

Second, class fields are soon coming to Javascript and are already available in `TypeScript` and `Babel`. Here's an example in `TypeScript`: https://glitch.com/edit/#!/lit-element-typescript?path=my-element.ts:7:2
