### ISSUE TITLE
LitElement.render has return type void, why not TemplateResult?

### ISSUE THREAD

**Issue by mikeleonard** [Polymer/lit-element#309]
### Description
In typescript you can currently extend LitElement with a class whose render method has a different type signature. For example this doesn't produce any typechecking errors:

```typescript
export class MyElement extends LitElement {
    render() {
        return "something other than TemplateResult";
    }
}
```

#### Expected Results

I would expect to see the following ts error:
```typescript
[ts]
Property 'render' in type 'MyElement' is not assignable to the same property in base type 'LitElement'.
  Type '() => string' is not assignable to type '() => TemplateResult'.
    Type 'string' is not assignable to type 'TemplateResult'. [2416]
(method) MyElement.render(): string
```

#### Proposal

In the LitElement class, change `protected render(): void` to `protected render(): TemplateResult`
```typescript
export declare class LitElement extends UpdatingElement {
    /**
     * Invoked on each update to perform rendering tasks. This method must return
     * a lit-html TemplateResult. Setting properties inside this method will *not*
     * trigger the element to update.
     * @returns {TemplateResult} Must return a lit-html TemplateResult.
     */
    protected render(): TemplateResult;
}
```

The type signature was previously `abstract protected render(): TemplateResult` and was changed to `protected render(): void` in this pull request: https://github.com/Polymer/lit-element/pull/228/files. 

This was done to change it from an abstract class to a normal class in order to make the mixin pattern work better. I agree with getting rid of abstract, but I'm not sure why the return type was changed to `void` - could it be changed back to TemplateResult? 

If there's a reason for having the return type as `void` then no problem at all, just wanted to ask the question before you hit 1.0.

**Comment by mikeleonard** [comment]
Also the `updateComplete` promise returned by `requestUpdate` has the type `Promise<unknown>`... however the documentation says it returns a promise of a boolean. 

It would be I think useful for typescript users to change this to boolean. Thoughts?
```javascript
     /**
     * Returns a Promise that resolves when the element has completed updating.
     * The Promise value is a boolean that is `true` if the element completed the
     * update without triggering another update. The Promise result is `false` if
     * a property was set inside `updated()`. This getter can be implemented to
     * await additional state. For example, it is sometimes useful to await a
     * rendered element before fulfilling this Promise. To do this, first await
     * `super.updateComplete` then any subsequent state.
     *
     * @returns {Promise} The Promise returns a boolean that indicates if the
     * update resolved without triggering another update.
     */
    readonly updateComplete: Promise<unknown>;
```

**Comment by mchyb** [comment]
This one can be closed, right?

**Comment by sorvell** [comment]
Yup.
