### ISSUE TITLE
Refrencing external svg file not working in safari.

### ISSUE THREAD

**Issue by ivands** [Polymer/lit-element#313]
For some reason the following code doesn't work in Safari.
Refrencing external svg files doesn't work in safari with lit-element.
The code does work with lit-html tho.
Could someone explain to me why this bug only apears in lit-element.
Is it a shadowDom bug or something?

```coffeescript
namespacedAttr = directive (namespace, value) -> (part) ->
  part.committer.element.setAttributeNS(
    namespace
    part.committer.name
    href
  )
```

Does work
```coffeescript
xlink = 'http://www.w3.org/1999/xlink'
href = '/icon.svg#icon-send'
template = html"
  <svg>
    <use xlink:href='#{ namespacedAttr xlink, href }' href='#{ href }'></use>
  </svg>
"

render template, document.body
```

Not working
```coffeescript
export default class IconSvg extends LitElement
  render: ->
    xlink = 'http://www.w3.org/1999/xlink'
    href = '/icon.svg#icon-send'
    return html"
      <svg>
        <use xlink:href='#{ namespacedAttr xlink, href }' href='#{ href }'></use>
      </svg>
    "
```

**Comment by kuka-radovan** [comment]
I have the same issue that I tried to solve today without any success.

**Comment by ivands** [comment]
@kuka-radovan chrome works fine for me because chrome uses the `href` attribute.
Safari is still using the `xlink:href` attribute that I'm guessing is the cause of the problem.

**Comment by ivands** [comment]
Maybe loading external SVG files into a custom element isn't the way to go.
In chrome the external SVG is loaded each time I use my custom element.
The browser doesn't even cache the SVG. 😭

**Comment by kevinmpowell** [comment]
This issue still exists and I ran into it today. I can confirm @ivands original issue. His reduced test cases show it working with `lit-html` but not with `lit-element`.

The example @keanulee provided is not doing the same thing. In @keanulee's example the SVG is using the `<image>` tag within the svg, not the `<use>` tag.

I'd like to see a working example in `lit-element` that uses the `<use>` tag.

**Comment by kevinmpowell** [comment]
I found the answer here: https://github.com/Polymer/lit-html/issues/423 (all the way at the bottom).

There's a directive you can add to support the `xlink:href` attribute (a namespaced attribute) in Safari.
