### ISSUE TITLE
Boolean attributes not set when rendering from HTML

### ISSUE THREAD

**Issue by KeithHenry** [Polymer/lit-element#314]
### Description
I have a basic component with a boolean property:

```ts
@customElement('my-component' as any)
class MyComponent extends LitElement {

    @property()
    foobar = false;

    render() {
        html`${this.foobar ? html`TRUE` : html`FALSE`}`;
    }
}
```

This is rendered by another library that isn't using Lit:

```html
<my-component foobar></my-component>
```

This should render `TRUE`, but renders `FALSE`. When inspecting the HTML the foobar attribute is present and using `$0.foobar` to access the property returns `''`.

If called with an explicit value (using `<my-component foobar="whatever"></my-component>`) this works.

#### Live Demo
https://stackblitz.com/edit/boolean-prop-bug

#### Steps to Reproduce
1. Create a TS element.
2. Use `@property` decorator on `boolean` property.
3. Attempt to set the attribute from outside Lit.
4. Attribute is set but not mapped to property correctly.

#### Expected Results
Control displays `TRUE`.

#### Actual Results
Control displays `FALSE`.

### Browsers Affected
Appears in Chrome without polyfill

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

### Versions
- lit-element: v0.6.3

**Comment by KeithHenry** [comment]
I think this might be something I've missed from the documentation, as adding an explicit type works:

```ts
@customElement('my-component' as any)
class MyComponent extends LitElement {

    @property({ type: Boolean })
    foobar = false;

    render() {
        html`${this.foobar ? html`TRUE` : html`FALSE`}`;
    }
}
```

**Comment by sorvell** [comment]
That's right. To indicate that the property value should be treated as a Boolean when serializing to or deserializing from an attribute, you should use `type: Boolean`.
