### ISSUE TITLE
[docs] Clarify docs on hasChanged & update lifecycle (e.g. multiple property changes)

### ISSUE THREAD

**Issue by jason-gu** [Polymer/lit-element#318]
According to the [documentation](https://lit-element.polymer-project.org/docs/properties#haschanged) if an observed property's hasChanged() returns true, LitElement starts an element update; returning false will result in no updates. But this isn't always the case, if you have multiple properties with multiple hasChanged methods, and some return true, others return false. LitElement will still update properties whose hasChanged() return false.

`
import {LitElement, html} from '@polymer/lit-element';

class MyElement extends LitElement {
	static get properties() {
		return {

			myProp: {
				type: String,
				attribute: 'my-prop',
				reflect: true,
				hasChanged(newValue, oldValue) {
					return true;
				}
			},

			someProp: {
				type: String,
				hasChanged(newValue, oldValue) {
					return false;
				}
			}
		};
	}

	constructor() {
		super();
		this.myProp = 'myProp';
		this.someProp = 'someProp';
	}

	attributeChangedCallback(name, oldValue, newValue) {
		super.attributeChangedCallback(name, oldValue, newValue);
	}

	changeAttributes() {
		let randomString = Math.floor(Math.random()*100).toString();
		this.setAttribute('my-prop', 'my-prop ' + randomString);
		this.setAttribute('someprop', 'someprop ' + randomString);
		this.requestUpdate();
	}

	changeProperties() {
		let randomString = Math.floor(Math.random()*100).toString();
		this.myProp = 'myProp ' + randomString;
		this.someProp = 'someProp ' + randomString;
	}

	render() {
		return html
<p>${this.myProp}</p>
<p>${this.someProp}</p>
<button @click="${this.changeAttributes}">Change Attributes</button>
<button @click="${this.changeProperties}">Change Properties</button>
;
	}

	updated() {
		console.log(this);
	}
}

customElements.define('my-element', MyElement);
`

#### Expected Results

Properties whose hashChanged() returning false should not be updated.

#### Actual Results

As long as there's one property's hasChanged() returns true, everything gets updated.

### Browsers Affected

- [*] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

### Versions

- "@polymer/lit-element": "latest",
- "@webcomponents/webcomponentsjs": "^2.2.0",
- "lit-html": "latest"

**Comment by jason-gu** [comment]
> That is the expected behavior - the return value is used to say whether the property changing should trigger an update. As long as at least one property says "yes, update" then an update happens.

I see what you mean, but IMO this is very confusing; the current behavior allows prop1 to control whether prop2 gets updated regardless of what prop2's hasChanged returns (true or false).

**Comment by sorvell** [comment]
We can try to clarify the documentation here. Here's the way we think about it. First, a property does not, itself, update, the element does. The element updates and calls its `render` method when a registered property changes or `requestUpdate` is called. 

A property changes whenever it's set to a different value. For properties of non-trivial type (i.e. objects), sometimes you want more direct control over whether or not the update system sees a "set" as a change. In particular, maybe an object's key updates and this should indicate that it's different and an update should occur. This is the intended usage for which `hasChanged` was designed.

If you want more direct control over the setting of a property, you can implement a getter/setter and call `requestUpdate(name, oldValue)` in the setter when an update should occur.

If you want to take some specific custom action (that you cannot achieve in the `render` method) based on the set of properties that have changed, you can implement `updated(changedProperties)` and take action based on the entire state of the element at that time.

**Comment by jason-gu** [comment]
@sorvell Thanks for the clarification. I think updating the doc to include how hasChanged() should be used and maybe some examples will definitely help other users.

**Comment by katejeffreys** [comment]
Thanks for raising it @jason-gu, I'll take a look at the docs.
