### ISSUE TITLE
requestUpdate() doesn't always trigger an update

### ISSUE THREAD

**Issue by jason-gu** [Polymer/lit-element#320]
See test code below: inside the handleClick(), the requestUpdate() call doesn't work.

```
import {html, LitElement} from '@polymer/lit-element';

const JSONType = {
	fromAttribute: (attr) => { return JSON.parse(attr) },
	toAttribute:   (prop) => { return JSON.stringify(prop) }
};

class MyElement extends LitElement {
	static get properties() {
		return {
			person: {
				type: JSONType,
				reflect: true
			}
		};
	}
	constructor() {
		super();
		this.person = {name: 'James', age: 6};
	}
	shouldUpdate(changedProps) {
		return changedProps.has('person');
	}
	handleClick(event) {

		// Doesn't Work
		this.person.name = 'Jason';
		this.person.age = 1;
		this.requestUpdate();

		// Works
		// this.person = Object.assign({}, this.person, { name: 'Jason', age: 1 });
		// this.person = {name: 'Jason', age: 1};
	}`
	`render() {
		return html`
<div>${this.num}</div>
<div>Name: ${this.person.name}, Age: ${this.person.age}</div>
<button type="button" @click="${this.handleClick}">Update Properties</button>
`;
	}
}
```

#### Expected Results
Click on the button update the element.

#### Actual Results
requestUpdate() doesn't trigger an update.

### Browsers Affected

- [*] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

### Versions

- lit-element: v0.6.3
- webcomponents: v2.2.1

**Comment by jolleekin** [comment]
Try
``` js
		this.person.name = 'Jason';
		this.person.age = 1;
		this.requestUpdate('person', this.person);
```

**Comment by jason-gu** [comment]
> ```js
> 		this.person.name = 'Jason';
> 		this.person.age = 1;
> 		this.requestUpdate('person', this.person);
> ```
Forgot to mention, I did try ```this.requestUpdate('person', oldValue);``` and it does work, but according to the [documentation](https://lit-element.polymer-project.org/docs/lifecycle/customize) ```this.requestUpdate()``` this should also work, as it creates an update request regardless of property changes.

**Comment by jolleekin** [comment]
It does create an update request with no changed properties, causing your `shouldUpdate` to return `false`.

**Comment by jason-gu** [comment]
> It does create an update request with no changed properties, causing your `shouldUpdate` to return `false`.

Thanks, it looks like shouldUpdate() is causing the issue here.
