### ISSUE TITLE
[docs] Add content: TypeScript decorators

### ISSUE THREAD

**Issue by katejeffreys** [Polymer/lit-element#338]
Add info on using typescript decorators - see also downlevel iteration https://github.com/Polymer/lit-element/issues/211

**Comment by bennypowers** [comment]
> I think switching between js and typescript styles in the docs can be confusing / make things look more complex than they really are. I like how firebase and the google cloud platform docs work where you chose the language and then all the examples are in the flavour you selected. e.g.
https://firebase.google.com/docs/admin/setup#initialize_the_sdk
captaincodeman in polymer slack

Typescript is cool and all, but it would be great if the docs reflected browser-standard JavaScript by default, with a 'flavour selector' to show TS code.

**Comment by katejeffreys** [comment]
To be handled in #420
