### ISSUE TITLE
[docs] Review Try LitElement page for technical accuracy

### ISSUE THREAD

**Issue by katejeffreys** [Polymer/lit-element#351]
Review the content at https://lit-element.polymer-project.org/guide/try for technical accuracy only. 

Markdown source: https://github.com/Polymer/lit-element/blob/master/docs/_guide/try.md

* [x] `@click="${this.clickHandler}"` 
* [x] change `i` to `item` in `Array.map` example

**Comment by frankiefu** [comment]
In [Style your template](https://lit-element.polymer-project.org/guide/try#6-style-your-template) section, the button click event handler could be like this:
```html
<button @click="${this.clickHandler}">Click</button>
```
