### ISSUE TITLE
[docs] Review Properties page for technical accuracy

### ISSUE THREAD

**Issue by katejeffreys** [Polymer/lit-element#354]
Review the content at https://lit-element.polymer-project.org/guide/properties for technical accuracy only. 

Markdown source: https://github.com/Polymer/lit-element/blob/master/docs/_guide/properties.md

* [x] Code embeds
* [x] check latest changes on serialization/types/etc
* [x] double check `blah: String` in samples, change to `blah: { type: String }`

**Comment by keanulee** [comment]
The TypeScript decorators code editor embed seems to be incorrectly placed after "Configure property options".

Some of the code editor embeds open index.ts on launch instead of my-element.ts/js.
