### ISSUE TITLE
[docs] Change all code samples & examples to remove quotes from around data bindings

### ISSUE THREAD

**Issue by katejeffreys** [Polymer/lit-element#363]
find out 

```
html`<button @click="${this.doStuff}">click</button>`
```

or 

```
html`<button @click=${this.doStuff}>click</button>`
```

Explain why, etc. Document it & update code samples

**Comment by katejeffreys** [comment]
https://github.com/Polymer/lit-element/pull/278

**Comment by katejeffreys** [comment]
@justinfagnani @keanulee @frankiefu opinions pls?

**Comment by keanulee** [comment]
Doesn't matter as long the expression is the complete attribute value. No quotes looks cleaner, but quotes is closer to standard HTML. Doc writer's choice IMO

**Comment by jhnsntmthy** [comment]
no quotes is more similar to how React injects attributes in JSX, so I'm used to that

**Comment by T-Knott-Mesh** [comment]
IMO closer to the syntax of standard HTML the better.

**Comment by katejeffreys** [comment]
https://github.com/Polymer/lit-element/pull/216

**Comment by katejeffreys** [comment]
So far I have this data:

* the quotes are 100% optional
* HTML syntax has quotes & some people would like to keep them for consistency
* No quotes looks cleaner & some people would like to get rid of them for concision

Taking them out makes editing my code samples super annoying because it removes syntax highlighting, so for my own sanity I'm going to leave them in my docs for now. I'll add a note somewhere saying they're optional.

**Comment by justinfagnani** [comment]
I think we should prefer non-quoted attribute bindings.

1. The symbol overhead for attribute bindings is already a bit high with `=${}`. `="${}"` is 50% more symbol characters.
2. Unquoted attributes are standard HTML, as long as they don't contain whitespace, `<` and some other control characters. This is in the spec.
3. VS Code's lit-html plug-in just fixed the bug where it doesn't highlight bindings in unquoted attributes: https://github.com/mjbvz/vscode-lit-html/pull/57

We can file a bug against Prettier to remove quotes.

**Comment by justinfagnani** [comment]
The Prettier playground, running 1.15.3, doesn't appear to change the quoting of bound attributes.

**Comment by katejeffreys** [comment]
@justinfagnani Sounds good.

Do you know of an automated way to fix all my code samples? I'm inclined to keep doing stuff the same way I have been to avoid inconsistency until I can fix them all at once.

**Comment by katejeffreys** [comment]
rolling into https://github.com/Polymer/lit-element/issues/395
