### ISSUE TITLE
[docs] Document changes to property declarations in #369

### ISSUE THREAD

**Issue by sorvell** [Polymer/lit-element#375]
Please refer to the changes noted in the [README](https://github.com/Polymer/lit-element/pull/369/files#diff-04c6e90faac2675aa89e2176d2eec7d8R38) and [CHANGELOG](https://github.com/Polymer/lit-element/pull/369/files#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR13).

We should also add a special note that although it's possible to `reflect: true` a `type: Object|Array` property, this should only be done in exceptional situations since the attribute becomes that JSON version of the property. If the property can have a non-trivial value, this will result in poor performance since the attribute can become a very long string.

**Comment by kevinpschaaf** [comment]
@katejeffreys Based on the changes in #369, this is the new behavior:

* LitElement uses a "converter" to serialize typed property values to string attribute values, and deserialize from string attribute values to typed property value
* The "converter" can specify either just a `fromAttribute` function, or an object with both a `toAttribute` and a `fromAttribute` function
* The `type` field is now only used as metadata to the converter. It is no longer invoked as a function by default.
* A built-in "default converter" is used if no `converter` is specified for a property, which handles common types: `String`, `Number`, `Boolean`, `Object`, and `Array`.  Any types outside of these will pass through the default converter as if they were `String`s (generally, it wouldn't make sense to use types outside of these without a custom `converter`).
* If `toAttribute` returns `null`, this is used as a signal to call `removeAttribute`
* If `toAttribute` returns `undefined`, this is used as a signal to not change the attribute
* Behavior of the default converter:
  * `fromAttribute`:

    | `type` | `attrValue !== null`  | `attrValue === null` (attribute removed) |
    | --- | --- | --- |
    | `String`  | `attrValue` | `null`  |
    | `Number`  | `Number(attrValue)` | `null`  |
    | `Boolean`  | `true` | `false`  |
    | `Object`  | `JSON.parse(attrValue)` | `null`  |
    | `Array`  | `JSON.parse(attrValue)` | `null`  |

  * `toAttribute`: (note returning `null` results in `removeAttribute`)

    | `type` | `propValue != null`  | `propValue == null`
    | --- | --- | --- |
    | `String`  | `propValue` | `null` |
    | `Number`  | `propValue` | `null` |
    | `Boolean`  | `propValue ? '' : null` | `null` |
    | `Object`  | `JSON.stringify(propValue)` | `null` |
    | `Array`  | `JSON.stringify(propValue)` | `null` |

**Comment by katejeffreys** [comment]
Staged here; https://20181218t010822-dot-polymer-lit-element.appspot.com/guide/properties
