### ISSUE TITLE
Question: How to really bundle lit-element with ESM as output.

### ISSUE THREAD

**Issue by andreabosman16** [Polymer/lit-element#382]
I am trying to bundle multiple web components with litelement within an application, but I cannot find a proper bundler that is able to output ESM bundles. Everything is bundled as Commonjs and this makes it impossible to use `<script src="adress_to_source" type=" module">` hopefully someone here knows a solution.

**Comment by katejeffreys** [comment]
to be handled in #397

sorry to e abrupt, triaging
