### ISSUE TITLE
[docs] After 1.0 release, update npm install instructions

### ISSUE THREAD

**Issue by arthurevans** [Polymer/lit-element#383]
This is a duplicate of the lit-html issue: https://github.com/Polymer/lit-html/issues/706

**Comment by katejeffreys** [comment]
`npm i lit-html@^1.0.0`

**Comment by justinfagnani** [comment]
Yeah, I think we want the same for lit-element, since it's a dependency of MWC, and we'll want to reduce duplication chances all around.

I mentioned to Kate in a review that we can't do this until we release 1.0, because `^1.0.0` doesn't match against pre-releases.

**Comment by katejeffreys** [comment]
After 1.0 release, change npm install instructions to:

```
npm install lit-element@^1.0.0
```

**Comment by katejeffreys** [comment]
https://github.com/Polymer/lit-element/blob/master/docs/_guide/index.md
https://github.com/Polymer/lit-element/blob/master/docs/_guide/start.md
https://github.com/Polymer/lit-element/blob/master/docs/_api/api-readme.md

**Comment by katejeffreys** [comment]
Also https://github.com/Polymer/lit-element/blob/master/docs/package.json

**Comment by katejeffreys** [comment]
And https://github.com/PolymerLabs/start-lit-element

**Comment by katejeffreys** [comment]
Fixed by #427
