### ISSUE TITLE
Improve support for setting css custom properties as mixins

### ISSUE THREAD

**Issue by sorvell** [Polymer/lit-element#39]
Many existing Polymer elements use the (deprecated) `@apply` feature to style multiple custom properties. This mostly works with LitElement now, but you cannot have multiple style elements in different lit-html templates that try to style the same mixin. Here's [an example](http://jsbin.com/guxoku/3/edit?html,output).

This actually a [ShadyCSS issue](https://github.com/webcomponents/shadycss/issues/178) and this is just a tracking issue.

**Comment by TimvdLippe** [comment]
Fixed in #102
