### ISSUE TITLE
[docs] build/test/deploy info for apps

### ISSUE THREAD

**Issue by katejeffreys** [Polymer/lit-element#397]
@arthurevans @graynorton @justinfagnani @kevinpschaaf 

Decide how & where to present this info

**Comment by katejeffreys** [comment]
@graynorton @justinfagnani @kevinpschaaf @arthurevans FYI

**Comment by katejeffreys** [comment]
#390 when doing this

**Comment by katejeffreys** [comment]
https://github.com/PolymerLabs/start-lit-element/pull/7 - attempted rollup (doesn't work)

**Comment by ashubham** [comment]
#125 is closed as a part of this, but #426 does not include any info about testing. Am I missing something here ? @katejeffreys @justinfagnani
