### ISSUE TITLE
[docs] Clarify docs on custom accessors, include use cases in issue comments

### ISSUE THREAD

**Issue by motss** [Polymer/lit-element#403]
It'd be great if a guide on how to create custom getter and setter can be added as part of the documentation for v1 release.

```ts
// contrived example, anyway
// `@property` has already taken care of `static get observedAttributes` and `static get properties`
// of native WC.
...

@customElement(MyElement.is)
export class MyElement extends LitElement {
  static get is() { return 'my-element'; }

  // ...Many property declarations here...

  // But, this one property needs custom setter and getter.
  @property({ type: String })
  public name: string = 'John Doe';

  private _name: string;

  // @ts-ignore
  public get name() {
    return this._name;
  }
  // @ts-ignore
  public set name(val: string) {
    /**
     * Don't set new value to `_name` with condition check.
     * Note that, by setting `name` attribute will change the value of
     * the attribute but not the value of the property.
     */
    if (val !== 'John Doe') return;

    this._value = val;
  }
}
```

**Comment by katejeffreys** [comment]
Have you seen this?

https://lit-element.polymer-project.org/guide/properties#accessors-custom

**Comment by motss** [comment]
@katejeffreys I'm aware of that but most of the time the docs just mention about using `static get properties` but not with the usage of `@property`. In addition to that, using `static get properties` for custom properties also means that you have to setup your own `static get observedAttributes` if you also want to observe changes of the property value from its attribute.

It does not work for me when I first tried it. But I need to verify it again with a reduced test case. That is why I came up with the code sample above which worked for me.

**Comment by katejeffreys** [comment]
I ass-umed custom getters and setters would work the same way for `@property` :) Will take a look at it and clarify these points. Thanks for the feedback & sample :)

**Comment by arthurevans** [comment]
Related to https://github.com/Polymer/lit-element/issues/338?

**Comment by katejeffreys** [comment]
To be handled in #420

**Comment by motss** [comment]
FWIW, the following code is what I'm looking for this issue. I thought I would update this when someone is facing the same issue.

https://github.com/Polymer/lit-element/blob/920a14afa6e2602b5b316d7693e147ab0657ad4a/src/test/lib/decorators_test.ts#L188-L220
