### ISSUE TITLE
[Question] Public class fields

### ISSUE THREAD

**Issue by stramel** [Polymer/lit-element#408]
What is the reason for using the static getter properties over public class fields?

Chrome 72 has shipped and Firefox and Safari are in development.

**Comment by LarsDenBakker** [comment]
The static properties getter tells `lit-element` which properties should trigger a re-render.

Public class fields are equivalent of setting properties in the constructor, which you also had to do with the static properties getter. So no real change there.

However combined with decorators, you don't need the static properties getter anymore:

```
class MyElement extends LitElement {
  @property({ type: String })
  myProperty = 'foo';
}

```

**Comment by sorvell** [comment]
That's right. In general, the static properties getter allows use without any transpiling today. It will likely someday be deprecated when platform support for decorators lands.
