### ISSUE TITLE
Unable to override performUpdate method

### ISSUE THREAD

**Issue by kambeena** [Polymer/lit-element#409]
#### Live Demo

https://stackblitz.com/edit/lit-element-example?file=index.js

https://glitch.com/edit/#!/hello-lit-element?path=index.html:1:0

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

### Versions

- lit-element: v0.6.5
- webcomponents: v2.2.1

I am unable to override performUpdate method. The demo is also not working at https://lit-element.polymer-project.org/guide/lifecycle#performupdate, no console log.  In my app I don't see console log.
async performUpdate() {
        //await new Promise((resolve) => requestAnimationFrame(() => resolve());
        console.log('Performing update..')
        super.performUpdate();
     }

**Comment by katejeffreys** [comment]
I think this is a versioning issue. Docs got ahead of the codebase - my bad.

**Comment by kambeena** [comment]
No problem. Thanks.

**Comment by sorvell** [comment]
The `performUpdate` method will be included in the 0.7 release which should be out shortly.
