### ISSUE TITLE
[Question] How to replace this.querySelectorAll('my-tab') with @queryAll annotation?

### ISSUE THREAD

**Issue by dflorey** [Polymer/lit-element#410]
I'm using

`let tabs: Tab[] = Array.from(this.querySelectorAll('my-tab'))`

to retrieve the list of slotted tab-elements.
Is there a way to replace it with a member called "tabs" with @queryAll annotation?
I tried with something like:

```
@queryAll("my-tab")
private _tabs: NodeListOf<Tab>
...
let tabs: Tab[] = Array.from(this._tabs)

```
but no luck yet... Ideas?

**Comment by katejeffreys** [comment]
to be handled in #420 

sorry to be abrupt, am triaging
