### ISSUE TITLE
Statically declared properties seem to not work as described in the guide

### ISSUE THREAD

**Issue by KrofDrakula** [Polymer/lit-element#411]
### Description

Declaring properties as `{type: Array}` or specifying a custom converter does not seem to work with v0.6.5 according to the guide docs.

#### Live Demo

https://codepen.io/KrofDrakula/pen/bOYJJo?editors=1010

#### Steps to Reproduce

Inspect the `console.log()` calls to see the properties to see that the converters aren't being invoked and return the incorrect values per the guide examples. The default Array converter only returns an array of a single string item, the string passed as the attribute value.

#### Expected Results

Per [the guide](https://lit-element.polymer-project.org/guide/properties#declare-properties-in-a-static-properties-getter), the default converter should JSON.parse() the stringified array in the attribute. I would expect the `converter` property of 

#### Actual Results

See the results displayed in the CodePen preview page and verify the console that no logs relating to the invocation of converters appears.

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [?] Edge
- [?] Safari 11
- [?] Safari 10
- [?] IE 11

Chrome and Firefox display the same behaviour; haven't tested in other browsers as I haven't set up any polyfills to support them.

### Versions

- lit-element: v0.6.5
- webcomponents: v2.2.1

**Comment by web-padawan** [comment]
This is again the problem of docs on master being ahead of actual release.
There should be 0.7.0 released to include `converter` and other changes.

**Comment by web-padawan** [comment]
Related to Polymer/lit-html#604

**Comment by sorvell** [comment]
This should be rectified shortly with the release of version 0.7. Sorry for the confusion.
