### ISSUE TITLE
Feature Request: Add `options` parameter to `@customElement` decorator

### ISSUE THREAD

**Issue by myateznik** [Polymer/lit-element#417]
### Description

Please consider adding optional `options` parameter to `@customElement` decorator for extensions of built-in elements.

Just pass options as third argument to: `window.customElements.define(tagName, clazz, options)`

#### Usage Example
```
import { LitElement, html, customElement } from '@polymer/lit-element'

@customElement('my-heading`, { extends: 'header' })
class MyHeading extends LitElement {
  render() {
    return html`Hello world!`
  }
}

// On page
<header is="my-heading"></header>
```

Equivalent to:
```
import { LitElement, html } from '@polymer/lit-element'

class MyHeading extends LitElement {
  render() {
    return html`Hello world!`
  }
}

customElements.define('my-heading`, MyHeading, { extends: 'header' })

// On page
<header is="my-heading"></header>
```

#### Live Demo
N / A

#### Steps to Reproduce
N / A

#### Expected Results
N / A

#### Actual Results
N / A

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

### Versions

- lit-element: N / A
- webcomponents: N / A

**Comment by sorvell** [comment]
We're generally not too keen on promoting use of custom elements that extend built in elements because Safari does not support it and has been generally against the feature.

**Comment by myateznik** [comment]
There are cases when it is necessary to preserve native capabilities / binding.

For example, to implement custom dialogs, it makes sense to expand the native element `dialog`, thereby obtaining greater accessibility with less code, which is important nowadays (mobile clients have already become mainstream and on average they have a slow connection).

In a specific example, this is a focus capture implementation that natively works on dialog elements, but on autonomous components, this behavior will have to be implemented in javascript.

Yes, maybe you can save native binding (focus capture) using class inheritance from `HTMLDialogElement`, however, until the javascript code executes, your element will not have these bindings, so it is not accessible enough. And this is a violation of UX since firstly we have a slow mobile connection, and secondly there is a certain percentage of users having disabled javascript.

Also note that class inheritance from `HTMLDialogElement` cannot be categorically considered as a replacement for the expansion of native elements through the `is` attribute, because in Safari this approach will not work anyway because Apple opposes the inheritance of classes inherited from `HTMLElement` (`HTMLDialogElement`, `HTMLQuoteElement`, etc.).

Note here that custom components do not necessarily use shadow dom they can use light dom.

Or another example, also related to accessibility: to reduce the amount of transmitted code, it makes sense to use the semantic elements `header`,` nav`, etc. Instead of specifying aria attributes, which, undoubtedly, can solve the accessibility problem, but can also increase amount of transmitted code.

For comparison, which is better:
```html
<nav is="global-nav">...</nav>
```
or:
```html
<global-nav role="navigation">...</global-nav>
```

The fact that Safari opposes this functionality is actually sad because it makes sense. This functionality is listed in the specification and has already been implemented in most major browsers with the exception of Apple. Looks like Apple is becoming Microsoft with its own Internet Explorer (Safari).

Apple simply does not want to implement such functionality, which simplifies the integration of custom elements into the native platform. From the very beginning, they are opposed and argue based on a purely personal notion and vision of the situation, and often they are very distant from real-world cases.

Apple also participated in the development of the CustomElements v1 specification and the only reason they agreed to preserve the `is` attribute and this functionality in the specification is to wait until the feature becomes at-risk at CR stage so that it can be removed.

However, this moment has not come, and the specification has retained this functionality, which may indicate that Apple’s vision of the situation is different from that of the web developer community. And it is precisely for this reason that the reasoning about this functionality has been going on for so long, and the opinions of the parties have not changed.

In this case, from the point of view of the web platform development, Apple is a minority, which unfortunately slows down the platform development because developers have to choose between three ways: to refuse to maintain functionality due to a minority (Safari), to abandon support for a minority (some projects can afford it), or to increase the amount of transferred code and using polyfiles.

One of the factors for the emergence of custom elements is the transfer of part of the repeated functionality to the client / platform and direct integration with the environment, because the implementation of some things work faster and better at a lower level.

And I do not think that the lack of implementation of this functionality in Safari should limit its use in other browsers. Again for Safari there are polyfils.

**Comment by justinfagnani** [comment]
Since LitElement isn't a mixin, exposing the `extends` option in some way wouldn't be usable. The `customElement` decorator isn't really necessary either, it's just a short convenience and doesn't help the type system like `@property`, `@query`, etc. If you need more out of it, `cutomElements.define()` works just fine.
