### ISSUE TITLE
Non-shadow dom API

### ISSUE THREAD

**Issue by LarsDenBakker** [Polymer/lit-element#42]
As a long-time user of Polymer, one of my biggest issues with Polymer.Element is it's hard buy-in with shadow dom. There is a method that you can overwrite to avoid creating a shadow root, but you really have to know what you're doing and then there are still issues around styling. Especially on browsers that need shady dom / css.

Shadow dom is a powerful tool and makes a lot of sense for building re-usable UI components. When building large complex applications, it is useful to split code up into separate components But in our experience, using shadow dom for all these private components has a lot of downsides. Closely associated components are unnecessarily isolated making tests more complicated, shared styles are duplicated many times over and especially on browser that do not have native shadow dom performance is negatively impacted. I think in the applications we build, over half our components do not need to use shadow dom. 

The current support for elements without shadow dom is to overwrite _createRoot and return 'this'. I'm worried that this is not a very intuitive API and already requires some in-depth knowledge of how this works internally. I'm hoping that there can be more official support for creating elements without shadow dom and that it's use cases are covered by documentation, demos and tests. I'd be happy to contribute this where possible.

**Comment by moebiusmania** [comment]
@LarsDenBakker this is a real good point, and for my experience a shared one. BTW YouTube itself *doesn't* use full Shadow DOM for the same reasons.

The `_createRoot => this` trick may be intuitive or not, but at least as opposite of Polymer it let you decide to use Shadow DOM or not individually, the main downside is that you loose support for `<slot>` element.  

It would be nice to have a sort of bultin `slot` polyfill activated when you opt to not use Shadow DOM.

**Comment by yavorski** [comment]
Started a new project with `lit-html` and `LitElement` 2 days ago.
I opted out of the shadow dom mainly because I wanted to use external stylesheet for my elements and to not have duplicated inlined css.
I also need to support firefox as well, and web components there are hidden behind a flag (really hope to be enabled by default soon).
Now `<link rel="stylesheet" href="my-element-style.css">` is supported in chrome/safari, but again shady css is really messy with firefox i am not sure it can be even pollyfilled.

**Comment by sorvell** [comment]
We'd like to encourage a default of using Shadow DOM because it's the right option when making a re-usable element since these need encapsulated dom and css. 

You have a point that when making an application, it is sometimes reasonable not to use Shadow DOM, and this is why we provide the `_createRoot` override point.

We're open to making this API simple and would welcome a proposal / PR.

**Comment by LarsDenBakker** [comment]
@sorvell Thanks for your  response. I'd be happy to make a PR, but we'd need to iron out some architecture first. 

A pattern I'd like to explore is the following:
```
<app-element-a>
  <style> element-d { border: 1px solid black; } </style>

  <app-element-b>
    <element-d>
      #shadowroot
    </element-d>
  </app-element-b>

  <app-element-c>
    <element-d>
      #shadowroot
    </element-d>
  </app-element-c>

</app-element-a>
```
In this example (pseudocode) element a, b and c don't use shadow dom, but render their template to the light dom. Element d is a reusable components and uses shadow dom. 

Element a renders styles which applies to all instances of element d in the dom of both children. 

This works fine on native shadow dom, but shady dom will hoist the styles to the head and scope the styles so that element a cannot select elements into element b. We can't turn off scoping, as it will make the styles apply everywhere, but perhaps there is some solution to this? An alternative could be to define scopes manually and pass them down as properties to sub components.

In terms of API, what I think would make it cleaner, and give more opportunities for optimization, is if we separate out the common functionality from LitElement into a LitElementBase class and then provide a LitElementLight class which renders to light dom. This will make it easier to add other features that make sense for rendering to light dom, and also reduce the required knowledge of internals for developers.

**Comment by Westbrook** [comment]
@LarsDenBakker could you clarify this paragraph a little further?
> This works fine on native shadow dom, but shady dom will hoist the styles to the head and scope the styles so that element a cannot select elements into element b. We can't turn off scoping, as it will make the styles apply everywhere, but perhaps there is some solution to this? An alternative could be to define scopes manually and pass them down as properties to sub components.

When you say "We can't turn off scoping, as it will make the styles apply everywhere" I can't understand how that's different from `element-a` having shadow dom so it's styles don't leak, but `element-b` and `element-c` using light dom so the styles from `element-a` apply to them.

It would seem that this approach would be available at current without any API changes, and wanted to make sure I understood you correctly. I've been doing something similar by extending the `_createRoot` technique as follows when not wanting to use scoped styles:
```
  /**
   * Set root to `this` so that styles are not contained.
   *
   * @return {object}
   */
  _createRoot() {
    return this;
  }
  /**
   * Prevent the hoisting and scoping of styles.
   */
  _applyRender(result, node) {
    render(result, node);
  }
```
My use case at current is to apply style to a page (when not building my app from a single shared parent node, and seems like it would do the work you're looking for if applied to `element-b` and `element-c` in your example.

Thanks in advance for sharing your thoughts, this is an important sticking point to work though in advance of bringing users in from other style application techniques!

**Comment by LarsDenBakker** [comment]
@Westbrook 

Given:
```
<app-element-a>
  <style> element-d { border: 1px solid black; } </style>

  <app-element-b>
    <element-d>
      #shadowroot
    </element-d>
  </app-element-b>

  <app-element-c>
    <element-d>
      #shadowroot
    </element-d>
  </app-element-c>

</app-element-a>
```

Compiles to shady dom like so (pseudocode):

```
<head>
  <style scope="app-element-a">
    element-d.app-element-a {
      border: 1px solid black;
    }
  </style>
</head>

<app-element-a>
  <style> element-d { border: 1px solid black; } </style>

  <app-element-b class="style-scope app-element-a">
    <element-d class="style-scope app-element-b">
      #shadowroot
    </element-d>
  </app-element-b>

  <app-element-c class="style-scope app-element-a">
    <element-d class="style-scope app-element-b">
      #shadowroot
    </element-d>
  </app-element-c>

</app-element-a>
```

So where in native shadow dom, a selector like `element-d` would match the elements inside element-b and element-c, in shady dom the selectors are scoped to only the dom of element-a. 

We could do what you're saying and use regular render instead of shady render, but it has two downsides. One is that it removes other parts from the shady dom polyfill such as css mixins and css variables. The other is that scoping is turned off. So instead of matching only the instances of element-d up until the first shadow root inside element-a, it will match all instances of element-d on the page. 

I'm also interested in elements being able to style upwards like you're describing. We have a very large application with architecturally separated pages developed by different teams. I'd like for the active page to be able to theme the larger application. With native shadow dom it's possible.

**Comment by LarsDenBakker** [comment]
After looking into this further, it seems I'm not entirely correct. I am running into some bugs when the top level element has no shadow root, but when it does it works more like expected. 

Styles are correctly scoped from the top shadow root down to the bottom shadow root across components. However, styles within custom elements without shadow roots are not hoisted.

I made a jsbin to illustrate what I mean. This construction works in shadow dom:
http://jsbin.com/pufosopeki/1/edit?html,output
But not in shady dom:
http://jsbin.com/mazimigara/1/edit?html,output

I don't understand enough about how shady dom/css works, but perhaps https://github.com/Polymer/lit-html/pull/337 will change this?

**Comment by sorvell** [comment]
Sorry for the delay on this. The new way to customize the rendering element is to implement `createRenderRoot()` (renamed from `_createRoot`).

We'd like to encourage use of Shadow DOM in LitElement and this is why it's the default. Since it's straightforward to customize this, we're inclined to leave it as is for now. It is completely reasonable to create a subclass that customizes this behavior as you see fit.

**Comment by asbachb** [comment]
I wonder if there's a workaround for having `slot` functionality when disabling Shadow DOM.

**Comment by Christian24** [comment]
@atla5 `<slot>` is only available when using shadow dom by shadow dom specification.

**Comment by jolleekin** [comment]
@asbachb @atla5 Here's one workaround to the missing `slot` functionality.
``` ts
@customElement('my-element' as any)
export class MyElement extends LitElement {
  /** The header content. Usually a [TemplateResult] but could be anything. */
  header?: any;

  /** The footer content. Usually a [TemplateResult] but could be anything. */
  footer?: any;

  /**
   * The body template function.
   *
   * The return value is usually a [TemplateResult] but could be anything.
   */
  bodyTemplate?: () => any;

  protected createRenderRoot() {
    return this;
  }

  protected render(): TemplateResult {
    return html`
      <style>
        /*
        Can't use :host here since we're rendering into the light DOM.

        NOTE:
        Duplicated styles will happen if there are more than one
        my-element in the same scope.
        */
        my-element {
          display: block;
        }
      </style>
      ${this.header}
      ${this.bodyTemplate ? this.bodyTemplate() : null}
      ${this.footer}
    `;
  }
}
```

### Usage
``` html
<my-element
  .header=${html`<h2>Header</h2>`}
  .bodyTemplate=${() => html`<p>Body</p>`}
>
</my-element>
```

**Comment by Rybadour** [comment]
@jolleekin Does this mean there is no way have child element like my below code without shadow DOM?

```
<custom-list>
   <li>foo</li>
   ...
</custom-list>
```

**Comment by jsilvermist** [comment]
@rybadour You would have to query the elements and manually append them at load time if I'm not mistaken.

**Comment by pgoforth** [comment]
The issue is compounded by the fact that returning any `TemplateResult` in your render method will automatically remove the children that used to be in your component and replace them with what was rendered in the template. What we need is a way to easily re-add the children into the generated template in much the same way that React allows you to add `children`.

**Comment by RamyXIII** [comment]
How can I render a nested element to the main DOM tree? Can I return the top element using `createRenderRoot()`?
In my stackblitz [example](https://stackblitz.com/edit/ruwkze?file=my-element.js), I have to implement `createRenderRoot() { return this; }` in all parent elements for stripe.js, which doesn't support shadow DOM, to work.

**Comment by RameezAijaz** [comment]
If you just want to render all the children inside host's dom then using connectedCallback() lifecycle event even with empty body will make child component render inside the host without shadowDom 

```
@customElement('test-element')
export class TestElement extends LitElement {

    connectedCallback(){
    }
    createRenderRoot() {
        return this;
    }

    render() {
        return html`
        `;
    }
}
```
Then following code 
```
<test-element>
     <p>Hello World</p>
</test-element>

```
will render 

```
<test-element>
     <p>Hello World</p>
</test-element>

```

**Comment by aaronanderson** [comment]
This worked for me:
```
@customElement('test-element')
export class TestElement extends LitElement {

  elementChildren: Array<Element> = [];

  createRenderRoot() {
    return this;
  }

  connectedCallback() {
    super.connectedCallback();
    this.elementChildren = Array.from(this.children);
  }

  render() {
    return html`<div>${this.elementChildren}</div>`;
  }  

}

```

**Comment by svdoever** [comment]
@aaronanderson seems to work for me as well!

I created a file `LitElementLight.ts`:
```typescript
import { LitElement } from 'lit-element';

class LitElementLight extends LitElement {
    elementChildren: Array<ChildNode> = [];
    slotContents: any;

    connectedCallback() {
        this.elementChildren = Array.from(this.childNodes);
        super.connectedCallback();
    }

    slotElements(): ChildNode[] {
        return this.elementChildren;
    }

    createRenderRoot() {
        return this;
    }
}
    
export {
    LitElementLight
};
```

and now can create "light" elements as follows:

`test-light.ts`:
```typescript
import { html, customElement } from 'lit-element';
import { LitElementLight } from './LitElementLight';

@customElement('test-light')
class TestLight extends LitElementLight {
    render() {
        return html`
            <div>I'm styled by the light!</div>
            <div>${this.slotElements()}</div> 
            <div>Styling is global</div> 
    `;
    }
}

declare global {
    interface HTMLElementTagNameMap {
        'test-light': TestLight;
    }
}
```

**Comment by fouad-j** [comment]
Hello, 

Thanks @svdoever  and @aaronanderson for your proposal.

I improved the code to allow displaying Slot in different parts of custom element.

```ts
import {LitElement} from 'lit-element';

class LitElementLight extends LitElement {
    slotMap: object;

    connectedCallback() {
        this.slotMap = Array
            .from(this.renderRoot.querySelectorAll('[slot]'))
            .reduce((map, obj) => ({
                ...map,
                [obj.getAttribute('slot')]: obj
            }), {});

        super.connectedCallback();
    }

    protected getSlot(slotName: string): ChildNode {
        return this.slotMap && this.slotMap[slotName];
    }

    createRenderRoot() {
        return this;
    }
}

export {LitElementLight};
```

```ts
@customElement('test-light')
class TestLight extends LitElementLight {
    render() {
        return html`
            <div>LitElement content bla...</div>
            <div>${this.getSlot('actions')}</div>
            <div>Styling is global</div>
    `;
    }
}

declare global {
    interface HTMLElementTagNameMap {
        'test-light': TestLight;
    }
}
```

```html
<test-light>
  <div slot="actions">
    <button type="button" class="btn btn-primary" (click)="toggleImage()">Angular Action</button>
    <button type="button" class="btn btn-secondary" v-on:click="counter += 1">VueJS Action</button>
  </div>
</test-light>
```

I created a public [gist](https://gist.github.com/fouad-j/0e19a0d9b94f50b53c87dbceca51b26c)
Please let me know if you have any suggestion

**Comment by justinfagnani** [comment]
@svdoever the problem with that approach is that it breaks composition. Since you record the light DOM children on at connected, you can get into a number of situations where the children are overwritten later, or re-recorded later.

The simplest example is disconnecting and reconnecting:

```js
const el = new TestLight();
document.body.append(el);
console.log(el.innerHTML); // shows 3 divs
const container = document.createElement('div');
document.body.append(container);
container.append(el); // should throw as you're trying to add the second div as a child to itself
```

Another example is using this with a template system:

```js
const go = (children) => render(
    html`<test-light>${children}</test-light>`,
    document.body);
go(html`<p>render 1</p>`); // renders 3 divs, with <p> as child of second
go(html`<p>render 2</p>`); // renders one <p> that overwrites the divs
```

There are of other cases where this breaks too. This is a big reason I'm not comfortable with most of the proposed solutions in the space. Shadow DOM is a composition primitive that's valuable precisely because composition is hard to impossible to get right without it.

**Comment by svdoever** [comment]
This is the reason why I had to move over to using StencilJS, where slots are supported without shadow dom.

**Comment by andyjessop** [comment]
This is the biggest issue for us adopting web components. We would have to use the light DOM because we use CSSModules to style our components, but if we can't have composition then web components are frankly unusable in a modern web app without huge friction.
