### ISSUE TITLE
[bug] Cannot find name 'ClassDescriptor' (v0.7.0)

### ISSUE THREAD

**Issue by lacolaco** [Polymer/lit-element#428]
### Description

When I use decorators of LitElement, TypeScript compiler emits errors.

```
ERROR in [at-loader] ./node_modules/@polymer/lit-element/lib/decorators.d.ts:37:105
    TS2304: Cannot find name 'ClassDescriptor'.

ERROR in [at-loader] ./node_modules/@polymer/lit-element/lib/decorators.d.ts:43:118
    TS2304: Cannot find name 'ClassElement'.

ERROR in [at-loader] ./node_modules/@polymer/lit-element/lib/decorators.d.ts:48:80
    TS2304: Cannot find name 'ClassElement'.

ERROR in [at-loader] ./node_modules/@polymer/lit-element/lib/decorators.d.ts:53:83
    TS2304: Cannot find name 'ClassElement'.
```

It looks a bug. `env.d.ts` is only accessible from LitElement source code.
https://github.com/Polymer/lit-element/blob/master/src/env.d.ts

#### Live Demo

https://stackblitz.com/edit/lit-element-example?file=index.js

https://glitch.com/edit/#!/hello-lit-element?path=index.html:1:0

#### Steps to Reproduce

1. Install v0.7.0
2. Use `@property()` in TypeScript 
3. Execute `tsc`

#### Expected Results

No errors.

#### Actual Results
Error is thrown

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

### Versions

- lit-element: v0.7.0
- webcomponents: vX.X.X

**Comment by motss** [comment]
FWIW, there is also another error.

```js
error TS2304: Cannod find name 'Constructor'.
```
