### ISSUE TITLE
lit-element breaks with polymerElement / css mixin imported via js

### ISSUE THREAD

**Issue by AndreasGalster** [Polymer/lit-element#43]
I have created a repo with a small reproduction here. I'm not sure if this error is generally happening or I'm doing something wrong here (don't think so though). 

Repro instructions and sample can be found here:
https://github.com/AndreasGalster/lit-css-prop-error

My app was working just fine until I've upgraded from lit-element 0.2 to 0.4, or 0.5

## Expected Result:
App shell won't throw an error

## Actual Result:
Lit-element breaks with a prop error:

```
Uncaught TypeError: Cannot read property '1' of null
    at new Template (lit-html.js:265)
    at eval (shady-render.js:34)
    at render (lit-html.js:129)
    at render (shady-render.js:40)
    at HTMLElement._applyRender (lit-element.js:190)
    at HTMLElement._propertiesChanged (lit-element.js:140)
    at HTMLElement._flushProperties (properties-changed.js:339)
    at HTMLElement._flushProperties (lit-element.js:150)
    at HTMLElement.ready (properties-changed.js:183)
    at HTMLElement.ready (lit-element.js:78)
```

**Comment by AndreasGalster** [comment]
Any thoughts on whether this can be fixed? @justinfagnani suggested to set window.shadyCSS to undefined somewhere top-level since shadyCSS is causing the issue. The proposed workaround is not working though. It works when placing it in shouldRender for every component using a PolymerElement, however eventually you will stumble upon this one:

```
TypeError: Cannot read property 'flushCustomStyles' of undefined
    at CustomStyleInterface.Object (custom-style-interface.js:53)
    at eval (document-wait.js:43)
```

Imo this is a major blocker for migrating to lit, I'm essentially giving up on migrating to lit and building more lit-components, since I simply cannot consume then within my app.

**Comment by AndreasGalster** [comment]
For anyone running into the same issues, the "best" thing you can do for now is remove the shadyCSS check in shady-render in lit.html, see here: https://github.com/Polymer/lit-html/blob/master/src/lib/shady-render.ts#L37

**Comment by sorvell** [comment]
Closing in favor of https://github.com/Polymer/lit-html/issues/326 which is in progress and should address this issue.
