### ISSUE TITLE
Do you need to install lit-html in order to use directives

### ISSUE THREAD

**Issue by Christian24** [Polymer/lit-element#430]
Hi,

This is more a question than an actual issue. Are directives supposed to be part of only lit-html and I need to install lit-html if I want to use them, or is the export just missing in the Typescript declaration file? I did not find any mentioning of that in the LitElement docs.

**Comment by web-padawan** [comment]
Yes, directives should be imported from `lit-html` and it is better to ask questions in the Slack 🙂

**Comment by Christian24** [comment]
Okay. I will close this then. However, I also wanted to use the oppurtunity to voice the desire to have this added to the docs ;)
