### ISSUE TITLE
render() not rendering... a single line of render function... not error..

### ISSUE THREAD

**Issue by viapek** [Polymer/lit-element#444]
### Description
html `` Render of firestore documents not working 

-- super nervous about posting this here as I'm a novice and even typing the line above I feel I should be looking at firestore for a solution but... Everything else is working just dandy. I have tried all sorts of variations with this. I have tried pushing the documents into a vanilla array an rendering that, I have tried putting it through a state management system and then rendering on a change subscription, I have tried rendering direct as per the below stackblitz... all to no avail.

The console logs are working just fine but the data is not rendering to the element.

Really sorry if this isn't a bug :/

#### Live Demo
https://stackblitz.com/edit/lit-element-example-kobutv

#### Steps to Reproduce
put in config your firebase config.
put in the name of a collection with documents
run it

#### Expected Results
document data rendered to element

#### Actual Results
watch the console log output successfully and nothing come to element
No error is thrown...

### Browsers Affected

- [x] Chrome
- [ ] Safari 11
- [ ] Safari 10

### Versions
"@polymer/lit-element": "^0.6.5",
"firebase": "^5.7.3",
"lit-html": "^1.0.0-rc.1", | and 2.0.0-rc.2 on stackblitz

**Comment by CaptainCodeman** [comment]
render() needs to return the template immediately, you can't put your async calls to firestore in there as the method will have exited and returns before the template comes back plus the return of the template inside the query callback and forEach wouldn't return it to the caller anyway.

Put your DB code somewhere else and have it set a property that will trigger the render instead.

**Comment by T-Knott-Mesh** [comment]
Hello ! 

It seems that render is never being called as there is never a property set to trigger a render. I would add a function called initializeFirestore() which is called on a native connectedCallback or LitElement Specific Lifecycle, and set a property such as mood or something else inside of your snapshot. 

Be sure to add your property to the properties getter. 

Then, when a snapshot comes in, the snapshot will set the property and the property will trigger a render. 

You could also call requestUpdate() manually.

https://lit-element.polymer-project.org/guide/lifecycle


https://lit-element.polymer-project.org/guide/properties


Good luck !

**Comment by viapek** [comment]
Thanks to both of you for being so polite... I'll RTFMA :)
