### ISSUE TITLE
[docs] Clarify when `hasChanged` is called

### ISSUE THREAD

**Issue by bebuch** [Polymer/lit-element#449]
### Description
Starting with lit-element version 0.7.0 `hasChanged` is no longer called repeatedly if `true` was returned before.

If you have a property with a default value and a user defined value, I expect two calls of `hasChanged`. The first one changes the value from `undefined` to the default value, the second call changes it from default value to user defined value.

This was the behavior until lit-element version 0.6.5. Starting with 0.7.0 it depends on the return value of `hasChanged`. If the first call returns `true`, the second call is not executed. Nevertheless the property becomes the user defined value.

#### Live Demo

Have a look at the log output to understand the examples:

Wrong behavior with lit-element version 0.7.0 and `hasChanged` returning `true`:
https://stackblitz.com/edit/lit-element-example-mnly7s

Correct behavior with lit-element version 0.7.0 and `hasChanged` returning `false`:
https://stackblitz.com/edit/lit-element-example-wrnjnp

Correct behavior with lit-element version 0.6.5 and `hasChanged` returning `true` or `false`:
https://stackblitz.com/edit/lit-element-example-yhf5al

#### Steps to Reproduce

1. Create a lit-element `my-element`
2. Create a property with a `hasChanged` function
3. Return `true` from the `hasChanged` function
4. Set a default value for the property in the constructor
5. Use `my-element` with a specified value for the property

#### Expected Results
Two calls of `hasChanged`:
1. With  `undefined` and the default value
2. With the default value and the user defined value

#### Actual Results
One call of `hasChanged`:
1. With  `undefined` and the default value

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [ ] ? Edge
- [ ] ? Safari 11
- [ ] ? Safari 10
- [ ] ? IE 11

### Versions
- lit-element: v0.7.0
- webcomponents: v2.2.3

**Comment by sorvell** [comment]
This change is by design and was done as a performance optimization. The value returned from `hasChanged` *only* indicates if a change should trigger an update. Once an update for a property has been triggered, the update will occur, and therefore, calling `hasChanged` after it's returned true would just be extra work.

If you're trying to use `hasChanged` for some other purpose, instead we recommend implementing your own getter/setter for the property.

**Comment by bebuch** [comment]
Thanks for clarifying!
