### ISSUE TITLE
Consider allowing string values in CSSResults?

### ISSUE THREAD

**Issue by 43081j** [Polymer/lit-element#451]
Currently `css` only accepts `CSSResult` values (other `css` calls) which means we can no longer do something like this:

```ts
static get styles() {
  return [css`
    :host {
      background-image: url('${rootPath}images/foo.png');
    }
  `];
}
```

This is a common pattern I have throughout my project to handle usages of `import.meta` so assets can have absolute paths.

If you can suggest a better way to handle passing in a path, fair enough, but otherwise it would be handy to be able to interpolate string values here.

**Comment by justinfagnani** [comment]
This would be a potential security vulnerability.

**Comment by 43081j** [comment]
What do you suggest for this use case? It seems like it should be a common one.. wanting to use the meta url in paths.

**Comment by justinfagnani** [comment]
cc @rictic @mikesamuel

**Comment by sorvell** [comment]
This should work as long as you use `css` to define `rootPath`. This ensures it's a literal from script and addresses the security concern.

```
const rootPath = css`...`;
```

**Comment by LarsDenBakker** [comment]
Since rootPath will likely be generated from a variable, its not possible to generate it through a `css` tag as css`${import.meta.url}` also throws.

**Comment by 43081j** [comment]
^ exactly this @sorvell 

its coming from `import.meta`, we don't define it. as people move more towards using `import.meta` i imagine this'll become a more common use case too.

**Comment by web-padawan** [comment]
Note: here is how I'm using the `CSSResult` at the moment to get data from `<dom-module>`:

```js
import { DomModule } from '@polymer/polymer/lib/elements/dom-module.js';
import { stylesFromTemplate } from '@polymer/polymer/lib/utils/style-gather.js';
import { CSSResult } from 'lit-element';

export const getStyleModule = (id, cb) => {
  const template = DomModule.import(id, 'template');
  let cssText =
    template &&
    stylesFromTemplate(template)
      .map(style => style.textContent)
      .join(' ');
  if (cb) {
    cssText = cb(cssText);
  }
  return new CSSResult(cssText);
};
```

The result is added to the styles like this:

```js
static get styles() {
  return [...super.styles, getStyleModule('lumo-button')];
}
```

See https://github.com/web-padawan/lit-components/tree/master/packages/polymer-style-module

**Comment by rictic** [comment]
Hm. When running in secure mode, we could add a check that it's a TrustedResourceUrl. I'm not sure how you'd build a TrustedResourceUrl out of `import.meta.url` though. You might need a new path with compiler checks to validate it.

**Comment by jsilvermist** [comment]
Why is this an issue with `css` but we can interpolate strings in `html`?

**Comment by LarsDenBakker** [comment]
Interpolated strings in `html` are set as `textContent`, not parsed as `HTML`. So there is no security risk there. With `css` there is, but it is unfortunately a big downside for developer experience :(

**Comment by bashmish** [comment]
In LitElement you define your styles via a static getter. This does not allow you to use element's instance properties which contain dynamic data which often comes from the untrusted user input. You compose you final styles once on a class level. I don't see where you will get untrusted user input there, you will likely always compose your static styles from other ES modules and just static values originating from your source code.

So I think the problem is exaggerated a lot. It certainly exists theoretically, but how often? I think the solution is unbalanced: it fixes the theoretical issue while breaking a very frequent use case.

**Comment by tlouisse** [comment]
I also would like to use css variables that are reusable in many context and not coupled to CSSResult per se.

For instance, I want to be able to reuse my (grid) breakpoints as a single source of truth, and reuse them in both css and js:
https://stackblitz.com/edit/lit-element-css-usecase?file=css-test.js
(using these variables: https://stackblitz.com/edit/lit-element-css-usecase?file=variables.js)

Or, more generically speaking: I might want to be able to combine my globally defined variables in other contexts  (maybe combine it with an other technology stack) that do not rely on CSSResult? I would like to be able to do that without wrapping all my vars in css``.

Of course, I would also be able to do:
```js
const myBreakpoint = 400;
const myStyles = css`
  @media (max-width: ${css([myBreakpoint])}px) {
     ...
  }
`
```

As far as the sanitization is concerned, how does this exactly happen?
It might happen here, but currently no browser supports this yet.
```js
     if (supportsAdoptingStyleSheets) {
        this._styleSheet = new CSSStyleSheet();
        this._styleSheet.replaceSync(this.cssText);
      }
```
https://github.com/Polymer/lit-element/blob/master/src/lib/css-tag.ts#L30

Or does it happen on `static get styles` level?
So then this would be the part where the first potential security risk would occur?
```js
    if (this._needsShimAdoptedStyleSheets) {
      this._needsShimAdoptedStyleSheets = false;
      (this.constructor as typeof LitElement)._uniqueStyles.forEach((s) => {
        const style = document.createElement('style');
        style.textContent = s.cssText;
        this.renderRoot!.appendChild(style);
      });
    }
```
https://github.com/Polymer/lit-element/blob/master/src/lit-element.ts#L206
No sanitization here either, or do I miss something?

If you look at the first code example above, you could also do:
```js
const myBreakpoint = somethingPotentiallyMaliciousProvidedByUserInput;
const myStyles = css`
  @media (max-width: ${css([myBreakpoint])}px) {
     ...
  }
`
```

Looking at it from this perspective, it would not be the css-tagged template function that prevents security issues, but the coding habits of the developer...

**Comment by 43081j** [comment]
> Ok, so you already trust the origin `import.meta` to load script from, so why not trust it for images and fonts too?

I do. I don't remember saying I don't, so not sure I quite follow you here...

> Do JS bundlers rewrite `import.meta.url` to a string literal? For example if I do `npm install https://github.com/...`?

It gets rewritten to a path relative to the output bundle afaik, with static assets output alongside it (as well as other chunks).

**Comment by mikesamuel** [comment]
@43081j 

> I do. I don't remember saying I don't, so not sure I quite follow you here...

Sorry for the confusion.  I was asking to see if we're reasoning along the same lines.

> It gets rewritten to a path relative to the output bundle afaik, with static assets output alongside it (as well as other chunks).

Thanks for explaining.

**Comment by justinfagnani** [comment]
@mikesamuel @rictic Would it be feasible to allow strings if we fed the bindings through the sanitizer with a fake`<style>` as the parent element?

**Comment by rictic** [comment]
Seems reasonable to me. I'm not sure what values are allowed as style text. Is there a TrustedStyleContent type?

**Comment by mikesamuel** [comment]
@justinfagnani Seems reasonable.  Which sanitizer are we talking about though?
