### ISSUE TITLE
Can't use static property for styles in TypeScript

### ISSUE THREAD

**Issue by justinfagnani** [Polymer/lit-element#452]
TypeScript compiles properties to assignment (for now). The means that a subclass of a class that has `static get styles() {...}` can't use TypeScript static properties to set styles. The ergonomics of static properties are nice enough that we should allow for them with our base classes:

```ts
class MyElement extends LitElement {
  static styles = css`
    :host {
      display: block;
    }
  `;
```

I suggest we remove the styles getter from LitElement, since it only returns an empty array. If we _really_ needed to keep it, we could just do:

```ts
LitElement.styles = [];
```

after the class definition.

**Comment by sorvell** [comment]
When investigating this we also detected an issue with `styles` being incorrect when elements are extended.
