### ISSUE TITLE
Need for context properties

### ISSUE THREAD

**Issue by askbeka** [Polymer/lit-element#46]
I like the turn project took, and I suppose Redux is going to be mainstream in  this area. And there is one thing that might improve the way LitElement works with Redux.

This idea is not unique, React also has [it](https://reactjs.org/docs/context.html). 

Now, in order pass a property down the hierarchy, each component needs to define it and pass over to its children

Better approach might be to have context properties that will be available for all affected scope/branch it will be applied.

I am not sure about implementation, but maybe `scoped custom element registry` and `WeakMap` might come in handy?

And it will be possible to have this sort of code

my-component-container.js
```javascript
   import MyComponent from './my-component.js';

   const mapStateToProps = state => ({ someState: state.someState });
   const mapDispatchToProps = dispatch =>
            ({ doSomething: (value) => dispatch({ type: 'DO_SOMETHING', payload: value }) });

   export default connect(mapStateToProps, mapDispatchToProps)(MyComponent);
```

my-component.js
```javascript
   ...
   export default class MyComponent extends LitElement {
        static get properties() {
            return {
               someState: String,
               doSomething: Function,
            };
        }
        _render({ someState, doSomething }) {
           return html`<input value=${someState} on-change=${doSomething}/>`;
       }
   };
```

connect.js
```javascript
   export const connect = (mapStateToProps, mapDispatchToProps) => baseElement => {
       return class extends baseElement {
           connectedCallback() {
                const { store } = this.context;
                if (!store) {
                   throw new Error('no store passed over');
                }
                this.__storeUnsubscribe = store.subscribe(() => this._stateChanged(store.getState()));
                ....
           }

           disconnectedCallback() {
              if (this.__storeUnsubscribe) {
                  this.__storeUnsubscribe();
              }
               ...
           }
       }
   }
```
index.html
```html
   <store-provider>
      <my-component></my-component>
   </store-provider>
   <script>
      import { createContext } from  '@polymer/lit-element';
      createContext('store-provider', { store: createStore() }));
   </script>
```

**Comment by askbeka** [comment]
@Lodin . Thank you for your response. But, one of the problems this issue addresses is testability and SSR. Problem with having static connect or store exported from the module makes it singleton, and harder to mock the store while testing and when doing SSR, especially when your app is a part of a larger app. This is issue also mentioned [here](https://redux.js.org/faq/store-setup).

I agree that having component in dom that does not have any visual footprint but just passes context can be confusing. probably this should not be a part of LitElement, more of a pwa-helpers. I´ll do a PR with and idea I have and link it here soon.

**Comment by Westbrook** [comment]
This talk was posted to the Slack channel, and it might be of interest to this conversation as it came up in the context of Context Properties there: https://youtu.be/6o5zaKHedTE

**Comment by askbeka** [comment]
@Westbrook , Thanks, that is an amazing approach, Never occurred to me.

**Comment by askbeka** [comment]
I have created a small lib called it [wc-context](https://github.com/askbeka/wc-context), no packaging yet, its coming soon. In mean time want to get some feedback. There is a Redux demo in demo folder.

**Comment by Lodin** [comment]
@askbeka I still think the function is better for it. I've got an idea to make them static and mimic new React.Context API completely. 

```javascript
const createContext = (default) => {
  let ctx = default;

  const provide = (newCtx) => {
    ctx = newCtx;
  }

  const consume = () => {
    if (!ctx) {
      throw new Error('Context is not defined');
    }

    // do whatever you want from consumer
  }

  return {consume, provide};
}

export {
  consume,
  provide,
} = createContext();
```
What do you think about this approach?

**Comment by askbeka** [comment]
@Lodin , This approach is not much different from just using store in component, I am not saying that it is bad, it may be all you need if you have one team working on whole app and it is not big. But in other cases this apprach does not scale very well.

Imagine that you have an app that is being developed by multiple teams some of them can be offshore and they have their own source control. You can store context as a global object in page and make them use that, but then you have a problem if you need multiple stores in your app, and components should be used with different stores.

Good thing that we have DOM and custom element and events to solve that. I am experimenting with it, for now I am not really happy with API, but I will try to release alpha version soon to get more feedback.
I don't have much time unfortunately:(

**Comment by Lodin** [comment]
@askbeka Oh I see it now. Thanks, talking with you was really useful. Waiting for your context lib!

**Comment by sorvell** [comment]
This outside the scope of LitElement since it is focused on creating custom elements that work with normal DOM API's. We might reconsider adding an API like this in the future if there's enough interest and a concrete proposal.

We recommend looking at [PWA Starter Kit](https://github.com/Polymer/pwa-starter-kit) for docs, examples, and best practices around using LitElement when making PWAs and other web apps. It uses Redux for state management.

**Comment by blikblum** [comment]
I created [wc-context](https://www.npmjs.com/package/wc-context) library that supports lit-element and skatejs as well vanilla web components

The API is still in flux

**Comment by rikakomoe** [comment]
Thanks for @Westbrook mentioning Justin Fagnani's presentation, @askbeka's demo code and @blikblum's library.

**Comment by askbeka** [comment]
@rikakomoe you are welcome. Thanks for reminding. Almost forgot about this issue.
 I couldn't find time to update on my final solution.

But, since then I have contributed context implementation for [haunted](  https://github.com/matthewp/haunted/blob/master/readme.md#usecontext).
Which implements hooks pattern with webcomponents.
  
There is also recent ongoing  attempt to make react-redux work you can track [here](https://github.com/matthewp/haunted/issues/126)

**Comment by rikakomoe** [comment]
@askbeka The [official guide](https://pwa-starter-kit.polymer-project.org/redux-and-state-management) requires a constant existing store before defining the element. The issue is, besides it is not tidy enough though, I am not building a website but a component, if the user creates more than one instance, all of them need their independent state. So I was looking for a declarative method to inject this store into children components, for convenience, without passing down the store over and over. React provides this dependency injection feature as its context while lit-element doesn't yet.

I'm interest about your final solution, if there were any updates/improvements against the solution I've seen so far.

**Comment by Lodin** [comment]
@rikakomoe, you can also try my context approach that implemented in the [@corpuscule/context](https://github.com/corpusculejs/corpuscule/tree/master/packages/context) library. It allows avoiding unnecessary HTML elements whose only purpose is to serve as a provider. With this library, you can make your root component a theme provider, a redux provider, a router provider, etc. at the same time without creating expensive HTML elements and increase nesting. It works with any implementation of web components.

The library is based on decorators, so you will need Babel to transpile your components while the decorator proposal is in development. Corpuscule project [provides](https://github.com/corpusculejs/babel-preset) solution for it as well.

BTW, the redux bindings (based on the context library) are also there: [@corpuscule/redux](https://github.com/corpusculejs/corpuscule/tree/master/packages/redux). It also works with any web component library as well as vanilla web components.

**Comment by rikakomoe** [comment]
@Lodin Thanks!

**Comment by askbeka** [comment]
@Lodin More news on this topic,
With new CSS display type [`display: contents`](https://www.w3.org/TR/css-display-3/#box-generation).
You should not be afraid of extra DOM, since it does not affect layout.
It is slready supported by [83%](https://caniuse.com/#feat=css-display-contents) of browsers
