### ISSUE TITLE
[docs] Implement site search 

### ISSUE THREAD

**Issue by katejeffreys** [Polymer/lit-element#461]
See https://github.com/Polymer/lit-html/issues/752. 

From that issue's description:

"Short term proposal: redirect to google.com/ with site:lit-html.polymer-project.org like we do on polymer-library.polymer-project.org
Longer term proposal: investigate docsearch, new integration with custom search, or something else."

**Comment by moderndeveloperllc** [comment]
@katejeffreys Looks like #464 fixed this.

**Comment by katejeffreys** [comment]
@moderndeveloperllc thanks!
