### ISSUE TITLE
CSS mixins not supported by new style system

### ISSUE THREAD

**Issue by irqbank** [Polymer/lit-element#466]
#### Live Demo
https://jsfiddle.net/cyfq8bas/

#### Steps to Reproduce
See jsfiddle

#### Expected Results
Button color is red

#### Actual Results
Button color is not red

### Browsers Affected
- [X] Chrome

### Versions
- lit-element: v2.0.0-rc.3
- webcomponents: N/A

**Comment by azakus** [comment]
This is working as intended. The `@apply` css mixin functionality is in critical "bugfix only" mode with the [removal of the native browser feature](https://www.chromestatus.com/feature/5753701012602880).

The new style API with static get styles is intended to be used with the [Constructible Stylesheets](https://wicg.github.io/construct-stylesheets/) proposal for greater performance styling Web Components, which would require extensive work on `@apply`.

Instead, we intend to investigate providing API to use the new [CSS Shadow Part](https://www.w3.org/TR/css-shadow-parts-1/) API with the `::part` syntax, which has [much more positive support from browser vendors](https://www.chromestatus.com/feature/5763933658939392).

In the meantime, you absolutely still use` @apply` with `<style>` elements in the `render` function.
