### ISSUE TITLE
`styles` are not read from the constructor chain

### ISSUE THREAD

**Issue by tlouisse** [Polymer/lit-element#467]
#### Live Demo
https://stackblitz.com/edit/lit-element-request-update-bug-lspgdq?file=test.js

#### Steps to Reproduce
1. Create function `MyStyleMixin` with `static get styles` defined. For instance:
```js
const MyStyleMixin = (superclass => class MyStyleMixin extends superclass {
  static get styles() { return [
    css`
      div {
        border: 2px solid blue;
      }`
    ];
  }
});
```
2. Create class `MyStyledElement` that applies `MyStyleMixin` and extends `LitElement`. 
Define a `render` function that are styled by `MyStyleMixin`. Define it as custom element `my-styled-element`.
For instance :
```js
class MyStyledElement extends MyStyleMixin(LitElement) {
  render() {
    return html`<div>Styles should be applied here</div>`;
  }  
}
customElements.define('my-styled-element', MyStyledElement);
```
3. Instantiate `<my-styled-element></my-styled-element>` on a page.

#### Expected Results
`<my-styled-element>` has a div with a blue 2px border.

#### Actual Results
`<my-styled-element>` has no styling at all.

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari 11
- [x] Safari 10
- [x] IE 11

### Versions

- lit-element: v2.0.0-rc.3
- webcomponents: v2.2.3

**Comment by web-padawan** [comment]
I have also noticed that while working on web-padawan/lit-components#30. Had to tweak the code when updating to 2.0.0-rc.3 and make sure the class extension in the tests does the following:

```js
static get styles() {
  return super.styles;
}
```
For me it was an acceptable tradeoff, but in general it looks like a regression.

**Comment by tlouisse** [comment]
@web-padawan : Yeah, I also already did this in my code as a workaround :)
But we have quite a few mixins that share styles and it feels a bit hacky to me if we have to trigger the LitElement like this everytime.

**Comment by azakus** [comment]
The intent is to inherit styles if they have not been set on the subclass:
https://github.com/Polymer/lit-element/blob/master/src/lit-element.ts#L75

**Comment by tlouisse** [comment]
Thanks for fixing the issue @azakus, pretty smart to check every level via `finalize` 👍 Was there a particular reason to rename it from `_finalize`to `finalize`if I may ask?
