### ISSUE TITLE
Can only style elements in default slot (not named slots)

### ISSUE THREAD

**Issue by jasonhulbert** [Polymer/lit-element#477]
### Description
Elements within slotted content cannot be styled in a named slot but CAN be styled in the unnamed/default slot.

#### Live Demo
https://stackblitz.com/edit/lit-element-example-vp6lqv

#### Steps to Reproduce
Example:

```
import { LitElement, html } from 'lit-element';

class MyElement extends LitElement {
  render() {
    return html`
      <style>
        ::slotted(a) {
          color: green;
        }
      </style>
      <p class="body"><slot></slot></p>
      <p class="cta"><slot name="cta"></slot></p>
    `;
  }
}

customElements.define('my-element', MyElement);
```

```
<my-element>
  <!-- Default slot -->
  This is some anonymous slot content <a href="#">with a link element</a>
  <!-- Named slot -->
  <p slot="cta">This is some named slot content <a href="#">with a link element</a></p>
</my-element>
```

1. Create an element with both a default slot and a named slot.
2. Add a style of `::slotted(a) { color: green }` either in the render method style tag OR in the static method `styles` value.
3. Add the element to the page.
4. Provide content containing a link element to both slots.

#### Expected Results

Both the link in the default slot and the link in the named slot should be green.

#### Actual Results

The link in the default slot is green but the link in the named slot is unstyled.

### Browsers Affected

- [ x ] Chrome
- [ x ] Firefox
- [ x ] Edge
- [ x ] Safari 11
- [ x ] Safari 10
- [ x ] IE 11

### Versions

- lit-element: v2.0.0-rc.2
- webcomponents: v2.2.3

**Comment by sorvell** [comment]
This is how `::slotted()` [styling works](https://developer.mozilla.org/en-US/docs/Web/CSS/::slotted). Only elements that are distributed into slots can be styled. Since in your example it's a `<p slot="cta">` that's distributed to the slot, only it can be styled, not the `<a>` which is a child of the `<p slot="cta">`. 

So if you want to style that 2nd `<a>`, the `<a>` itself must be distributed to the named slot. Something like this: 

```
<!-- Named slot -->
<span slot="cta">This is some named slot content </span>
<a href="#" slot="cta">with a link element</a></p>
```

Here's the example modified to do this: https://stackblitz.com/edit/lit-element-example-pejc9r?file=index.html.

**Comment by jasonhulbert** [comment]
@sorvell  - Thanks for your response.

Right, that's the premise of the issue. There is no way to style a link that is within within a slotted element.

I don't need to just slot a link element, I need to slot the text and the link. That link could be at the beginning, middle or end of the text. The default slot allows for this. Obviously, your example would allow me to style the link but it doesn't accomplish the end goal.

I gather here that there is no way to style something within a slotted element other than global styles. 
Is there any way to accomplish the task as described? For example, is there a way to only slot the contents of the slotted element instead of the element itself? Or, maybe something like this made up code...

```
<template slot="cta">
  Text and stuff <a href="#">with a link</a> and then more text.
</template>
```

I'm just surprised this is so easily dismissed as I expect this will be a pretty common use case for named slots.

**Comment by jsilvermist** [comment]
One way is to make custom elements to work with `slot`s, and have the styling be self contained. A way I ended up having to do it to style native elements is to use a `FlattenedNodesObserver` and manually append the nodes to a dynamically generated container, while styling it as normal shadow dom.
