### ISSUE TITLE
[rc4] styles getting applied twice

### ISSUE THREAD

**Issue by moderndeveloperllc** [Polymer/lit-element#480]
It appears that styles are getting applied twice in the shadow DOM:
```
  static get styles() {
    return [
      css`
          .error {
            background: red;
            color: #fff;
          }
          .success {
            background: green;
            color: #fff;
          }
          .warning {
            background: yellow;
            color: #fff;
          }`,
    ];
  }
```
shows double in Chrome 71 element inspector:

![screenshot 2019-01-24 at 6 10 00 pm](https://user-images.githubusercontent.com/1920405/51716726-8f23f580-2003-11e9-9732-489750ce7108.png)

### Versions

- lit-element: v2.0.0-rc4
- webcomponents: v2.2.4

**Comment by sorvell** [comment]
Thanks, we'll get this fixed asap.
