### ISSUE TITLE
Hi, what should be the correct way to write something like "switch condition" in render html code?

### ISSUE THREAD

**Issue by PotterDai** [Polymer/lit-element#483]
Hi, what should be the correct way to write something like "switch" in render html code?
For example, I have a repeated list 
```
html`
<div>
${repeat(items, item=>item.id, (item, ind)=> {
    	switch(item.type) {
		case typeA:
			return html`...`;
		case typeB:
			return html`...`;
		default:
			return html`...`;
	}	
})}
</div>
`;
```
Is this the correct way of handling switch condition ? Thx!

**Comment by KeithHenry** [comment]
Also: yes @PotterDai that will work fine. Here is the relevant documentation: https://lit-html.polymer-project.org/guide/writing-templates#conditional-templates

**Comment by PotterDai** [comment]
@jorgecasar Thank you for remind! Will do so and close the issue!
@KeithHenry Thank you very much for the info! =D
