### ISSUE TITLE
[docs] Mention directives in docs and link lit-html docs

### ISSUE THREAD

**Issue by Christian24** [Polymer/lit-element#506]
Hi,

I have a suggestion for the docs: Maybe it makes sense to mention directives in the Templates-Guide in the docs. This is kinda extending on #430. My point is this: People who start learning LitElement might not be aware that directives exist, as they are only exported from and documented in lit-html.  Therefore I think it makes sense to add a couple sentences saying something like "If you want to use advanced templating features of lit-html in conjunction with LitElement you can find more info in the lit-html docs here: https://lit-html.polymer-project.org/guide/writing-templates. To use these features you need to install lit-html alongside LitElement". 

What do you think? I might be able submit an early draft of it as well if desired.

**Comment by katejeffreys** [comment]
Will look at this tonight or tomorrow. Thanks!

**Comment by justinfagnani** [comment]
I think along with this it would be nice to add an intro to the page that mentions lit-html with a link to it's site.

**Comment by Christian24** [comment]
I do agree. I feel sometimes the docs loose the connection to lit-html. Especially the template guide sounds a bit like all these concepts are from LitElement, while in reality they do come from lit-html.

**Comment by arthurevans** [comment]
Fixed in #826.
