### ISSUE TITLE
[docs] how to use property accessors with @property decorator

### ISSUE THREAD

**Issue by Christian24** [Polymer/lit-element#519]
Hi,

I would love to have some documentation on how to use property accessors with `@property`-decorator. I like how I can define a property with a decorator. 
````typescript
@property
info: string = 'Hello world!';
````
However, it is not documented how this works with custom accessors. I have found out myself that putting it on the getter like this works:
````typescript
 _info: string = '';

  @property({ type: String })
  public get info(): string {
    return this._info;
  }
  public set info(value: string) {
    const oldValue = this.info;
    this._info = value;
    this.requestUpdate('info', oldValue);
  }
````
Is this considered best practice in this case? I wouldn't like this, because for other properties I could still write it on the class field. I would prefer to be able to put all property decorators on the class fields. Or am I supposed to use `static get properties()` again like this:
````typescript
static get properties(): PropertyDeclarations {
return {'info': {type: String}}
}
  _info: string = '';
  public get info(): string {
    return this._info;
  }
  public set info(value: string) {
    const oldValue = this.info;
    this._info = value;
    this.requestUpdate('info', oldValue);
  }
````
It would be great if there'd be documentation on how to handle this. It feels a bit like mostly `static get properties()` is addressed, so a statement on whatever decorators are considered an equal alternative would be nice too. 

If no solution to this problem currently exists, I would have a suggestion as well:  
````typescript
//Override property name manually. 
@property({ type: String, name: 'info' })
 _info: string = '';

  public get info(): string {
    return this._info;
  }
  public set info(value: string) {
    const oldValue = this.info;
    this._info = value;
    this.requestUpdate('info', oldValue);
  }

**Comment by navigalia** [comment]
Hi @Christian24,

As you very well indicate, I think the best practice (object-oriented thinking) is your first choice. That's what I do. The other options I don't like.

**Comment by Christian24** [comment]
I just submitted a PR which adds a little documentation on this topic (although very little).

**Comment by arthurevans** [comment]
Related to #530.
