### ISSUE TITLE
[Firefox] Shady DOM seems to eat td/tr elements

### ISSUE THREAD

**Issue by myfreeweb** [Polymer/lit-element#52]
Running a Firefox nightly build from ~~2018-04-29~~ 2018-05-10, with anything that renders `<tr>` rows like this (`repeat` vs `.map` doesn't matter):

```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <script src="https://unpkg.com/@webcomponents/webcomponentsjs@next/webcomponents-loader.js"></script>
</head>
<body>
  <script type="module">
    import {LitElement, html} from 'https://unpkg.com/@polymer/lit-element@latest/lit-element.js?module';
    class MyElement extends LitElement {
      _render({ }) {
        return html`<style> .mood { color: green; } </style>
          Web Components are
          <table>
            <tbody>
              ${[ {one: 'dank', two: 'af'} ].map(item => html`
                <tr><td>${item.one}</td><td>${item.two}</td></tr>
              `)}
            </tbody>
          </table>
        `;
      }
    }
    customElements.define('my-element', MyElement);
  </script>
  <my-element></my-element>
</body>
</html>
```

Everything is fine with Shadow DOM (`dom.webcomponents.shadowdom.enabled`):

![wayland-screenshot-2018-05-10_15-00-30-fs8](https://user-images.githubusercontent.com/208340/39868664-45a3cd16-5463-11e8-9719-aee3ce1845dd.png)

But with the polyfill / Shady DOM, the table rows / cells are gone, all text is dumped together into the `tbody`:

![wayland-screenshot-2018-05-10_14-59-14-fs8](https://user-images.githubusercontent.com/208340/39868648-36de6ac0-5463-11e8-889a-b9e4293d8f9d.png)

**Comment by zacharytamas** [comment]
I've ran into this exact thing as well.

**Comment by sorvell** [comment]
Closed in favor of https://github.com/webcomponents/shadydom/issues/208 which is in progress.
