### ISSUE TITLE
Should `nothing` from lit-html be in the export from lit-element?

### ISSUE THREAD

**Issue by KeithHenry** [Polymer/lit-element#522]
So that slot fallback content still appears it's recommended to use `nothing` rather than `''`, `undefined` or `null`. 

As this is will be commonly used should it be included in the re-`export` from `lit-html`?

i.e. Add it here: https://github.com/Polymer/lit-element/blob/a5af1e83587553ce414c5cb9ee16c1280e6c637f/src/lit-element.ts#L21

I'm not sure whether this counts as a directive or something so commonly used that it needs to be included for the same reasons that `html` is?

**Comment by justinfagnani** [comment]
There's a bunch we could export from lit-html, but I think the current set is fine. Importing from `lit-html` works.
