### ISSUE TITLE
webcomponent-tester test?

### ISSUE THREAD

**Issue by sebs** [Polymer/lit-element#53]
Maybe add them, I would like to continue to tdd

**Comment by TimvdLippe** [comment]
@sebs Could you clarify what you are looking for? We are testing our implementation already in https://github.com/Polymer/lit-element/tree/master/src/test For any usage testing, that should be similar to how you tested PolymerElements, as `lit-element` is still just a webcomponent.

**Comment by sebs** [comment]
I am closing this, I cant remember either. Will re-open when I set up the next project and problems re-appear
