### ISSUE TITLE
[docs] Styles: make it simpler and friendlier

### ISSUE THREAD

**Issue by jbingham** [Polymer/lit-element#542]
Styling a component feels more complicated than it should. The doc leads with a bunch of jargon and concepts that will be unfamiliar to new users of Web Components. We'd like to communicate that it's super easy -- here's a tiny code snippet that does exactly what you want and sets you on the right path. The stuff about shadow DOM and host styles and all of that should feel like an elegant and better way of doing things. Currently it comes across more as overwhelming and a bit intimidating. Obviously not intended. It's not hard! Let's make it seem as ergonomic as it is.

**Comment by katejeffreys** [comment]
Agree completely!
