### ISSUE TITLE
properties is called twice for each class

### ISSUE THREAD

**Issue by blikblum** [Polymer/lit-element#55]
This occurs because the check to `constructor.properties` value at https://github.com/Polymer/polymer/blob/master/lib/mixins/properties-mixin.js#L89

**Comment by TimvdLippe** [comment]
@blikblum Can you provide a JSBin that shows the issue?

**Comment by blikblum** [comment]
Of course: https://lit-element-example-23f7hs.stackblitz.io

**Comment by sorvell** [comment]
This issue was moved to Polymer/polymer#5252
