### ISSUE TITLE
[docs] Note that external stylesheets are not supported on polyfill

### ISSUE THREAD

**Issue by kevinpschaaf** [Polymer/lit-element#561]
### Description
Under https://lit-element.polymer-project.org/guide/styles#external-stylesheet, it states:
> ...you can load an external stylesheet into a shadow root with a <link> element

The ShadyDOM scoping polyfill does not support scoping styles referenced via `<link rel="stylesheet">` in a shadow root.  Any styles loaded via the external stylesheet will _not_ be correctly scoped to the element under polyfill.  This is an open issue (https://github.com/webcomponents/shadycss/issues/97) that we haven't considered high-priority to support since the FOUC issue of the native feature makes the ability to load external stylesheets somewhat dubious.

This should at least be added in the list of caveats, or else not recommended at all.

**Comment by danielbarion** [comment]
#747

Kevin, maybe this PR help this question.
