### ISSUE TITLE
[docs] Headers for in-page hash links get covered by sticky page header

### ISSUE THREAD

**Issue by kevinpschaaf** [Polymer/lit-element#563]
### Description
When clicking on a #-link on the site, the browser scrolls the linked header to the top of the page, which is obscured by the sticky page header.

Consider investigating margin/padding hacks to avoid?

#### Live Demo
Example: https://lit-element.polymer-project.org/guide/styles#static-styles

#### Expected Results
"Define styles in a static styles property" header is visible.

#### Actual Results
"Define styles in a static styles property" header is obscured.

**Comment by frankiefu** [comment]
This should do the trick: https://stackoverflow.com/a/28824157
