### ISSUE TITLE
Template composing not working?

### ISSUE THREAD

**Issue by evilK7062** [Polymer/lit-element#572]
Regardig the template composing as showed in the docs https://lit-element.polymer-project.org/guide/templates#compose-a-template-from-other-templates.

It's not working in the demo, and neither in my local project 
https://stackblitz.com/edit/jmhpnq?file=my-page.js

**Comment by Westbrook** [comment]
In your demo here, you are attempting to call `static` getters from a non-static methods, where they are not available. Try:
```
import { LitElement, html } from 'lit-element';

class MyPage extends LitElement {
  render() {
    return html`
      ${this.headerTemplate}
      ${this.articleTemplate}
      ${this.footerTemplate}
    `;
  }
  get headerTemplate() {
    return html`<header>header</header>`;
  }
  get articleTemplate() {
    return html`<article>article</article>`;
  }
  get footerTemplate() {
    return html`<footer>footer</footer>`;
  }
}
customElements.define('my-page', MyPage);
```
See it here: https://stackblitz.com/edit/jmhpnq-xxp7jj?file=my-page.js

**Comment by evilK7062** [comment]
Yeah make sense as render is obviously not static here, I guess that the example in the docs, the getters should also be not static.  
Thanks!
