### ISSUE TITLE
[docs] Publish: Bug in TypeScript configuration

### ISSUE THREAD

**Issue by abenz1267** [Polymer/lit-element#574]
### Description
"ES2017" is not a valid value for the TypeScript configuration. It will result in:

#### Steps to Reproduce
Follow the guide here https://lit-element.polymer-project.org/guide/publish#transpiling-with-typescript and try to build.

#### Expected Results
No error thrown.

#### Actual Results
```
TS6046: Argument for '--module' option must be: 'none', 'commonjs', 'amd', 'system', 'umd', 'es6', 'es2015', 'esnext'.
```

### Versions
- lit-element": "^2.0.1"

**Comment by jogibear9988** [comment]
for target and lib it's okay but not for module! see: https://www.typescriptlang.org/docs/handbook/compiler-options.html
