### ISSUE TITLE
Arrays Filtered / Sorted within render are incorrectly rendered

### ISSUE THREAD

**Issue by nick-woodward** [Polymer/lit-element#577]
### Description

If you `filter` / `sort` a list within the render call then it leads to properties being incorrectly bound to multiple elements. 

The examples below should be pretty self explanatory.

#### Live Demo

**Filter Example**

https://glitch.com/edit/#!/lit-element-filter-render-issue?path=index.js:4:0

**Sort Example**

https://glitch.com/edit/#!/lit-element-sort-render-issue?path=index.js:22:0

#### Expected Results

Only the item that is checked is updated.

#### Actual Results

Multiple items are checked / unchecked.

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

### Versions

- lit-element: v2.0.1

**Comment by Westbrook** [comment]
You might be interested in checking out the [`repeat` directive](https://lit-html.polymer-project.org/guide/template-reference#repeat):

https://glitch.com/edit/#!/ember-profit?path=index.js:21:89

**Comment by nick-woodward** [comment]
@westbrook Interesting I was actually originally using repeat in my application when i was having this issue. 

I’ll try to reproduce the same issue I was having with repeat and follow up.

**Comment by nick-woodward** [comment]
Ah, I understand now. Basically by default `repeat` uses the index for caching purposes and to detect value changes.

https://github.com/Polymer/lit-html/blob/874b786ebba6aae0a6f3a4d2487ccc312e7926a3/src/directives/repeat.ts#L122-L126

So the piece I was missing, is I needed to specify the `KeyFn` to be something other than index.

However, the one thing it doesn't explain is why using the native `filter` and `map` acts in a similar way.
