### ISSUE TITLE
appreciate your feedback for custom element reactions diagram

### ISSUE THREAD

**Issue by AndyOGo** [Polymer/lit-element#579]
I just released an adapted version of the interactive react lifecycle methods diagram for custom element reactions:
https://andyogo.github.io/custom-element-reactions-diagram/

If you have time, I would appreciate your feedback very much.

**Comment by web-padawan** [comment]
Consider removing some of the locales as they still mention React (at least, Russian and Ukrainian).
Also, the "version toggle" does not make much sense to me. Custom Elements v1 are the only stable version at the moment, what was previously called "v0" is about to be removed from Chrome.

**Comment by web-padawan** [comment]
Moved my previous comment to w3c/webcomponents#784
This issue seems a duplicate to me, so maybe it should be closed.

**Comment by justinfagnani** [comment]
@AndyOGo I just took a look, and it seems like you're trying to fit custom elements into a well-known React lifecycle diagram style, yes?

I'm not sure the axes on this make sense though. The phases doesn't actually apply to all of connecting, updating and disconnecting. It seems like both axes are related to time, and so they overlap in meaning.

**Comment by justinfagnani** [comment]
Closed in favor of w3c/webcomponents#784
