### ISSUE TITLE
customElement doesn't re-render child components

### ISSUE THREAD

**Issue by FaBeyyy** [Polymer/lit-element#580]
### Description
When a lit-element component is instantiated as an html element inside a parent component e.g
``` js
render() {
  <child-component .props=${this.props} />
}
```
prop changes from the parent component will not re-render the child components even if the changed props are passed down.

This does work if the child component is instantiated as a js object, e.g
```js 
${new ChildComponent(this.props)}
```

#### Live Demo
https://stackblitz.com/edit/lit-element-example-dartwr

#### Expected Results
re-rendering of parent component should re-render child components that are passed the changing props, no matter how the are instantiated.

#### Actual Results
re-rendering only works when instantiated as js object.

### Browsers Affected

- [x ] Chrome
- [x ] Firefox

### Versions
- lit-element: "^2.0.1"

**Comment by Lodin** [comment]
You cannot use `constructor` for settings properties of any descendant of `HTMLElement` since all DOM elements have an empty constructor. So when you write:
```html
<child-element .props=${this.props}></child-element>
```
it basically works in following way:
```javascript
const el = document.createElement('child-element');
el.props = this.props;
```
It means that you have to define your properties as a trigger with:
```javascript
static get properties() {
  return { 
    props: {type: Object}
  }
}
```
[Here](https://stackblitz.com/edit/lit-element-example-a9nnnj) is the fixed example that works as you expect

**Comment by FaBeyyy** [comment]
> You cannot use `constructor` for settings properties of any descendant of `HTMLElement` since all DOM elements have an empty constructor. So when you write:
> 
> ```
> <child-element .props=${this.props}></child-element>
> ```
> 
> it basically works in following way:
> 
> ```js
> const el = document.createElement('child-element');
> el.props = this.props;
> ```
> 
> It means that you have to define a trigger for your properties with:
> 
> ```js
> static get properties() {
>   return { 
>     props: {type: Object}
>   }
> }
> ```
> 
> in a `ChildComponent` as well, and remove `constructor` because it does nothing in terms of custom HTML element.
> 
> [Here](https://stackblitz.com/edit/lit-element-example-a9nnnj) is the fixed example that works as you expect

I know I can't use the constructor for setting the props when defining as HTML element it was just for the sake of the example as I was using one class for both showcases.

Still, I don't understand why I have to manually define the properties in the static get properties but not when instantiating via js object. I think it should be either way but the same behaviour for both.
Guess this can be closed as its more of a design discussion than an issue

**Comment by jsilvermist** [comment]
Because when you use a JS object you're reconstructing the entire dom element every render, when you use proper html you are only passing in new properties.
