### ISSUE TITLE
[docs] Use a LitElement component link is broken

### ISSUE THREAD

**Issue by andretefras** [Polymer/lit-element#582]
### Description

The link [Use a LitElement component](https://lit-element.polymer-project.org/use) from [this](https://lit-element.polymer-project.org/try/create) page is actually broken.

#### Live Demo
https://lit-element.polymer-project.org/try/create

#### Steps to Reproduce
1. Follow the link on the page bottom.

**Comment by glrodasz** [comment]
The problem is that, there is not link at all: https://github.com/Polymer/lit-element/blob/master/docs/_try/create.md
