### ISSUE TITLE
use explicit lit-html version

### ISSUE THREAD

**Issue by magic-akari** [Polymer/lit-element#589]
https://github.com/Polymer/lit-element/blob/36e1991546a51d846f8880e6b58c0143384fec7b/package.json#L59-L61

It is better to use explicit lit-html version such as 

```json
 "dependencies": { 
   "lit-html": "1.0.0" 
 }, 
```

The unpkg will modify import path with the dependencies version.
It may break the code when use implicit version. ( E.g. I used https://unpkg.com/lit-element@2.0.0-rc.5/lit-element.js?module )

**Comment by ChALkeR** [comment]
> explicit version

But  that breaks update propagation for important dependency fixes.

What specific problem does unpkg have with implicit versions?
Do you have a testcase?

_I am not associated with to lit-element development._

**Comment by magic-akari** [comment]
testcase: https://gist.github.com/b3f84546d947a78c0831b5ace0e40540.git

It worked before the `lit-html@1.0.0` publishes. (it works with the latest `lit-element@2.0.1` and `lit-html@1.0.0` as well).
It seems there is a break change about the implement of directive between `1.0.0-rc2` and `1.0.0`, while version `lit-html@^1.0.0-rc.2` contains `lit-html@1.0.0`

**Comment by ChALkeR** [comment]
@magic-akari 
```diff
- import { repeat } from "https://unpkg.com/lit-html@1.0.0-rc.2/directives/repeat.js?module";
+ import { repeat } from "https://unpkg.com/lit-html@^1.0.0-rc.2/directives/repeat.js?module";
```

Does this work for you?

**Comment by sorvell** [comment]
The intention is that we want LitElement to use the latest non-breaking version of lit-html and that dependency is correct. Syncing the versions was trickier when both lit-element and lit-html were in pre-release but it should be more straightforward now that both are in general release.
