### ISSUE TITLE
Custom templating

### ISSUE THREAD

**Issue by goldingdamien** [Polymer/lit-element#591]
Looking at all the guides, it looks like everything is completely focused on using lit-html template strings.
There are many template libraries that are already in use that would be nice to use.
I think it would be appropriate that templates can be easily customized to use the way the user wants.
I have looked at the lit-element and lit-html documentation but can not see an easy way to construct and modify classes such as the TemplateResult and DefaultTemplateProcessor.
Is there currently a way to create a custom template mechanism and if not could this be considered.

Regards.

**Comment by justinfagnani** [comment]
The whole point of LitElement is to use lit-html. You may be interested in the base class for LitElement - UpdatingElement, which has all the update lifecycle, but not the hook into lit-html.

Even if you do customize lit-html's syntax via a TemplateProcessor, it's still going to be lit-html and expressions will be in JavaScript, which is a pretty fundamental difference from most template languages. IOW, lit-html can be customized a fair bit, but it's not designed to let you implement any template language.

**Comment by goldingdamien** [comment]
If that is the case, is my assumption correct that current and future functionality of LitElement outside of templating can be done just as easily through the vanilla web components and other vanilla JS functions?

**Comment by justinfagnani** [comment]
Not exactly, because LitElement allows for declaring reactive properties that easily reflect/sync to attributes and trigger the update lifecycle. That's why I referred you to UpdatingElement.

**Comment by goldingdamien** [comment]
Ok, thanks.
I will close the issue, and leave the information below for reference.

Just to clarify my concern. Learning how to use a library, implementing it and then having to backtrack later can waste a lot of time. Out of experience frameworks can become a large restraint on development speed when lacking customizability.
I also have existing templates that I would like to use.

As a solution, I have created a test LitElement function that can use mustache templates, and will test out Webpack loaders for mustache/handlebars to render beforehand.

**Comment by justinfagnani** [comment]
Like I said, you're probably interested in UpdatingElement.

**Comment by daKmoR** [comment]
if it wasn't clear here is the updating element
https://github.com/Polymer/lit-element/blob/master/src/lib/updating-element.ts#L199

it gives you all the features of lit-element without lit-html... so you can easily add your own renderer there

**Comment by goldingdamien** [comment]
How would I normally access UpdatingElement though?

**Comment by blikblum** [comment]
Here are two examples of UpdatingElement usage:

https://github.com/blikblum/raw-element/blob/master/src/index.js -> no template at all
https://github.com/blikblum/snabbdom-element/blob/master/src/index.js -> using snnabdom

**Comment by goldingdamien** [comment]
Thanks
