### ISSUE TITLE
Focusing slotted child in firstUpdated does not work

### ISSUE THREAD

**Issue by jonrimmer** [Polymer/lit-element#605]
### Description
The guide recommends using the `firstUpdated` lifecycle method to programatically focus a child node. If the node you wish to focus is slotted inside another custom element, calling `focus()` does nothing.

I'm not sure if this is a lit-element bug, a browser bug, or a deficiency of the Shadow DOM v1 design.

#### Live Demo

https://stackblitz.com/edit/y3xeha?file=my-element.js

#### Steps to Reproduce

1. Create a custom element that places its light DOM children into a `<slot>`:

```js
class FirstElement extends LitElement {
  render() {
    return html`<slot></slot>`;
  }
}
```

2. Create a second custom element that uses the first, and composed a button inside it:

```js
class SecondElement extends LitElement {
  render() {
    return html`
      <first-element>
        <button>I should be focused</button>
     </first-element>
    `
  }
}
```

3. Have the second custom element attempt to focus the button it has composed inside the first:

```js
  firstUpdated() {
    this.querySelector('button').focus();
  }
```

#### Expected Results

When an instance of the second element is added to the DOM, the button it contains should be focussed.

#### Actual Results

The button is not focussed.

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [ ] Edge (untested)
- [x] Safari 11
- [ ] Safari 10 (untested)
- [ ] IE 11 (untested)

### Versions
<!--
`npm ls` will show the version of webcomponents.js and lit-element
```
    "@webcomponents/webcomponentsjs": "^2.2.7",
    "lit-element": "^2.0.1"
```

**Comment by Westbrook** [comment]
In this case you are using the right callback, however your code is not taking into account the requirement that the child element must also be fully update before you can focus its contents. If take a look at https://stackblitz.com/edit/y3xeha-o4gmjt?file=my-element.js you will see the context in question working as expected.

The operative difference is the following:
```
  async focusButton() {
    await this.shadowRoot.querySelector('my-frame').updateComplete;
    this.shadowRoot.querySelector('#test').focus(); 
  }
```
Here the parent element is waiting for its child to completely update before attempting to focus it's contents. This delay ensure that the button will actually have a `<slot/>` to be displayed in (i.e. actually be available for receiving focus) before focusing the element.

Hope that helps!

**Comment by jonrimmer** [comment]
@Westbrook Thanks, that works for my use-case. Although I notice the problem reappears if composed element also composes its slotted content: https://stackblitz.com/edit/y3xeha-mqtjqg?file=my-element.js

It would be nice if there was some lifecycle method that was called when the DOM was definitely ready to be manipulated.

**Comment by Westbrook** [comment]
You may be referencing this: https://github.com/Polymer/lit-element/pull/400 Very WIP, some what speculative, and may not be exactly what you're looking for, so if you have thoughts or use cases that you think it should support, add them to https://github.com/Polymer/lit-element/issues/365

Cheers!
