### ISSUE TITLE
Boolean attribute on child element stops working after multiple updates

### ISSUE THREAD

**Issue by SirkoS** [Polymer/lit-element#613]
### Description

I have a boolean property on an element that is propagated to a child-element. In particular, It is directly linked to the `checked` property of an `<input type="checkbox" />`.
The change on the input element is propagated to the respective property of the custom element using an event handler as [suggested in the docs](https://lit-element.polymer-project.org/guide/events#handle-fired-event). So in my understanding I have a two-way data-binding here between the custom elements property and the `checked` property of the input.

After  the property has been changed once from within the custom element (by clicking on the input element), changes from the outside are not propagated.

#### Live Demo

https://jsfiddle.net/sirko/bcuxe1dk/

#### Steps to Reproduce

1. click the first checkbox     - all checkboxes change.
2. click the second checkbox - all but the first change.
3. click the third checkbox - all but the first and second change.
4. ...

*Note, that the text-output based on the property is updated correctly.*

#### Expected Results
All checkboxes should change according to the one being clicked.

#### Actual Results
Only those custom elements / checkboxes change, that have so far not been triggered themselves.

### Browsers Affected

- [ ] Chrome
- [x] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

*(can not check other browsers right now, but will do so later)*

### Versions

- lit-element: v2.0.1
- webcomponents: v2.2.7

**Comment by thepassle** [comment]
This should help you out:
https://github.com/Polymer/lit-element/issues/601#issuecomment-469626034

**Comment by sorvell** [comment]
This is specifically how the `<input>` element works. Attributes are only applied for initial configuration. After that the property is the "source of truth" and changes to the attribute have no effect. If you simply change to using a property binding instead (`.checked=${...}`) you'll get the behavior you want.

https://jsfiddle.net/sorvell1/ko9sc3tv/2/
