### ISSUE TITLE
How can I know slot is slotted?

### ISSUE THREAD

**Issue by sheweichun** [Polymer/lit-element#625]
```ts
import { LitElement, html,customElements } from 'lit-element';


class MyElement extends LitElement {

  render(){
    const {slotted} = this;  //how to get this slotted variable
    return html`
      <p>
          <slot></slot>
           ${slotted ? 'has slot' : 'no slot'}
      </p>
    `;
  }
}
customElements.define('my-element', MyElement);
```html
<my-elemen></my-elemen>
<my-elemen>test</my-elemen>
```

2. Question
 in MyElement' render function, how can I get a variable to tell me the slot is slotted?

**Comment by sorvell** [comment]
By "slotted" do you mean that element children have been assigned to the slot? I'm going to assume that's the case.

To see what elements are assigned to a `<slot>`, call `assignedNodes()` on the slot ([docs](https://developer.mozilla.org/en-US/docs/Web/API/HTMLSlotElement/assignedNodes)).

To be informed of of changes to the `assignedNodes()` of a slot, you can listen to the `slotchange` event on the `<slot>` ([docs](https://developer.mozilla.org/en-US/docs/Web/Events/slotchange)).
