### ISSUE TITLE
Create your own property accesors in TypeScript

### ISSUE THREAD

**Issue by navigalia** [Polymer/lit-element#629]
### Description

There is no way to create your own property accesors in TypeScript.

The JavaScript example in this [section](https://lit-element.polymer-project.org/guide/properties#accessors-custom) works well, but in TypeScript I get a "Duplicate identifier" error with `prop` for example.

I've also tried combinations `prop`/`_prop` that compile but don't work well as in the JavaScript example.

#### TypeScript Demo

```ts
import { LitElement, html, customElement, property } from 'lit-element';

@customElement('my-element')
class MyElement extends LitElement {

  @property({ type : Number }) prop = 0;

  set prop(val) {
    let oldVal = this._prop;
    this._prop = Math.floor(val);
    this.requestUpdate('prop', oldVal);
  }

  get prop() { return this._prop; }

  render() {
    return html`
      <p>prop: ${this.prop}</p>
      <button @click="${() =>  { this.prop = Math.random()*10; }}">
        change prop
      </button>
    `;
  }

}
```

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari 11
- [x] Safari 10
- [x] IE 11

### Versions

- lit-element: v2.1.0

**Comment by motss** [comment]
@navigalia You can with `TypeScript` but with a little trick that the Polymer Team never document this. I've reported something similar before in https://github.com/Polymer/lit-element/issues/403.

The basic is as follows:
```ts
...

@customElement('my-element')
class MyElement extends LitElement {
  @property({ type: Number })
  get prop() { ... }
  set prop(val) { ... }

  render() { ... }
}
```

Hope this helps. `lit-element` with TypeScript is awesome again! 🎉

**Comment by navigalia** [comment]
Thank you @motss, this helped, now it works perfectly 🎉

**Comment by Christian24** [comment]
There is a docs issue for this already in #519.
