### ISSUE TITLE
How to get data from 2-way binding component

### ISSUE THREAD

**Issue by eufat** [Polymer/lit-element#64]
Since lit-element use unidirectional data binding, for ex: `<p>${myprops}</p>` . How do I get a data from a component which in its pattern use 2-way binding in LitElement? for example in routing `<app-route/>` component with PolymerElement
```
<app-route
    route="{{route}}"
    pattern="/:page"
    data="{{pageRoute}}">
</app-route>
```
And the data is propagated (I dont exactly know how this works) to `pageRoute.page`, 
```
<iron-pages selected="[[pageRoute.page]]" attr-for-selected="page-name" fallback-selection="fallback">
    <div page-name="test">Test</div>
    <div page-name="fallback">Not found</div>
</iron-pages>
```

**Comment by eskan** [comment]
HI,
you should listen for event : https://github.com/PolymerElements/app-route#integrating-with-other-routing-code and set properties.
in that particular case there's many other way to do this :

```
_render({page}) {
 return html`${page =="test" ? html`<div page-name="test">Test</div>` :  html`<div page-name="fallback">Not found</div>`}`;
}
```

```
_render({page}) {
  if(page =="test") return html`<div page-name="test">Test</div>`
  else return html `<div page-name="fallback">Not found</div>`
}
```
but you should take a look to the pwa starter kit https://github.com/Polymer/pwa-starter-kit wich use some pwa helpers https://github.com/Polymer/pwa-helpers#routerjs to achieve this.

**Comment by TimvdLippe** [comment]
@eskan is correct. 2-way binding is a Polymer-specific concept. https://github.com/Polymer/pwa-starter-kit is a great starting point for learning how it could be possible to propagate data based on `lit-element`. Of course you are free to choose your own way, like listening to events and react accordingly.
