### ISSUE TITLE
Modify binded properties doesn't trigger properties update or render

### ISSUE THREAD

**Issue by vlaraort** [Polymer/lit-element#644]
### Description
When an array property is binded from a lit-element parent to a child, the child is not updated if the property is modified.

It's used as in the documentation:
https://lit-html.polymer-project.org/guide/template-reference#binding-types

```
const myTemplate3 = (data) => html`<my-list .listItems=${data.items}></my-list>`;
```

#### Live Demo
https://jsfiddle.net/ot4Lp6mb/

#### Steps to Reproduce

1. Create `parent-element`
2. Create `child-element`
3. Bind an array property from parent to child
4. Modify the property in the parent

#### Expected Results
Array property should be updated in the child and re-rendered

#### Actual Results
The property is updated, but the render function is not called, also the `updated` function, or the attribute param. The updated is not reflected in the DOM.

### Browsers Affected

- [x] Chrome

### Versions

- lit-element: latest (from CDN in live demo)
- webcomponents: latest (from CDN in live demo)

**Comment by jolleekin** [comment]
Mutating the array doesn't work. Create a new array instead.
``` js
this.elements = [...this.elements, item];
```

**Comment by vlaraort** [comment]
Oh wow, I totally missed that, thank you!
