### ISSUE TITLE
[docs]: example re-registers element

### ISSUE THREAD

**Issue by ebidel** [Polymer/lit-element#649]
The section under "Example: Declare properties with TypeScript decorators" uses the `@customElements` decorator and then reregisters the element using `customElements.define()` below the class

<img width="790" alt="Screen Shot 2019-04-13 at 10 26 44 AM" src="https://user-images.githubusercontent.com/238208/56083199-ae4a4c00-5dd6-11e9-855f-121b3ff336bd.png">

**Comment by zixsma** [comment]
I think this issue has been fixed already. Should we close this issue?
[https://lit-element.polymer-project.org/guide/properties#initialize-property-values-when-using-typescript-decorators](https://lit-element.polymer-project.org/guide/properties#initialize-property-values-when-using-typescript-decorators)

**Comment by arthurevans** [comment]
Yep, fixed long ago, closing.
