### ISSUE TITLE
[docs]: cssLiteral still mentioned

### ISSUE THREAD

**Issue by ebidel** [Polymer/lit-element#650]
https://lit-element.polymer-project.org/guide/styles#expressions-in-static-styles

Looks like `cssLiteral` was removed in https://github.com/Polymer/lit-element/commit/56bfa0b871278a2c6a4e73c33920f65564c864ef but the docs still mention.

**Comment by hyperpress** [comment]
This is currently waiting for a merge from #600

**Comment by arthurevans** [comment]
Fixed in #600.
