### ISSUE TITLE
[docs] Handling events outside of LitElement/LitHTML

### ISSUE THREAD

**Issue by Viniter** [Polymer/lit-element#654]
The documentation is pretty misleading when showing examples of handling custom events dispatched on LitElement components outside of lit-html context.

[Documentation says](https://lit-element.polymer-project.org/guide/events):
> To handle an event fired by a LitElement-based component that you’re using on ***any HTML page***:
> `<my-element onMyEvent="(e) => {console.log(e)}"></my-element>`
> `<my-element onClick="(e) => {console.log(e)}"></my-element>`

(emphasis mine)

This doesn't work in plain HTML, the example likely shows JSX. Neither React nor JSX is mentioned anywhere on the page and the paragraph clearly says "any HTML page", which is misleading. 

As far as I know, the only way to attach event listener in plain HTML + JS context, would be using `addEventListener()`. It would be useful to show an example of that.

The issue was also discussed in a [Polymer Project Slack thread](https://polymer.slack.com/archives/C03PF4L4L/p1555344427117900).

**Comment by chase-moskal** [comment]
> `<my-element onMyEvent="(e) => {console.log(e)}"></my-element>`

> This doesn't work in plain HTML, the example likely shows JSX. Neither React nor JSX is mentioned anywhere on the page and the paragraph clearly says "any HTML page", which is misleading.

hmm, wait a second.. it is *really close* to valid html syntax, the following actually works today:

```html
<div onclick="console.log('clicked!')">clickme</div>
```

these are some seriously OG tactics i haven't seen for a long time, that's for sure, but i'm wondering:

does lit-element do some magic to make these old-fashioned attribute-string-eval monstrosities work with custom events? that would be pretty cool and consistent with standard html elements

the documentation you cited would not work under the standard html rules, as we can't pass in a function reference, we actually have to pass a little script — this certainly needs to be reviewed by somebody in-the-know

**Comment by Viniter** [comment]
>does lit-element do some magic to make these old-fashioned attribute-string-eval monstrosities work with custom events? that would be pretty cool and consistent with standard html elements

Now that's what I originally thought, or at least what the docs lead me to believe. But I did play around with it a bit and it doesn't seem to do anything with custom events. It would be cool tho.

Here's a [stackblitz](https://stackblitz.com/edit/vu5e8d), showing it doesn't work. The event get's fired and you can listen to it using `addEventListener`, but the attribute does nothing.

> the documentation you cited would not work under the standard html rules, as we can't pass in a function reference, we actually have to pass a little script — this certainly needs to be reviewed by somebody in-the-know

It also seems to use case sensitive attributes which would be misleading. I played around with both the way it's in the docs and the way standard events handlers can be attached through attributes and neither seems to work.

Also, I don't see how could it work. LitElement would somehow have to know what events you dispatch and bind the attributes with their names to event listeners. Not mentioning the string eval. All that for a feature that is barely mentioned. Yeah, I think it's just confusingly written doc.

**Comment by arthurevans** [comment]
Yeah, this doc is wrong, as @Viniter said, you should be using standard JS to add an event handler in this case.

**Comment by SampsonCrowley** [comment]
Wow I just wasted so much time because of these docs

**Comment by arthurevans** [comment]
@SampsonCrowley Really sorry about that. This should be fixed by #760 .

**Comment by SampsonCrowley** [comment]
@arthurevans @justinfagnani _should_ this format work though??

obviously it doesn't now, but is support for html level functions (e.g. native `onclick` in standard html `<button onclick="foo();"></button>`) something that we should try to add? or would that be a `lit-html` issue?

It does seem like a gap in functionality. if we add it in, then servers could add listeners into standard generated markup

**Comment by SampsonCrowley** [comment]
the wrapper that turns attributes into listeners could probably be done using something like ``Function(`return function onmyevent(event) {${passedAttribute};};`)()``

**Comment by SampsonCrowley** [comment]
I suppose servers could also just add a `<script></script>` tag that references the element by ID, but I think that would get tricky when dealing with potential combinations of light and shadow dom where fallback markup is nested with other webcomponents and slotted elements

**Comment by justinfagnani** [comment]
It can't work with CSP policies than prohibit `eval`. We keep compatibility with those policies, and in general don't want to add new unsafe sinks to HTML.
