### ISSUE TITLE
Defining styles in a style element doesnt work as described

### ISSUE THREAD

**Issue by dedego** [Polymer/lit-element#656]
The described example: https://lit-element.polymer-project.org/guide/styles#style-element sets the styles on the class and not on the instance as described.

In my case I wanted to experiment with simple flexbox components where I would have a flexbox wrapper and a flexitem with all the possibilities to set the values per instance. Now I will have the settings for the first flexitem on all my instances.

As the documentation states that the style element is the solution for having styles per instance, is this a bug? One can have a opinion I what I am trying to accomplish is a good idea, but anyone have a suggestion on what would work?

**Comment by Westbrook** [comment]
In both of your cases it would seem that you're running into the realities outline in the link provided by @dedego:
> *Expressions inside a <style> element won’t update per instance in ShadyCSS.* Due to limitations of the ShadyCSS polyfill, you can’t use element properties in CSS rules as the expressions won’t be evaluated.

You might look into the application of [CSS Custom Properties](https://developer.mozilla.org/en-US/docs/Web/CSS/--*) in this context as it may provide an alternate API for the results your are looking to achieve. 

```
return html`
      <style>
        @media screen and (min-width: 960px) {
          img {
            shape-outside: url(var(--shape-src));
          }
        }
      </style>
`;
```

or 

```
return html`
      <style>
        :host {
                display: var(--display-type);
                flex: var(--flex-settings);
                // ...etc.
        }
      </style>
`;
```

With this approach you should also be able to rely on the `static get styles()` entry which will continue to provide better performance in your components as `adoptedStylesheet` expands its browser coverage.

**Comment by dedego** [comment]
Finally managed to apply styles per instance by doing:
`
@customElement('flex-wrap')
class Flex extends LitElement {
  @property() direction: 'row' | 'column' = 'row';
    @property() wrap: 'nowrap' | 'wrap' | 'wrap-reverse' = 'nowrap';
    @property() justify: 'flex-start' | 'flex-end' | 'center' | 'space-between' | 'space-around' | 'space-evenly' = 'flex-start';

    static get styles() {
        return css`
            :host {
                display:flex;
                width: 100%;
            }
        `;
    }

    render() {
        // As style is not explicitly defined, we ignore TS warnings for now
        const { direction, wrap, justify } = this;
        // @ts-ignore
        this.style.flexDirection = `${direction}`;
        // @ts-ignore
        this.style.flexWrap = `${wrap}`;
        // @ts-ignore
        this.style.justifyContent = `${justify}`;
        return html`<slot></slot>`;
    }
}
`

and for targetting childnodes like @vrspider , you could do:

`
class SomeElement extends LitElement {
  // In the connectedCallback the <img /> element cannot yet be found.
  firstUpdated() {
    if (window.matchMedia("(min-width: 960px)").matches) {
      const { shapeSrc } = this;
      this.shadowRoot.querySelector('img').style.shapeOutside = shapeSrc;
    }
  }

  render() {
    return html`<figure><img src="" /></figure>`;
  }
}
`

**Comment by e111077** [comment]
Endorsing @Westbrook's answer on this one. Although lit-element supports javascript manipulation for styles, we don't recommend it as best practice for developer experience and security.
