### ISSUE TITLE
Injecting lit-html into Components or DOM Question

### ISSUE THREAD

**Issue by MVSICA-FICTA** [Polymer/lit-element#663]
Discovering lit-html was amazing and learning how it is utilized in a larger component model like lit-element is also amazing. There are some nice wrapper and factory patterns in some of the demos I've seen, yet it seems that there is a requirement to pick only one option: lit-html or lit-element as a way to manage template literals.

Using Reactive and FSM driven logic I'm inclined to reach for just lit-html, yet a few static lit-elements could be leveraged to prop up the app. Using lit-html I can create or fetch a template and simply render it dynamically in a functional way.

Is lit-element prepared for this kind of external injection? Can the lit-html template be targeted at a specific lit-element component and become part of it? Or at least can the components style rules be applied to what is injected? 

Injecting into a lit-element is one option but I'd like things to remain completely open ended, allowing straight DOM injection as well. I've just not seen much about these options mentioned so far. I'd be interested in learning everything I can about leveraging the strengths of both lit-html and lit-element together, using each without them cramping each others strengths if possible.

**Comment by Christian24** [comment]
I am not quite sure I understand exactly what you mean. 

If you want to create components based only on lit-html, you can still use components based on LitElement (or any other web component) in your template. 

Likewise `html` returns a TemplateResult, so you can use it straight in your template too:

````ts
render() {
  const template1 = html`<p>Hello</p>`;
  return html`${template1} <p> world</p>`;
}
````
You could also straight up use HTML with `unsafeHTML` directive: https://lit-html.polymer-project.org/guide/template-reference#unsafehtml

In case of injecting stuff into other components for me most of the time for me property bindings are enough. If it is not I am working on an event based dependency injection solution for web components that I will release to npm soon: https://github.com/Christian24/webcomponents-di

**Comment by MVSICA-FICTA** [comment]
What I am asking is straightforward. I just want to use the lit-html and the lit-element approaches to rendering together but independently to build the DOM. Yes, there is the property binding facility but I'm driving and evolving the DOM dynamically so I would control the injection myself, essentially working outside the typical web component approach.

Since lit-element has more support for component model structure and style I'm consequently asking how injected lit-html fragments will work. Will these fragments be isolated or be integrated under the style of a component they are injected into? Is there good or poor integration when using lit-html and lit-element side-by-side as alternate ways to render into the DOM?

Using lit-html inside the lit-element component model should not be the only option. It should also be allowed to be used in a side-by-side way together but independently. There should be more documentation and samples about this and not just the assumption that the web component model and it's property binding system is the only game in town.

**Comment by MVSICA-FICTA** [comment]
UPDATE It was important for me to be able to target different DOM nodes and bind full Web Components to separate roots. I believe I have now found the solution in Svelte, which offers a flexible range of composition options. I like it's syntax and compiler approach and it's focus on productivity and how it does not obscure getting things done with technology like Web Components that is still emerging.
