### ISSUE TITLE
litElementsVersion is wrong in 2.1.0

### ISSUE THREAD

**Issue by Artur-** [Polymer/lit-element#665]
https://github.com/Polymer/lit-element/blob/v2.1.0/src/lit-element.ts#L34

Maybe it would be time to `// TODO(justinfagnani): inject version number at build time`

Took a while to realize that I am actually using 2.1.0 and not 2.0.1 as `window.litElementVersions` says.

**Comment by sorvell** [comment]
Sorry about that. We'll get this fixed in the next release.

**Comment by justinfagnani** [comment]
cc @azakus too
