### ISSUE TITLE
Is possible to invoke a method of child element made with lit element? 

### ISSUE THREAD

**Issue by ianes1978** [Polymer/lit-element#666]
Is possible to invoke a method of child element made with lit element?  I see that with polymer elements is possible but i don t find examples with lit element... I would like to trigger a method from the parent element.

**Comment by Westbrook** [comment]
If you have access to a custom element, then you have access to any of the public API of that custom element, so yes.

**Comment by ianes1978** [comment]
child-element.js
```

import { LitElement, html } from 'lit-element';

class ChildElement extends LitElement {
  render(){
    return html`
      <!-- template content -->
      <p>A paragraph</p>
    `;
  }
methodToTrigger(){
alert("method triggered");
}
}

customElements.define('child-element', ChildElement );
```

parent-element.js

```
import { LitElement, html } from 'lit-element';
import 'child-element'

class ParentElement extends LitElement {

  render(){
      return html`
   <child-element id="cld"></child-element>
<button @click="${()=>{this.triggerChild()}}></button>
    `;
  }
triggerChild(){
let elementChild=this.shadowroot.getElementById("cld")
elementChild.methodToTrigger()
}

}
// Register the new element with the browser.
customElements.define('parent-element', ParentElement);
```


How i made a public API?
something like this code?

**Comment by Westbrook** [comment]
That looks good!

Tweaked a couple of points to make sure it's working:
https://stackblitz.com/edit/yeeunw?file=my-element.js

Enjoy!

**Comment by ianes1978** [comment]
works !!!
tnx

**Comment by remmel** [comment]
Thanks for your example @ianes1978, this is (now?) `this.shadowRoot` instead of `this.shadowroot` can you update your example?
