### ISSUE TITLE
Extremly slow on IE 11

### ISSUE THREAD

**Issue by quetzalsly** [Polymer/lit-element#669]
### Description
A polymer 2.0 or 3.0 not using lit-element works perfectly, but the lit-element branch of the same site is extremly slow.

#### Live Demo
`polykart.store` //polymer 1.0?
`https://shop.polymer-project.org` //polymer 2.0?
`http://lit-element-dot-polymer-shop.appspot.com` //lit element + redux

#### Steps to Reproduce
Open each site in ie 11 on windows 7 (if that matters).

#### Expected Results
The site feels like 60 fps.

#### Actual Results
The site feels like 1 fps.

### Browsers Affected
- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [x ] IE 11

### Versions
"lit-element": "2.1.0",
"lit-html": "1.0.0",
"pwa-helpers": "0.9.1",
"redux": "4.0.1",
"redux-thunk": "2.3.0",
"reselect": "4.0.0"

Those are my own tests which also produce same slow results as polymer shop hosted sites.

**Comment by sorvell** [comment]
We identified an issue in the Shop app's usage of local storage that was specific to an IE11 bug. A fix is in progress.

**Comment by quetzalsly** [comment]
Confirmed that the fix works, thanks! I will close this since it's nothing to do with lit-element.
