### ISSUE TITLE
Property not updated when re-rendered with value in template

### ISSUE THREAD

**Issue by Fyrd** [Polymer/lit-element#675]
### Description
Property not updated when re-rendered with value in template

#### Live Demo
https://codepen.io/Fyrd/pen/yWOwLE

#### Steps to Reproduce
1. In the demo, notice that clicking "Toggle index" will switch between rendering two items, both with "myprop" value "foo"
2. Click one of the items to change its value to "bar"
3. Toggle index again, notice that *both* values now have as value "bar" when instead toggling should reset them back to "foo".

#### Expected Results
Toggling the index should re-render `<my-child>` with myprop value "foo"

#### Actual Results
`<my-child>` has myprop value "bar"

### Browsers Affected
Occurs in all browsers I tried:
- [ x] Chrome
- [ x] Firefox
- [ x] Safari 11

### Versions
- lit-element: v2.1.0

**Comment by sorvell** [comment]
Currently, `lit-html` dirty checks property part bindings like the `.myprop` one in the example against the previous value rendered by lit and not the current property value of the element. See the related [lit-html issue](https://github.com/Polymer/lit-html/issues/877) where this behavior is being discussed.

In the meantime, it's easy to customize the behavior here by using a directive. Here's an updated example showing how: https://codepen.io/sorvell/pen/BeLqMN?editors=0010 and the directive here for easy reference:

```
  // Dirty check value against element property value, not part's previous value.
  const elementDirtyCheck = directive((value) => (part) => {
    const {name, element} = part.committer;
    if (value !== element[name]) {
      part.setValue(value);
    }
  });
```

Closing this issue in favor of the referenced lit-html one.

**Comment by Fyrd** [comment]
@sorvell Ah, should have realized it was more of a lit-html issue. Thanks for the info & workaround!
