### ISSUE TITLE
Feature request: A sane IE 11 example

### ISSUE THREAD

**Issue by cekvenich** [Polymer/lit-element#677]
Hi. I'm searching www for a sane lil-element hello world that is ie11 compatible.
Home page here says: any browser that supports modules. 

1. So example has to check for modules and failover to work w/o.
2. Checks if it needs polyfills and load only minimal what is needed. From a CDN, eg:  unpkg. (sane).  And keep an eye on load size (eg http://gtmetrix.com waterfall) and UX.
3. Maximum avoid tooling, #796 is not a solution as it is not simple to setup, and who can tell if it is setup right after hours

Is this too much help to ask? 

I hope ie11 is not just a hand wave, it has 6% market share (+/-2) and that all levels of front end developers and designers should be able to use this. Tooling can be added to automate a production flow: after a hello world works.
I know we all don't like ie11 but we are doing professional/paid/commercial development, so it can't be just working under laboratory condition.

**Comment by hyperpress** [comment]
So, the first thing you can do is consult the docs:
https://pwa-starter-kit.polymer-project.org/ for examples. You'll see there
that E11 is supported, which kind of undercuts the idea about not wanting
to.

Also, you can ask questions on the @polymer Slack beginners or general
channels. Hope this relieves your worries. Let us know if we can help.

**Comment by cekvenich** [comment]
@hyperpress  I can read that it is supported. I want a simple hello world example of IE 11.
Your item links to https://github.com/Polymer/pwa-starter-kit
That is not simple, requires tooling that I mentioned I don't want. And it includes Redux. Also, I don't need full polymer. 
I just want a simplest ie11 lil-element example that works, with simple hosted and small polyfills.

**Comment by hyperpress** [comment]
There is a simple example in the example in the TRY section of LitELement
docs. It requires polyfills for IE11 support. That's all explained. And
yes, it requires build tools, like polymer build or roll up or webpack to
work with it.

It sounds like you want features and support from modern browsers to work
in a decades old browser. Your going to disappointed in that case. But it
is supported if you're willing to do some build steps. I don't know of
anything close to LitElement that does what you want, but maybe someone
else here can help.

**Comment by cekvenich** [comment]
@hyperpress No I don't want that, don't put words in my mouth. That does not help anyone. I believe that I was eloquent and clear in my request without your personal interpretation.

**Comment by hyperpress** [comment]
I apologize if I misunderstood. But you listed three wants in your issue:

1. The TRY page and Getting Started in lit-element docs have very simple
examples. Have you looked at those and still need help?

2.  Please refer to:
https://www.npmjs.com/package/@webcomponents/webcomponentsjs#how-to-use for
loading polyfills.

You can load via unpkg, which is used in examples. Have you tried, and it's
not working?

3. You need ES5 compiled. Polymer build, and and PRPL differential serving
is about as simple as it gets, and your not clear on what you willing to
settle for, so I don't know how to help beyond that.

>

**Comment by cekvenich** [comment]
What is the html file that runs in ie? Where? 
@hyperpress Also, are you a developer here? Do you represent developers here?

**Comment by hyperpress** [comment]
I've tried to be helpful, and I've been a contributor and user since
Polymer 2 beta through LitElement and lit HTML release. I know this
software. I've sincerely tried to answer your questions. No problem, I
won't make that mistake again. Hopefully someone else can help you

**Comment by cekvenich** [comment]
@hyperpress Looks like you are representative of this community.
And now we can all decide if we should use this or not - based on the helpfulness in the context of this thread.

**Comment by jsilvermist** [comment]
@cekvenich Get out of here already, you ask rudely for examples in a place meant for bug reports, are rude to the person who tries to explain things to you, then imply he's unhelpful because you didn't get the response from him you wanted? Or maybe you did and were just looking for an opportunity to be negative the entire time.

This issue should be closed and locked.

**Comment by iantrich** [comment]
@cekvenich the context shows @hyperpress  trying to be helpful and yourself being rude.

**Comment by cekvenich** [comment]
I'll let the thread speak for itself.

**Comment by ashubham** [comment]
Help in this regard would be appreciated. Is there a sample which runs on IE11 ? The `Glitch` on the Readme seems to use `modules` so does not run on IE.

**Comment by phetw** [comment]
Hi all, I created a simple [example](https://github.com/phetw/awesome-panel) of `lit-element` setup that works on `IE11`. Suggestions for improvements are welcome :)

**Comment by sghoweri** [comment]
> Hi all, I created a simple [example](https://github.com/phetw/awesome-panel) of `lit-element` setup that works on `IE11`. Suggestions for improvement are welcome :)

Thanks @phetw!!

**Comment by lp74** [comment]
Hi @phetw, may you provide the same example (awesome) using webpack as packet bundler?

**Comment by lp74** [comment]
Hi @phetw, I've been able to replicate the simple example using webpack. Thank you!

**Comment by marcodelpercio** [comment]
I agree, there's no really clear example of how to.mske this work on IE11. I've seen the repo sample published by @phetw but it is still confusing the setup. It says that the browser would automatically load the correct file using 2 script tags and the nomodule trick however his source code doesn't actually do that and yet it loads the polyfill. It's very confusing. The other examples don't even address that.

**Comment by phetw** [comment]
@marcodelpercio  Essentially there are only 2 steps to make lit-element component works on IE11. First , typescript needs to be compile to javascript and javascript needs to be transpile to es5. Second, webcomponent polyfills must be included for the likes of shadow DOM etc. to work on older browsers.  

PS. I have a branch specifically for the using nomodule trick  [here](https://github.com/phetw/awesome-panel/tree/with-legacy), which I decided to merg that to master to avoid anymore confusion.

**Comment by juanmendes** [comment]
While I agree that @cekvenich could have been more polished in his replies and started using an angry tone, couldn't the team provide a simple example that explains how to workaround the decision not to provide es5 bundles? [This comment on a similar issue for lit-html](https://github.com/Polymer/lit-html/issues/210#issuecomment-387598403) mentions the following:

> Yep agree, but remember lit-html is still pre-release. Imagine the team will include UMD bundles alongside ES modules for 1.0. Because yeah as you say, it's almost universal to exclude node_modules from transpilation.

 I'm also struggling on how to use `lit-html` on a project that needs to support IE 11. I know this is for `lit-element`, but I believe the problem is the same: the burden of transpiling `lit` is offloaded to the user. 

The solution also seems to be the same: use a babel plugin in your webpack/rollup/parcel configuration since `lit-***` only provides es6 bundles. I really appreciate the example created by @phetw for rollup and I think it would be great to have the same for webpack. @lp74 seems to have achieved this but didn't create a minimal demo. I will try to create one and post it here.

Are there plans to provide both es6 and es5 bundles so that users don't require custom configurations and extra plugins?

**Comment by cekvenich** [comment]
ps: The maintainers/committers here *EDITED* what they posted. Look at the notes, they all say edited. This is rare in open source. Hence I will do the same.

The point is: the docs say ie11 is supported. However, there are no tests or examples that would work on ie11. The solution is to edit the docs and say: IE 11 is not supported.

**Comment by juanmendes** [comment]
@cekvenich Did you get it working? I think the best thing to do here is to create your own example to be a good citizen like @phetw and help others that are struggling with this. I will also try to do that. 

I do really hope that `lit-html` provides the separate bundles so every user who cares about IE 11 doesn't have to customize their build.

**Comment by cekvenich** [comment]
@juanmendes My ID+google can show the history of my contribution to open source bugs, examples, etc. since Apache Struts days. I pointed to docs that said ie11 is supported. This hit some kind of nerve by accident. I was told that I wish for old browsers to have new features. I don't, I just wanted to see if this can be used w/ ie11 - as their own docs state. They felt I was insulting them by saying the docs say it supports ie11 when it did not. I feel no need to give this particular community anything. As does any ID here, just click and search to see who has given more or less to the open-source world, some just don't give back and others gave a lot. I did not check this thread since a year ago, and did not look at the code by phetw. 

As to your second part, I did get Custom Elements(CE) to work with both ie11 and modern browsers with a single code base.  So one can write CE component once, have it used by all, with automatic polyfills(eg promise) as needed with a very small codebase. I did not use code here, I had to re-write it, so no lit-element support (as I decided not to depend on this community for my projects) I used .ts to generate es5 code. If you want the link to the open source (not lit-element) CE code you need to find a way to contact me outside of this community. Good luck.

**Comment by web-padawan** [comment]
I'm not a maintainer of this repo but let me clarify two things:

1. It is possible to configure Babel as described here https://github.com/Polymer/lit-element/issues/883#issuecomment-577651183.
2. You can check out https://open-wc.org/building/ for webpack & rollup presets with IE11 support

However, please do not expect same performance in IE11 as in other browsers. There are polyfill-related performance implications that are nearly impossible to fully mitigate:

1. `ShadyCSS` performs CSS scoping in runtime, every time user refreshes a page
2. `ShadyDOM` monkey-patches a lot of browser API (which in particular breaks DevTools).

Please keep this in mind if IE11 support is a hard requirement for your projects.
