### ISSUE TITLE
Area: Docs. MVP for editable code sample widget checked in to github.

### ISSUE THREAD

**Issue by arthurevans** [Polymer/lit-element#678]

**Comment by arthurevans** [comment]
I think @e111077 is working on something here.

**Comment by e111077** [comment]
Check it! [PolymerLabs/code-sample-editor](https://github.com/PolymerLabs/code-sample-editor)

Still requires a bit of work before comfortable calling it a full MVP, but in a demo-able state

**Comment by kevinpschaaf** [comment]
Closing, now tracked in PolymerLabs/code-sample-editor#10
