### ISSUE TITLE
Support for read-only properties?

### ISSUE THREAD

**Issue by miztroh** [Polymer/lit-element#68]
Is it planned for ``lit-element`` to support read-only properties?

**Comment by LarsDenBakker** [comment]
The static properties getter is meant only for properties that trigger rendering (and are thus not read only). Other properties can just be plain javascript:

```
class MyComponent extends LitElement {
  get myReadOnlyProps() {
    return 'this is read only';
  }
}
```

**Comment by miztroh** [comment]
So, if you're wanting some internally-managed properties, is the recommended approach to just prefix the property names with a double underscore?  e.g. ``__fooInternalState`` instead of ``fooInternalState``?

**Comment by LarsDenBakker** [comment]
I think LitElement takes no stance on this. It's a plain javascript class, so you could use whatever methods available in JS for this goal. 

You could do a prefix which is what the polymer team uses on most of their projects or you could use a symbol to hide the property if you really wanted to do. There is also an ecmascript proposal coming up that supports private properties.

**Comment by miztroh** [comment]
OK, thanks.
