### ISSUE TITLE
Add example Webpack config to site

### ISSUE THREAD

**Issue by kevinpschaaf** [Polymer/lit-element#684]

**Comment by ianes1978** [comment]
if you want i have made a example 
[lit-element-webpack-starter](https://github.com/ianes1978/lit-element-webpack-starter)

**Comment by arthurevans** [comment]
We decided against providing our own sample webpack config. We now provide a sample Rollup config, along with general build guidance, and pointers to open-wc's sample webpack config, all in the new Build for production section: https://lit-element.polymer-project.org/guide/build
