### ISSUE TITLE
Lit-element, CSS Variables and IE11

### ISSUE THREAD

**Issue by Salet** [Polymer/lit-element#686]
I would normally post this is a question on StackOverflow, but I believe this might at least be a Lit-element's documentation issue.

How would I go about using Lit-element to create WebComponents that are using CSS Variables and would show up properly in Internet Explorer 11? From what I read in the docs IE11 is supported by simply importing the webcomponents.js bundle/loader, which mostly works fine, but the CSS Custom Properties are not applied to my component no matter how the styles were attached (css helper, style tag, link tag).

In the webcomponents.js docs I read that ShadyCSS requires some additional setup, but from what I can see in the sources it's already used in shady-render.ts in lit-html. Do I need to provide any additional setup when importing the components?

#### Live Demo
https://stackblitz.com/edit/lit-element-example-sncrr7
(unfortunately this can't be opened in IE11 directly since neither StackBlitz or Glitch.com seem to support it anymore)

```html
<!doctype html>
<html>
  <head>
    <script src="./node_modules/@webcomponents/webcomponentsjs/custom-elements-es5-adapter.js"></script>
    <script src="./node_modules/@webcomponents/webcomponentsjs/webcomponents-bundle.js"></script>

    <style>
      :root {
        --global-color: red;
      }
    </style>
  </head>
  <body>
    <my-element></my-element>
  </body>
</html>
```

```jsx
import {LitElement, html, css} from 'lit-element';

class MyElement extends LitElement {
  static get styles() {
    return [css`.mood { color: var(--global-color); }`];
  }

  render() {
    return html`
      <span class="mood">CSS Variables usage!</span>`;
  }
}

customElements.define('my-element', MyElement);
```

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [x] IE 11

### Versions
- lit-element: v2.1.0
- webcomponents: v2.2.10

**Comment by web-padawan** [comment]
You need to use `custom-style` from Polymer is you want IE11 support.
See the documentation on using it here https://polymer-library.polymer-project.org/3.0/docs/devguide/custom-css-properties#use-the-custom-css-properties-provided-by-a-polymer-element

**Comment by sorvell** [comment]
Yup, `custom-style` from `Polymer` is the easiest way to do this. However, you can also directly use `ShadyCSS` to roll your own version: https://github.com/webcomponents/shadycss#about-customstyleinterface.
