### ISSUE TITLE
Polymer Slack has poor discoverability

### ISSUE THREAD

**Issue by graynorton** [Polymer/lit-element#687]
### Description

Polymer Slack has poor discoverability

https://twitter.com/lkraav/status/1132243748069490689?s=20

#### Steps to Reproduce

Search Google for "Polymer Slack", use find-in-page while on any of the Polymer Project sites, try to find via site navigation

#### Expected Results

It's easy to discover that the Polymer Slack community exists and to sign up for it
#### Actual Results

It's not easy
### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

### Versions

- lit-element: vX.X.X
- webcomponents: vX.X.X

**Comment by DeadWisdom** [comment]
The slack link is broken.

**Comment by arthurevans** [comment]
@DeadWisdom thanks for letting us know--can you try this new one?

https://join.slack.com/t/polymer/shared_invite/enQtNTAzNzg3NjU4ODM4LTAzMzZlY2M0NWYxNGFhMjA1MDE2NTFlZWIyYzE4NzgxNDgxZGIxZjdiYjA3NGNlODA3YWJkZmM4NzQwMzdlZWY

I'll update the site.

**Comment by DeadWisdom** [comment]
Works great, thanks!

**Comment by andrico1234** [comment]
Hey all, the link above is no longer active

**Comment by arthurevans** [comment]
If you wound up on this page looking for the Polymer slack link, note that it's been renamed to the Lit & Friends slack. You can find that link on the Lit community page: https://lit.dev/docs/resources/community/

Apparently the updated community pages hadn't been deployed to the older  lit-html and lit-element sites; that should be fixed now.
