### ISSUE TITLE
is _requestRender() necessary all the time to re render?

### ISSUE THREAD

**Issue by codingphasedotcom** [Polymer/lit-element#69]
Hi I'm noticing I'm constantly having to use the requestRender menthod because the components don't render when theres a change in the data. Is this normal?

**Comment by nicolasparada** [comment]
Are you perhaps using an Object?
Ex:

```js
static get properties() {
  return {
    state: Object
  }
}
```

Mutating properties of `this.state` then will not trigger a rerender. You must override it completely.
```js
this.state = Object.assign({}, this.state, newState)
```

**Comment by codingphasedotcom** [comment]
ok got it thanks
