### ISSUE TITLE
[docs] docs mostly talk about decorators as a Typescript feature

### ISSUE THREAD

**Issue by Christian24** [Polymer/lit-element#692]
The docs mostly talk about decorators as a Typescript specific feature: https://github.com/Polymer/lit-element/search?l=Markdown&q=decorators

Since decorators are a language proposal for JavaScript and also work with Babel the docs should propably drop the phrasing Typescript decorators in favor of decorators. 

I think it would also make sense to have a general explanation what decorators are and how they can be used, similar what is already in the README. I am not sure where I would put that yet. 

What do you think?

**Comment by arthurevans** [comment]
Related to #530
