### ISSUE TITLE
Update component on slotchange event

### ISSUE THREAD

**Issue by YerkoPalma** [Polymer/lit-element#700]
### Description
Not actually sure if this is a bug or a simple question. I'm having problems to update a component on `slotchange` event. I have this template

```js
render () {
    return html`
    <ul class="todo-list active">
      <slot></slot>
    </ul>
    <div class="todo-panels">
      <a @click="${this.showAll}" href="#" id="all-todos" class="active">All</a>
      <a @click="${this.showPending}" href="#" id="pending-todos">Pending</a>
      <a @click="${this.showDone}" href="#" id="done-todos">Done</a>
    </div>
    `
  }
```

I'm adding elements by selecting my component and appending child, this doesn't re render my module, but on the next render it actually updates.

```js
const todoList = document.querySelector('todo-list') // <- This is my component
todoList.appendChild(todoItem)
```

This isn't firing the slotchange event, tried like this

```html
<slot @slotchange="${this.requestUpdate}"></slot>
```

and like this

```js
firstUpdated () {
  this.shadowRoot.querySelector('slot').addEventListener('slotchange', this.requestUpdate)
}
```

But nothing works. Is this the right way to call this? should I be using a different method to rerender the component?

### Browsers Affected

- [ ] Chrome
- [x] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

### Versions

- lit-element: v2.1.0
- webcomponents: not used

**Comment by justinfagnani** [comment]
@YerkoPalma closing this since it hasn't activity recently. Please re-open if it's still a problem and my suggestion doesn't work.
