### ISSUE TITLE
Bug when element with Conditionals rendering is used more than once and conditional change during runtime

### ISSUE THREAD

**Issue by Mile76** [Polymer/lit-element#714]
#### Steps to Reproduce

1. Create `my-element` **with Conditionals**

Render based on a Boolean condition:
e.g.
```js
html`
  ${this.myBool?
    html`<p>Render some HTML if myBool is true</p>`:
    html`<p>Render some other HTML if myBool is false</p>`}
`;
```
2. Append `my-element` **two times** to document.body
3. Trigger change of property myBool from false to true during runtime of app

#### Expected Results
Both `my-element` reflect the change of the myBool property and show changed rendered HTML.

#### Actual Results

Of the two elements the first implemented `my-element` reflects the change to property myBool whereas the second element does not update

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

### Versions
2.1.0

edit (justinfagnani): added code fences around example

**Comment by justinfagnani** [comment]
@Mile76 I'm closing this since it hasn't had recently activity and it this should be working. Please re-open if it's still an issue.
