### ISSUE TITLE
Closure Compiler Support

### ISSUE THREAD

**Issue by ribrdb** [Polymer/lit-element#716]
Is there a way to compile things using LitElement with Closure Compiler?
Since `@property` has the `@ExportDecoratedItems` tag, I thought tsickle might just make things work. But sadly it doesn't.
I've gotten it to work with something like this:
```ts
class MyElement extends LitElement {
  @property({=type: String=})
  uri: string = '';
}
Object.defineProperty(
    MyElement.prototype, goog.reflect.objectProperty('uri', MyElement.prototype),
    Object.getOwnPropertyDescriptor(MyElement.prototype, 'uri')!);
```
But that's pretty ugly to write for every property. Is there some easier way?

**Comment by ribrdb** [comment]
I found a nicer workaround for the non-decorator property definitions:
```ts
class MyElement extends LitElement {
  uri: string = '';
  static get properties() {
    return goog.reflect.object(MyElement, {
      uri: {type: String}
    })
  }
}
```
Tagging the class with `@polymer` also seems to work with the non-decorator version, but I'm not sure if that make other changes to the class.

**Comment by justinfagnani** [comment]
For Closure you need to use the static properties property. @rictic or @azakus can you comment on what else is needed?

**Comment by rictic** [comment]
With tsickle, properties should be properly protected from renaming. Are you compiling with `--generate_exports` and `--export_local_property_definitions`?

**Comment by ribrdb** [comment]
Are you saying the decorator should work with tsickle, or the static properties style?
It doesn't look like I had those flags set, I'll give that a try.

**Comment by rictic** [comment]
Yeah, idiomatic code with the `@property` decorator should just work.

**Comment by ribrdb** [comment]
Yes, adding those flags seems to fix the decorated properties. Thanks!

**Comment by rictic** [comment]
Glad to hear it!
