### ISSUE TITLE
Waiting for unpkg.com in chrome 

### ISSUE THREAD

**Issue by sowmiyaseshadriii** [Polymer/lit-element#717]
I have implemented component using lit-element and currently my import like this

`
import {
  LitElement,
  html,
  css
} from "https://unpkg.com/@polymer/lit-element@latest/lit-element.js?module";
`
initally was working fine but now unfortunately its saying `waiting fot unpkg.com` in chrome

**Comment by abraham** [comment]
unpkg seems to be having some issues currently. https://twitter.com/mikethefuture/status/1144049912159637508

**Comment by chase-moskal** [comment]
i wonder if you could use **import maps**, via es-module-shims, and define fallbacks to unpkg (like [unpkg, jsdelivr]), such that if unpkg doesn't load, the browser should fall back to the secondary cdn

i assume it won't wait a full 60 second timeout before attempting the fallback, that would defeat the purpose of the feature..

**Comment by bicknellr** [comment]
@abraham, thanks for pointing out that unpkg was having some problems at the time this was posted. The URL listed in the issue seems to be working now, so I'm going to close.
