### ISSUE TITLE
Styling not applied in FF / Safari when property asynchronously set in connectedCallback

### ISSUE THREAD

**Issue by xwatkins** [Polymer/lit-element#718]
### Description
When a property is set in `connectedCallback()` from data fetched asynchronously, `render()` is called as it should but the styling is not applied in FF and Safari (it works fine in Chrome). See CodePen below for example.

#### Live Demo
https://codepen.io/xwatkins/pen/eweNNb

#### Steps to Reproduce
1. Define styling using `static get styles()`.
2. define a property (not initialised).
3. in `render()`, return `null` if that property is `undefined`, otherwise display the value of the property.
4. in `connectedCallback()`, make an asynchronous request and set the property from 2. when the promise resolves.

#### Expected Results
The styling should be applied when rendering happens.

#### Actual Results
Styling is not applied in FF/Safari. Inspecting elements, the `<style>` tag in the shadow DOM are empty.

### Browsers Affected

- [ ] Chrome
- [x] Firefox
- [?] Edge
- [x] Safari 11
- [x] Safari 10
- [?] IE 11

### Versions
- lit-element: v2.2.0
- webcomponents: v2.2.10

**Comment by Westbrook** [comment]
In your render function, you use:
```
render() {
        if(!this.sequence) {
          return null;
        }
        return html`<div>${this.sequence}</div>`;
      }
```

Returning `null` the first time seems to be confusing FF and Safari. When you update to the following your pattern begins to work again:
```
render() {
        if(!this.sequence) {
          return html``;
        }
        return html`<div>${this.sequence}</div>`;
      }
```
Notice the return of an actual `TemplateResult` from `render()`. I believe this allows `lit-html` to continue to manage the node cleanly across the multiple renders, but hopefully someone more knowledgable than I can speak to what is actually happening between the two return statements.

**Comment by xwatkins** [comment]
I see, thanks @Westbrook , I guess I was using a React pattern here!
