### ISSUE TITLE
Can't share StackBlitz projects from LitElement home page

### ISSUE THREAD

**Issue by aomarks** [Polymer/lit-element#719]
1) Go to https://lit-element.polymer-project.org/
2) Click "LAUNCH CODE EDITOR (JAVASCRIPT)"
3) Click "Edit on StackBlitz"
4) Reload page or open the URL in a new tab
5) Observe that the project is lost
6) Try 1-3 again
7) Click "Share"
8) Observe that URL presented under "EDITOR URL" is "https://stackblitz.com/run", which also won't link to the project

**Comment by e111077** [comment]
Unfortunately this is unsupported by stackblitz when generating a project on the fly as we do. You must sign in and hit the "fork" button to share. Have filed a bug on StackBlitz/core#1006
