### ISSUE TITLE
Render Timing/State Accuracy Issue

### ISSUE THREAD

**Issue by Westbrook** [Polymer/lit-element#721]
### Description
When combining click event state changed with custom event state changes a series of boolean properties seem to be coming out of sync with the rendered UI. As you'll see below the extent of the issue seems to exist in the `my-element.js` code which is fairly stripped down to the issue at hand. That being so, I didn't get into reducing the complexity of the supporting files in the reproduction. Please let me know if you'd prefer I find a way to remove the complexity in those files to ease the use of the demo code in finding the root of the issue herein.

#### Live Demo
https://stackblitz.com/edit/lit-timing-issue?file=my-element.js

#### Steps to Reproduce
1. Visit the demo.
  - see
```
Values:
projecting: false
projecting2: false
projecting3: false
```
2. Click "Toggle Projection 2"
  - see
```
Values:
projecting: false
projecting2: false
projecting3: true
```
3. Click "Toggle Projection"
  - see
```
Values:
projecting: true
projecting2: false
projecting3: true
```
4. Inspect the `<my-element/>` element that is bound by the red border.
5. In the console access `$0.projecting3` which is now `false` and out of sync with the UI that is processing `projecting3: ${this.projecting3 ? 'true' : 'false'}` as "projecting3: true".

#### Expected Results
Step 3 above you result in:
3. Click "Toggle Projection"
  - see
```
Values:
projecting: true
projecting2: false
projecting3: false
```
And the value for `projecting3` should be similarly `false` when accessed in the console.

#### Actual Results
The visual representation for `projecting3` and the actual JS representation as not in sync.

### Browsers Affected

- [x] Chrome
- [x] Firefox ESR (though some on the internals happen out of order, so the issue is expressed via the `projecting2` property instead.
- [ ] Edge
- [x] Safari 12
- [ ] Safari 10
- [ ] IE 11

### Versions

- lit-element: v2.2.0
- webcomponents: v2.2.10

**Comment by justinfagnani** [comment]
Closing in favor of #800.
