### ISSUE TITLE
Pseudo elements like ::part and ::theme

### ISSUE THREAD

**Issue by anpfeiffer** [Polymer/lit-element#725]
Hi, is there a chance that the pseudo elements ::part and ::theme work in all browser?

It works for Chrome and opera but not in Firefox or Edge.

Thank you

**Comment by sorvell** [comment]
There is a branch with some experimental work [here](https://github.com/Polymer/lit-element/blob/part-styled3/src/lib/part-styled-element.ts) that we did awhile back. We're not super happy with the performance impact of this approach and we're not sure right now if/when/how we're going to carry this forward.

One thing we think definitely makes sense and can be implemented with minimal performance impact is to use `part` attributes in an element's DOM and then have a system that can inject stylesheets into elements that target (only) these parts. This approach is not strictly a polyfill for `::part` but it is inspired by and compatible with it and gives some of the same functionality. There's an example in that same branch [here](https://github.com/Polymer/lit-element/blob/part-styled3/demo/pseudo-part-styled.html). Hope that helps.

**Comment by justinfagnani** [comment]
Let's track this in https://github.com/webcomponents/polyfills/issues/252
