### ISSUE TITLE
Using lit-element with dom-if

### ISSUE THREAD

**Issue by vdegenne** [Polymer/lit-element#73]
I am sure this is an issue the Polymer team is aware of but I wanted to open this to make sure.

Using `dom-if` in a `lit-element` is not working as expected. For instance,

```javascript
_render(props) {
  return html`
    <dom-if if="${props.shouldRenderThis}">
      <template>
        <mwc-button label="add" on-click="${_ => this.addFunction()}"></mwc-button>
      </template>
    </dom-if>
  `;
}
```

This will render and visually not broken, but if one clicks on the `<mwc-button>` the `on-click` event-listener is not triggered, therefore the `addFunction` is not called.

And lit-element doesn't really propose a solution, at least not a user-friendly one AFAIK. The work-around I am using right now is something similar to : 

```javascript
_render(props) {

  let addButton = html``;
  if (props.shouldRenderThis) {
    addButton = html`
      <mwc-button label="add" on-click="${_ => this.addFunction()}"></mwc-button>
    `;
  }

  return html`
    ${addButton}
  `;
}
```

Is there a better solution to create conditional templates in `lit-element` ? Or is there a working branch already trying to leverage this question ?

Thanks Polymer.

**Comment by LarsDenBakker** [comment]
Hi @vdegenne 

You don't need to use dom-if with LitElement, you can use any javascript construction that pleases your eyes. Such as the example you listed above, or a ternary expression:

_render(props) {
  return html`
        ${props.shouldRenderThis ? html`<mwc-button label="add" on-click="${_ => this.addFunction()}"></mwc-button>` : ''} 
  `;
}
