### ISSUE TITLE
[Firefox] Attributes are reassigned if used in styles

### ISSUE THREAD

**Issue by jofan** [Polymer/lit-element#74]
If using the attribute values in the style tag, the values of attributes are reassigned between each other. I created a simple demo: [Stackblitz Demo](https://stackblitz.com/edit/lit-element-firefox-bug?file=index.js)

In the demo the relevant code looks like:
```
_render({top, left, animal, whales}) {
    return html`
      <style>
        :host {
          display: block;
          position:absolute;
          top: ${top}px;
          left: ${left}px;
        }
      </style>
      <h4>Type: ${animal}</h4>
      <div>Whales: ${'🐳'.repeat(whales)}</div>
      <p>Top: ${top}, Left: ${left}</p>
      <slot></slot>
    `;
  }
```

In Chrome it works but in Firefox __animal__ and __top__, and __whales__ and __left__ will have changed values with each other. Removing __top__ and __left__ from style declaration makes the issue go away.

<img width="417" alt="firefox_bug" src="https://user-images.githubusercontent.com/34047/40363613-5115df7e-5dd0-11e8-9f0b-460025b32189.png">

**Comment by blikblum** [comment]
I see the same bug on Chrome 63 on windows

**Comment by eskan** [comment]
Hi,
this look more a lit-html issue but i'm not sure you can use expression inside <style>, template are a dom hack to substitute values in places.
To achieve this you need to use inline style
```
style$=${`top: ${top}; left: ${left};`}
```
you can also use css custom properties 
```
:host {
          display: block;
          position:absolute;
          --my-top: 100px;
          --my-left: 300px;
          top: var(--my-top);
          left: var(--my-left);
        }
```
and
`this.style.setProperty('--my-top','400px');`

**Comment by eskan** [comment]
@jofan here isn't only string literal it's lit-html which use string literal to build template result with "parts" and this is dom relative.
@justinfagnani may you confirm that lit-html can't be use inside <style> ?

**Comment by blikblum** [comment]
Support for style is advertised as one of the lit-html features: https://github.com/polymer/lit-html#css-compatible-syntax

**Comment by eskan** [comment]
@blikblum i understand this as "lit html syntax is compatible with css syntax" so you can write style inside template string. (vs include expression in CSS style)

**Comment by smalluban** [comment]
Using expressions inside of the `<style>` element is not supported in browsers where `shadycss` is required. The shim takes `<style>` element and put it in the head of the document (it adds also scope to template element and CSS selectors). It has to be done before `render` method is called, so your values are placed in incorrect place.

**Comment by jofan** [comment]
@smalluban Thanks for that explanation. Then it's promising for the future when the shim is no longer necessary.

**Comment by valdrinkoshi** [comment]
Modifying the content of a stylesheet is bad practice, because that invalidates all the styles of that stylesheet, potentially causing unnecessary layout/paint. The most efficient way would be to use css custom properties as suggested in https://github.com/Polymer/lit-element/issues/74#issuecomment-391368188
