### ISSUE TITLE
[Proposal] use generics in typing `PropertyValues`

### ISSUE THREAD

**Issue by emilio-martinez** [Polymer/lit-element#744]
### Description

Currently `PropertyValues` is typed as

```ts
type PropertyValues = Map<PropertyKey, unknown>;
```

As shown in the live demo (below) this will provide no hinting whatsoever around what keys are actually available in the current class or not. My proposal is to define `PropertyValues` as follows.

```ts
type PropertyValues<T = any> = keyof T extends PropertyKey ? Map<keyof T, unknown> : never;
```

**Pros**
- It's opt-in.
- It's backwards compatible with the current definition.
- `props.has('unknownProp')` wouldn't type-check when using `PropertyValues<this>`.
- `props.has('notAnAtProp')` wouldn't type-check when using `PropertyValues<ImplementedInterface>` (see demo for example).

**Cons**
- People may expect `PropertyValues<this>` to infer and type-check `@properties`, even though the expected behavior is that it won't until applying `PropertyValues<ImplementedInterface>`.

#### Live Demo

https://stackblitz.com/edit/lit-element-property-values-with-generics-kyk1w8?file=my-element.ts

#### Other notes

Happy to provide a PR if this seems like a good idea.

### Versions

- lit-element: v2.2.0

**Comment by justinfagnani** [comment]
I like this. The question is whether the false positives for properties that are not decorated is too misleading.

@rictic @sorvell ?

**Comment by rictic** [comment]
Seems like a good change to me. 👍

**Comment by justinfagnani** [comment]
@emilio-martinez a PR sounds great!

**Comment by emilio-martinez** [comment]
Opened PR
