### ISSUE TITLE
Document how to override updateComplete using _getUpdateComplete

### ISSUE THREAD

**Issue by aomarks** [Polymer/lit-element#746]
I think we should update https://lit-element.polymer-project.org/guide/lifecycle#updatecomplete to explain how users can override `updateComplete` after https://github.com/Polymer/lit-element/pull/745 gets in. Due to a TypeScript ES5 limitation (see PR for more details), you cannot simply override `get updateComplete`, and we've added `_getUpdateComplete` as a `protected` override point for this purpose.

**Comment by justinfagnani** [comment]
Note that this only applies to subclassing LitElement, in TypeScript, and overriding `updateComplete`, while also targeting ES5 with the TypeScript compiler. Subclassing works fine in plain JS, targeting ES2015+, or compiling to ES5 with Babel.
