### ISSUE TITLE
html from database

### ISSUE THREAD

**Issue by mrherndon** [Polymer/lit-element#75]
I've been having a hard time all day with this one.
I have a complicated templating system, but I'll simplify here.

So I've got some templates that pull from json:

![image](https://user-images.githubusercontent.com/8726819/40386706-1970889e-5dd0-11e8-980c-b318f5cf7248.png)

![image](https://user-images.githubusercontent.com/8726819/40386746-31a3941a-5dd0-11e8-929d-1904cfef6eb3.png)
They render as I would expect:, (note the text break)
![image](https://user-images.githubusercontent.com/8726819/40387061-1a733c36-5dd1-11e8-86eb-4daca65cf651.png)

And I have other ones that pull very similar content from the database.  It essentially looks the same.  But it renders it all as text.
![image](https://user-images.githubusercontent.com/8726819/40386919-ac8554f2-5dd0-11e8-800d-db8a115a1904.png)

I have tried wrapping the db entry in html\`\` and creating a function that wraps it.  Nothing seems to work.  Is there a way to insert html in a ${} and preserve the html-ness?

**Comment by eskan** [comment]
Hi,
lit provide unsafeHTML :  https://polymer.github.io/lit-html/api/modules/_lib_unsafe_html_.html

**Comment by mrherndon** [comment]
Well, that is straight embarrassing.  I'm already pulling repeat from lit anyway.  Didn't even think to look through there.  
As an added bonus, I was very close to doing exactly what unsafeHTML was doing but didn't think to innerHTML a template element.  Apparently, it solves the issues that I was running into.  
Thanks, @eskan, you rock.
After I confirm that it works, I'll come back and close this out, and my shame with it.

**Comment by mrherndon** [comment]
Yup, totally solves the problem.

**Comment by TimvdLippe** [comment]
No shame at all! Mistakes happen and this was easy to overlook. Glad the function solved your problem.
