### ISSUE TITLE
Change imports to relative paths

### ISSUE THREAD

**Issue by tirithen** [Polymer/lit-element#76]
Hi, we are starting a new Polymer 3 project and want to use lit-element if possible. We prefer to just use the source files as is when developing to exclude any extra build steps and it works perfectly in previous projects (using Polymer 2 and 3.0.0-pre). With ES6 imports this is super handy, how come that you don't write your imports as relative paths?

When trying the same approach with lit-element we get the following error because of this:

`Uncaught TypeError: Failed to resolve module specifier "@polymer/lit-element/lit-element.js". Relative references must start with either "/", "./", or "../".`

Also `polymer serve` will not work since it gets the URL's wrong. With `polymer build` it works fine but having to build before each page load is inconvenient.

Would you consider changing all the import statements so that they are relative to the file that is importing? This would remove the need to build entirely for development (and possibly even for pages that targets recent browsers), it does not make much sense to me to have a build step just to change import paths.

**Comment by TimvdLippe** [comment]
Please read about our reasoning and response in https://github.com/Polymer/polymer/issues/5238#issuecomment-390012108 This was a hard call to make, but we can provide an experimental solution (empathy) to transform to relative paths. I am actually using empathy and lit-element already in my side-project and it works great for me :)

**Comment by tirithen** [comment]
Thanks for explaining and the links, I guess this is the way it needs to be for now. Lots of npm packages are written like this anyway.

**Comment by simonh1000** [comment]
I get the same error after following https://lit-element.polymer-project.org/guide/start

**Comment by dss010101** [comment]
getting this same error...have this in my main:
`<script type="module" src="https://cdn.jsdelivr.net/gh/lit/dist@2/all/lit-all.min.js" ></script>`

and this line in my component js cause the same error:
`import {LitElement, html} from 'lit'`

what is the recommended way of doing this?  as the tutorial do not seem to cover this

**Comment by bicknellr** [comment]
> getting this same error...have this in my main: `<script type="module" src="https://cdn.jsdelivr.net/gh/lit/dist@2/all/lit-all.min.js" ></script>`
> 
> and this line in my component js cause the same error: `import {LitElement, html} from 'lit'`
> 
> what is the recommended way of doing this? as the tutorial do not seem to cover this

I left a reply [here](https://github.com/lit/lit/issues/2272#issuecomment-1226660014).
