### ISSUE TITLE
Styling using static styles property is inefficient on non Chrome browsers

### ISSUE THREAD

**Issue by blikblum** [Polymer/lit-element#761]
### Description
Currently, in browsers that supports native shadow dom but does not implement `adoptedStyleSheets`, the styles are appended to the shadowRoot of each component instance as a style element. This has two drawbacks:

 - The browser has to parse the styles each time an instance is created
 - Increase the memory usage (each component instance will hold a copy of the styles)

Reference: https://github.com/mozilla/standards-positions/issues/103#issuecomment-517949722

#### Live Demo
NA

#### Steps to Reproduce
NA

### Browsers Affected

- [ ] Chrome
- [x] Firefox
- [] Edge
- [x] Safari 11
- [x] Safari 10
- [] IE 11

### Versions

- lit-element: v2.2.1

**Comment by justinfagnani** [comment]
Firefox 70 now caches stylesheets like Chrome and Safari: https://bugzilla.mozilla.org/show_bug.cgi?id=1480146
