### ISSUE TITLE
what's the hook for after rendering?

### ISSUE THREAD

**Issue by zzzgit** [Polymer/lit-element#764]
After rendering, I want to do something, then which hook method should I use?

**Comment by justinfagnani** [comment]
Implement `updated()`: https://lit-element.polymer-project.org/guide/lifecycle#updated

**Comment by Taewa** [comment]
`updateComplete` is also helpful.

https://lit.dev/docs/v1/components/lifecycle/#updatecomplete

**Comment by vvaradarajan** [comment]
updateComplete can occur before render is done. A way out is to await updateComplete and then execute your code within a settimeout (ex: setTimeout(()=>console.log('this is the code that executes after one event cycle") ).  This forces the event cycle to complete allowing all the queued up renders to be executed.

**Comment by ilyagr** [comment]
What if I'm only using lit-html? How can I wait until I'm sure the user is seeing the updated render?

Specifically, I'm trying to do something like (sorry for the naivete):

```ts
await render(html`Loading: Doing work...`, loading_elt);
do_work();
await render(html``, loading_elt);
```

**Comment by AndrewJakubowicz** [comment]
Thanks for the question @ilyagr . `lit-html`'s `render` function is synchronous. So you do not need to use `await`, and on the next JavaScript statement after `render`ing, the DOM will have been updated by `lit-html`.

From your code example, it looks more like you want to render a visual indication that you're loading. Then `do_work()`, then clear that loading state. I'm making a lot of assumptions, but you probably want something like:

```js
render(html`Loading: Doing work...`, loading_elt); // Instantly render loading state.
await do_work(); // User may need to wait, but they can see the "Doing work" UI.
render(html``, loading_elt); // Work is done, instantly clear loading render
```

**Comment by ilyagr** [comment]
Thanks for the answer. It's good to know it's meant to be synchronous.

It doesn't feel like it is -- I see the old message after the work should be done. In fact, `do_work` was also originally synchronous. I'll keep debugging.

I am a bit new to web development, so the fact that `await undefined` works tripped me up and made me think that `render` is not synchronous. Well, now I know :)

**Comment by AndrewJakubowicz** [comment]
Message me on [the Lit Discord](https://lit.dev/discord/) if you find something else while debugging, since this is outside the scope of this particular issue.

See this minimal example: https://codepen.io/Spyr1014/pen/ExMObXX?editors=1000
