### ISSUE TITLE
what's the relationship between lit-element and polymer?

### ISSUE THREAD

**Issue by zzzgit** [Polymer/lit-element#768]
What's the relationship between lit-element and polymer?

Is  `lit-element` the successor of polymer?

**Comment by mchyb** [comment]
I think [this summary](https://github.com/Polymer/polymer/issues/5240#issuecomment-391337152) should answer your question.

**Comment by SampsonCrowley** [comment]
built by the same organization, but pretty much unrelated. LitElement is more about minimalism, polymer is more of a full on framework like react or vue

**Comment by justinfagnani** [comment]
> Is `lit-element` the successor of polymer?

I would say yes, with the caveat that Polymer 3 is still supported for bugs and security issues. You can keep using it indefinitely, and mix-and-match LitElement as needed/desired.
