### ISSUE TITLE
Support CSSStyleSheet for .styles property

### ISSUE THREAD

**Issue by samthor** [Polymer/lit-element#774]
lit-element should support returning a `CSSStyleSheet` object from the static class getter `.styles()`, in order to support the upcoming CSS Modules spec.

This behavior should be supported:

```js
import styles from './my-element.css';

class MyElement extends LitElement {
  static get styles() { return [styles]; }
}
```

Currently, I can do this, but it's using browser support only:

```js
import styles from './my-element.css';

class MyElement extends LitElement {
  constructor() {
    super();

    // Lit doesn't clobber this, since it has zero styles
    this.shadowRoot.adoptedStyleSheets = [styles];
  }
}
```

**Comment by danielbarion** [comment]
Take a look: https://github.com/Polymer/lit-element/pull/747

Maybe this can help you...

**Comment by samthor** [comment]
@danielbarion that's not related. I don't have the raw string, CSS Modules gives you a parsed `CSSStyleSheet`.

**Comment by grvpanchal** [comment]
Can we have ability to modify LitElement.styles as we dynamically load styles?
