### ISSUE TITLE
IE11, global css styles affect html elements inside a custom element

### ISSUE THREAD

**Issue by nathan-andosen** [Polymer/lit-element#777]
### Description

Setting css styles for a p element in my application is affecting the p element inside a lit-element in IE11 only.

Is this a known issue and can't be prevented for IE11? Or is there a way I can work around this?

#### Live Demo

In the live demo you will see I have set a global style (p { font-style: italic; }) which is leaking into my custom element.

https://stackblitz.com/edit/lit-element-css

#### Steps to Reproduce

View the live demo above, basically you just have to set a global style on a html element, like a p tag, and it will affect the p tag inside the custom element.

#### Expected Results

The p tag inside the custom element is not affected by global styles

#### Actual Results

The p tag inside the custom element is affected by global styles

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [x] IE 11

### Versions

- lit-element: v2.2.1
- webcomponents: v2.2.10

**Comment by justinfagnani** [comment]
This is always true for emulated shadow DOM. There's nothing we can do to prevent global styles from selecting elements in emulated shadow roots.
