### ISSUE TITLE
feature: globally set a hyphen conversion between attribute and property names

### ISSUE THREAD

**Issue by zzzgit** [Polymer/lit-element#779]
```
	static get properties() {
		return {
			myPropName: { attribute: true },
		};
	}
```

If I define a property like this, the corresponding attribute name should be `mypropname` by default.

Can you provide a way to globally set a hyphen style conversion?

`GlobalSetting.prop2attributeConv = "hyphen"`

then the corresponding attribute name will be `my-prop-name` by default.

**Comment by danleyb2** [comment]
you can configure the attribute name

```js
myPropName: { attribute: 'my-prop-name' },

```

**Comment by daKmoR** [comment]
you could make your own helper function that does it
```js
	static get properties() {
		return autoSetHypenedAttribute({
			myPropName: { attribute: true },
		});
	}
```

- iterate over the object elements
- if attribute === true convert key => hypened and set attribute vlaue

**Comment by justinfagnani** [comment]
We're not going to do any global settings. That would break every other LitElement on the page.

I like @daKmoR's helper idea, except that when we get auto-doc generation going, it won't know how to deal with that.

**Comment by justinfagnani** [comment]
Closing, since we can't add a global option like this. I recommend just setting the `attribute` option so that other readers and tools will be able to understand what the attribute name will be.
