### ISSUE TITLE
I can't use this in hasChanged

### ISSUE THREAD

**Issue by zzzgit** [Polymer/lit-element#784]
![222222222222](https://i.imgur.com/VcwHwv4.png)

I tried to watch the value change of the prop `disabled`.

If it is set to `true` from `false`, I will invoke a property method.

I have two questions: 
1. `this` is not accessible here, the only way to overcome it is to declare a `that` outside it?
2. is it the appropriate way to watch prop change in the method `hasChanged`?

**Comment by justinfagnani** [comment]
`this` isn't available. `hasChanged` should be a pure function.

You should use `update` to observe changes:

```js
update(changedProperties) {
  if (changedProperties.has('disabled') {
    // do things
  }
  super.update(changedProperties);
}
```

**Comment by zzzgit** [comment]
> `this` isn't available. `hasChanged` should be a pure function.
> 
> You should use `update` to observe changes:
> 
> ```js
> update(changedProperties) {
>   if (changedProperties.has('disabled') {
>     // do things
>   }
>   super.update(changedProperties);
> }
> ```

I think it's an important usage for people who are familiar with vue. However, this usage is not in the documentation.

**Comment by T-Knott-Mesh** [comment]
You can also do something like the following: 

@property decorator can be achieved with babel or typescript.

```javascript
   private _title: string = "";

    set title(title: string) {
        const old = this._title;
        if(old !== title){
            this._title = title;
            this.requestUpdate("title", old)
        }
    }

    @property({type: String})
    get title(): string {
        return this._title;
    }`

**Comment by jordanaustin** [comment]
> > `this` isn't available. `hasChanged` should be a pure function.
> > You should use `update` to observe changes:
> > ```js
> > update(changedProperties) {
> >   if (changedProperties.has('disabled') {
> >     // do things
> >   }
> >   super.update(changedProperties);
> > }
> > ```
> 
> I think it's an important usage for people who are familiar with `vue`. However, this usage is not in the documentation.

More documentation is always a good thing, so I'm with you on that 👍. Just a note on why it might not be documented explicitly: static methods on classes refer to the class itself and not an instance of the class, this is why you cannot use `this` in the properties list method.

**Comment by zzzgit** [comment]
It's `updated` rather than `update`.
Thank you, guys.

I have another question:

```js
	updated(changedProperties) {
		changedProperties.forEach((oldValue, propName) => {
			console.log( `${propName} changed. oldValue:`, oldValue)
		})
	}
```

There's only `oldValue` I can get from the API. What if I want the `newValue` also?

**Comment by zzzgit** [comment]
I tried to implement a wath API by myself.

base element:

```js
import {LitElement} from 'lit-element'

class EnhancedElement extends LitElement {
	attributeChangedCallback(attr, oldValue, newValue) {
		super.attributeChangedCallback(attr, oldValue, newValue)
		if (!this.watch) {
			return null
		}
		if (this.watch().hasOwnProperty(attr)) {
			const watcher = this.watch()[attr]
			watcher.bind(this, newValue, oldValue)()
		}
	}
}

export default EnhancedElement
```

child component:

```js
class Foo extends EnhancedElement {
	static get properties() {
		return {
			disabled: {type: Boolean},
		}
	}
	watch() {
		return {
			disabled(value, old) {
				console.log("disabled:", value)
			},
		}
	}
}

customElements.define('lit-foo', Foo)
```

**Comment by zzzgit** [comment]
How do you think?

**Comment by jordanaustin** [comment]
> It's `updated` rather than `update`.
> Thank you, guys.
> 
> I have another question:
> 
> ```js
> 	updated(changedProperties) {
> 		changedProperties.forEach((oldValue, propName) => {
> 			console.log( `${propName} changed. oldValue:`, oldValue)
> 		})
> 	}
> ```
> 
> There's only `oldValue` I can get from the API. What if I want the `newValue` also?

To get the 'newValue' you can just use this.propName, by the time updated has been called the property is updated and ready to use.

**Comment by justinfagnani** [comment]
Summary: You can definitely implement observers on top of LitElement. It's not something we want to do in LitElement though. We're trying to limit meta-programming to be compiler-friendly. `update` and `updated` are the official ways to do this.
