### ISSUE TITLE
App built with LitElement becomes whitewashed after leaving the tab and returning to it

### ISSUE THREAD

**Issue by ernsheong** [Polymer/lit-element#791]
How my app should look:
![image](https://user-images.githubusercontent.com/1343284/63917066-500fc400-ca6c-11e9-9355-dd161ec5e751.png)

How my app looks after leaving the tab open and navigating to other tabs:
![image](https://user-images.githubusercontent.com/1343284/63917084-6289fd80-ca6c-11e9-9e55-ed59f1eefe45.png)

Parts of the screen is missing.

Sometimes the app looks like it is close to being a blank white screen.

Browser: Chrome 76
OS: Mojave macOS

**Comment by ernsheong** [comment]
Another example:
![image](https://user-images.githubusercontent.com/1343284/63923852-d383e200-ca79-11e9-827e-0207a2e3f1d7.png)

**Comment by motss** [comment]
> Another example:
> ![image](https://user-images.githubusercontent.com/1343284/63923852-d383e200-ca79-11e9-827e-0207a2e3f1d7.png)

It looks like something wrong in the app itself. It'd be best to see if any re-render get triggered to verify such problem. A reduced test case might help.

**Comment by CaptainCodeman** [comment]
Are the items in the DOM? Are they hidden with CSS? Some things to check before considering whether it's lit, the browser or something else ...

**Comment by ernsheong** [comment]
It's probably the **browser**. It can't be the app.

Related Slack thread (https://polymer.slack.com/archives/C03PF4L4L/p1566974952006700):
![image](https://user-images.githubusercontent.com/1343284/63989866-7c7f1b00-cb14-11e9-8ac0-7ea553e50f3a.png)

**Comment by ernsheong** [comment]
I will close this for now as it seems to be better in latest Chrome and also it doesn't seem to be a lit issue. Was hoping to hear from others, but looks like it's just me apparently.
