### ISSUE TITLE
Polymer.importPath in LitElement

### ISSUE THREAD

**Issue by madeInLagny** [Polymer/lit-element#796]
Polymer treats relative URLs as relative to main document. Polymer 3 provides a [[importPath]] value for relative URLs. LitElement does not provide this helper. What is the best way to handle relative paths in LitElement using Polymer CLI build process ?

**Comment by Westbrook** [comment]
You'll want to use `import.meta.url` in cases like this.

Here's the post from the Polymer site about when that was added to the CLI: https://www.polymer-project.org/blog/2018-04-12-polymer-3-tools-update, the upgrade docs that touch on this: https://polymer-library.polymer-project.org/3.0/docs/upgrade and the associated CLI tests: https://github.com/Polymer/tools/blob/e38aadcec27f516103ff279b37d085192026515c/packages/bundler/src/test/import-meta-url_test.ts I like reading tests sometimes to understand how I might be able to use something, though these tests are pretty terse and a little out of context for learning from, IMO.

Here's an explainer on usage more generally: https://medium.com/@iamstan/tips-for-writing-es-modules-in-node-js-96ec688615a4#2f05 This might be the best place to start to work out how you'll actually make use of this feature in your own code, but wanted to ensure you had context above.

**Comment by madeInLagny** [comment]
Thank you.
Reading through the docs, I ended up with 
`src="${new URL('relative/file.js', import.meta.url)}"`
as the correct syntax for media src relative path.
There seems to be some compatibility issues with Edge though...

**Comment by Westbrook** [comment]
I am pretty sure you need to stringify with the `.href` property of the `new URL()`, and that the CLI _should_ be covering any cross-browser issues.

However, if you are able to successfully recreate the situation in Edge, then please raise an issue or see if one might already exist in https://github.com/Polymer/tools/issues where the CLI's workflow is tracked.

**Comment by justinfagnani** [comment]
@madeInLagny 
> There seems to be some compatibility issues with Edge though...

What issues?

**Comment by justinfagnani** [comment]
Closing, as `import.meta.url` is the standard equivalent of Polymer's `importPath`.

**Comment by madeInLagny** [comment]
> I am pretty sure you need to stringify with the `.href` property of the `new URL()`, and that the CLI _should_ be covering any cross-browser issues.
> 
> However, if you are able to successfully recreate the situation in Edge, then please raise an issue or see if one might already exist in https://github.com/Polymer/tools/issues where the CLI's workflow is tracked.

Can you please show how the stringify syntax looks like ?

**Comment by Westbrook** [comment]
In your case, it _should_ just be `src="${new URL('relative/file.js', import.meta.url).href}`.

`new URL('relative/file.js', import.meta.url)` return the whole URL object, where as `new URL('relative/file.js', import.meta.url).href` is the string.

Hope that helps!

**Comment by justinfagnani** [comment]
Also note that `import.meta.url` is a string already, so it really is equivalent to `importPath`. You can use it the same ways.

**Comment by madeInLagny** [comment]
I am now incorporating a variable component in the url. I can't get the right syntax for it.

I tried:

`<img src="${new URL("./media/overview-${ifDefined(this.i18NextCurrentLanguage)}-xs.gif", import.meta.url)}"/>`

but this does not resolve to the correct url and returns:

http://127.0.0.1:8081/src/components/landing%20page%20elements/features/%22./media/overview-part%20=%3E%20%7B%20%20if%20(value%20===%20undefined%20&&%20part%20instanceof%20AttributePart)%20%7B%20%20%20%20if%20(value%20!==%20part.value)%20%7B%20%20%20%20%20%20const%20name%20=%20part.committer.name;%20%20%20%20%20%20part.committer.element.removeAttribute(name);%20%20%20%20%7D%20%20%7D%20else%20%7B%20%20%20%20part.setValue(value);%20%20%7D%7D-xs.gif%22

What should be the correct syntax ?

**Comment by justinfagnani** [comment]
You can't use a directive like that. A directive isn't a normal function that returns a value that URL can understand. Also, it appears you have a nested `${}` expression inside a normal string and not a template literal. Regular strings will just contain a literal `${}` and not interpret the expression.

Try:

```js
let imgUrl = undefined;
if (this.i18NextCurrentLanguage !== undefined) {
  imgUrl = new URL(
      `./media/overview-${this.i18NextCurrentLanguage}-xs.gif`, 
      import.meta.url
  ).toString();
}
return html`<img src=${ifDefined(imgUrl)}/>`
```

**Comment by madeInLagny** [comment]
Thank you !
