### ISSUE TITLE
Closure compiler chokes on LitElement

### ISSUE THREAD

**Issue by joncass** [Polymer/lit-element#80]
When I try to use Closure Compiler on code that uses `LitElement`, I get the error `The class in an extends clause must be a qualified name`. It looks like this is a known issue for Closure: https://github.com/google/closure-compiler/issues/2650 but unclear if/when they are planning to address it.

**Comment by joncass** [comment]
Hey @sorvell et al - any updates on this? Thanks!

**Comment by TimvdLippe** [comment]
Cross-posting from #93: this appears to be a limitation of Closure https://github.com/google/closure-compiler/issues/1876#issuecomment-231138616

**Comment by TimvdLippe** [comment]
Closing this per the above comment. Sadly we are not able to fix this issue 😢
