### ISSUE TITLE
lit-html/lit-element overwrites `input.value` with old/incorrect values in Firefox in some cases

### ISSUE THREAD

**Issue by TehShrike** [Polymer/lit-element#807]
This bug occurs in Firefox.  The bug does not occur in Chrome.

A full demo with reproduction steps is at https://codepen.io/TehShrike/pen/vYBrZeb

It boils down to this snippet:

```js
class Foo extends LitElement {
  render() {
    return html`
      <input
        type=time
        value="00:00"
        @input=${this.onInput}
      />
    `
  }
  
  onInput(event) {
	// do stuff
  }
}
```

To reproduce: set focus on the hour portion of the time input.  Press two reasonable digit keys (e.g. 0 then 4, or 1 and then 1).

Expected behavior: the `onInput` callback should be called twice – one for each keypress.

Observed behavior: the `onInput` callback is only called for the first keypress.

You can verify that Firefox does actually fire two events by trying [this vanilla js equivalent](https://codepen.io/TehShrike/pen/NWKzgYx).

Reproduced with lit-element@2.2.1

**Comment by TehShrike** [comment]
Can anyone point me to a unit test that I could use as the basis for a new failing test?  This bug seems pretty serious, and makes lit-element/lit-html effectively broken for forms in Firefox

**Comment by TehShrike** [comment]
lit-html seems to actually be setting the `value` on the element back to a previous (incorrect) state.

**Comment by kylebuch8** [comment]
@TehShrike I'm not sure this is an issue with lit-element. I think it's an issue with web components and Firefox in general. Take a look at the demo I created and open it in Firefox.

https://stackblitz.com/edit/js-gbvehf

You'll notice the first two examples, a lit-element example and a vanilla web component example, work the exact same. The third example is not in a web component and works properly for some reason.

**Comment by TehShrike** [comment]
Well balls.  That's interesting.

More than that, it looks like it's only an issue in Firefox's shadow DOM – I tried a custom element without a shadow DOM and that behaved as expected too: https://stackblitz.com/edit/js-qt8zdm?file=index.js

Looks like it is an issue with Firefox.

**Comment by TehShrike** [comment]
I opened an issue in the Firefox issue tracker: https://bugzilla.mozilla.org/show_bug.cgi?id=1612202
