### ISSUE TITLE
LitElement does not render ligature

### ISSUE THREAD

**Issue by regnou** [Polymer/lit-element#809]
How to render ligature ? (the 'favorite' material icon does not appear)

  ```
render() {
    return html`
      <link
        rel="stylesheet"
        href="https://unpkg.com/-components-web@latest/dist/-components-web.min.css"
      />

      <link
        rel="stylesheet"
        href="https://.googleapis.com/?family=+Icons"
      />

      <button class="mdc-button">
        <i class="-icons mdc-button__icon" aria-hidden="true">favorite</i>
        <span class="mdc-button__label">Button</span>
      </button>
```

**Comment by danielbarion** [comment]
Hey @regnou, 

Take a look in this project in my github:

https://github.com/danielbarion/instruct-contacts/blob/master/src/components/top-bar/index.js

The demo: https://friendly-bose-005e60.netlify.com/

**Comment by danielbarion** [comment]
Hi @regnou, solved ? This issue can be closed ?
@sorvell, @justinfagnani, @arthurevans

**Comment by rotemgrim** [comment]
> Hey @regnou,
> 
> Take a look in this project in my github:
> 
> https://github.com/danielbarion/instruct-contacts/blob/master/src/components/top-bar/index.js
> 
> The demo: https://friendly-bose-005e60.netlify.com/

Hi @danielbarion ,
I have the same problem as @regnou - material icons wont show inside shadow dom.
I duplicated what you did in your project but still, it doesn't work:
[https://stackblitz.com/edit/typescript-xgh95b](see example here)

when I add:
`createRenderRoot() {
   return this;
}
`
It dose work. can you explain why its not working with shadow dom?

**Comment by rotemgrim** [comment]
OK I did a little digging, 
it turns out that Chrome is loading the @font-face (that should be global attribute) 
only once at first page load.

when we add the link:
`<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">`
to the lit-element Chrome does not load the @font-face again
and that's why we don't see the icon.

A quick workaround is to append the link both on the head section in index.html 
and in the lit-element.

[example that don't work](https://stackblitz.com/edit/typescript-xgh95b)
[example that work](https://stackblitz.com/edit/typescript-2blvnd)
The difference is the added link in index.html head section.

**Comment by chase-moskal** [comment]
just curious here, i'm clearly missing a lot here-- what is "ligature"?

and also, why are all of OP's links broken or invalid? eg

- https://unpkg.com/-components-web@latest/dist/-components-web.min.css
- https://.googleapis.com/?family=+Icons

i can't imagine any such example working under any circumstances, not without some scary magic anyways

**Comment by rotemgrim** [comment]
> just curious here, i'm clearly missing a lot here-- what is "ligature"? css `font-variant-ligatures`, right? is the problem that font ligatures aren't rendering as expected, or that a "material icon does not appear"?
> 
> and also, why are all of OP's links broken or invalid? eg
> 
> * https://unpkg.com/-components-web@latest/dist/-components-web.min.css
> * https://.googleapis.com/?family=+Icons
> 
> i can't imagine any such example working under any circumstances, not without some scary magic anyways

hey @chase-moskal , 
the problem I encounter was that material icons won't appear and it looked like the "font-variant-ligatures" property is not taking effect.

LOL Now that I look on @regnou example it really shouldn't work...
but I jumped straight to @danielbarion example that didn't work for me.

**Comment by danielbarion** [comment]
I did some tests into your broken example, but no success until now...

Maybe my build process with rollup is fixing this?

**Comment by justinfagnani** [comment]
I think this is either a difference in how Chrome and Safari handle `@font-face`, or just a bug in Chrome. LitElement doesn't do anything with `<link>` tags, so it's not a bug here. We'll dig up the right Chrome bug.

**Comment by sorvell** [comment]
Unfortunately, this is a long standing [Chrome bug](https://bugs.chromium.org/p/chromium/issues/detail?id=336876). It looks like it also does not currently work on FireFox, but it does work on Safari.

This is not a LitElement issue, but it is pretty annoying. Our current recommendation is to place the font stylesheet in the main document as has been suggested above.
