### ISSUE TITLE
Slotted content inside a <p>

### ISSUE THREAD

**Issue by pshihn** [Polymer/lit-element#814]
This is not lit-element specific per say, but general web components - but people here would be most suitable to answer this.

Issue:  Slotted content doesn't get slotted when the custom element is inside a <p> element
See live here: https://codesandbox.io/embed/static-dvd6u

Works:
```html
<div>
  <my-element>
    <div class="caption">Red box</div>
  </my-element>
</div>
```

Doesn't work:
```html
<p>
  <my-element>
    <div class="caption">Red box</div>
  </my-element>
</p>
```

I know `<p>` is treated specially by the HTML parser. So is this a bug in the spec or the browser implementation? (Both firefox and Chrome behave the same)
Perhaps this is as designed?

**Comment by pshihn** [comment]
Seems like the issue is related to the slotted element being a `block`. 
If I use an inline element, then it works as expected.  
Also note that `my-element` itself is a `block` - although it may not have been rendered as such when the `<p>` tag was parsed 

```html
<p>
  <my-element>
    <span class="caption">Red box</span>
  </my-element>
</p>
```

**Comment by pshihn** [comment]
"Paragraphs are block-level elements, and notably will automatically close if another block-level element is parsed before the closing </p> tag."
But i'm not sure this is the right behavior... will file an issue is W3c/web components

**Comment by justinfagnani** [comment]
This is the correct behavior. Unknown elements are inline, so that's allowed, but when the first  block element is hit, it closes the nearest `<p>`. So what you should see in devtools is:

```html
<p>
  <my-element></my-element>
</p>
<div class="caption">Red box</div>
```

I'm not sure if there's a way to wrap a block element in something that'll not close the `<p>`. Note, that that this should happen during parsing. Direct DOM construction of this is fine.

**Comment by pshihn** [comment]
Yep, agree this happens when parsing.
If `my-element` is registered inline before the HTML is parsed and the :host is set to `display: inline-block` even then this will happen because CSS has not parsed yet. 

Even if the DOM parsed to the following, it would be fine: 
```html
<p>
</p>
<my-element>
  <div class="caption">Red box</div>
</my-element>
```

I think this is an annoying limitation - not being able to declaratively add custom elements in a `<p>` -> which is very common. Imagine adding a custom image or video player web component in a paragraph (akin to `<img>` and `<video>` which are inline by default). If it happens to use slots, it won't work. :(

**Comment by pshihn** [comment]
Closing this issue in favor of the issue here: https://github.com/w3c/webcomponents/issues/841
