### ISSUE TITLE
Wrong slot position

### ISSUE THREAD

**Issue by bilogic** [Polymer/lit-element#818]
My HTML as follows

```
 <column-matcher>
	<column-row name="Date" value="19/19/19"></column-row>
	<column-row name="Date" value="19/19/19"></column-row>
	...
 <column-matcher>
```

My ```column-matcher.js``` returns a HTML of
```
<fieldset>
	<legend>
		Statement Lines
	</legend>
	<table class="data statementMapping">
		<thead>
			<tr>
				<td colspan="2">Statement data...</td>
				<td class="no-border">Assign to...</td>
			</tr>
		</thead>
		<tbody id="mappingData">
			<slot></slot>
		</tbody>
	</table>
</fieldset>
```

For whatever reason, the ```column-rows``` appear right after ```</legend>``` instead of before ```</tbody>```. Bug?

**Comment by bilogic** [comment]
I found the issue. Browse will move ```<slot></slot>``` out as they are not allowed inside a ```<table>```.

**Comment by jsilvermist** [comment]
You can use divs with `display: table;` and etc to achieve this the way you're trying to.
