### ISSUE TITLE
Boolean prop doesn't work as expected

### ISSUE THREAD

**Issue by lufego** [Polymer/lit-element#819]
### Description

Boolean prop doesn't work as expected

#### Steps to Reproduce
```html
<image-container prop3="false" />
```

```js
import { LitElement, html, customElement, property } from 'lit-element';

@customElement('image-container')
export class ImageContainer extends LitElement {
  @property({type : Boolean}) prop3 = false;

  render() {
    return html`
      <p>prop3: ${!!this.prop3}</p> // This outputs TRUE
    `;
  }
}

```

#### Expected Results
Output is actually the value passed in the prop and not wether the prop is passed or not

#### Actual Results
It doesn't care about the prop value. It only considers if the prop is passed or not

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari 11
- [ ] Safari 10
- [x] IE 11

### Versions

- lit-element: v2.2.1

**Comment by web-padawan** [comment]
Try using `.prop3="${false}"` syntax if you need to pass `false` as boolean value.

Currently you are trying to pass `prop3="false"` which sets a string to an attribute.

**Comment by lufego** [comment]
using 

```js
<image-container .prop3="${false}" />
```

throws an `Unexpected token` error since it's not valid html

**Comment by web-padawan** [comment]
That snippet which I mentioned will work in lit-html template.

Generally, in HTML the absence of attribute means "false". If the attribute is set, it means "true" regardless of the value.

**Comment by lufego** [comment]
Thank you!
