### ISSUE TITLE
Asynchronous call not working 

### ISSUE THREAD

**Issue by boluabraham** [Polymer/lit-element#831]
### Description
I am quite new in the use of lit-element. I came across an element written in previous versions of polymer, I upgraded the version and edited the code but it seems that I am missing something. Any assistance will be appreciated

#### Live Demo
https://stackblitz.com/edit/lit-element-example

### Browsers Affected

- . Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

### Versions

- lit-element: v2.0.0
- webcomponents: v2.2.3

**Comment by jordanaustin** [comment]
Hi there 👋 welcome to the lit community :). Looking at this example, everything seems to be working on my end, what's not working for you?

**Comment by web-padawan** [comment]
That's just a default example. Author did not provide any actual example.

I guess author needs either `Polymer.Async.microTask.run` (P2) or even `this.async` (P1) 🤔 
Anyways, there is nothing like that implemented in `lit-element`.

**Comment by sorvell** [comment]
We'll need more information about the actual issue to help. Closing this due to age. Please re-open with more info if needed, see https://github.com/Polymer/lit-element/blob/master/CONTRIBUTING.md#filing-bugs.
