### ISSUE TITLE
Make lit-element run natively in a node environment (i.e. Electron)

### ISSUE THREAD

**Issue by jarodburchill** [Polymer/lit-element#844]
Hello,

From what I can tell, currently, one cannot natively use lit-element by requiring it in a node environment like electron.

One workaround that I have seen used is adding [esm](https://www.npmjs.com/package/esm) to an electron app to use lit-element. 

However, I am wondering if native node environment support would be something this project would ever consider or if there is a standard way you might suggest to do something like this?

Thanks!

**Comment by justinfagnani** [comment]
Node 13.2 and greater support standard JS modules now. If Electron is updated to a recent version of Node, that should just work. Otherwise LitElement can be bundled with Rollup.
