### ISSUE TITLE
Export the `lit-html` directives through `lit-element`

### ISSUE THREAD

**Issue by gerarts** [Polymer/lit-element#846]
Would it be possible to export the set of directives from `lit-html` in [`lit-element.ts`](https://github.com/Polymer/lit-element/blob/master/src/lit-element.ts)?

At the moment users have to either add `lit-html` as a separate dependency (which can cause some duplication issues in bundles which can break the way the directives are supposed to work) or import directives by fishing them out of `lit-element`'s dependencies like this:

```typescript
import { ifDefined } from 'lit-element/node_modules/lit-html/directives/if-defined';
```

**Comment by gerarts** [comment]
I've created a PR with *a* solution. I could imagine that some people would prefer these to live somewhere else like `lit-element/directives` or have each one of them exported though their own file like `lit-element/directives/if-defined` for project-structuring or tree-shaking reasons.

**Comment by web-padawan** [comment]
As mentioned in https://github.com/Polymer/lit-element/issues/430#issuecomment-453508564 and previously discussed in the other issues, directives should be imported from `lit-html`. IMO it doesn't make sense to re-export them here.

Maintaining that kind of code would be just extra boilerplate, i.e. after the animation directives are added to `lit-html` we would have to add more changes to `lit-element`, etc.

**Comment by gerarts** [comment]
I've noticed users will think up their own way to do this, though. Some will add `lit-html` as a standalone dependency, some will import through `lit-element/node_modules/...` etc.

I agree that unnecessary boilerplate should be avoided, but maybe a recommended way to use directives in 'lit-element` should be added to the documentation.

Users shouldn't really have to add `lit-html` with its own version as a dependency when using `lit-element` because `lit-element` should dictate which version of `lit-html` a developer is using in the project. When deduplication is not setup correctly in a project `lit-html`'s directives will straight up not work because `lit-element`'s `instanceof` sees them as different objects.

I feel like there's an opportunity to encourage better code-quality here.

**Comment by web-padawan** [comment]
> Users shouldn't really have to add lit-html with its own version as a dependency when using lit-element because lit-element should dictate which version of lit-html a developer is using in the project.

`lit-html` is already a true dependency of `lit-element`. The correct version range is:

```
"lit-element": "^2.0.0",
"lit-html": "^1.0.0" 
```

I agree it makes sense to mention that somewhere in the docs.

**Comment by gerarts** [comment]
It gets mentioned [here](https://lit-element.polymer-project.org/guide/templates#using-other-lit-html-features) but I'm noticing that `npm` will replace the `^1.0.0` in some cases with `1.1.2`. The annoying thing about this is that is usually doesn't break the project immediately but later when one of the two updates at some point and a version-mismatch is caused. But I guess that's more a problem with these projects and not with `lit-element`.

I agree that leaving it as it is now is probably the most elegant solution.

What do you think about logging a warning when a non-directive function is passed as an attribute that is not a property or event-handler? I can't really think of a good reason to pass a function to an attribute that gets serialised to a string anyway. Maybe a direct reference to somewhere in the documentation. Because this is either a developer trying to pass a function as a property or handler but that forgot to add the period or `@`, or a directive that got detached because of some duplicate dependency issue.

Or is this outside of the scope of "help" you want `lit-element` / `lit-html` to provide?

**Comment by web-padawan** [comment]
> The annoying thing about this is that is usually doesn't break the project immediately but later when one of the two updates at some point and a version-mismatch is caused.

Please see https://github.com/Polymer/lit-element/issues/682#issuecomment-530972808 for an answer from the maintainer entitled to make such decisions.

**Comment by gerarts** [comment]
Yes, I agree. Thats why:

> I agree that leaving it as it is now is probably the most elegant solution.

But I still see this break for some of our developers and a bit more information about _why is my directive suddenly stringifying itself_ would probably help some people. So what are your thoughts about:

> What do you think about logging a warning when a non-directive function is passed as an attribute that is not a property or event-handler? I can't really think of a good reason to pass a function to an attribute that gets serialised to a string anyway. Maybe a direct reference to somewhere in the documentation. Because this is either a developer trying to pass a function as a property or handler but that forgot to add the period or `@`, or a directive that got detached because of some duplicate dependency issue.
> 
> Or is this outside of the scope of "help" you want `lit-element` / `lit-html` to provide?

**Comment by web-padawan** [comment]
> logging a warning when a non-directive function is passed as an attribute that is not a property or event-handler?

Seems like a use case for [lit-analyzer](https://github.com/runem/lit-analyzer), so feel free to submit an issue there.

**Comment by justinfagnani** [comment]
Directives are separate modules so that they don't load if you don't use them. We don't export them out of the main lit-html module and won't export them out of the main lit-element module either.

Ensuring that modules that lit-html directives and TemplateResults use the same copy of lit-html is important for a number reasons. Re-exporting directives won't solve that on its own. Right now the recommendation is to make sure you have compatible lit-html dependency constraints, ideally as wide as possible, and run `npm dedupe`.
