### ISSUE TITLE
Deno?

### ISSUE THREAD

**Issue by askbeka** [Polymer/lit-element#85]
I will live it here to start discussion. https://github.com/ry/deno

**Comment by LarsDenBakker** [comment]
What does that have to do with lit-element?

**Comment by askbeka** [comment]
@LarsDenBakker At first glance, it states that it is going to be browser compatible, including imports, that might open more doors for this project and others, solving main problems Polymer project had when deciding to move to npm. But it is not clear yet what package management will look like, seems like there is no one yet:) I wanted to know what polymer teem thinks about this, since whole project is about future of the web, deno looks like a future:)

**Comment by TimvdLippe** [comment]
@askbeka We are following the process, but I do not think we have any actionable item regarding that just yet. Feel free to follow the progress on Deno and notify us if any major changes happen (although I imagine we will be notified via social media anyways)
