### ISSUE TITLE
styles doesnt load if .select:before{content: '\hex' }

### ISSUE THREAD

**Issue by mnts** [Polymer/lit-element#858]
so if I try to add content: html entity with \ symbol , style returns empty..

**Comment by web-padawan** [comment]
Duplicate of #637.

As mentioned in that issue, you need to escape the backslash, e.g. `content:"\\2014"`

**Comment by kevinpschaaf** [comment]
Closing as dup of #637 (which is still open to track fixing docs around the need to escape strings in JS).
