### ISSUE TITLE
Nested slots

### ISSUE THREAD

**Issue by flyweight** [Polymer/lit-element#862]
My use case needs elements included from light dom, is it possible to pass nested slots in such as:

#### index.html
```
<my-app>
  <p slot="title"></p>
</my-app>
```

#### my-app.html
```
<page-one></page-one>
<page-two><slot name="title" slot="title"></slot></page-two>
```

**Comment by Westbrook** [comment]
100%, just like this: https://stackblitz.com/edit/nested-slots?file=index.ts

Good luck with the rest of your project!

**Comment by flyweight** [comment]
@Westbrook Perfect.  Thanks for the fast and helpful response.

**Comment by barroudjo** [comment]
Can you avoid giving it a name when nesting a slot ?
