### ISSUE TITLE
Bare imports in LitElement

### ISSUE THREAD

**Issue by antonioaltamura** [Polymer/lit-element#871]
Hello,
maybe this is not the best place for asking this, but there are no other places.
I'm wondering why the LitElement uses bare imports in its source and force us to use Polymer CLI or a bundler (or pika).
I cannot see the point of this design decision, I would be glad to learn the reason behind.

**Comment by justinfagnani** [comment]
There is no other viable way for LitElement to import lit-html. WIth npm there's no guarantee where lit-html will be installed to, so there's no relative or absolute path we could use. Most tools do not deal well with cross-package paths either.

Bare specifiers on the other hand are well supported in most tools. You can use the Polymer CLI, but also other tools like `es-dev-server`, Webpack, Parcel, Rollup with `rollup-plugin-node-resolve`, unpkg.com, Pika, and more.

**Comment by antonioaltamura** [comment]
Thanks for the answer. I'm not totally sure I'm persuaded on the npm argument: npm has a unique root, the only thing a user can do is to change the root, and in this case this would be valid for all the packages, preserving the cross-package paths in any case. Also, manually changing/renaming the dir of single modules makes no sense.
What am I missing?

**Comment by LarsDenBakker** [comment]
`lit-element` would need to import `lit-html` from it's modules directory like so: `./node_modules/lit-html/lit-html.js`. 

When someone then installs `lit-element`, `lit-html` is no longer installed at that location. It's actually at `../lit-html/lit-html.js` relative from `lit-element.js`. 

`npm` does not guarantee the location of modules, not the name of the module folder. importing by package name is how npm works, for better or worse. There is a proposal for implementing this in the browser too: https://github.com/WICG/import-maps it's implemented in chrome behind a flag. With https://github.com/guybedford/es-module-shims you can use import maps on any browser that supports modules.

**Comment by antonioaltamura** [comment]
Thanks for the answer. I partially see your point.

> `lit-element` would need to import `lit-html`. 

Wouldn't be easier to provide a complete bundle or install `lit-html` in `./node_modules/lit-element/node_modules`?
Npm used to install package deps in a specific `node_modules` directory inside the package itself once, if I'm not wrong.

**Comment by LarsDenBakker** [comment]
That will not work when you have other dependencies that need `lit-html` as well. And besides `lit-html` and `lit-element`, this problem will apply to other types of packages as well. For example `lit-element` itself is a shared dependency of many web components you might use in an application. 

All things considered bare imports are the best solution right now, and they might be the standard solution in the future. For now with a small transformation step we get pretty close to build free development

**Comment by antonioaltamura** [comment]
Actually, re-reading your previous message:

> lit-element would need to import lit-html from it's modules directory like so: ./node_modules/lit-html/lit-html.js.

correct. But, again, wouldn't be easier for the user to provide a "production build" when all the paths are relative to the `node_modules` directory of the project of the user? You keep discriminating 2 use cases, but actually here there is just one real use case, the case the user uses lit-element as a dependency of his own project, am I wrong?

**Comment by web-padawan** [comment]
> the case the user uses lit-element as a dependency of his own project.

It doesn't make sense to bundle `lit-html` with `lit-element` because it does not re-export everything from `lit-html`. This would actually harm more than help as already mentioned.
As an example, directives have to be imported separately and that's intentional.

This is not an issue, this is how npm works. The bare imports have been discussed many times.
Please see https://github.com/Polymer/polymer/issues/5411#issuecomment-477364441 for explanation by the Polymer team.

**Comment by justinfagnani** [comment]
Closing this since we're definitely keeping the bare imports.
