### ISSUE TITLE
TypeScript: LitElement.render returns TemplateResult | void

### ISSUE THREAD

**Issue by mgenware** [Polymer/lit-element#874]
### Description
`LitElement.render` returns`TemplateResult|void`, which makes it look less type safe for typescript users.

Source code of `lit-element.ts`:
```ts
  /**
   * Invoked on each update to perform rendering tasks. This method must return
   * a lit-html TemplateResult. Setting properties inside this method will *not*
   * trigger the element to update.
   */
  protected render(): TemplateResult|void {
  }
```

Wondering if it's possible to make it an abstract function with only `TemplateResult` as return type, 

#### Steps to Reproduce
```ts
render() {
  if (this.prop) {
    return html`<p></p>`;
  }
}
```

#### Expected Results
TypeScript compile error.

#### Actual Results
Compiles fine on strict mode.

### Versions
- lit-element: v2.2.1

**Comment by chase-moskal** [comment]
does it make sense in some cases, for a component to return `null` or `undefined`, to indicate that nothing should be rendered?

**Comment by CaptainCodeman** [comment]
There's already a `shouldUpdate` method that will prevent rendering

**Comment by mgenware** [comment]
lit-element [docs](https://lit-element.polymer-project.org/guide/lifecycle#render) says:
> `render` Returns | TemplateResult | Must return a lit-html TemplateResult.

lit-html [docs](https://lit-html.polymer-project.org/guide/writing-templates#conditional-templates) says:
> The DOM is inconsistent in some cases with its behavior towards undefined & null. Using an empty string ('') is the most consistent.

From my experience with TypeScript, returning an empty string resulted in compile error:
```
Type '() => TemplateResult | ""' is not assignable to type '() => void | TemplateResult'.
```

And not returning anything (equal to returning `undefined` in JS) results in bugs where property changes don't trigger a re-render.

I usually do this to return an empty thing, and it works:
```ts
return html``;
```

**Comment by justinfagnani** [comment]
`render()` can really return any type of value. We've had a bug around that though, but it was just fixed in https://github.com/Polymer/lit-element/pull/712. That updates the return type too. We'll have with this woon.
