### ISSUE TITLE
Lit Element indentation issue for VSCode

### ISSUE THREAD

**Issue by tvvignesh** [Polymer/lit-element#875]
Hi. I am using Lit-Element with Typescript, ESLint and IONIC in VSCode and my indentation is getting always messed up difficult to make sense of (Screenshot below). Any way to actually make the alignment more neat?

If I use prettier, things are getting messed up even more. It works well for Node.js but messed up alignment and indentation when using LitElement.

![Screenshot from 2020-01-14 19-02-25](https://user-images.githubusercontent.com/1165845/72348606-c6058680-3700-11ea-80bb-b48265c717b2.png)

**PS:** I am using many IONIC 4 components within Lit Element. Hence you see ion all over.

**Comment by justinfagnani** [comment]
This is really an issue for the code formatters. Can you file issues there? I know Prettier has done work to try to make expressions inside template literals better in the past.
