### ISSUE TITLE
Suggested way to render dynamic/generic elements

### ISSUE THREAD

**Issue by orielmaute** [Polymer/lit-element#88]
Our user interface can be configured by the end-user at runtime. Therefore we have a meta model that describes the user interface. At low-level this metamodel has javascript objects e.g. like `{ tag: "button", textContent: "Login", disabled: true }` to represent a single html element.

We are looking for a way to render these objects in an elegant way with lit-element. Currently we tried the following:
<pre>
class GenericElem extends LitElement {

  static get properties() { return {
    data: Object,
  }}

  _render({data}) {    
    if (data) {
      switch (data.tag) {
        case "button": return html `&ltbutton disabled=${data.disabled}&gt${data.textContent}&lt/button&gt`;
        case "input": return html `&ltinput&gt${data.textContent}&lt/input&gt`;
        ...
      }
    } 
    
  }
}
</pre>

We are looking for a better approach; without a switch-statement for every possible element (data.tag). 
Any suggestions? Is there a way to make the element name (button, input) dynamic in the template?
Maybe another try would be to create the element in _didRender(props, changedProps, prevProps) via document.createElement(data.tag) and attach it to the shadowRoot, but what if the elements has children itself (recursive), e.g.
{ tag: "p", textContent: "Welcome", children: [{ tag: "button", textContent: "Login", disabled: true }]}

Any suggestions?

**Comment by eskan** [comment]
hi,
you can use hidden.
```
  _render({data}) {    
      return html `<button hidden?=${!data.button} disabled=${data.disabled}>${data.textContent}</button><input hidden?=${!data.input}>${data.textContent}</input>`;
 }
```

**Comment by LarsDenBakker** [comment]
If you want to get really dynamic, and if you can trust the source that your data comes from, you can just construct the HTML yourself and use unsafeHTML. This tells lit-html that you know what you're doing:

```
const data = { tag: "button", textContent: "Login", disabled: true };

const html = unsafeHTML`
  <${data.tag} ${data.disabled ? 'disabled' : ''}>${data.textContent}</${data.tag>
`;
```

See: https://github.com/LarsDenBakker/lit-html-examples/blob/master/src/3-advanced/07-external-template.js for more

**Comment by sorvell** [comment]
You should be able to parameterize element names when static directive lands in lit-html. Here's the [reference issue](https://github.com/Polymer/lit-html/issues/78). 

Work on this feature is underway in lit-html, and until it lands the technique you're using is not unreasonable.

**Comment by sorvell** [comment]
Based on the previous comment, closing this issue in favor of https://github.com/Polymer/lit-html/issues/78.

**Comment by textheader** [comment]
https://hypertexter.space/questions/dynamic-html-dom-element-name-changes

**Comment by justinfagnani** [comment]
@textheader I really hope you're not getting into the business of spamming GitHub issues with generative AI answers, as it seems like you might be doing with that site and your initial comments on GitHub.
