### ISSUE TITLE
Using Captcha within lit-elements

### ISSUE THREAD

**Issue by tvvignesh** [Polymer/lit-element#880]
Hi. When I try to use Google Recaptcha V2 inside a lit-element component, I get error saying:
```
Uncaught DOMException: Blocked a frame with origin “https://www.google.com" from accessing a cross-origin frame.
```
While I found some references for React:
https://medium.com/@tomas_26986/using-recaptcha-with-react-and-shadow-dom-abfd19fa03a

And also some discussions here for Polymer:
https://github.com/cbalit/re-captcha/issues/6

Any guidance to do this for lit-elements

Thanks.

**Comment by justinfagnani** [comment]
I asked the reCAPTCHA team about this and filed an internal bug. They'll get back on feasibility. Until then, this isn't a LitElement specific issue. I think you'll have to create an element in the main document and attach reCAPTCHA to that. Thanks for the heads up!
