### ISSUE TITLE
es5 transpiling for component library

### ISSUE THREAD

**Issue by lsimone** [Polymer/lit-element#883]
We are trying to build a component library with es5 as target transpilation.

If I do not transpile `lit-element`, it will not work for older browsers.
While if I do it through babel/webpack (@babel/preset-env preset), `lit-element` will throw at the beginning the error (in the screenshot) that I tried to solve through [babel-plugin-transform-custom-element-classes](https://github.com/github/babel-plugin-transform-custom-element-classes) without luck.
I also tried other approaches but maybe I am missing the point or it's just not feasible.

Is there a way to bundle haunted together with components and authoring such a library?
Do you have any suggestion?

_P.s: I tried to use polymer slack for this question as suggested, but I cannot enter since I have no invitation._

![image](https://user-images.githubusercontent.com/3266650/72929438-1f516380-3d5a-11ea-98c9-d210247b6c25.png)

**Comment by web-padawan** [comment]
There are several options that you could choose from:

1. use [`@wecomponents/webcomponentsjs/custom-elements-es5-adapter.js`](https://github.com/webcomponents/polyfills/blob/78c69a568de9a75adaf599b1146ead5787956a36/packages/webcomponentsjs/README.md#custom-elements-es5-adapterjs) to make custom elements work when transpiled to ES5 (see the link where it is explained in more detail)

2. use [webpack-babel-multi-target-plugin](https://github.com/DanielSchaffer/webpack-babel-multi-target-plugin) for differential serving, to build ES5 bundle for legacy browsers (IE11), and ES module bundle for modern browsers. Then you don't need an adapter.

**Comment by justinfagnani** [comment]
Yes, ` @webcomponents/webcomponentsjs/custom-elements-es5-adapter.js` is required if you compile custom elements to ES5. Be sure to load it in a document-level script tag, don't import it from a module into your component.

We should mention this more clearly in the docs. cc @arthurevans

**Comment by arthurevans** [comment]
Also @lsimone did you try the slack invite link from our footer? (https://www.polymer-project.org/slack-invite) As far as I can tell, this should still work fine.

**Comment by lsimone** [comment]
> There are several options that you could choose from:
> 
> 1. use [`@webcomponents/webcomponentsjs/custom-elements-es5-adapter.js`](https://github.com/webcomponents/polyfills/blob/78c69a568de9a75adaf599b1146ead5787956a36/packages/webcomponentsjs/README.md#custom-elements-es5-adapterjs) to make custom elements work when transpiled to ES5 (see the link where it is explained in more detail)

Thanks @web-padawan , I tried this approach but it seems it does not work as expected:

```javascript
const loadShim = () => new Promise((resolve, reject) => {
  let docHead = document.getElementsByTagName('head')[0]
  let script = document.createElement('script')
  script.type = 'text/javascript'
  script.src = 'https://cdnjs.cloudflare.com/ajax/libs/webcomponentsjs/2.4.1/custom-elements-es5-adapter.js'
  script.onload = resolve
  docHead.appendChild(script)
})

loadShim().then(() => {
  console.warn('Shim loaded')
  require('lib/userProfile.js')
})
```

This still results in a `Uncaught TypeError: Class constructor LitElement cannot be invoked without 'new' at new UserProfile (index.js:44)`.

Any similar issue encountered? What I am missing about the adapter?

_If I just don't transpile `lit-element` from node modules when I bundle my library component and don't load the shim, the web component works (but it's not es5 compatible)._

**Comment by web-padawan** [comment]
@lsimone please keep in mind that Babel doesn't transpile node_modules by default so you need to take care of  including `lit-html` and `lit-element` to `babel-loader` like this:

```js
  rules: [
    {
      test: /\.js$/,
      loader: 'babel-loader',
      exclude: /node_modules\/(?!(lit-element|lit-html)\/).*/,
      options: {
        cacheDirectory: true
      }
    }
  ]
```

**Comment by web-padawan** [comment]
So we discussed this in person and now I remember that there are 2 things to keep in mind:

1. Babel config **MUST** be in `babel.config.js` and NOT `.babelrc` to transpile node_modules
2. You need `@babel/plugin-transform-runtime` because of `for .. of` loops in LitElement.

This is how the working config might look like:

```js
module.exports = {
  presets: [
    [
      "@babel/preset-env",
      {
        modules: false,
        targets: {
          ie: 11
        }
      }
    ]
  ],
  plugins: [
    [
      "@babel/plugin-transform-runtime",
      {
        regenerator: true
      }
    ]
  ]
};
```

/cc @arthurevans we should add this to the docs. I can contribute to that, and maybe write down an entire ES5 transpilation guide. Please let me know where you want it to be placed.

**Comment by lsimone** [comment]
Thanks @web-padawan , great!
After this you mention, I had to add an import to make it work on IE11 too:
```
import '@webcomponents/webcomponentsjs/webcomponents-bundle.js'
```

**Comment by justinfagnani** [comment]
You really should not import the shim. Put it in a script tag in the document, and in the HTML. The shim needs to be a blocking script so it can patch HTMLElement before any definitions are loaded.

**Comment by lsimone** [comment]
@justinfagnani if you are referring to the import I just mentioned, it's loaded before anything in my entry module, that's why it's working

**Comment by arthurevans** [comment]
@web-padawan Thanks! I was working on related stuff last week, but I had some other things come up. I will tag you when I have something to review.

**Comment by arthurevans** [comment]
@web-padawan I tried building using a config like you showed in https://github.com/Polymer/lit-element/issues/883#issuecomment-577651183, and I couldn't get it to work. As far as I could tell, this results in the Babel runtime helpers/polyfills getting added into the app bundle.

To get my code working on IE11, I configured rollup to create two bundles: one the ES5-compiled version of my code, and the other, the Babel polyfills (CoreJS+regenerator runtime libraries). Then I modified to load order to be:

- Babel polyfills
- web components polyfills
- my code

That seemed to work for me, but it ends up importing the entire CoreJS and regenerator runtime libraries, whereas the single bundle built with `plugin-transform-runtime` theoretically only imports the features you need. Wish I could figure out a way to get Babel to do the treeshaking, but then export two separate files.

**Comment by infoanishgarg** [comment]
Element.ts:34 Uncaught TypeError: Class constructor s cannot be invoked without 'new'

I am also getting this issue for ES5

**Comment by justinfagnani** [comment]
@infoanishgarg please use the https://github.com/lit/lit monorepo for issues.
