### ISSUE TITLE
Need urgent help with IE support, packaging and styling

### ISSUE THREAD

**Issue by Chibionos** [Polymer/lit-element#885]
First off I love what you guys have done with Lit-element it is a more approachable form of web component development that I am enjoying.

I am not able to export a Lit Element for use in IE. I have looked for various to do it with no proper direction. The project needs IE support and we are building controls that are used on React and Angular. 

I have looked into this repo https://github.com/phetw/awesome-panel for inspirations and got ES5 build out that works in IE but I hit an issue with CSS. Is there any documentation that explains how we can get a lit element packaged properly so that it works for IE ?

The example uses hosted here: https://condescending-curie-01f040.netlify.com/
uses ShadyCSS to get the styling done, I am not sure how I can accomplish what ShadyCSS after I package the component.

We bet a lot on the IE support as your website says it is supported we need help moving forward. 

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [x] IE 11

**Comment by kevinpschaaf** [comment]
Thanks for raising this.  We're tracking the TS issue and will attempt to help getting this resolved.

**Comment by sorvell** [comment]
The `Build for Production` section of the [Use a component](https://lit-element.polymer-project.org/guide/use) section of the docs is probably useful here.

It seems like you have the bundling issue worked out other than ShadyCSS. We wouldn't recommend bundling ShadyCSS directly with your components. Instead, it should be loaded separately. This is for the same reason we don't generally bundle individual components: it leads to lots of code duplication if multiple components are loaded.

That said, if you have a use case where you're sharing a bunch of components and want to make a single bundle of absolutely everything, you should be able to just include ShadyCSS with that and things should work ok.

Closing this issue based on this recommendation, but please feel free to re-open it with a more specific question if you need more information.
