### ISSUE TITLE
Documentation on accessing elements in the template

### ISSUE THREAD

**Issue by nicolasr75** [Polymer/lit-element#886]
I know that shadowRoot is DOM standard but it may increase acceptance if you add some notes about accessing elements in the template to the documentation. I was converting a Polymer app to lit-element and got stuck at the following line:

`this.$.myDialog.open()`

It took me a while to find out that there is shadowRoot in the DOM which would allow me the following:

`this.shadowRoot.getElementById("myDialog").open();`

I found a line like this in an anti-pattern example in the templates chapter. But in this case I am not setting a property but calling a method of a Polymer paper-dialog. I hope this makes sense?

**Comment by web-padawan** [comment]
You can use `@query` decorator to get reference to the dialog. Seems like it lacks docs indeed.

**Comment by nicolasr75** [comment]
Btw the corresponding documentation in Polymer 3 is this:
https://polymer-library.polymer-project.org/3.0/docs/devguide/dom-template#node-finding

Not that easy to find too! The sections heading is _Static node map_. A better title would have been something like _Accessing elements in the shadow DOM_.

**Comment by abraham** [comment]
There is a basic example documented that hasn't been deployed to the doc site yet.

https://github.com/Polymer/lit-element/blob/master/src/lib/decorators.ts#L190-L209

**Comment by justinfagnani** [comment]
I think we need more than API docs here. There are parts of this that are relevant to the guide's template section, lifecycle, and decorators (which we don't have in the guide).
