### ISSUE TITLE
Add ability to override default converter and default getter/setter

### ISSUE THREAD

**Issue by bschlenk** [Polymer/lit-element#891]
### Description

It would be great if it were possible to override the [defaultConverter](https://github.com/Polymer/lit-element/blob/master/src/lib/updating-element.ts#L138) for attributes, and the [default getter/setter](https://github.com/Polymer/lit-element/blob/master/src/lib/updating-element.ts#L307-L320) for properties.

My team is converting our existing web components library over to lit-element. We made some not-so-great decisions in our components, but we want to keep the behavior for now for backwards compatibility reasons. The main bad decision is that we special case boolean attributes so that the string "false" is treated falsy (contrary to native boolean attributes which are a presence check). We also coerce properties, so setting a boolean property to the string "false" would convert it to boolean false. We have similar conversions for number, array, and object.

With the way lit is now, this means that every single boolean property requires us to set a custom converter, and we also need to define our own getter/setter. This is a *lot* of boiler plate for us, and really puts a damper on the development process. If we were able to override the defaultConverter & getters/setters, then we could simply subclass `LitElement`, override these to get our behavior, and that would be it.

**Comment by justinfagnani** [comment]
You can already override [`static createProperty()`](https://github.com/Polymer/lit-element/blob/41e9fd3b8c18b3070f9df2a2f21915b796b2b298/src/lib/updating-element.ts#L290) already to provide a different default property declaration, which can in turn use a different default property converter.

Overriding the accessor creation is harder right now because `state _ensureClassProperties()` and `static _classProperties` are private. We could potentially make them protected, or offer another static just for defining the property.

**Comment by bschlenk** [comment]
I tried overriding the `createProperty()` function but I couldn't get it to work. I basically copied the one you linked above into another class and modified the `get` and `set` in the `Object.defineProperty` call, but it didn't work. I don't remember what sort of errors I was getting though. I can try it again when I have time so I can give you some more detailed error messages. One issue with copying it is that it has to reference the private `_ensureClassProperties` and `_classProperties`. I'm also not all that sure about how polymorphism works with static methods on classes in js.

We've come up with a workaround for now, it's a function that we pass each class into that reads the existing static `properties` and for each one that is set to type `Boolean`, we do our own `Object.defineProperty` to create a getter and setter. We just need to remember to pass all our classes into this function before we call `customElements.define`.

**Comment by javier-garcia-meteologica** [comment]
Typescript complains when you override `createProperty` with a similarly specified function.

```
[tsserver 2341] [E] Property '_ensureClassProperties' is private and only accessible within class 'UpdatingElement'.
[tsserver 2341] [E] Property '_classProperties' is private and only accessible within class 'UpdatingElement'.
[tsserver 2341] [E] Property '_requestUpdate' is private and only accessible within class 'UpdatingElement'.
```

**Comment by sorvell** [comment]
Closing this issue in favor of #911 where we're tracking this issue.
