### ISSUE TITLE
Exceptions in `firstUpdated` are not logged to console

### ISSUE THREAD

**Issue by chooglen** [Polymer/lit-element#897]
### Description
In Chrome, exceptions thrown in `firstUpdated()` are reported differently from exceptions thrown in `render()`. There does not appear to be any difference in Safari.

In Chrome:
Thrown in `render()`:

![image](https://user-images.githubusercontent.com/58092771/74389197-4f68b100-4db2-11ea-8ba3-7484c68b90ca.png)

Thrown in `firstUpdated()`. This is only visible with "Verbose" logging enabled

![image](https://user-images.githubusercontent.com/58092771/74389251-76bf7e00-4db2-11ea-9618-de2aa1e26bdd.png)

#### Steps to Reproduce

```js
class MyElement extends LitElement {
//....
  firstUpdated() {
    // If we throw the error here, it only appears in the console if verbose logging is enabled
    throw new Error('Thrown from firstUpdated');
  }
  render() {
    // If we throw the error here, it appears in the console in red
    throw new Error('Thrown from render');
  }
}
```

#### Expected Results
Both errors should be logged to the console in red.

#### Actual Results
Only the `render()` error is logged in red. The `firstUpdated()` error is only shown when `Verbose` logging is enabled.

### Browsers Affected
- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

### Versions

- lit-element: v2.2.1
- webcomponents: v2.4.0

**Comment by sorvell** [comment]
Sorry for the delay on this. We're unable to repro this issue now, see https://output.jsbin.com/meramin.

Closing as this no longer seems to be a problem. Please feel free to re-open with more info if the problem persists.
