### ISSUE TITLE
Setting innerHTML leads to total meltdown

### ISSUE THREAD

**Issue by positlabs** [Polymer/lit-element#90]
I'm making a simple control panel with some sub-components (checkboxes, sliders, etc). In one of the components, I was clearing out the contents of the element by setting `this.innerHTML = ''` in the constructor. All seemed fine until I realized that it was doing some crazy stuff to all of the subsequent components. Strange things like id attribute being removed, click handlers not being assigned to the correct elements, and properties not being set.

It was really difficult to debug since the symptoms were seemingly random. I wonder if there is a way to `console.warn` people against doing this.

**Comment by TimvdLippe** [comment]
Could you post a JSBin of the issue you are seeing?

**Comment by positlabs** [comment]
I tried to reproduce in codepen, but it's working fine in that environment. Could it be an issue with webpack?

https://codepen.io/positlabs/pen/xzgpdz?editors=1010

**Comment by TimvdLippe** [comment]
It could be :( Unfortunately we are unable to debug and fix without a
reproducible case. It might be specific to your setup indeed.

**Comment by sorvell** [comment]
For safety, lit-html automatically escapes html in rendering. In your example, `innerHTML` is captured and rendered into the element via a lit template part. The html will be escaped.

Perhaps this is the problem?

If so, the `unsafeHTML` directive in lit-html can be used to render HTML. This should be done only with trusted HTML content. Here's your example updated to demonstrate this: https://codepen.io/sorvell/pen/KeqLPd?editors=1010

**Comment by positlabs** [comment]
@sorvell that's good to know, thanks! Maybe a better (safer) approach is to pop all of the initial child nodes into a document fragment, and use that? I'm curious about what the best option is for this. Seems like a use-case that would be fairly common.

However, the issue I had was with setting innerHTML in the constructor, not in the rendering of it. If I have some time I can try creating a more complete test case.

**Comment by sorvell** [comment]
The other thing to point out is that setting `this.innerHTML` on an element in its constructor should throw, per [spec](https://html.spec.whatwg.org/multipage/custom-elements.html#custom-element-conformance). It does this on Safari but not yet on Chrome. Closing based on the [previous response](https://github.com/Polymer/lit-element/issues/90#issuecomment-397111898).
