### ISSUE TITLE
lit-element 2.3.0 Release Plan

### ISSUE THREAD

**Issue by nicolejadeyee** [Polymer/lit-element#900]
# 2.3.0 Release Plan

Release Plan that outlines the focused tasks for lit-element 2.3.0.

[Milestone](https://github.com/Polymer/lit-html/milestone/14)

## Notable Changes
- Enhancements

- Bug Fixes

## Release Process
- [ ] [Run Google Internal Tests]()
- [ ] [1.2.0 Release Notes]()
- [ ] [Verify 2.3.0 CHANGELOG]()

**Comment by web-padawan** [comment]
@sorvell @justinfagnani any chance that you could publish `dev` or `RC` version first?

We have this pending PR waiting for new release: https://github.com/vaadin/component-mixins/pull/55
Pre-release tag would allow us to test `getStyles` API that will land in 2.3.0

**Comment by justinfagnani** [comment]
Yeah, we can do that. 👍

**Comment by justinfagnani** [comment]
@web-padawan I just published 2.3.0-pre.1 to npm, under the `@next` tag. Let us know when you get a chance to try out `getStyles`.

**Comment by web-padawan** [comment]
@justinfagnani thanks a lot! 

The new version passed our tests in the `ThemableElement` PR above.
