### ISSUE TITLE
Bundle size and @licence comments

### ISSUE THREAD

**Issue by georges-gomes** [Polymer/lit-element#901]
Following our analysis on Web Component bundle sizes
https://webcomponents.dev/blog/all-the-ways-to-make-a-web-component/

I looked at `lit-element` component bundle more closely.

<img width="869" alt="image" src="https://user-images.githubusercontent.com/5250572/75028383-7012c400-54a0-11ea-9fac-c74e3fd75746.png">

It's a 26.937 bytes minified with Terser default settings - see link for details

But ~5kb are `@licence` comments

```
/**
 * @license
 * Copyright (c) 2017 The Polymer Project Authors. All rights reserved.
 * This code may only be used under the BSD style license found at
 * http://polymer.github.io/LICENSE.txt
 * The complete set of authors may be found at
 * http://polymer.github.io/AUTHORS.txt
 * The complete set of contributors may be found at
 * http://polymer.github.io/CONTRIBUTORS.txt
 * Code distributed by Google as part of the polymer project is also
 * subject to an additional IP rights grant found at
 * http://polymer.github.io/PATENTS.txt
 */
```

(Some are 2017 and some are 2019)

A lot of them are coming from `lit-html` but `lit-element` has a few.

### Values

| File  | Size |
|-----|-----|
| Uncompressed with licences |  26.937 bytes |
| Uncompressed without licences | 20.439 bytes |
| gzip with licences | 7.308 bytes |
| gzip without licences | 6.892 bytes |

diff : 5kb uncompressed - 416 bytes zipped

My counter component is very small, so I expect that more `@licence` comments to go in as soon as you use more directives and more features of lit.

### Questions
- Do we care? (My feeling is yes because there is a lot of other things that could be done with this payload instead)
- If yes, where should this be fixed?
     In `lit-element` and `lit-html` source code?
     In Terser?
     In a Rollup plugin to dedup `@licences`?

(for the last option it still requires identical comment content -> source code update)

**Comment by web-padawan** [comment]
Duplicate of #590, maybe it's better to continue there.

**Comment by georges-gomes** [comment]
Missed that sorry!
