### ISSUE TITLE
Mounting element to svg

### ISSUE THREAD

**Issue by jens-ox** [Polymer/lit-element#908]
Hi everyone!

I'd like to mount a lit-element to an existing svg:
```html
<svg>
  <my-element></my-element>
</svg>
```

I did not manage to get this to work. Instead, I had to move the svg tags to the render function of the element (and remove the svg tags from the html):

```javascript
import { LitElement, html } from 'lit-element'

class MyElement extends LitElement {
  //...

  render () {
    return html`
      <svg>
        <!-- stuff -->
      </svg>
    `
  }
}
```

For context, see the [d3-lit source](https://github.com/jens-ox/d3-lit/blob/master/src/components/axis.js), where I want to render an axis to an existing svg.

Is there any way to achieve this? Using `svg` instead of `html` from the `lit-element` package did not work.

**Comment by justinfagnani** [comment]
This isn't directly possible because custom elements are currently in the HTML namespace, and can't be defined to be in the SVG namespace. See https://github.com/w3c/webcomponents/issues/634

A workaround is to use `<foreignObject>` and put the custom element inside of it: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/foreignObject

**Comment by justinfagnani** [comment]
I'm closing because there's really nothing we can do about this on the LitElement side. Please comment on the w3c/webcomponents issue to advocate for SVG-compatible custom elements.

**Comment by jens-ox** [comment]
Thanks for getting back, makes sense.

**Comment by crlmahlberg** [comment]
@justinfagnani Thank you for the `<foreignObject>` workaround. Just one problem there: When I `transform:scale()` the SVG, it doesn't re-render itself afterwards, meaning that the entire SVG with the LitElement inside gets bigger but also becomes blurry. Text and everything else becomes less clear. That is not the case with pure SVGs. Any idea what's causing this strange behavior and how to fix it?

**Comment by justinfagnani** [comment]
@crlmahlberg Sorry, I don't know about that. Presumably it's the same for any `<foreignObject>`.

**Comment by crlmahlberg** [comment]
@justinfagnani No, it happens to me specifically with a LitElement for some reason. Perhaps a shadow DOM issue? A `<button>` or a `<p>` as a `<foreignObject>`works fine. But thanks anyways!
