### ISSUE TITLE
Improve documentation on lifecycle methods

### ISSUE THREAD

**Issue by djlauk** [Polymer/lit-element#912]
## Initiative / goal

On the Polymer slack (new) users of lit-element often ask "How can I achieve ...", and in many cases the answer is "use lifecycle method ...". One question I noticed frequently is "How can I access attribute values in the constructor?"
(The answer is, of course: "You can't. Use a lifecycle method.")

This indicates to me, that this information is not easy to extract from the documentation. I believe the current documentation can be improved by adding guidance, which method to use for which common case. (In its current state, the documentation seems more like a technical reference to me.)

### Scope

My suggestions would be to do the following:

- [ ] Split current lifecycle documentation in two parts: "reference" and "common use cases" (titles open for discussion)
- [ ] Write set of common use cases (should refer to the appropriate paragraphs in "reference")

## Acceptance criteria and must have scope

- Lifecycle documentation contains reference section
- Lifecycle documentation contains common use cases (or scenarios)

**Comment by djlauk** [comment]
As a suggestion, here's a reply from me [on a thread on Polymer slack](https://polymer.slack.com/archives/C03PF4L4L/p1583332327406000?thread_ts=1583331227.401100&cid=C03PF4L4L):

> So far my go to practice with regard to lifecycle and/or derived data has been:
>
> - `property.hasChanged` for checking “Is this a change?”
> - `constructor` for default values
> - `firstUpdated` for initializing private fields from attributes (as the constructor doesn’t have access to them)
> - `updated` for keeping derived data up to date or reacting to changes
> - custom JS property getters (not lit element properties) for derived data that is “cheap” to calculate and if it's not likely to change often
>
> This is where I’m at, for now, but I’m still learning, too, so take it with a grain of salt.

Other things I would add now, for completeness:

- `connectedCallback` for initializing private fields, if it's imperative that this happens *before the first render*
- `connectedCallback` for attaching event listeners for events happening outside the scope of this element and it's children (remember to remove them in `disconnectedCallback` again!)

**Comment by justinfagnani** [comment]
Thanks @djlauk. I think this is good to add and would welcome a PR for it. WDYT @arthurevans?

**Comment by kevinpschaaf** [comment]
We have some similar treatment for lifecycle docs in Polymer: https://polymer-library.polymer-project.org/3.0/docs/devguide/custom-elements#element-lifecycle.  The table there describes both when the lifecycle is called, and also common types of work to do in each.  Seems like adding a table like this might provide a better overview for the detailed docs that follow on https://lit-element.polymer-project.org/guide/lifecycle.

**Comment by arthurevans** [comment]
Yeah, the outline we were working on called for a breakdown kind of like this:

- Overview
- [ assorted use cases ]
- Lifecycle reference

The current use cases we have in the outline are rather obtuse. Like one says "CE reactions wrt async rendering" but I think the meat of that section is really "One-time initialization" split between initialization that depends on the DOM (firstUpdated) and init that doesn't (constructor, say) and could also perhaps embrace not-quite-one-time initialization, like the `connectedCallback` use cases that @djlauk mentioned.

Our plan was to try and get the team to brainstorm about other use cases we should be covering in this section. So far, however, we haven't gotten to it.

**Comment by djlauk** [comment]
I'm a bit uncertain now... shall I still give it a try or is there more you want to sort out first?

**Comment by djlauk** [comment]
Sorry, if this is a not-so-smart question, but: Did I forget a step or something in my PR?

I don't see the changes of the PR in the docs. At first I thought it might be due to caching, but it's been more than a week and now I wonder what happened to my contribution...
