### ISSUE TITLE
Cannot call a function inside the LitElement class from a <template> within a vaadin-grid-column.

### ISSUE THREAD

**Issue by Krishuthapa** [Polymer/lit-element#915]
``` 
<vaadin-grid-column>
          <template is="card-tray">
            <campaign-card
              campaignId$="{{item.id}}"
              name$="{{item.name}}"
              scientist$="{{item.scientist.name}}"
              createdDate$="{{item.created_date}}"
              campaignStatus$="{{item.status}}"
              synthesisType$="{{item.synthesis_type}}"
              url="[[getUrl(item.id)]]"
            >
            </campaign-card>
          </template>
        </vaadin-grid-column>
```

This is the content inside the vaadin grid within the render function. Inside the template there is a function named getUrl(item.id). The function definition is made inside the LitElement class. Through this function call, I want to compute the URL to be sent as a prop to the <campaign-card> component. But, the function isn't called and gives warning as:

`method 'getUrl' is not defined`  
 
How can we solve this?

**Comment by web-padawan** [comment]
Hello, please don't use Polymer templates inside `lit-html` templates. They won't work.
You should use `renderer` property instead, and pass it to `vaadin-grid-column`.

Check out this example: https://glitch.com/edit/#!/vaadin-grid-renderer?path=app.js

**Comment by Krishuthapa** [comment]
@web-padawan  can we also use renderer property inside <iron-list> in  lit-html? Seems like vaadin-grid is not correct element for my requirement.

**Comment by web-padawan** [comment]
> Can we also use renderer property inside `<iron-list>` in lit-html? 

No, consider using [lit-virtualizer](https://github.com/PolymerLabs/uni-virtualizer/tree/master/packages/lit-virtualizer) instead.

**Comment by Krishuthapa** [comment]
@web-padawan , thanks it worked for virtualized list. But, how can we implement infinite scrolling in it?

**Comment by justinfagnani** [comment]
`url="[[getUrl(item.id)]]"` is a Polymer binding, and Polymer's template system has no reference to the containing LitElement. There's really not a way to make this work on our end. Thanks @web-padawan for the pointers.
