### ISSUE TITLE
Delete references to polymer-cli from main docs, and link to open-wc

### ISSUE THREAD

**Issue by mercmobily** [Polymer/lit-element#919]
polymer-cli "works" but it hasn't received a real commit for over 8 months, and issues are piling up quickly. It's not a good look.

Using [es-dev-server](https://open-wc.org/developing/es-dev-server.html) would be a much better idea -- and it will give developers a much better idea of what they should actually use.

The [very first page of lit-element's documentation](https://lit-element.polymer-project.org/guide/start) links to https://github.com/PolymerLabs/start-lit-element which had its last commit 1 year ago and refers to polymer-cli.

Also, it would be graceful to have a link to open-wc from the documentation.

I think a section "Writing apps" would ideally link to open-wc, and summarise what's provided with `npm init @open-wc`.

Right now, lit-element is telling users to use an effectively abandoned repository to serve elements, an outdated "hello world" project and no mention of how to create a full app, which is most people's goals.

**Comment by arthurevans** [comment]
We're working on a replacement for this getting started guide that provides a more modern starting point (and no Polymer CLI).

**Comment by mercmobily** [comment]
Are you going to suggest people to use es-dev-server? What about a link to open-wc?

**Comment by arthurevans** [comment]
Yeah, the new starter project (https://github.com/PolymerLabs/lit-element-starter-ts is the working version, typescript flavor) uses es-dev-server. (There will probably be links to open-wc as well; that's where we're pointing people for an app project scaffold at the moment.)

**Comment by mercmobily** [comment]
I realise that lit in typescript, but please keep your heart open to people who use ES6 rather than typescript to do things.

**Comment by arthurevans** [comment]
Heck @mercmobily, I don't even _know_ TypeScript. The first version is TypeScript because it has more moving parts. There'll be a JavaScript version, too, for folks like you and me.

**Comment by mercmobily** [comment]
@arthurevans Ahhahahah that makes 2 of us :D The amount of moving parts (as well as the super-verbose code -- I hate types!) is what keeps me WELL away from TS...

**Comment by noelmace** [comment]
So @mercmobily, do you think moving the docs from polymer-cli to open-wc is still on the table, or should we wait for the new starter project? In the first case, I would be happy to send a PR for that as I'm currently working on this topic.

**Comment by shipagency** [comment]
@arthurevans how is the progress on getting the docs updated?

**Comment by arthurevans** [comment]
@shipagency Hoping to get a public draft out this week.

**Comment by arthurevans** [comment]
New draft is staged here: https://new-getting-started-dot-polymer-lit-element.appspot.com/guide/start
PR is here, if you have feedback: https://github.com/Polymer/lit-element/pull/969

**Comment by mercmobily** [comment]
Wow... just WOW. This is going to be the best Getting Started I've seen in a very, very long time!
Really impressive work. I like the reference to the open-wc generator.
I am humbled by how well this is written.

**Comment by arthurevans** [comment]
Thanks for the kind words, @mercmobily ! Update is live, closing.
