### ISSUE TITLE
Cannot set vertical margin between the items in the iron-list.

### ISSUE THREAD

**Issue by Krishuthapa** [Polymer/lit-element#920]
Cannot set vertical margin between the items in the iron-list.

I have used an iron-list in LitElement which contains the array of a custom component.

```
 <iron-list .items="${this.filteredModuleList}" as="item">
        <template>
          <campaign-card
            campaignId$="{{item.id}}"
            name$="{{item.name}}"
            scientist$="{{item.scientist.name}}"
            createdDate$="{{item.created_date}}"
            campaignStatus$="{{item.status}}"
            synthesisType$="{{item.synthesis_type.name}}"
            targetId$="{{item.target.id}}"
            cardTopic="${this.cardTopic}"
          >
          </campaign-card>
        </template>
      </iron-list>
```
I want to set the vertical margin between these elements. But it does not work. How can I set the margin-top and margin-bottom?

**Comment by kevinpschaaf** [comment]
It's not clear that this is a LitElement issue; if it's just a matter of styling the list item it probably belongs in the `iron-list` issue tracker.

Either way, per our CONTRIBUTING guidelines, we'll need a reproduction case to help you work out the right styling. Can you post a repro and we can go from there.

**Comment by kevinpschaaf** [comment]
Since we haven't heard back with a repro case, we're going to close this issue. If you are still having issues, please open a new issue with a reproduction case.  Thanks.
