### ISSUE TITLE
Pseudo-native select using litelement

### ISSUE THREAD

**Issue by shipagency** [Polymer/lit-element#951]
I realise that this is not an issue with lit-element. However, I am trying my luck and use all of the karma points I have, after spending _countless_, _countless_ hours trying to make this work.
I want to be able to do this:

````
  <nn-select id="select" name="portId" >
      ${this.options.map(item => {
            return html`<option>${item.name}</option>`
          })}
     </nn-select>
````

nn-select is meant to be a super-simple element. However, since the native select can't have slotted elements, I actually do it manually -- shifting the options elements from the slot and into the actual native select.
Spoiler: it doesn't work. I am just hoping it might be fixed by a little bit of Justin's or Steve's magic

````
import { LitElement, html } from 'lit-element'
export class NnSelect extends LitElement {
  render () {
    return html`
      <slot @slotchange="${this.addSlotToSelect}"></slot>
      <select id="native"></select>
    `
  }

  addSlotToSelect (e) {
    const select = this.shadowRoot.querySelector('#native')
    const options = e.srcElement.assignedElements()

    // Remove all of the existing children in the native select
    while (options.length && select.firstChild) {
      if (!select.lastElementChild.value) break
      select.removeChild(select.lastElementChild)
    }

    // Move the options from the slot into here
    for (const option of options) {
      select.appendChild(option)
    }
  }
}
customElements.define('nn-select', NnSelect)
````

It doesn't work. I mean, it works the first time. However, once the options change, really strange things begin to happen: the element ends up with only one option.

I don't have a repo to reproduce this,  since:

* I am hoping I am doing something totally glaring and stupid, which can be fixed by a something simple.

* Spent so many hours on this, I am crossing my fingers to see if I can avoid creating a repo for this

**Comment by CaptainCodeman** [comment]
Why not just pass the key / value pairs that you want the `<option>`'s to contain, into the custom element as an array property?

**Comment by daKmoR** [comment]
as browser only allow `option` tags within a `select` tab all you really can do is wrap the select itself 😅

We do it like that
https://lion-web-components.netlify.com/?path=/docs/forms-select--default-story

Alternatively you need to fully recreate all aspects of a select... e.g. overlays, accessibility, different behaviour for windows/mac/android/iphone...
We have a starting point for that as well... although it behaves the same on android/iphone 😅
https://lion-web-components.netlify.com/?path=/docs/forms-select-rich--default-story

**Comment by shipagency** [comment]
The point is for nn-select to be a drop in replacement for select. What I want to do is adding whatever was slotted in co-select copied over manually into the native select...

**Comment by daKmoR** [comment]
I am afraid that is impossible according to the HTML spec

https://www.w3.org/TR/html52/sec-forms.html#the-option-element
```
Contexts in which this element can be used:
- As a child of a select element.
- As a child of a datalist element.
- As a child of an optgroup element.
```

e.g. you `<nn-select>` is not part of that list and therefore the browser will not allow an `<option>` tag as a child of your component

**Comment by sorvell** [comment]
Yeah, as noted above, this type of wrapping is not supported in the platform. You'd need to have the user slot in a `<select>` including the `<option>`'s.

**Comment by shipagency** [comment]
@sorvell You may have missed the fact that I was indeed appending <options> to the native `select` element!

In the end, I was able to achieve this by:

1) Leaving the slots where they were, just hidden
2) Making clones of the options entries in the slot and shoving them in the select

Like this:


````
  render () {
    return html`
      <div style="display: none">
        <slot @slotchange="${this.addSlotToSelect}"></slot>
      </div>
      <select id="native" real-time-event="selected"></select>
    `
  }

  async addSlotToSelect (e) {
    const select = this.shadowRoot.querySelector('#native')
    const options = e.srcElement.assignedElements()
    while (select.firstChild) {
      if (!select.lastElementChild.value) break
      select.removeChild(select.lastElementChild)
    }
    for (const option of options) {
      select.appendChild(option.cloneNode(true))
    }
  }
````

@sorvell Is there anything absolutely horrific in this solution? Remember that the goal is to have a total drop-in replacement to a select, using web components to theme, AND that I am appending clones of the slotted elements, which are meant to be `<options>`.

It's working... I was just wondering if I am making a monstruisity.

THANK YOU for your feedback everybody and have a safe Easter!

**Comment by JohnBernardsson** [comment]
@shipagency I sincerely hope that approach worked for you without issues, because I am going to do exactly the same... 😅 

Pinging also @daKmoR and @sorvell in case you guys think this is a wrong approach to go on with, and care to comment here 🙏

**Comment by justinfagnani** [comment]
@JohnBernardsson this is the wrong repo. Please use [lit/lit](https://github.com/lit/lit)

**Comment by JohnBernardsson** [comment]
@justinfagnani should I post an issue/query in there? I just wanted to get some confirmation on the approach shared by @shipagency on this matter, as I understand this is not a lit problem but a limitation by the platform. But I can crate an issue there and link this one if that makes more sense...
