### ISSUE TITLE
handle component error

### ISSUE THREAD

**Issue by quentin29200** [Polymer/lit-element#953]
How handle JS errors from LitElement component's such as [lwc feature's](https://developer.salesforce.com/docs/component-library/documentation/en/lwc/lwc.create_lifecycle_hooks_error) ?

I tried to handle errors with `window.onerror` and on my webcomponent

```
<my-content @error=${MyView._trackError}> content... </my-content>

```

```
  private static _trackError(err): void {
    console.log('SIMULATE TRACK ERROR', err);
  }
```

It doesn't work. I need this to log my application

**Comment by sorvell** [comment]
We don't plan to add this type of feature to LitElement and it's not directly supported in the platform, but you could implement something like this yourself.

You'd need to wrap over all of the lifecycle of the element and try/catch the code, firing an event if there's an exception, for example, `constructor`, `connected/disconnectedCallback`, and probably `performUpdate`.

To get a sense of what you'd do in `performUpdate`, something like:

```
performUpdate() {
  try {
    super.performUpdate();
  } catch(err) {
    this.dispatchEvent(new CustomEvent('error', {detail: err});
  }
}
```

You could even make a class decorator that emits a subclass of the given class that wraps these call sites.

**Comment by justinfagnani** [comment]
@sorvell We could potentially offer a mixin that listens for error events and provides an error property that templates can use.

**Comment by quentin29200** [comment]
Ok, thank's a lot, it's working fine. 
I created a trackError decorator.

```
export const trackError = (descriptor: Constructor<HTMLElement> | ClassDescriptor): any => {
  const { kind, elements } = <ClassDescriptor>descriptor;
  return {
    kind,
    elements,
    // This callback is called once the class is otherwise fully defined
    finisher(clazz: Constructor<HTMLElement>): void {
      const { performUpdate } = clazz.prototype;
      // And all functions needed

      clazz.prototype.performUpdate = function(): void {
        try {
          performUpdate.call(this);
        } catch (err) {
          sendEventDetail('error', err, this);
        }
      };

      // And all functions needed
    },
  };
};

```

```
@trackError
@customElement('my-component')
export default class MyComponent extends LitElement { ... }
```

**Comment by lsgroup** [comment]
Hi - needing this mixin that @justinfagnani was talking about.  

I couldn't get @quentin29200 decorator code to work (my own fault I'm sure).  Wrote a mixin (below) and was able to get that working.  

I've only included constructor, disconnectedCallback, connectedCallback, and performUpdate.  Am I missing any lifecycle events?

I'm surprised there aren't more people interested - error tracking in production is critical.  Other than a mixin / decorator window.onerror is essentially broken.  Any plans for an officially supported mixin / decorator?


```
export const LoggingMixin = (superClass) => class extends superClass {
  constructor() {
    try {
      super();
      console.log('LoggingMixin', `${this.localName} constructor()`);
    } catch(err) {
      console.log("LoggingMixin constructor() ERROR!", err);
      dispatchEvent(new CustomEvent('error', {detail: err}));
    }
  }
  connectedCallback() {
    try {
      super.connectedCallback();
      console.log('LoggingMixin', `${this.localName} connectedCallback()`);
    } catch(err) {
      console.log("LoggingMixin connectedCallback() ERROR!", err);
      dispatchEvent(new CustomEvent('error', {detail: err}));
    }
  }
  disconnectedCallback() {
    try {
      super.disconnectedCallback();
      console.log('LoggingMixin', `${this.localName} disconnectedCallback()`);
    } catch(err) {
      console.log("LoggingMixin disconnectedCallback() ERROR!", err);
      dispatchEvent(new CustomEvent('error', {detail: err}));
    }
  }
  performUpdate() {
    try {
      console.log('LoggingMixin', `${this.localName} performUpdate()`);
      super.performUpdate();
    } catch(err) {
      console.log("LoggingMixin performUpdate() ERROR!", {err, 'this':this});
      //let payload = {title: event.message, error:event.error, line:event.lineno, col:event.colno, src:event.target.location.href};
      let payload = {title: err.message, error:err, class:this.localName};
      dispatchEvent(new CustomEvent('error', {'detail':payload}));
    }
  }
}

```

**Comment by quentin29200** [comment]
@lsgroup In Lit, you can handling error in lifecycle today https://lit.dev/docs/components/lifecycle/#errors-in-the-update-cycle

**Comment by lsgroup** [comment]
Thanks!!!  deleted my mixin and replaced with window.addEventListener("unhandledrejection"...  works great!
