### ISSUE TITLE
[question] <slot> inside <textarea>

### ISSUE THREAD

**Issue by tamis-laan** [Polymer/lit-element#954]
The following piece of code wil render the <slot> </slot> inside the textarea as html is not allowed.

``` javascript 
render() {
    return html` <textarea> <slot> </slot> </textarea>`
}
```
Thus <slot> becomes unusable, is there a way to use javascript to set the slow inside?

**Comment by arthurevans** [comment]
By spec, the text area only allows text content, so you can't _usefully_ add a slot to it.

Testing in Chrome, I was able to add a slot by calling `appendChild`, but the slot's contents are never displayed. 

If you want to let users set the starting text in the textarea, you could expose a property on your element that gets bound to the textarea's value:

```js
return html` <textarea .value=${this.myprop}></textarea>`
```
If you really need to configure the default text for the textarea based on slotted content, you could consider having a hidden slot element (a sibling, not a child, of the textarea), and grab the text that gets slotted in. That could look something like this:

```js
updateSlotted({target}) {
  this.myprop = target.assignedNodes().map((n) => n.textContent).join('');
}

render() {
  return html`<textarea .value=${this.myprop}></textarea>
    <div hidden>
      <slot @slotchange=${this.updateSlotted}></slot>
    </div>`;
}
```

Hope that helps!

**Comment by kevinpschaaf** [comment]
Closing, as the solution @arthurevans gave above are the best options to deal with slotting content into textarea.  Hope that helps your use case!
