### ISSUE TITLE
Ereditate theming from lightdom *solution*

### ISSUE THREAD

**Issue by ianes1978** [Polymer/lit-element#955]
Hello all,
i would like to share my solution of global theming with webcomponent (lit-element). 
I made a tool to ereditate in the shadowdom the outside styles:
without lost advantages of shadowdom.
(styles enter but cant exit from webcomponent)
**npm:** [lit-css-global-scope](https://www.npmjs.com/package/lit-css-global-scope)

i hope can be helpfull, and have suggestion to improve it (or if someone have a smarter way to do it)
tnx

**Comment by sorvell** [comment]
It looks like this package pulls in global styles to a given element's Shadow DOM. That's a reasonable way to share global styling, as long as users know they are opt'ing into it. One consideration you're probably aware of is that styles will not match between scopes. So, for example, descendant selectors have to match entirely without a given scope (document or shadowRoot). Thanks for posting the library.
