### ISSUE TITLE
Is it possible to provide a new typescript cutomElement decorator without parameter tagName?

### ISSUE THREAD

**Issue by changchengqin** [Polymer/lit-element#958]
## Description 

Is it possible to provide a new typescript cutomElement decorator without parameter tagName?

Because manually defining the tag name of a customElment is an error-prone, unconstrained and meaningless thing, especially when the project is getting bigger.

This new decorator automatically uses the name of the web component class and the name of the namespace in which it is located and connects them with hyphen .

### Expected Results

for example,

I defined a web component class like this:

``` typescript
namespace user.common {
    @newCustomElementDecorator
    export class Header extends LitElement {
    }
}
```
Finally, the `newCustomElementDecorator` decorator will automatically define a web component named `user-common-header`

**Comment by justinfagnani** [comment]
You can easily define such a decorator yourself. We've avoided implicit name conversions as much as possible in the project and don't have any place where we convert between camel, kebab, or snake cases. I wouldn't want to add it now.

**Comment by changchengqin** [comment]
OK,thks.
