### ISSUE TITLE
[Typescript] Multiple extensions of class LitElement cannot render properly

### ISSUE THREAD

**Issue by changchengqin** [Polymer/lit-element#966]
### Description

I have the following two custom base classes, the structure is as follows:
```typescript
export class PageElement extends LitElement {
}

export class RootPageElement extends PageElement {
}

```
Then my custom element inherits from BaseB:
```typescript
@customeElements('my-element')
class MyElement extends RootPageElement{
    render() {
       return html`<h1>hello world</h1>`
    }
}
```
When I use the custom element `my-element` in the html page, the content `hello world` cannot be rendered normally
#### Live demo
https://github.com/changchengqin/lit-element-starter-ts.git

#### Steps to Reproduce
1. Clone the repo
2. Run `npm install`
3. Run `npm run build:watch`
4. Run `npm run serve`
5. Open brower: http://localhost:xxxx/dev/index.html

#### Expected Results

render `hello world` on web page 

#### Actual Results

render nothing.

### Browsers Affected

- [ ] Chrome
- [ ] Safari 11
- [ ] Firefox
- [ ] Edge
- [ ] Safari 10
- [ ] IE 11

### Versions

- lit-element: v2.3.1
- lit-html: v1.2.1

**Comment by justinfagnani** [comment]
This is very odd. Are you seeing any errors in the console? Can you make an online reproduction in something like Stackblitz.

**Comment by justinfagnani** [comment]
I don't see the problem here at least: https://stackblitz.com/edit/lit-element-hhmsta?file=src/index.js

**Comment by changchengqin** [comment]
@jordanaustin 
this happens in typescript projects, pure javascript projects are no problem.

**Comment by abraham** [comment]
@changchengqin I checked out your project and followed the steps and the dev index.html can't find `my-element.js`

**Comment by changchengqin** [comment]
check this online demo
https://stackblitz.com/edit/typescript-2y9dgn

**Comment by changchengqin** [comment]
I just tried it again myself, and updated the sample repository I provided, this problem no longer exists.
I do not know why.
Two days ago, it was obviously impossible.
thank you all.

**Comment by changchengqin** [comment]
But I still have a question, why create a typescript project in stackBlitz, and then use LitElement routinely, the console always reports an error:
![image](https://user-images.githubusercontent.com/3336443/79821264-e3618500-83c0-11ea-9c73-3db5407aa8a1.png)

**Comment by jordanaustin** [comment]
> @jordanaustin
> this happens in typescript projects, pure javascript projects are no problem.

I think you're looking at reply @justinfagnani

**Comment by changchengqin** [comment]
@jordanaustin 
haha, yes. Your two names are very close. I mentioned it wrong.

**Comment by abraham** [comment]
Using the updated repo `MyElement#render` seems to be working as expected.

<img width="832" alt="Screen Shot 2020-04-21 at 08 56 21" src="https://user-images.githubusercontent.com/3341/79874552-1f3f1f00-83ae-11ea-9389-7055f25fc199.png">

**Comment by justinfagnani** [comment]
@changchengqin if you're compiling to ES5, you need to include the custom elements es5 adapter: https://github.com/webcomponents/polyfills/tree/master/packages/webcomponentsjs#custom-elements-es5-adapterjs

**Comment by changchengqin** [comment]
@justinfagnani thks.

**Comment by changchengqin** [comment]
In the end, I found the root cause of incorrect rendering:
The super.connectedCallback () method is not called in the connectedCallback () method of the second parent class
