### ISSUE TITLE
A deep node clone breaks YouTube scripts

### ISSUE THREAD

**Issue by danny0838** [Polymer/lit-element#968]
I recently encountered an issue that [performing a deep node cloning in YouTube site breaks its scripts](https://stackoverflow.com/questions/61307541/a-deep-clone-breaks-youtube-scripts). It seems something in YouTube's source code has caused it, but as its codes are obfuscated it's difficult to investigate. A clue I can see so far is that YouTube uses Polymer project, so I'm posting here for a help to find out the cause and for a solution to avoid the issue.

### Description
Performing a deep cloning in a YouTube page breaks its scripts.

#### Steps to Reproduce
1. Visit a YouTube Page.
2. Confirm that clicking on a tricolon (`⁝`) pops a context menu.
3. Perform a deep node cloning, such as: `document.documentElement.cloneNode(true);`, using either browser console or the content script of an extension of Firefox Quantum or Chromium.

#### Expected Results
The YouTube page should work as usual after performing the the deep clone.

#### Actual Results
After performing the deep clone, clicking on a tricolon no longer pops a context menu.

### Browsers Affected
- [x] Chrome
- [x] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

### Versions
Not sure. Seems like v2.* in 2016.

**Comment by justinfagnani** [comment]
> Expected Results
> The YouTube page should work as usual after performing the the deep clone.

Why is this an expected result? Is YouTube supporting cloning its internal DOM?

Web components can have state in JavaScript that isn't cloned when the DOM nodes are. This is also true of any other non-web-components web framework. If the application itself doesn't copying it's DOM, it's almost always not going to work.

**Comment by danny0838** [comment]
@justinfagnani The issue is not about that the CLONED nodes doesn't work, but the ORIGINAL page gets broken by a clone in the background (note: the cloned are NOT inserted into the page).

A clone in the background may be initiated by a user script or a browser extension, for example, simply to retrieve some transformed information from the original page. Normally a clone in the background never interferes with the original page, but in this case it does, and that is an issue which is probably unexpected by the user or the extension developer.
