### ISSUE TITLE
Set "type" to "module" in package.json

### ISSUE THREAD

**Issue by vikerman** [Polymer/lit-element#973]
## Description
- Who wants the functionality
Those loading lit-element in Node >=13 while doing SSR

- What it is they want
Load lit-element as ES Modules without converting to CJS.

- Why they want it
This lets toolchain to load lit based project as ES Modules so that they can run in Node without using bundling tools.

## Acceptance criteria
What the card must do in order to accept it as complete. Acceptance Criteria must be concrete or measurable.
Create a release after changing "type": "module" in package.json

**Comment by zandaqo** [comment]
Either this, or have explicit CJS export as "main". Currently, Node attempts to load it as CJS but encounters "import/export" syntax and breaks.

A practical use case: Jest as of version 25.2 supports ES Modules (without Babel) and work fabulously for me, except for importing these webpack-oriented packages that are seen as CJS in Node's eyes but  are ES Modules in reality.
