### ISSUE TITLE
OnChange not fired in input field of litElement

### ISSUE THREAD

**Issue by Wasseratem** [Polymer/lit-element#975]
I have following code:

    
    export class ViTextfield extends LitElement 
    {
    static get properties() {
        return { 
            value: { type: String }, 
      }

     onChange(e) { console.log(e.target.value) }

     render()
    {
        return html`
        <div>
     
            <div>
                <input id="vi-input" 
                    type="text" 
                    value="${this.value}"
                    @change=${this.onChange} />
            </div>
        </div>
            `
    }

So everything is working fine for itself.
Now the developer who is using my component should be able to set the value thorugh the property e.g.

      document.getElementById('myComponent').value = 1;

Now that brings 2 problems:
1) the value itself is not updated and 2) the onchange is not fired

Problem 1 I fixed with changing    

    value="${this.value}"

to   

    .value="${this.value}"

even I dont know why it is working (found this hack online).

But still the onChange is not firing...

**Comment by daKmoR** [comment]
1. the input is a native input and it only reads it's initial value as an attribute. (you can test this by changing the value of a native input and will see that it won't update it's "value property")

2. the native input also doesn't fire an event if you are updating the value programmatically... (e.g. only user interaction will trigger events)
you will need to check this in your component... .e.g user input = event... and for your value you want to use a setter and/or something in updated

**Comment by justinfagnani** [comment]
@daKmoR is correct here. This is the way `<input>` works in all cases. Thanks for the.... input, @daKmoR ;)
