### ISSUE TITLE
Conditional rendering expression

### ISSUE THREAD

**Issue by theolavaux** [Polymer/lit-element#979]
I believe there is no syntax such as : [react inline conditional rendering with &&](https://fr.reactjs.org/docs/conditional-rendering.html#inline-if-with-logical--operator) in Lit-Element yet, it simply outputs a boolean value. Is there a cleaner/shorter syntax than ${title ? html`<h1>${title}</h1>`: ''} inside template litterals ?

Would something like ${title && html`<h1>${title}</h1>`} be possible to avoid rendering empty templates ?

**Comment by justinfagnani** [comment]
This would be a breaking change, so we couldn't do it till 2.0 even if we wanted to. But we chose this behavior specifically. If you render `${true}` we intend to write "true" to the DOM.

**Comment by theolavaux** [comment]
Totally understand your point, could it be done using directive then?
