### ISSUE TITLE
Change _attributeNameForProperty to protected

### ISSUE THREAD

**Issue by bschlenk** [Polymer/lit-element#985]
### Description

[_attributeNameForProperty](https://github.com/Polymer/lit-element/blob/bcd500a6ebcd3c32d44b4b974dd4f2ed82aae62e/src/lib/updating-element.ts#L436) can be overridden, e.g. to support kebab-cased attributes. However, it requires a `// @ts-ignore` comment because the method is currently private. It should be `protected` to make it easier to override.

### Versions

- lit-element: v2.3.1

**Comment by sorvell** [comment]
Custom attribute naming is already supported via specifying the `attribute` property option. Here's an example: https://stackblitz.com/edit/lit-element-demo-dtkn9t?file=index.html

We can consider this change, but would like to avoid it if the current support is sufficient.

**Comment by bschlenk** [comment]
I’d like to be able to set that behavior once in a subclass of LitElement, instead of on every single property of every single component.

**Comment by sorvell** [comment]
Sorry for the delay on this. We're opting not to make this change as it's possible to customize centrally via an override of `createProperty`. Here's an example: https://stackblitz.com/edit/lit-element-demo-3h2hdz?file=src%2Fmy-element.js

**Comment by bschlenk** [comment]
👍 Thanks for the example!
